### ISSUE TITLE
Upload through fetch

### ISSUE THREAD

**Issue by mschipperheyn** [marcshilling/react-native-image-picker#1]
Any suggestions on uploading an image to a server using fetch?

**Comment by marcshilling** [comment]
Not quite there yet with our react native project. I'm mostly a front-end guy. Will post here once we have it sending the photos to our server.

**Comment by darkrishabh** [comment]
@mschipperheyn I think you must have found it by now. if you havent you can use https://github.com/booxood/react-native-file-upload

**Comment by sorenbs** [comment]
Here's my approach if anyone is curious:

var options = {
      title: 'Upload image',
      cancelButtonTitle: 'Cancel',
      takePhotoButtonTitle: 'Take Photo...',
      chooseFromLibraryButtonTitle: 'Choose from Library...',
      returnBase64Image: true,
      returnIsVertical: false
    };
UIImagePickerManager.showImagePicker(options, (type, response) => {
      if (type !== 'cancel') {
        var source;
        if (type === 'data') { 
          source = {uri: 'data:image/jpeg;base64,' + response, isStatic: true};
        } else { 
          source = {uri: response};
        }

        console.log("uploading image");

         fetch('my-server-endpoint',{
           method: 'post',
           body: "data=" + encodeURIComponent(source.uri)
         }).then(response => {
           console.log("image uploaded")
           console.log(response)
         }).catch(console.log);

        //this.setState({avatarSource:source});
      } else {
        console.log('Cancel');
      }
    });

Simply use decodeURIComponent on the server to get the image data

**Comment by marcshilling** [comment]
Thanks @darkrishabh and @sorenbs...closing this.

**Comment by MikaelCarpenter** [comment]
Anyone have experience uploading to a Django backend? I keep getting `image is not a file` when i send the post request as `image: source.uri`

I've tried encoding it but that didn't work either. I'm not very familiar with Django so not sure what it expects for an image.

**Comment by alvaromb** [comment]
@MikaelCarpenter I'm experiencing the same issue, have you managed to solve it?

**Comment by marcshilling** [comment]
Let's continue this discussion on #31 - I just posted a comment.

**Comment by percyteng** [comment]
@sorenbs Can you please share your code sample on the backend too? Thanks!

**Comment by Settao** [comment]
Any body solved this React Native to Django backend image upload?  I am using fetch and multipart-form.  It works on iOS simulator with Expo XDE.  But it fails on Android.

**Comment by MuhammadArsalan472121** [comment]
I want to upload the selected image to my server here is my code...
anyone can help?

async function getUser() {
            try {
              const response = await axios.post(
                'https://mysite.com/api/v1/idimage'
              );
              console.log(response);
              console.log(response.status);

              navigation.navigate('NationalIDCard');
            } catch (error) {
              console.error(error);
            }
          }
          getUser();
          
          
          
import React, {Fragment, Component} from 'react';
import ImagePicker from 'react-native-image-picker';
import {
  SafeAreaView,
  StyleSheet,
  View,
  Text,
  StatusBar,
  Image,
  Button,
  Dimensions,
  TouchableOpacity,
} from 'react-native';

import IconAD from 'react-native-vector-icons/AntDesign';
import IconSLI from 'react-native-vector-icons/SimpleLineIcons';
import DateTimePickerModal from 'react-native-modal-datetime-picker';

import {
  Colors,
} from 'react-native/Libraries/NewAppScreen';

export default class NationalIDCard extends Component {
  constructor(props) {
    super(props);
    this.state = {
      filepath: {
        data: '',
        uri: '',
      },
      fileData: '',
      fileUri: '',
    };
  }

  chooseImage = () => {
    let options = {
      title: 'Select Image',
     
      storageOptions: {
        skipBackup: true,
        path: 'images',
      },
    };
    ImagePicker.showImagePicker(options, response => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else {
        const source = {uri: response.uri};

        // You can also display the image using data:
        // const source = { uri: 'data:image/jpeg;base64,' + response.data };
        // alert(JSON.stringify(response));
        // console.log('response', JSON.stringify(response));
        this.setState({
          
          filePath: response.path,
          fileData: response.data,
          fileUri: response.uri,
        });
        console.log(response.path);
      }
    });
  };

  
  renderFileData() {
    if (this.state.fileData) {
      return (
        <Image
          source={{uri: 'data:image/jpeg;base64,' + this.state.fileData}}
          style={styles.images}
        />
      );
    } else {
      return (
        <View style={styles.iconStyle}>
          <IconAD name={'upload'} size={150} color={'#707070'} />
        </View>
      );
    }
  }


  state = {visibility: false, DateDisplay: 'Enter Expiry Date'};
  handleConfirm = date => {
    this.setState({DateDisplay: date.toString()});
  };

  onPressCancel = () => {
    this.setState({visibility: false});
  };
  onPressButton = () => {
    this.setState({visibility: true});
  };
  pressHandlerContinue = () => {
    this.props.navigation.navigate('Welcome');
  };

  render() {
    return (
      <Fragment>
        <StatusBar barStyle="dark-content" />
        <View style={styles.body}>
          <View
            style={{
              flex: 0.2,
              justifyContent: 'center',
              alignItems: 'center',
            }}>
            <Text style={styles.title}>Add National ID card</Text>
          </View>
          <View
            style={{
              flex: 0.5,
              justifyContent: 'center',
              alignItems: 'center',
            }}>
            {this.renderFileData()}
          </View>
         

          <View style={styles.btnParentSection}>
            <TouchableOpacity
              onPress={this.chooseImage}
              style={styles.btnSection}>
              <Text style={styles.btnText}>Choose File</Text>
            </TouchableOpacity>
           <Text style={{fontSize:16,fontWeight:'700'}}>
             {'Enter Expiry Date: '}
           </Text>
            <TouchableOpacity
              onPress={this.onPressButton}
              style={{
                flexDirection: 'row',
                justifyContent: 'center',
                paddingLeft: 10,
                width: '80%',
                alignItems: 'center',
                borderWidth: 1,
              }}>
              <IconSLI name="calendar" size={20} color="#6F6F6F" />
              <Text
                style={{
                  height: 50,
                  width: '95%',
                  textAlignVertical:'center',
                  color: '#707070',
                  padding:15
                }}>
                {this.state.DateDisplay}
              </Text>
              <DateTimePickerModal
                isVisible={this.state.visibility}
                onConfirm={this.handleConfirm}
                onCancel={this.onPressCancel}
                mode="date"
              />
            </TouchableOpacity>
          </View>
          <View
            style={{
              flex: 0.1,
              justifyContent: 'center',
              alignItems: 'center',
            }}>
            <TouchableOpacity
              onPress={this.pressHandlerContinue}
              style={{
                backgroundColor: '#FD941E',
                height: 50,
                width: '80%',
                justifyContent: 'center',
                alignItems: 'center',
              }}>
              <Text style={{fontSize: 20, color: '#ffffff'}}>
                CONTINUE TO HOME
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </Fragment>
    );
  }
}

const styles = StyleSheet.create({
  body: {
    flex: 1,
    backgroundColor: Colors.white,
    height: Dimensions.get('screen').height - 20,
    width: Dimensions.get('screen').width,
  },
  title: {
    fontWeight: 'bold',
    fontSize: 20,
    margin: 10,
  },

  images: {
    width: 300,
    height: 400,
    borderColor: 'black',
    borderWidth: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconStyle: {
    width: 300,
    height: 400,
    borderColor: 'black',
    borderWidth: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnParentSection: {
    flex: 0.2,
    alignItems: 'center',
    marginTop: 30,
  },
  btnSection: {
    width: '80%',
    height: 50,
    backgroundColor: '#DCDCDC',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
    marginBottom: 10,
  },
  btnText: {
    textAlign: 'center',
    color: 'gray',
    fontSize: 14,
    fontWeight: 'bold',
  },
});
