### ISSUE TITLE
On RN0.18.0/android4.4 enviroment, take photo from camera can not get data

### ISSUE THREAD

**Issue by sadikelong** [marcshilling/react-native-image-picker#100]
Hi yfuks, 
I use your code in my demo project. I debug the code, and found a problem that when I take photo from camera, my app is dead(I get the information from Android Studio).
![image](https://cloud.githubusercontent.com/assets/7940552/12815491/9a5c8b6c-cb81-11e5-9677-bf1a198c143c.png)
So when I take the photo, the app can not get the result. The log is below:
![image](https://cloud.githubusercontent.com/assets/7940552/12815533/d656c4ca-cb81-11e5-8aac-c54caab0030c.png)

But sometimes, my app can show the picture which take from camera, but most time, the app can not get the uri of the pic which take from camera.

Is it the problem with android4.4 or RN0.18.0? Sorry for my poor English : )

**Comment by yfuks** [comment]
Hi @sadikelong !

The line in your log show that you have an issues with Overlays (i assume)
Are you sure you don't get the uri ? Can you show me showImagePicker result ?

That can appears if you take a picture while the dev menu is still opened.

in **RN 0.18.0** you don't need to override ReactActivity.onCreate. That's maybe an issue with your implementation

**Comment by sadikelong** [comment]
Hi, @yfuks 
I didn't override ReactActivity.onCreate. So I think the problem is related with RN.
My code is below:
![image](https://cloud.githubusercontent.com/assets/7940552/12816443/83221cae-cb87-11e5-9487-6c31a3839ffd.png)
![image](https://cloud.githubusercontent.com/assets/7940552/12816456/98091b2c-cb87-11e5-9f4b-453f545c1efb.png)
I set two breakpoints in MainActivity.onActivityResult function, but the program did not go to there.
![image](https://cloud.githubusercontent.com/assets/7940552/12816511/d5a5293a-cb87-11e5-8ef3-9084b6f04823.png)
So the showImagePicker has no log.

But I test several times, sometimes it works well, the showImagePicker can get the uri.

**Comment by yfuks** [comment]
You should transform
```javascript
<TouchableOpacity onPress={this._pickImg}>
  ...
</TouchableOpacity>
```
into
```javascript
<TouchableOpacity onPress={() => this._pickImg()}>
  ...
</TouchableOpacity>
```
To set the ```_pickImg()```*context* with your React.class *context*
That could be the trick

**Comment by yfuks** [comment]
No response i close

**Comment by FlorianeEnnaji** [comment]
I kinda have the same problem, when I choose to take a picture, my app's instance is killed and a new one gets created when I click on 'save' (so I'm not able to get the picture).
I'm also using RN 18

**Comment by yfuks** [comment]
I get this kind of issue once @FlorianeEnnaji just a question did you force your app to be in portrait in you manifest ?

The app can sometime reload by herself after orientation

Try to add the folowing line in your manifest.xml, btw it's more a work around than a real solution
```xml
android:configChanges="orientation|screenSize"
```

```xml
<application
      android:name=".myapp"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:windowSoftInputMode="adjustResize"
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:screenOrientation="portrait"
        android:configChanges="orientation|screenSize">
```

http://stackoverflow.com/a/5913370

**Comment by FlorianeEnnaji** [comment]
You were right. I'm sorry, thank you for your answer!

**Comment by sadikelong** [comment]
@yfuks , For Spring Festival, I have no response in time. This issue is not relate with your code, I think it has something with Android runtime permissions.
@FlorianeEnnaji , do you have a log screenshot? Is the log show 【Couldn't find method canDrawOverlays, referenced from method com.facebook.react.ReactActivity.onCreate】.
