### ISSUE TITLE
[iOS] Camera doesn't launch

### ISSUE THREAD

**Issue by qasimalbaqali** [marcshilling/react-native-image-picker#101]
The choose picture from library works perfectly and nothing is wrong with it, but take photo button which should launch the camera doesn't. Using the same exact code from the example, as I said the choosing a picture from library works perfectly just the camera part which doesn't work. Is there a bug currently with the camera launch? Do I need to set permission first for it to work?

**Comment by marcshilling** [comment]
Yes it requires permission, which is requested automatically upon the camera opening.

Let's get the obvious questions out of the way - are you on the iOS simulator?

**Comment by qasimalbaqali** [comment]
@marcshilling  Yes. Stupid me didn't check the console log until now. I have to build it on a real iphone for it to launch the camera.

**Comment by marcshilling** [comment]
No worries...yup just build it on your device and it should work!
