### ISSUE TITLE
[iOS] Add .xcode for easiest installation

### ISSUE THREAD

**Issue by yfuks** [marcshilling/react-native-image-picker#102]
@marcshilling :)
I think that could be a great enhancement ! I don't really know how it work but other modules does this way it's much more simple !

**Comment by marcshilling** [comment]
Yeah, I've been meaning to get around to doing this. I'll get around to it soon.

**Comment by jamesone** [comment]
What is this for @yfuks

**Comment by yfuks** [comment]
@jamesone 
It's simplify iOS native library linking in xcode project !

**Comment by jamesone** [comment]
@yfuks  - Nice. Although it's super easy to do at the moment :) Hopefully it will benefit other using the component!

**Comment by marcshilling** [comment]
@yfuks done in 0.14.1!

**Comment by yfuks** [comment]
Nice! Thank you :+1:
