### ISSUE TITLE
Testing Example project on Ipad: error when choosing photos from library

### ISSUE THREAD

**Issue by riccardod** [marcshilling/react-native-image-picker#103]
Hi,
I have a problem on Ipad devices. 
I tested the Example project and it runs fine both for photos and for library pictures  on Iphone devices.
On IPad, taking pictures from camera works fine but when I try to choose from library I get an error at main.m file at line:
` return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
`

**Comment by marcshilling** [comment]
I can't reproduce this...choosing photos works fine on my iPad Air 2 simulator. Are you testing on a simulator (which one)? On device (which one)?

**Comment by riccardod** [comment]
Hi, I tried the example project both on ipad Air 2 device and on the simulator.
The problem only appears in landscape mode.

**Comment by marcshilling** [comment]
Works in landscape for me also...

**Comment by riccardod** [comment]
Here is what I did :
- Checked out the repository
- cd in the react-native-image-picker/ios/Example
- npm install
- Selected Ipad Air as a simulator 
- Ok path: Selectiong "Portrait" as device orientation, run the project then select ->Photo (first circled button)->Choose from library: Works as expected and let select photos
- Not Ok path: Deselecting "Portrait" as device orientation (leaving "Landscape")-> Photo ->Choose from library -> Error
I recorded a 30 seconds video showing the problem http://cl.ly/0P1W0O3V293M

**Comment by marcshilling** [comment]
Interesting. If you leave Portrait selected, and then actually rotate the device to landscape, it works. Is this not sufficient? Are you trying to lock your app to landscape mode? 

Don't really have time to investigate right now but I will look into it when I can. Until then, PRs are always welcome.

**Comment by marcshilling** [comment]
The issue is that UIImagePickerController does not support landscape mode. I don't plan on moving away from using the built-in iOS solution for this, so you may be out of luck with this library if you need a landscape only app. Sorry :(

**Comment by riccardod** [comment]
Adding portrait mode is ok for me.
