### ISSUE TITLE
.gif support

### ISSUE THREAD

**Issue by cpsiaki** [marcshilling/react-native-image-picker#106]
This package is incredible. Thanks so much for putting it together.

Is there .gif support? Is that a feature that might be in the works? Is it there and I've missed it?

Thanks.

**Comment by yfuks** [comment]
It's already there for iOS, not for Android

**Comment by yfuks** [comment]
@cpsiaki 
Well i have a "good" info. I try something with *.gif* on **Android**.
You can get animated gif if you don't resize the image and you do like folowing : 

```javascript
/*
 * Don't use the folowing options :
 * maxWidth - maxHeight
 * angle
 * quality
 */
var options = {
  title: 'Select Avatar',
  cancelButtonTitle: 'Cancel',
  takePhotoButtonTitle: 'Take Photo...',
  chooseFromLibraryButtonTitle: 'Choose from Library...',
  noData: false, // we use response.data to display gif
  allowsEditing: false // make sure we don't edit the gif
};

ImagePickerManager.showImagePicker(options, (response) => {
  const source = {uri: 'data:image/gif;base64,' + response.data};
});
```
Sorry i know it's not very mutch but animated gif on **Android** are in a particular [Class](http://developer.android.com/reference/android/graphics/Movie.html) and it's make it harder to manage
