### ISSUE TITLE
[iOS]  Rebuild or First App Update, Lost Image

### ISSUE THREAD

**Issue by Max93** [marcshilling/react-native-image-picker#107]
On iOS images was stored in Documents folder. The Document folder was stored into an folder with an hexadecimal name. This folder is regenerated and renamed for each build. For this reason if you store the absolute URL of image you loose the reference from it.

For this reason I propose to return the name of the image and the path declared on storageOptions.

I know is simple to get this information from absolute URL (simple JS String manipulation) but for me is important to inform programmer of the possibility to lose their references from love pictures.

Thank's.

**Comment by marcshilling** [comment]
I'm not sure I follow...

The Documents folder should always persist for an app on the same device. Are you using the iOS simulator?

**Comment by Max93** [comment]
yep I'm using iOS simulator, but i have tested it into app in production

**Comment by marcshilling** [comment]
Gotcha, so the path TO the Documents directory could change, but once inside your Documents directory, everything remains the same. 

I think this falls a little outside the responsibility of this image picker component. We are returning the absolute path where the photo is **at that current moment**, AND since the photos are being saved to the Documents directory, we've guaranteed that they will be persisted forever on the device as long as the app is installed. It should be up to the developer to then know to never rely on the absolute path and maybe use something like [react-native-fs](https://github.com/johanneslumpe/react-native-fs) to find the path to the Documents directory.

This is definitely valuable information to know though, so thank you!

**Comment by Max93** [comment]
you are right ... it is outside the the responsibility of this image picker component. But the picker return an absolute path and it's good to inform the coder about the possibility to loose their (only the reference) photo.

**Comment by marcshilling** [comment]
I added a note to the README referencing this issue. Thanks for bringing it my attention!

**Comment by puredazzle** [comment]
Hello,

Wouldn't it be good then if the plugin also returned only the filename?

**Comment by i-tu** [comment]
Just letting you know that I found an alternative to using [react-native-fs](https://github.com/johanneslumpe/react-native-fs).

A path prepended with `~` expands to the app Documents directory.

See https://github.com/facebook/react-native/commit/23909cd6f62056de0cd0f7c06e3997dd967c139a

**Comment by redconnect** [comment]
@i-tu This solution works if you prefix with ~/Documents/images e.g. `~/Documents/images/myimage.png`

**Comment by jsina** [comment]
@Max93 could you give me some hint how could I get the uri when I'm taking the photo on IOS?

**Comment by jsina** [comment]
@i-tu could you please give me more description?
how could I get the image absolute uri on code below?
```
gePicker.showImagePicker(options, (data) => {})
```

**Comment by jsina** [comment]
@xhw1993 this is all what I've done
```
 selectPhotoTapped = () => {
    const options = {
      title: 'عکس پروفایل خود را انتخاب کنید',
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true,
        // waitUntilSaved: true,
        // cameraRoll: true,
      },
      cancelButtonTitle: 'خروج',
      takePhotoButtonTitle: 'عکس گرفتن...',
      chooseFromLibraryButtonTitle: 'انتخاب از گالری...',
    };
    ImagePicker.showImagePicker(options, (response) => {
      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        this.resetErrorState();
        this.props.dispatch(uploadProfilePic(response));
      }
    });
  };
```

**Comment by reactdevrocks** [comment]
@jsina use this for ios
`(Platform.OS==='android') ? response.uri : response.uri.replace('file://', '')`
and in options
`storageOptions: {
        skipBackup: true,
        path: 'images',
        cameraRoll: true,
        waitUntilSaved: true
      }`

**Comment by ManigandanRaamanathan** [comment]
> @jsina use this for ios
> `(Platform.OS==='android') ? response.uri : response.uri.replace('file://', '')`
> and in options
> `storageOptions: { skipBackup: true, path: 'images', cameraRoll: true, waitUntilSaved: true }`

Is this working? @jsina

**Comment by ifo234** [comment]
I run into this issue as well, but my source was RNCamera. in some phone the "~" fix the problem to recover images but there was phone where only react-native-fs worked to get the correct path (which works for ios and android):

`var RNFS = require('react-native-fs');
RNFS.DocumentDirectoryPath`

**Comment by rahulmishra1991** [comment]
> @jsina use this for ios
> `(Platform.OS==='android') ? response.uri : response.uri.replace('file://', '')`
> and in options
> `storageOptions: { skipBackup: true, path: 'images', cameraRoll: true, waitUntilSaved: true }`

Yes that works for me...Thanks for sharing.

**Comment by Johan-dutoit** [comment]
Updated the title to make it easier to understand the problem while pinned.

**Comment by aaz11zaa** [comment]
https://github.com/react-native-community/react-native-image-picker/issues/107#issuecomment-450341021

**Comment by sinodko** [comment]
> @jsina use this for ios
> `(Platform.OS==='android') ? response.uri : response.uri.replace('file://', '')`
> and in options
> `storageOptions: { skipBackup: true, path: 'images', cameraRoll: true, waitUntilSaved: true }`

This is not working for me. After closing metro server and restarting the app i cant open the file

**Comment by jordangrant** [comment]
Solution based on the discussion: (tks for the hints guys)

```
const options = {
     title: 'Select Avatar',
     storageOptions: { skipBackup: true, path: 'images', cameraRoll: true, waitUntilSaved: true },
};

ImagePicker.showImagePicker(options, (response) => {
   var path = response.uri;
   if (Platform.OS === 'ios') {
      path = '~' + path.substring(path.indexOf('/Documents'));
   }

   if (response.didCancel) {
      console.log('User cancelled image picker');
   } else if (response.error) {
      console.log('ImagePicker Error: ', response.error);
   } else {
      this.changeAvatar(path);
   }
});
```
FYI this is the path before transforming it, and after it's just ~/Documents.....
![IMG_0043](https://user-images.githubusercontent.com/7986493/64582465-919d4a80-d35b-11e9-8ae9-2202dd84e830.jpg)
