### ISSUE TITLE
use rnpm for easier install

### ISSUE THREAD

**Issue by sebathi** [marcshilling/react-native-image-picker#111]
https://github.com/rnpm/rnpm

**Comment by marcshilling** [comment]
Is there something that needs to be done in order for rnpm to work? Shouldn't `rnpm install react-native-image-picker` install and link the library without any additional config or am I missing something?

**Comment by cldwalker** [comment]
I just tried this with rnpm 1.4.1 and react-native-image-picker 0.17.0 on android and `rnpm link react-native-image-picker` almost works. The only tweak I had to make was in android/app/src/main/java/com/badinstagram/MainActivity.java change `new ImagePickerPackage()` to `new ImagePickerPackage(this)`. @marcshilling If you can adjust newImagePickerPackage argument, this should work out of the box for android.

If I don't make the above change, `react-native run-android` eventually errors with:
```sh
:app:generateDebugSources
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/me/.gitbeam/BadInstagram/android/app/src/main/java/com/badinstagram/MainActivity.java:40: error: constructor ImagePickerPackage in class ImagePickerPackage cannot be applied to given types;
        new ImagePickerPackage(),
        ^
  required: Activity
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED
```

**Comment by yfuks** [comment]
Will make the folowing change :)

**Comment by yfuks** [comment]
Since it's a breaking change i update image-picker to **0.18.0** ...
From **0.15.0** to **0.18.0** in 3 days well... let's say no one see that :D

**Comment by yfuks** [comment]
Just a question @cldwalker, you don't get any issue with permissions ?

**Comment by cldwalker** [comment]
@yfuks Great. I don't think so. I was able to take pictures and select photos fine. Also confirmed `rnpm link` works for ios device. Would be helpful to update README to mention `rnpm`

**Comment by marcshilling** [comment]
I don't plan on adding a mention of `rnpm` to this README. It's far more important to explain the vanilla installation instructions. If people are aware of rnpm and want to use it, it works.
