### ISSUE TITLE
Creating a file size of 0?

### ISSUE THREAD

**Issue by skleest** [marcshilling/react-native-image-picker#113]
Using iOS, RN 0.13.2. CameraRoll access is working well, but taking a picture with it creates a filesize of 0 with no content. Played around with camera options (quality, allowsEditing, nodata, storageOptions) all without success. Any ideas here? Thank you.

**Comment by OwaysisApp** [comment]
+1

**Comment by marcshilling** [comment]
Make sure you're updated to the latest version, there was a bug but taking a photo works for me now. 

post some code?

**Comment by skleest** [comment]
Oh wow, using npm install @latest did do the magic for me (first installed the component only two days ago, but probably didn't use @latest). Thanks!
