### ISSUE TITLE
[iOS] Is it possible to customize the actionsheet tint color?

### ISSUE THREAD

**Issue by kkgelu** [marcshilling/react-native-image-picker#114]
This is what I would like to have on iOS:
```
  self.alertController.view.tintColor = [UIColor redColor];
```
but do it from JS.  Thanks.

**Comment by yfuks** [comment]
**PR** are the best way to offers a new feature ! :)

**Comment by yfuks** [comment]
@kkgelu 
Since it exist an [ActionSheetComponent](https://facebook.github.io/react-native/docs/actionsheetios.html#content) that allow you to change the tint color i recommend you to use it and use the folowings function from this module : 
```javascript
imagePicker.launchCamera(options, (response)  => {
  // handle response
});
```
```javascript
imagePicker.launchImageLibrary(options, (response)  => {
  // handle response
});
```

**Comment by williambout** [comment]
+1 for tintColor support
