### ISSUE TITLE
[iOS] Video Recording Max Time

### ISSUE THREAD

**Issue by yamill** [marcshilling/react-native-image-picker#115]
I think it would be nice if we could limit the video recording max time

**Comment by yfuks** [comment]
**PR** are the best way to offers a new feature ! :)

**Comment by yfuks** [comment]
option ```durationLimit``` have been added with video picking in **Android**
Version **0.17.0**
Not available on iOS for the moment

**Comment by yamill** [comment]
@yfuks awesome thanks :)

I'll see if I can maybe take a shot at submitting a PR for this.
