### ISSUE TITLE
[Android] If allowsEditing is set in options, response is always returned with didcancel as true

### ISSUE THREAD

**Issue by nickv118** [marcshilling/react-native-image-picker#117]
Hi guys.

I would appreciate if somebody can help me with my issue.

I have integrated this library in react native application, but when allowsEditing is set to true, the picker result always contains only 'didcancel:true' and no image data or uri in it.

This only happens in android.

I would like to hear your thoughts on this.

Thanks.
Nick.

**Comment by yfuks** [comment]
The module return ```didCancel``` after you crop the image?
Or you pick the image and it directly return ```didCancel```?

**Comment by marcshilling** [comment]
Sounds like you're on an old version. Upgrade and read the docs

**Comment by nickv118** [comment]
@yfuks it's after i crop the image, but there's no way to complete action without crop though, it was mandatory to do crop after i chose an image.

@marcshilling i am already using latest version. 0.15.0

**Comment by marcshilling** [comment]
Go ahead and post some code then

**Comment by nickv118** [comment]
@marcshilling  here's the main code i used.

`defaultPhotoOptions = {
    title: 'choose photo',
    cancelButtonTitle: 'cancel',
    takePhotoButtonTitle: 'camera',
    chooseFromLibraryButtonTitle: 'gallery',
    quality: 0.9,
    noData: false, 
    maxWidth: 176,
    maxHeight: 176,
    allowsEditing: true
}

UIImagePickerManager.showImagePicker(defaultPhotoOptions, (response) => {
            console.log('picker result: ', response);
            if (response.didCancel)
                return
            handler(response) //handler is defined somewhere else.
        })
`

**Comment by marcshilling** [comment]
I'll have to defer this one to you @yfuks. I am able to reproduce, but can't figure out the issue. The crop operation calls `onActivityResult` with `resultCode = 0`, triggering the `didCancel` callback. 
Another thing of note, I get a Toast that says "Unable to save cropped image."

**Comment by yfuks** [comment]
Also reproduce it :)
Probably a problem with the way we save the croped image.

**Comment by yfuks** [comment]
If you really need to make it work quickly, add

```javascript
storageOptions: {}
```

in your options

**Comment by yfuks** [comment]
So it seems that the croping intent can't read into the internal storage of the app
http://stackoverflow.com/a/24418124

**Comment by yfuks** [comment]
Fix in **0.15.1**
I have issue with publish don't really know why @marcshilling can you try?

**Comment by nickv118** [comment]
isnt 0.15.1 not published to npm?

**Comment by yfuks** [comment]
@nickv118 0.16.0 published ! :)
