### ISSUE TITLE
[Android - iOS] multi select

### ISSUE THREAD

**Issue by gre** [marcshilling/react-native-image-picker#119]
not sure if it is out of scope of this, but it would be great if this would support image multi-selection.

like in https://github.com/questbeat/QBImagePicker

![](https://github.com/questbeat/QBImagePicker/blob/master/screenshot02.png?raw=true)

**Comment by yfuks** [comment]
**PR** are the best way to offers a new feature ! :)

**Comment by yfuks** [comment]
It can be done in **Android** for sure. Don't know about **iOS**

**Comment by marcshilling** [comment]
I'm not sure if I want to support this. If anything, I would want it to be an option (defaults to single selection), but at that point we'd literally be using 2 completely different image selection libraries. Not to mention I think it's crazy to depend on ANOTHER open source library to accomplish this. UIImagePicker is built into iOS and does not support multiple selection, so anyone looking for that functionality already knows up front that they need to roll their own solution. If you really want this, I'd suggest building your own react native wrapper around QBImagePicker.

**Comment by gre** [comment]
yeah make sense, that's what I've been doing, QBImagePicker default to "single selection" already so we could easily make a react-native-qb-image-picker.
