### ISSUE TITLE
[Android] Options are not overriden

### ISSUE THREAD

**Issue by xiaobuu** [marcshilling/react-native-image-picker#120]
If showImagePicker is called with allowsEditing set to true once, all other showImagePicker calls will finally have the image editor open, even allowsEditing isn't set, I'm not sure whether other options are overriden. This behaviour doesn't occur on ios.

**Comment by yfuks** [comment]
just set
```
allowsEditing: false
```
if you want to override the option

**Comment by yfuks** [comment]
@marcshilling in iOS all options are "reset" when you ```showImagePicker``` one again ?
Or option is set to false when key is not set ?

**Comment by marcshilling** [comment]
@yfuks it is set to false by default and options are reset every call

**Comment by yfuks** [comment]
fix in **0.16.1**
