### ISSUE TITLE
Android no picture back

### ISSUE THREAD

**Issue by rainmeterLotus** [marcshilling/react-native-image-picker#121]
I run on android,use "ImagePickerManager.launchImageLibrary" ,but nothing back!!!the log is not !!

**Comment by rainmeterLotus** [comment]
because of ImpagePickerMoudle's onActivityResult no call

**Comment by marcshilling** [comment]
The API recently changed...update to the latest version, update your code based on the README, and then if you are still having issues come back and post some of your code.

**Comment by marcshilling** [comment]
@rainmeterLotus any update here?

**Comment by agutoli** [comment]
Hello @marcshilling @rainmeterLotus, I fix it and solve for me... https://github.com/marcshilling/react-native-image-picker/pull/130

**Comment by marcshilling** [comment]
Closing because this is a React Native versioning issue. This library will be kept up to date with the latest version of RN.
