### ISSUE TITLE
[Question] Is it using the native component or creating a very similar web view clone?

### ISSUE THREAD

**Issue by ahmedbaracat** [marcshilling/react-native-image-picker#122]

**Comment by bcalik** [comment]
You can not pick image using WebView. File inputs won't work. This is native.

**Comment by ahmedbaracat** [comment]
Thank you, but does this work with live reloads without compiling? I am new to React :)

**Comment by bcalik** [comment]
It will probably require recompiling because installation process require modifying Android app permissions, java files etc.

**Comment by ahmedbaracat** [comment]
One last thing....Is it the same for iOS?

**Comment by bcalik** [comment]
Probably yes, but why does it bother you? You will only compile once after installation, then you can work with live reloads.

**Comment by ahmedbaracat** [comment]
I am asking this, and correct me if I am wrong, because I may be changing the labels or the buttons of the image picker and seeing if this would mean that I will recompile or not.

**Comment by bcalik** [comment]
No you won't need to recompile, because you will not touch any ios or android files while changing the views.

**Comment by ahmedbaracat** [comment]
I am not sure I am following, So I am chaining the labels and the buttons of the image picker which is a native view, but don't need to recompile, How is that possible?

**Comment by bcalik** [comment]
Buttons and labels are on your javascript code, that is how react works. This question is not relevant with the image picker. This component only gives you a javascript helpers to call your image gallery app or camera app to pick/shot images. Then it returns to your react app and callback function gives you the photo.

**Comment by ahmedbaracat** [comment]
So the image picker component is handling rendering the view, it is essentially wrapping the native APIs, right?

**Comment by marcshilling** [comment]
Yes. The native image picking components are being used on both platforms.
