### ISSUE TITLE
Picking video doesn't return a real path

### ISSUE THREAD

**Issue by Anthonyzou** [marcshilling/react-native-image-picker#124]
When prompting for videos on Android what gets returned is not an actual file path. 
What gets returned from `showImagePicker` is something like `{ uri: 'content://media/external/video/media/30267' }`

**Comment by yfuks** [comment]
[Android URI](http://developer.android.com/reference/java/net/URI.html) (i re-post to you...)

But well i guess you don't want to read so...
Uri is the way to access a data in Android, not the filepath.
I don't know why it seems "useless" to you. Please read some doc.

And that's specified by the [README.md](https://github.com/marcshilling/react-native-image-picker/blob/master/README.md)
> response.uri is the uri to the local file asset on the device (photo or video)

**Comment by Anthonyzou** [comment]
what gets returned for video is something like this 'content://media/external/video/media/30267'.
This is not an actual path to any file man

**Comment by yfuks** [comment]
Well i have to explain it to you over and over...

That's because it's an Android URI
Please read the [doc](http://developer.android.com/reference/java/net/URI.html) about Android URI..... **Seriously do it** !!!!
You don't need the filepath because you have the uri.

Tell me one, only one case that you can't use an uri and you need a filepath ????

Ps : You don't need to open 2 **issues** and 1 **PR** for that. One **PR** was certainly enough

**Comment by Anthonyzou** [comment]
I am using this library https://github.com/comiclee/react-native-fileupload/
I need the absolute file path...
```javascript
    var obj = {
        uploadUrl: 'http://127.0.0.1:3000',
        method: 'POST', // default 'POST',support 'POST' and 'PUT'
        headers: {
          'Accept': 'application/json',
        },
        fields: {
            'hello': 'world',
        },
        files: [
          {
            name: 'one', // optional, if none then `filename` is used instead
            filename: 'one.w4a', // require, file name
            filepath: '/xxx/one.w4a', // require, file absoluete path
            filetype: 'audio/x-m4a', // options, if none, will get mimetype from `filepath` extension
          },
        ]
    };
```
