### ISSUE TITLE
Add a path attribute when picking videos so it matches what is returned from images

### ISSUE THREAD

**Issue by Anthonyzou** [marcshilling/react-native-image-picker#125]
When you pick images what gets returned is an object similar to this

  ```json
  { "path": "/storage/emulated/0/Pictures/image-7dda44cb-8d84-4df4-82b6-f23dd581d4d3.jpg",
    "uri": "file:///storage/emulated/0/Pictures/image-7dda44cb-8d84-4df4-82b6-f23dd581d4d3.jpg",
    "height": 2048,
    "width": 1536,
    "isVertical": true }
  ```

Videos however only return a content type uri.

  ```json
  { "uri": "content://media/external/video/media/170" }
  ```

What the actual path to the above is this

    /storage/emulated/0/Download/stock-footage-close-approach-to-waterfall-by-boat-milford-sound-fjord-south-island-new-zealand.mp4

What would be ideal is videos returning an object like this

  ```json
  { "path": "/storage/emulated/0/Download/stock-footage-close-approach-to-waterfall-by-boat-milford-sound-fjord-south-island-new-zealand.mp4",
  "uri": "content://media/external/video/media/170" }
  ```

**Comment by yfuks** [comment]
For what purpose ?
The ```path``` is more there for debug than for a real usage (it's not even in README)

**Comment by Anthonyzou** [comment]
the react native upload library I use has an API where It will uploaded based on the absolute file path.

I could live without the path attribute but the uri for video is not close to a file path.

https://github.com/comiclee/react-native-fileupload/

```javascript
    var obj = {
        uploadUrl: 'http://127.0.0.1:3000',
        method: 'POST', // default 'POST',support 'POST' and 'PUT'
        headers: {
          'Accept': 'application/json',
        },
        fields: {
            'hello': 'world',
        },
        files: [
          {
            name: 'one', // optional, if none then `filename` is used instead
            filename: 'one.w4a', // require, file name
            filepath: '/xxx/one.w4a', // require, file absoluete path
            filetype: 'audio/x-m4a', // options, if none, will get mimetype from `filepath` extension
          },
        ]
    };
```

**Comment by yfuks** [comment]
Well first of all i highly recommend you to not use this module since there is no official support since december 2015 and it don't support uri.

Looks like [react-native-file-uploader](https://github.com/farmisen/react-native-file-uploader) support uri. (no support since 13 jan too :/)

And if you really want to use [react-native-fileupload](https://github.com/comiclee/react-native-fileupload/) ask for an uri support.
