### ISSUE TITLE
Preview aspectX and aspectY in editing mode

### ISSUE THREAD

**Issue by williambout** [marcshilling/react-native-image-picker#127]
Hi,
In editing mode, the mask for resizing is square.
Would it be possible to use aspectX and aspectY values in order to change the mask's ratio ?

**Comment by yfuks** [comment]
For **Android** yes. Options ```aspectX``` and ```aspectY``` are not implemented for **iOS**.

https://github.com/marcshilling/react-native-image-picker#options

**Comment by marcshilling** [comment]
On iOS, we're just using the default editing mode of UIImagePickerController, which only supports a square mask. I don't plan to stray away from the default native behavior with this library.
