### ISSUE TITLE
Not working with RN 0.19+?

### ISSUE THREAD

**Issue by skleest** [marcshilling/react-native-image-picker#129]
It's working on simulator, but not on physical device here.
Console error: 'One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.'

Any ideas? It happened after updating from RN0.13 to 0.21, then I tried 0.20 and 0.19. I changed require function form RNImagePicker to ImagePicker. Thank you.

**Comment by marcshilling** [comment]
var ImagePickerManager = require('NativeModules').ImagePickerManager;

**Comment by yfuks** [comment]
Are you sure it's an issue with this module ?

Can you paste the full log ?

**Comment by skleest** [comment]
I'm not 100% sure but this is what I know:
-Module works on simulator (uploading a picture from gallery)
-If I run it on device, the app does not start, just a blank white screen shows. Error message is only displayed in console, and it just states the log pasted above, nothing else
-If I remove the require statement for ImagePicker, the app runs fine.
Any other information I can provide to help?

**Comment by yfuks** [comment]
Please check the folowing issues on React-native repo (look like your)
https://github.com/facebook/react-native/issues/5507#issuecomment-190541129
https://github.com/facebook/react-native/issues/3634

> If I remove the require statement for ImagePicker, the app runs fine.

ImagePicker is the only native module in your app ?

**Comment by skleest** [comment]
Thanks, I actually came across both of those issues as well. I have downgraded RN all the way to 0.16 and it works as expected now (so I'm guessing issue with 0.17+). I have other native modules like FB login that are working, as well as an Array polyfill. If anyone sees this issue and has RN 0.17+ working fine on device (debug mode/loaded from server), I'd love to know.

**Comment by davidjeffries** [comment]
Running this project with no problems on RN 0.21

**Comment by yfuks** [comment]
@skleest we almost have the same instalation with **FB login** (for **Android**) i don't know what to say..

You sure you update your installation and your file ? Or you just update the **RN** version in your package.json ?

**Comment by marcshilling** [comment]
Closing this. See the code I posted in #136 if you're still having issues.

**Comment by skleest** [comment]
Got it, thanks for your work everyone.
