### ISSUE TITLE
How to get an asset URI from the base64 image

### ISSUE THREAD

**Issue by eyaleizenberg** [marcshilling/react-native-image-picker#13]
Hi,
Good stuff with the component! Thanks a lot!

I am able to successfully upload an image to s3 when I choose an existing image from the camera roll. However, I am unable to do so with the base64 data that the 'take picture from camera' returns.

So my questions are:
1. Were you able to upload a base64 image to s3 use xhr? If yes, can you share some code? (specifically the part where/if you converted the base64 so amazon could handle it?)

2. Do you know how I can save the base64 data to an image in the camera roll in order for me to get the asset uri which I can easily upload to s3?

Thanks a lot!

**Comment by alejomendoza** [comment]
Hey @eyaleizenberg check out the native module https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageStoreManager.m

**Comment by alejomendoza** [comment]
if you import the module you can do NativeModules.getBase64ForTag() etc...

**Comment by eyaleizenberg** [comment]
@alejomendoza sorry, I am really ignorant when it comes to objective C. What can I do with this module in regard to my questions?

**Comment by marcshilling** [comment]
The uri response now returns the uri to the local file system asset in the /tmp directory. I think the issue of uploading the image is solved by that.
