### ISSUE TITLE
[iOS] Not getting any base64 data back from the camera. 

### ISSUE THREAD

**Issue by nicholasstephan** [marcshilling/react-native-image-picker#137]
Using the options below, I'm getting a base64 `data` value back when the user picks an image from their library but just an empty string when they take a new photo.

What am I doing wrong? 

`{
      title: 'Upload Photo',
      cancelButtonTitle: 'Cancel',
      takePhotoButtonTitle: 'Take Photo...',
      chooseFromLibraryButtonTitle: 'Choose from Library...',
      noData: false,
      mediaType: 'photo',
      quality: 0.2,
}`

**Comment by yfuks** [comment]
On **Android** on **iOS** or both ?

**Comment by nicholasstephan** [comment]
Just on iOS.

**Comment by yfuks** [comment]
@marcshilling an idea ?

**Comment by marcshilling** [comment]
@nicholasstephan just tested the latest code on device with your same options and data returned successfully, so I'm not sure what's going on with you. I will note that it took ~10 seconds to return, but it did eventually finish. Transmitting all that base64 data is not very performant, I'd recommend you specify `maxWidth`/`maxHeight`. When I set those to `300`, the return was almost instantaneous.

**Comment by nicholasstephan** [comment]
Thanks for the quick response. Adding max widths and heights makes sense, I'll definitely do that. 

But I'm still getting just an empty string. I'll fire up a new react-native project to try to isolate the problem, or prove it's something else somehow causing the trouble.

**Comment by kanerogers** [comment]
I'm having the same issue on iOS. `noData: false` is returning an empty string.

What's more, though I'm getting a `uri` back in the response, if I try to display the image with a `<Image />` component, I just see white space. :crying_cat_face:

**Comment by marcshilling** [comment]
I don't know what to tell you guys...it's working for me.

@kanerogers as far as the uri is concerned, you are likely just using `<Image>` incorrectly...
`<Image style={styles.avatar} source={{uri: response.uri.replace('file://', ''), isStatic: true}} />`

**Comment by kanerogers** [comment]
Thanks for the tip, Marc, but this was working for me previously on iOS. As
such I do think I have the Image component configured correctly, as it
still works fine on Android. 😊

I have, however, recently upgraded to RN21 - what version are you testing
on. Maybe something is going on there?

K

**Comment by kanerogers** [comment]
FWIW I've tried upgrading to the latest version of the component, but it's
made no difference.

What can I do to help pin down the issue, Marc?

**Comment by marcshilling** [comment]
Just published v0.18.3, which includes an Example project at the root using React Native 0.21. Again, taking a photo successfully returns a base64 string for me. Can you run the Example project and report your results?

**Comment by kanerogers** [comment]
Hey there, Marc,

Gave it a shot, and it worked fine!

Upon closer inspection, it looks like I had *not actually upgraded *to the
latest version. Once I changed my imports in my iOS project, imported the
latest version of the library and recompiled, everything worked perfectly.

Thank you so much for your patience!

**Comment by marcshilling** [comment]
Great! @nicholasstephan did you get it figured out?

**Comment by nicholasstephan** [comment]
@marcshilling, I haven't tried in my main app yet, but I put together a quick test project using React Native v0.21 and your new v0.18.3 and everything worked perfectly! So I think I'm good.

Thanks for the help.
