### ISSUE TITLE
why？？

### ISSUE THREAD

**Issue by mvpdream** [marcshilling/react-native-image-picker#138]
![image](https://cloud.githubusercontent.com/assets/16203724/13594076/5b6f9e7e-e53c-11e5-98a0-78fefb2c9152.png)

**Comment by yfuks** [comment]
You probably update your **RN** version in you package.json but not in your native code
```
react-native upgrade
```

**Comment by marcshilling** [comment]
You have an issue with your RN environment, not this library.
