### ISSUE TITLE
Any changelog file ? Any github release ?

### ISSUE THREAD

**Issue by guizmaii** [marcshilling/react-native-image-picker#139]
Could you add a CHANGELOG.md file in your project (you can find a good start here : http://keepachangelog.com/) to track changes please ? It will help the community to follow you and your project. 

And could you tag your releases with Github releases please ? It'll greatly help to !

Thanks ;)

**Comment by marcshilling** [comment]
I'll start creating releases when I publish to npm. I just created the first one now. I'll make sure these include relevant information in the notes also, so a CHANGELOG.md shouldn't be needed.

@yfuks if you publish to npm in the future, create a release on here as well and describe the changes. Thanks! :)

**Comment by guizmaii** [comment]
Thanks =)

Note : A changelog file is easier for you to maintain because people could add a line by them self and you're not oblige to do this annoying job ;)

**Comment by yfuks** [comment]
@marcshilling no problem !

@guizmaii we rarely have 20 changes for a new release that's not to mutch to deal with ^^
And i feel like github releases are a bit more clear
