### ISSUE TITLE
It works great on simulator ,but failed with real device

### ISSUE THREAD

**Issue by nwpuhmz** [marcshilling/react-native-image-picker#14]
hi,
it works great on simulator ,but on the real device (iOS 8.1)showing this error message:
undefined is not an object(evaluating 'UIImagePickerManager.showImagePicker")

Is there something wrong with linking lib ?

Your early reply will be appreciated.Thanks !

**Comment by marcshilling** [comment]
Works fine on device for me. Are you still having issues?

**Comment by nevir** [comment]
I'm seeing this as well with an optimized bundle
