### ISSUE TITLE
Can't see taken photo in Photos app [iOS]

### ISSUE THREAD

**Issue by gorjanz** [marcshilling/react-native-image-picker#141]
I am calling the camera directly, with the following code:
```
ImagePickerManager.launchCamera(config.imagePickerOptions, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      }
      else if (response.error) {
        console.log('ImagePickerManager Error: ', response.error);
      }

      else {
        // save the uri to Async Storage
      }
    });
  }

config.imagePickerOptions: {
    title: 'Choose photo',
    cancelButtonTitle: 'Cancel',
    takePhotoButtonTitle: 'Take Photo...',
    chooseFromLibraryButtonTitle: 'Choose from Library...',

    cameraType: 'back',
    mediaType: 'photo',
    videoQuality: 'high',
    durationLimit: 10, 
    maxWidth: 1000,
    maxHeight: 1000,
    aspectX: 2,
    aspectY: 1,
    quality: 0.2,
    angle: 0,

    allowsEditing: false,
    noData: true, 
    storageOptions: {
      skipBackup: true,
      path: 'images'
    }
  }
```

I want to be able to see the photo, in the native photos/gallery apps, both on iOS and android. I can't seem to be able to see them, when I take a photo, come back to my react-native app, and then open one of the native gallery / photos apps.
On android, I was able to find it manually via file system explorer app, but it was still not showing in the native gallery apps.

Is there something I am missing, or am I using some option incorrectly?

**Comment by marcshilling** [comment]
That's not how this module works. It does not save photos to the camera roll or gallery - you either choose an existing one or take one to use immediately. If you are getting photo information back after you take the initial photo, everything is working correctly.

**Comment by gorjanz** [comment]
I need the photo saved to the device, in order for later in time, to take all taken photos programmatically, and upload them to a file server.
How would you propose I do this? Because my plan was, to use this module to take the photo and store it on the device, and save the name/uri of the photo, in order for later to know which are the photos, and upload them manually.

My problem is that, I want to upload the image, in byte multi parts, and not in base64 encoded format.
Any thoughts on how this can be achieved?

**Comment by marcshilling** [comment]
Sounds like you have more complex requirements than this library is intended for. 

I will say that I've successfully uploaded images to a server using this library in conjunction with [react-native-file-upload](https://github.com/booxood/react-native-file-upload). If your end-goal is uploading to a server, use the uri, not data.

**Comment by gorjanz** [comment]
But, if I do not pass the base64 encoded data, only the uri, will the image the user just took, be saved somewhere, in order to be accessed later, by using the uri?

**Comment by marcshilling** [comment]
Please read the README...all the information is there.

If you supply the `storageOptions` key, the selected photo will be SAVED to the Documents directory for the application. Then, yes, that uri returned can be used at any time to access the saved photo.

**Comment by gorjanz** [comment]
Thanks for the information. I am pretty new to iOS development and the whole eco-system, so it is not clear for me, wether saving the image in the Documents directory, enables the image to be viewed by the  camera roll.

**Comment by marcshilling** [comment]
If you want, it looks like you can use [this](https://facebook.github.io/react-native/docs/cameraroll.html) to save the uri returned from this library to the Camera Roll/Gallery.
