### ISSUE TITLE
 Class ImagePickerManager was not exported

### ISSUE THREAD

**Issue by ivanbabanov** [marcshilling/react-native-image-picker#145]
I'm receiving error message when I'm running app on iOS:
2016-03-11 01:34:22.670 [info][tid:main][RCTBridge.m:120] Class ImagePickerManager was not exported. Did you forget to use RCT_EXPORT_MODULE()?

I see that RCT_EXPORT_MODULE() is used into ImagePickerManager.m 
I'm using ReactNative 0.18 (Could it be a problem?) I'm getting "null" object when I'm trying to use ImagePickerManager in JS code.

**Comment by ivanbabanov** [comment]
Looks like upgrade to React-Native 0.20 solved problem

**Comment by marcshilling** [comment]
Cool, but I'm curious what about lower versions of React Native cause an issue. Because I've been developing this since ~0.12 and thought I was always compatible...if anyone has thoughts please let me know!
