### ISSUE TITLE
Is there a way to know whether the photo was shot or taken from the library ?

### ISSUE THREAD

**Issue by DrRazor** [marcshilling/react-native-image-picker#149]
I need to do different things depending on how the image is loaded

**Comment by marcshilling** [comment]
Unfortunately, nothing in the callback indicates which source it came from. I don't plan on adding that feature, but I have some alternatives for you...

1. Fork the repo and include the source in the response callback - this would be a super easy addition
2. Build your own [Alert](http://facebook.github.io/react-native/docs/alert.html) dialog for Take Photo/Choose From Library, and use `ImagePickerManager.launchCamera()` or `ImagePickerManager. launchImageLibrary()` to fire them off directly. Then, you'll have to ability to know which they selected from your JS code.

**Comment by DrRazor** [comment]
Thanks a lot ! I added the source in the response, it was very easy indeed ! cheers
