### ISSUE TITLE
Image Compression

### ISSUE THREAD

**Issue by akishek22** [marcshilling/react-native-image-picker#15]
So far this has been working great. After taking a picture through the camera it grabs the `UIImage *image = info[UIImagePickerControllerOriginalImage];` which is quite large. Any idea on how to get the image size smaller?

**Comment by marcshilling** [comment]
You can now specify a value from 0 (worst) to 1(best) for the "quality" key in the options object which controls the image compression.

**Comment by leoyb** [comment]
@marcshilling How to ensure maximum compression without distortion

**Comment by Atuldhaka** [comment]
yes, please provide a workaround for the compression without image distortion, because for small images it gets much distorted.
