### ISSUE TITLE
Changing the language of camera buttons

### ISSUE THREAD

**Issue by mfuruskog** [marcshilling/react-native-image-picker#150]
Is it possible to change the language of the camera overlay? I want 'Use Photo' and 'Retake' to be in Swedish but even though the language on the device is Swedish the buttons are still in English.

**Comment by marcshilling** [comment]
I don't know much about localization, but the screen you are looking at with 'Use Photo' and 'Retake' is the native iOS `UIImagePickerController`. I have a hunch that if you were to change your iPhone's language setting to Swedish, those titles would change. Can you try that out?

**Comment by mfuruskog** [comment]
Thanks for your response! My language was already set to Swedish on the phone but the camera was still in English. However, by adding Swedish as a localization in Xcode it now works!

**Comment by marcshilling** [comment]
Cool, good to know that it's localizable!

**Comment by Javier07v** [comment]
here what worked well when I was implementing that:

const options = {
    title: 'Agregar una foto',
    storageOptions: {
        skipBackup: true,
        path: 'images',
        
    },
    takePhotoButtonTitle:'Acceder a la cámara',
    chooseFromLibraryButtonTitle:'Importar desde la libreria',
    cancelButtonTitle:'Cancelar'
};

its in spanish but you can translate into your language

**Comment by euZebe** [comment]
@mfuruskog could you please explain how to add any language as a localization in Info.plist ?

**Comment by bbodensieck** [comment]
> @mfuruskog could you please explain how to add any language as a localization in Info.plist ?

A little late but probably helps someone. It is called `Localization native development region` in the Info.plist or just like this in the source code view.
```
<key>CFBundleDevelopmentRegion</key>
<string>en,fr</string>  
```
https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledevelopmentregion

**Comment by itsramiel** [comment]
Why is it not working with me?
