### ISSUE TITLE
Why uploading a video doesn't return base64 data?

### ISSUE THREAD

**Issue by radiegtya** [marcshilling/react-native-image-picker#151]
Why uploading a video doesn't return base64 data while image did? I need the base64 data

**Comment by marcshilling** [comment]
The reason is that base64 encoding video is extremely non-performant. If you really need this, take the uri and perform the encoding yourself - I'm not planning on adding this functionality. If anyone knows a way of getting base64 videos in a performant manner, I would accept a PR.

**Comment by radiegtya** [comment]
Dunno but when I take video uri and encode to base64, it always fail. Do you have any solution to manually convert this?

**Comment by StephaneP** [comment]
I actually made a module to do so, but yeah performance is poor, using xhr uri should send over the proper data though.

**Comment by SarahYT** [comment]
How did you manage converting the video to base64 plz?
