### ISSUE TITLE
Take picture cannot displayed on real device, while simulator did

### ISSUE THREAD

**Issue by radiegtya** [marcshilling/react-native-image-picker#152]
Here is what I did:
1. take picture using ImagePicker
2. save the data to server via passing base64 data
3. read the url from server
4. on simulator it's just work, while on real device the image is not displayed
5. btw image from camera roll upload work on both device and simulator, only take picture didn't

Please help, thanks

**Comment by marcshilling** [comment]
Please post some code

**Comment by marcshilling** [comment]
No response from author - closing.
