### ISSUE TITLE
Can´t upload image fetched from CameraRoll

### ISSUE THREAD

**Issue by BigPun86** [marcshilling/react-native-image-picker#153]
Hey there!

I am using React Natives Camera Roll to get my photos. When i upload this to my server from iOS device everything is fine. On Android this won´t work. Is there something additional i have to do, beside adding permissions maybe?

This is how my image looks like before i send it to the server: 

     'content://media/external/images/media/142'

**Comment by yfuks** [comment]
First of all how did you upload your image on iOS ?
Then ```content://media/external/images/media/142``` is an URI so you need to use a module that support URI for upload or you need to use the file in **base64**

**Comment by BigPun86** [comment]
@yfuks i am using react-native-fileupload to upload my images to server. Doing this with my iOS device works just fine, but not when i am trying to do the same with my Android device

**Comment by yfuks** [comment]
Since this is not related to this module i close.

**Comment by marcshilling** [comment]
@yfuks maybe we should provide a little helper method on the Android side to get the url from a uri. This isn't the first time someone has had trouble with it.

Something like...
`ImagePickerManager.getUrl(response.uri)`

Thoughts?

**Comment by kiliwalk** [comment]
in my case using `image-picker` in android, the uri responded is same like `'content://xxxx'`. to upload this file, my approach is here:
```
  var formdata = new FormData();
  formdata.append('image', {type: 'image/jpeg', name: 'anything.jpg', uri});
  var xhr = new XMLHttpRequest();
  xhr.open('POST', 'http://my.com/api');
  xhr.onload = () => {
     //process server api response here
  }
  xhr.send(formdata);
```
hopes that help u:D

**Comment by yfuks** [comment]
@marcshilling sorry for the late response !

Yes it could help some people even if i'm sure they could do what they want with the **URI** ! :)

Great example @kiliwalk !

I will do it soon. Sorry for the lack of attention recently :yum:

**Comment by esganzerla** [comment]
Hi, Im trying to upload an image as @kiliwalk posted the example, and I believe it is uploading to the server...

But everytime I do it the server is returning:
```
[image] => Array
        (
            [name] => anything.jpg
            [type] => 
            [tmp_name] => 
            [error] => 1
            [size] => 0
        )
```

Does anyone know what's going on? And how I can fix it?

Thanks!

**Comment by cnakh** [comment]
@esganzerla do you solved the problem? now I am using XMLHttpRequest to upload image with progress, but it get as what you mentioned above.

**Comment by DV31** [comment]
> Hi, Im trying to upload an image as @kiliwalk posted the example, and I believe it is uploading to the server...
> 
> But everytime I do it the server is returning:
> 
> ```
> [image] => Array
>         (
>             [name] => anything.jpg
>             [type] => 
>             [tmp_name] => 
>             [error] => 1
>             [size] => 0
>         )
> ```
> Does anyone know what's going on? And how I can fix it?
> 
> Thanks!
> 
> P.S.: Running on Android

try to upload smaller image, error : 1, means file you are trying to upload is larger then the maximum file size limit.
