### ISSUE TITLE
App crashes when scrolling a lot in android

### ISSUE THREAD

**Issue by DanielDanielDanielDanielDaniel** [marcshilling/react-native-image-picker#155]
react-native v0.21

After scrolling a lot (about 200 images) in the gallery, the app crashes:

```sh
E/AndroidRuntime(30838): java.lang.OutOfMemoryError: Failed to allocate a 51916812 byte allocation with 16777216 free bytes and 38MB until OOM
E/AndroidRuntime(30838): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(30838): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/AndroidRuntime(30838): 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:634)
E/AndroidRuntime(30838): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:610)
E/AndroidRuntime(30838): 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:392)
E/AndroidRuntime(30838): 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:418)
E/AndroidRuntime(30838): 	at com.imagepicker.ImagePickerModule.getResizedImage(ImagePickerModule.java:484)
E/AndroidRuntime(30838): 	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:388)
E/AndroidRuntime(30838): 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:173)
E/AndroidRuntime(30838): 	at com.facebook.react.ReactInstanceManagerImpl.onActivityResult(ReactInstanceManagerImpl.java:526)
E/AndroidRuntime(30838): 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:180)
E/AndroidRuntime(30838): 	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
E/AndroidRuntime(30838): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3603)
E/AndroidRuntime(30838): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3650)
E/AndroidRuntime(30838): 	at android.app.ActivityThread.access$1400(ActivityThread.java:154)
E/AndroidRuntime(30838): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
E/AndroidRuntime(30838): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30838): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(30838): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(30838): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30838): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(30838): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(30838): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by marcshilling** [comment]
Hmmm, may just be an issue with Android and not this library (since all we're doing is using the built-in Android gallery). Thoughts @yfuks ?

**Comment by yfuks** [comment]
Yeah it's an issue with Android built-in gallery.

**Comment by marcshilling** [comment]
Although curiously, the memory crash does originate from `com.imagepicker.ImagePickerModule.getResizedImage(ImagePickerModule.java:484)`

@DanielDanielDanielDanielDaniel does it crash purely from scrolling the gallery? Or are you scrolling a lot, and then selecting an image?

**Comment by penkzhou** [comment]
Another reason maybe that the whole app is getting the edge of OOM, and the pick image action trigger the OOM occurrence.

**Comment by gunters63** [comment]
You could try using:
````
android:largeHeap="true"
````
in your application tag in AndroidManifest.xml.

Although this is a kind of last-resort measure :)

**Comment by marcshilling** [comment]
Issue is outside the scope of this library, closing.

**Comment by kbeckmann** [comment]
Hi! I've been running into this issue as well and the reason seems to be that you decode the images in full resolution and then scale them down. https://developer.android.com/training/displaying-bitmaps/load-bitmap.html#read-bitmap has some good info on how to decode images directly into a downscaled buffer. 
Is this a big issue for other users as well, and in that case should we work on a patch to solve this properly?

**Comment by GeoffreyPlitt** [comment]
We are also getting an OOM crash with ImagePickerModule.getResizedImage().

**Comment by agrass** [comment]
Same problem:
```
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:620)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:376)
       at com.imagepicker.ImagePickerModule.getResizedImage(ImagePickerModule.java:594)
```

**Comment by cpfeiffer** [comment]
If you don't specify a maximum size for the image, the user selected image will be "scaled" to its original size when you specify an image quality != 1.0. This will usually fail with the mentioned OOME.

IOW, make sure to specify quality `1.0` to avoid recoding images.

**Comment by kesha-antonov** [comment]
@cpfeiffer Where to specify it? ```<Image quality={1.0} />``` ?

**Comment by cpfeiffer** [comment]
The default value is already `1.0`, just make sure you don't set a different value. See 
https://github.com/react-community/react-native-image-picker/#usage for setting the options.
