### ISSUE TITLE
Do we actually need these manifest statements?

### ISSUE THREAD

**Issue by alexeypodolian** [marcshilling/react-native-image-picker#157]
@marcshilling 
Do we actually need [these manifest statements](https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/AndroidManifest.xml#L5)?

```xml
    // min sdk version not sure if it's actually useful
    <uses-sdk 
        android:minSdkVersion="11"/>
    // required permission not sure if it's actually useful
    <uses-permission android:name="android.permission.CAMERA" />
```

It's confusing because we don't need `CAMERA` permission at all. And also we don't need declare `uses-sdk` in manifest because it will be rewritten by `minSdkVersion` field from `build.gradle`.

**Comment by webzepter** [comment]
I have the same problem. My app that uses this module crashes on Android 6 without this granted permission. I removed these permission statements from `AndroidManifest.xml` and then app works fine.

**Comment by AndrewPetrus** [comment]
Got the same trouble, please fix ASAP

**Comment by marcshilling** [comment]
Ok, they are removed: https://github.com/marcshilling/react-native-image-picker/releases/tag/v0.18.4
