### ISSUE TITLE
How to check duplicate photos?

### ISSUE THREAD

**Issue by stoneWeb** [marcshilling/react-native-image-picker#158]
Add more photos, but these photos are repeated, How to check it?

**Comment by marcshilling** [comment]
I don't understand your issue...can you clarify more? Sounds like you are launching the image picker multiple times to select multiple photos. If that's the case, there's no way to prevent duplicates there. The photo library will always display every photo on your device - there's no way to filter it. You should roll your own solution and build a photo picker that supports multiple selection.
