### ISSUE TITLE
App don't launch when I link Binary with Librairies

### ISSUE THREAD

**Issue by zoontek** [marcshilling/react-native-image-picker#161]
Using react-native-image-picker 0.18.5 with an iPhone 4 (iOS 7.1.2), the app fails on startup when I link libRNImagePicker.a via "Link Binary with Librairies".

As RN supports iOS7, I believe react-native-image-picker does too.

![](https://dl.dropboxusercontent.com/u/4181800/rnimagepicker_fail.png)

**Comment by marcshilling** [comment]
Interesting. There is conditional code in there for iOS 7 apps:

```objectivec
if ([UIAlertController class] && [UIAlertAction class]) { // iOS 8+
```

`UIAlertAction` does not exist outside of that block, so I'm not sure why you would be getting a symbol not found error. If you can figure this out, let me know.

**Comment by zoontek** [comment]
When I comment the whole ```if ([UIAlertController class] && [UIAlertAction class])``` block it compiles well.
Sadly I don't know Objective-C at all so it's hard for me to find a solution.

**Comment by marcshilling** [comment]
@zoontek Check out [this answer]( http://stackoverflow.com/a/24060887/3178793). Can you go to "Build Phases" and trying making `UIKit` optional?

**Comment by zoontek** [comment]
@marcshilling UIKit is not linked in React Native used Frameworks and Libraries

**Comment by marcshilling** [comment]
I see the issue. Fixing now, stand by.

**Comment by marcshilling** [comment]
@zoontek ok, nevermind. I was going to make some changes, but then I remembered I have an iPod Touch on iOS 7.1.2, and the app builds and runs fine on it. This must be something related to your specific project environment. I know for a fact that other people have been able to run this library on iOS 7 as well. Does the Example project compile for you? If so, I'd recommend comparing the Example to your project and seeing what the difference is.

**Comment by marcshilling** [comment]
The other option you have is forking the library, and removing the iOS 8 conditional code entirely. That seems to be working for you, so I'm gonna close this.

**Comment by zoontek** [comment]
@marcshilling Example runs well with RN 0.21, fails with RN 0.22. Maybe you can try it with your iTouch.

**Comment by marcshilling** [comment]
@zoontek go ahead and grab `v.0.18.6` from `npm`. I've updated the Example project to use React Native 0.22, and it still works on my iOS 7 iPod. Make sure to run `npm install` in the Example project after updating to pick up the new dependencies

**Comment by zoontek** [comment]
@marcshilling I found the reason of my problem (but can't explain why it fails). See the previous comment :)

**Comment by marcshilling** [comment]
Interesting...not sure either, but glad you got it working!
