### ISSUE TITLE
Anyway to get raw binary image data?

### ISSUE THREAD

**Issue by narychen** [marcshilling/react-native-image-picker#162]
The response data is encoded in base64. But sometimes we need raw binary data.

**Comment by marcshilling** [comment]
Any idea how to do this on iOS/Android?

**Comment by narychen** [comment]
If the base64 response data is returned directly from native api, I think we should make a conversion method to translate it in the native module. Because it will be blockable to do the base64 decoding in javascript. And then the native could return the javascript side an Arraybuffer maybe.

**Comment by hejun311** [comment]
How to get binary date in this respose data?

**Comment by yfuks** [comment]
You need to add the feature in **iOS** and **Android**
**PR** are welcome !

**Comment by npomfret** [comment]
Javascript and binary data don't really play well together, hence people tend to convert to json.

What did you need the binary for?  I've done some work on a different project where we needed to post raw binary data - we ended up writing a bit of native code to do the job.

**Comment by narychen** [comment]
I finally use the base64 format to transport the data.
