### ISSUE TITLE
Change aspect ratio of the crop box on iOS?

### ISSUE THREAD

**Issue by gnl** [marcshilling/react-native-image-picker#167]
Is that possible / planned, for example by using the aspectX / aspectY options?

Thanks

**Comment by rgoldiez** [comment]
+1

**Comment by yfuks** [comment]
I don't know if that's possible with the native picker iOS.

@marcshilling ?

**Comment by marcshilling** [comment]
Not planned. Using default iOS edit tools. PRs welcome.

**Comment by bendellarocco** [comment]
+1

**Comment by marcshilling** [comment]
@bendellarocco not supported by default in iOS. [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) might be a better choice for you.

**Comment by bendellarocco** [comment]
@marcshilling thank you
