### ISSUE TITLE
android: OnRequestPermissionsResultCallback

### ISSUE THREAD

**Issue by garrett-kl** [marcshilling/react-native-image-picker#168]
Android 6+ (M) permission changes; permissions for the camera and media from the manifest aren't always granted and shouldn't be assumed.

Possible to implement OnRequestPermissionsResultCallback in react-native-image-picker?  In the meantime there is a work around:  wrapping calls into react-native-image-picker with custom permission checks.

**Comment by yfuks** [comment]
We can make a custom permission check for sure.
Thanks for the info !

**Comment by yfuks** [comment]
Done in **0.18.13** :)

**Comment by yfuks** [comment]
Ok not done ^^
I read that wrong, will do it soon :)

**Comment by marcshilling** [comment]
I don't think it should be the responsibility of individual libraries to check permissions. If you're adding a library that accesses the camera, that's on you to add to your own Manifest file.

**Comment by johnculviner** [comment]
@marcshilling this isn't handled solely in the Manifest file anymore for APK 23+ it is to be requested and handled at runtime. I think this is becoming increasingly relevant as everyone gets newer phones and you compile for APK 23+
