### ISSUE TITLE
Android: takePhotoButtonTitle,this option can't show and work!

### ISSUE THREAD

**Issue by zhangyan91711** [marcshilling/react-native-image-picker#170]
Sorry,when I use this package today,the option 'takePhotoButtonTitle' can't show in the open dialog,I have tried on two Project,but the result is the same,'takePhotoButtonTitle' can't show ,it means it can't take a photo or take a video,please ,I need your help!

It can show and work before,when I used it in a few days ago!

This is my code,just as the same you given:

var options = {
      title:'choose picture',
      takePhotoButtonTitle:'take a photo',
      chooseFromLibraryButtonTitle: 'choose from local lirbary',
      quality: 0.8,
      maxWidth: 800,
      maxHeight: 800,
      cameraType: 'back',
      storageOptions: {
        skipBackup: true
      }
    };

    ImagePickerManager.showImagePicker(options,(response) => {
      console.log('Response = ', response);
      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePickerManager Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else{
        var source = {uri:response.uri, isStatic:true};
        this.setState({
          avatarSource:source
        });
      }
    });

**Comment by chinloong91** [comment]
works perfectly for version ```0.18.12```

**Comment by zhangyan91711** [comment]
how to install the special version package?how to write?

**Comment by chinloong91** [comment]
```npm install <package>@version --save```

**Comment by yfuks** [comment]
It was on a real device or on the emulator ?

**Comment by zhangyan91711** [comment]
It was on Genymotion emulator ,the version0.18.12 can work normally,just the latest version can't show the Camera

**Comment by marcshilling** [comment]
Closing this. Obviously the camera doesn't work on the simulator...how would it?
