### ISSUE TITLE
Application terminated unexpectedly

### ISSUE THREAD

**Issue by peace201105** [marcshilling/react-native-image-picker#175]
When I chose the 'Chose from Library...' button ,my app terminated unexpectedly.How can i deal with?

**Comment by yfuks** [comment]
Can you show us some stackTrace, code ?

**Comment by yfuks** [comment]
Make sure the app don't crush by her self (run the library out of your app)

**Comment by peace201105** [comment]
Oh,I validate the package in the ipad,Xcode crash.
but I run in iphone,it run normally.
doesn't  the package support Ipad?

**Comment by yfuks** [comment]
@marcshilling any idea ?

**Comment by marcshilling** [comment]
Please upgrade to the latest version `v0.18.15` and confirm its still happening. If so, please post some of your code that's using the Image Picker.

**Comment by PyYoshi** [comment]
@peace201105 

Perhaps adding this code in AppDelegate.m would solve the issue.

```Objective-C
#if __IPHONE_OS_VERSION_MAX_ALLOWED < 90000
- (NSUInteger)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window
#else
- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window
#endif
{
  if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
    return UIInterfaceOrientationMaskAll;
  else
    return UIInterfaceOrientationMaskAllButUpsideDown;
}
```
