### ISSUE TITLE
Not cropping after capture in Android

### ISSUE THREAD

**Issue by bradbumbalough** [marcshilling/react-native-image-picker#177]
I have the latest release, but am unable to make the cropping dialog appear after capturing an image. It works when I select an image, and works as expected in iOS.

Here's my options:

```JavaScript
const IMAGE_PICKER_OPTIONS = {
  title: 'Select Profile Image',
  takePhotoButtonTitle: 'Take Photo',
  chooseFromLibraryButtonTitle: 'Choose from Library',
  cancelButtonTitle: 'Cancel',
  mediaType: 'photo',
  quality: 1,
  aspectX: 1,
  aspectY: 1,
  allowsEditing: true,
  noData: true,
  storageOptions: {
    skipBackUp: true
  }
}
```

I'm getting the image returned from the camera and it's being uploaded to the server, albeit uncropped.

**Comment by yfuks** [comment]
On some app the crop don't perform, i don't know if we can do something about it.

I will investigate further and see if i can found a fix.

**Comment by bradbumbalough** [comment]
Thanks!

**Comment by yfuks** [comment]
Well i just found that the only way to have a crop that work on all app is to make a custom crop activity, seems to be the best choice, but will take a **really big** amount of time.

Or the other solution is to use a JAVA library that do the crop but i don't plan on using anything else than the native **API**

**Comment by bradbumbalough** [comment]
So you're saying in the native API it doesn't progress to cropping after capture?

**Comment by yfuks** [comment]
Yep.

**Comment by ernestom** [comment]
> On some app the crop don't perform

Hi @yfuks. In which cases the video trimming scene is presented in Android? I need the feature for both iOS and Android and am willing to implement whatever is needed. My Android-fu is rusty so I'd appreciate any pointers as to where to start :)

**Comment by yfuks** [comment]
> In which cases the video trimming scene is presented in Android?

We were talking about image croping there. So to answer your question : actually never (in both **iOS** **Android**).

Well a pointer to start (just found it with google) : 
[how to trim the video programatically in android](https://www.androidpit.com/forum/627490/how-to-trim-the-video-programatically-in-android)
[AVSimpleEditoriOS](https://developer.apple.com/library/ios/samplecode/AVSimpleEditoriOS/Introduction/Intro.html)

**Comment by ernestom** [comment]
Ok, thanks! The video trimming is presented in iOS though.
