### ISSUE TITLE
Get gps location from image

### ISSUE THREAD

**Issue by npomfret** [marcshilling/react-native-image-picker#178]
I notice in the react-naive [example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/CameraRollExample.js) project that its possible to get the GPS location data and other meta-data from the image (in the _\_renderImage_ function).  Can the same be done using this project?

Does it also alway mutate the image?  I just notice that the modified date in the exif data is the current date, rather than when the image was taken

**Comment by yfuks** [comment]
In **Android** it can be done for sure, @marcshilling an idea for **iOS** ?

> Does it also alway mutate the image? I just notice that the modified date in the exif data is the current date, rather than when the image was taken

No idea :/

**Comment by polyma** [comment]
+1!

**Comment by npomfret** [comment]
The IOS camera roll will provide this information as data associated with the asset.  Android does not.  So long as this component doesn't remove any  of the exif data then maybe theres a javascript api out there that will parse the information from the jpeg files.

**Comment by Dacello** [comment]
@npomfret @yfuks FYI Android does provide gps metadata in the exif. I've confirmed that gps metadata is accessible via `ExifInterface`, at the same point where the module deals extracting with orientation. https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L381

**Comment by esthor** [comment]
How to get it on iOS then, without forcing the user to pick the photo they just took (using the react-native-image-picker camera) from the CameraRoll?

**Comment by npomfret** [comment]
GPS data appears in Android in the metadata only if the user has switched on GPS tagging in their camera app.  From iOS you need to find the image in the camera roll and get the GPS data from there.  The react-native camera roll example shows how to do it i believe.

**Comment by charlle** [comment]
iOS `Take Photo` not returning all the data to include: latitude and longitude.  I can take the same photo from within the app using react-native-image-picker (no data) and with the native camera and then `choose from library` (data is present).  I see that your capturing lat/lng in your code, so don't know what is happening.

**Comment by claudioviola** [comment]
I'm working on Android device (Nexus 5) and I didn't receive any GPS from both: library and camera.
This is my options:
` const options = {
            title: 'Pick Picture',
            storageOptions: {
                skipBackup: true,
                path: 'images'
            }
        };`

How can I check if location services are enabled for the app?
In AndroidManifest I have follow settings:

`
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
`

Do I'm wronging somethings?
Thank you!

**Comment by AlmogRnD** [comment]
+1, anyone figure this out?

**Comment by rashmimhatre100** [comment]
Anyone getting lat/lng on taking photo using ImagePicker??

**Comment by d41z** [comment]
@rashmimhatre100 hello!, did u get more information?

**Comment by rashmimhatre100** [comment]
Hi I am getting below response which is not including lat/lng.
    response = 
    { height: 4208,
    timestamp: '2018-06-12T10:47:42Z',
    uri: 'content://com.assureidbackoffice.provider/app_images/Android/data/com.assureidbackoffice/files/Pictures/image-09f23745-6852-4336-8758-07f9428671bb.jpg',
    data: 'img data',
    originalRotation: 0,
    path: '/storage/emulated/0/Android/data/com.assureidbackoffice/files/Pictures/image-09f23745-6852-4336-8758-07f942867 1bb.jpg',
    isVertical: true,
    fileSize: 2060975,
    fileName: 'image-09f23745-6852-4336-8758-07f9428671bb.jpg',
    type: 'image/jpeg',
    width: 2368 }


`

**Comment by sigitprstyo** [comment]
@rashmimhatre how to get the address? Thanks anyway

**Comment by NathanNovak** [comment]
@rashmimhatre100  are you on Android? Can you please go into more depth about getting location data?

**Comment by haifahrul** [comment]
Why sometime get GPS location and sometime not getting,

@rashmimhatre100 

Any one can help?

**Comment by alexg-93** [comment]
> Added maxWidth : 8000 and maxHeight : 8000 to options and also keep your mobile settings, system app=>camera => Save location info **ON**. Now one can get lat/lng, also address is available in metadata.
> 
> ```
>   browseFile = ()=>{
>   var ImagePicker = require('react-native-image-picker');
>   var options = {
>     quality       : 1,
>     mediaType    : "photo",
>     cameraType  : "back",
>     allowsEditing : true,
>     noData          : true,
>     maxWidth      : 8000, 
>     maxHeight     : 8000,
>   };
>   
>   ImagePicker.showImagePicker((response) => {
>     console.log('response: ', response);
>     console.log('response latitude: ', response.latitude);
>     console.log('response longitude: ', response.longitude);
>   });
> ```
> 
> }
> 
> ```
>  'response=> ', { height: 4208,
>  width: 2368,
>  type: 'image/jpeg',
>  fileName: 'image-a58aedd4-bf19-467d-b872-e9a7c26ce0bd.jpg',
>  longitude: 73.93666076660156,
>  path: '/storage/emulated/0/Android/data/com.assureidbackoffice/files/Pictures/image-a58aedd4-bf19-467d-b872-e9a7c26ce0bd.jpg',
>  timestamp: '2018-06-12T11:03:41Z',
>  uri: 'content://com.assureidbackoffice.provider/app_images/Android/data/com.assureidbackoffice/files/Pictures/image-a58aedd4-bf19-467d-b872-e9a7c26ce0bd.jpg',
>  data: 'image data',
>  originalRotation: 0,
>  latitude: 18.5183048248291,
>  isVertical: true,
>  fileSize: 3250731 }
> ```

not working for me on IOS ..Cant get the exif data location when taking a picture with the camera from library but when taking pic from native camera location works..

**Comment by mithleshsps** [comment]
> Anyone getting lat/lng on taking photo using ImagePicker??
in Android version 11

**Comment by Paulraj153u1** [comment]
> 

not working for android

**Comment by Paulraj153u1** [comment]
> > Anyone getting lat/lng on taking photo using ImagePicker??
> > in Android version 11

no , not working above code ref

**Comment by Paulraj153u1** [comment]
> > Anyone getting lat/lng on taking photo using ImagePicker??
> > in Android version 11

if you find anything let me know ,thanks
