### ISSUE TITLE
[iOS] Keyboard theme broke after taking photo from camera

### ISSUE THREAD

**Issue by oureta** [marcshilling/react-native-image-picker#182]
I'm using v0.18.5. This does not happen when selecting photos from Library.
![keyboard theme broke](https://cloud.githubusercontent.com/assets/16153783/14706782/47189e1a-07f3-11e6-934e-0f0510a6f8c0.jpg)

**Comment by marcshilling** [comment]
What am I looking at here?

**Comment by marcshilling** [comment]
Either an iOS bug or a React Native bug...this component has nothing to do with the keyboard so I'm gonna close for now unless you can pinpoint it being related.
