### ISSUE TITLE
Cannot display array of images

### ISSUE THREAD

**Issue by chansila** [marcshilling/react-native-image-picker#186]
Great module, thanks!

Now I meet some problem as I try to customize my app when the user select or take image it will save in state as an array, but when I try to map it back in view it doesn't show anything.

Here some of my code:

```
state = {
    imageSource: []
  };
```
```
this.setState({
  imageSource: this.state.imageSource.concat(source) 
});
```

```
viewImages(){

      this.state.imageSource.map(function(image){
      console.log(image);
        return(
          <View style={[styles.image, styles.imageContainer, {marginBottom: 20}]}>
            <Image style={styles.image} source={image} />
          </View>
        )
      });
    
  }
```
here in side my view render:

```
<View style={styles.containerImage}>
          {this.viewImages()}
</View>
```

and here is my console log when i debug it: (if I take picture two times i will got two objects) like below:

```
Object {uri: "file:///storage/emulated/0/Pictures/image-e23b89ed-83b9-4e10-8912-c96e87aab6f0.jpg", isStatic: true}
Object {uri: "file:///storage/emulated/0/Pictures/image-473d8554-2f53-4870-b94e-03306a17f6e6.jpg", isStatic: true}
```

Where did I go wrong?

Thank.

**Comment by chansila** [comment]
I was my fault. I write it in the wrong place :)

**Comment by rashmimhatre100** [comment]
I am also facing the same problem how did you solved it?

**Comment by sandeepsinghs** [comment]
Try this 
Let consider array as
`var arr=[{image:require('image1')},{image:require('image2')},{image:require('image3')}];
`
then parse array values for displaying on Image View as 

`<Image style = { styles.imageStyle}
                           source={this.state.arr[itemIndex].image}/>`

Let me know any issues.

**Comment by rashmimhatre100** [comment]
@sandeepsinghs I am not having display issues with images stored in my local folder. I am uploading images to aws s3 and getting these remote images. So right now I am using [cachedImage](https://www.npmjs.com/package/react-native-cached-image) and it is working fine for now.
