### ISSUE TITLE
directly get base64 data of a image without launching the picker

### ISSUE THREAD

**Issue by narychen** [marcshilling/react-native-image-picker#188]
Is there a way to do this? So that we can use Camera Roll of react-native to get image uri and use the uri to get the image binary or base64 data, then we can transform or send the data to server or any other stuff things.

**Comment by yfuks** [comment]
Yep there is a way !

Need to add a native method for this purpose.  Since it's a really specific usage i don't plan on doing it. **PR** are welcome !

**Comment by marcshilling** [comment]
@narychen the library is called react-native-**image-picker** and you're asking to not show the **image picker**!? Madness! I'd recommend forking and rolling your own solution.

**Comment by narychen** [comment]
Picker could be an abstract stuff that cannot be seen but can be done by users.
I've been finished this by my own. Thanks a lot for you guys help.
