### ISSUE TITLE
A problem with camera

### ISSUE THREAD

**Issue by MervynFang** [marcshilling/react-native-image-picker#193]
When I use camera to get the picture, the response.didCancel is always true after taking the photo and can't get the picture. What's wrong? It's correct in getting picture from Image Library.

**Comment by yfuks** [comment]
On **iOS** or on **Android** ?

**Comment by yfuks** [comment]
Are you sure that you use the latest version of the package ?

**Comment by MervynFang** [comment]
on Android, my package version is 0.18.15 @yfuks

**Comment by MervynFang** [comment]
I didn't test in iOS, because my project just use in Android. @yfuks

**Comment by yfuks** [comment]
Can you try to run the example and tell me if you face the same issue ?

**Comment by MervynFang** [comment]
I would try it later, thanks

**Comment by MervynFang** [comment]
@yfuks I run the Example in four phones and three XiaoMi phones's  didcancel all is true, and the Sumsung Note 4 can get the image, so it's the issue of device, three XiaoMi Phones' Android version include Android 4.4.4, 5.0.2 and 5.1.1.

**Comment by yfuks** [comment]
Since i don't have any XiaoMi phones's to test can you try to debug further ?

If you can test with ```allowsEditing: false``` and ```allowsEditing: true``` to see if there is a difference.
And in your [ImagePickerModule.java](https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java) try to find why ***Line 313*** the activity result is not ```Activity.RESULT_OK```

If you find something in your stack trace it could be great to paste it there :)

**Comment by MervynFang** [comment]
`allowsEditing: false` is ok to get the image, thanks a lot, nice guy.
I will try to debug ImagePickerModule.java later. Now my time is limited and facing deadline.
Otherwise can i know how you debug java code in RN project? just like Native Android？

**Comment by coolguy001tv** [comment]
I am facing the same problem with Meizu MX4( android 5.1). 
And `allowsEditing: false` did solve my problem.

**Comment by HughLi** [comment]
I am facing the same problem with iOS( 9.3).

**Comment by marcshilling** [comment]
Post your JS code

**Comment by marcshilling** [comment]
How can we move this forward?

@HughLi are you still having the problem?  I don't believe this is an issue on iOS. Just tested multiple scenarios with the Example project and it seems fine.

Will close soon if no update.

**Comment by marcshilling** [comment]
Old issue + no response from OP = closing
