### ISSUE TITLE
Undefined is not an object (ImagePickerManager.showImagePicker) when compiling app as UniversalFramework

### ISSUE THREAD

**Issue by EricPKerr** [marcshilling/react-native-image-picker#194]
We are embedding a react-native application within another application as a UniversalFramework.  This application uses several react-native libraries, which all have something to the effect of `const MyLibrary = require('NativeModules').MyLibrary;` to load native code and work fine.

This react-native-image-picker library doesn't seem to work, where the `const ImagePickerManager = require('NativeModules').ImagePickerManager;` is an undefined object.

We are using react-native 0.21.0, and react-native-image-picker 0.18.15.

We have disabled the Optimization Level as described as a possible fix by https://github.com/marcshilling/react-native-image-picker/issues/14 

<img width="828" alt="screen shot 2016-05-02 at 1 43 18 pm" src="https://cloud.githubusercontent.com/assets/20335/14963975/e5036f12-106b-11e6-978d-4b146c07fdda.png">

The app compiles in the simulator, but does not work in simulator or on device once compiled as a Universal Framework and embedded within our main application.  The main app will compile and run, but it crashes when we attempt to execute the code which relies on `ImagePickerManager` being defined.  Here's the full termination exception:

```
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'x.showImagePicker')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'x.showImage..., stack:
value@32:9534
touchableHandlePress@21:26342
```

Here is the "Build Universal Framework" script we are using:

```
# Taken from https://medium.com/@syshen/create-an-ios-universal-framework-148eb130a46c
# In an attempt to build a universal framework (for simulator and device)
# Does not work with Swift!

######################
# Options
######################

set -e

REVEAL_ARCHIVE_IN_FINDER=true

FRAMEWORK_NAME=MerchantMobileEmbedded

SIMULATOR_LIBRARY_PATH="${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/${FRAMEWORK_NAME}.framework"

DEVICE_LIBRARY_PATH="${BUILD_DIR}/${CONFIGURATION}-iphoneos/${FRAMEWORK_NAME}.framework"

UNIVERSAL_LIBRARY_DIR="${BUILD_DIR}/${CONFIGURATION}-iphoneuniversal"

FRAMEWORK="${UNIVERSAL_LIBRARY_DIR}/${FRAMEWORK_NAME}.framework"

######################
# Build Frameworks
######################

xcodebuild -project ${PROJECT_NAME}.xcodeproj -scheme ${FRAMEWORK_NAME} -sdk iphonesimulator VALID_ARCHS="i386 x86_64" ARCHS="i386 x86_64" -configuration ${CONFIGURATION} ONLY_ACTIVE_ARCH=NO clean build CONFIGURATION_BUILD_DIR=${BUILD_DIR}/${CONFIGURATION}-iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 2>&1

xcodebuild -project ${PROJECT_NAME}.xcodeproj -scheme ${FRAMEWORK_NAME} -sdk iphoneos VALID_ARCHS="armv7 arm64" ARCHS="armv7 arm64" -configuration ${CONFIGURATION} clean build CONFIGURATION_BUILD_DIR=${BUILD_DIR}/${CONFIGURATION}-iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 2>&1

######################
# Create directory for universal
######################

rm -rf "${UNIVERSAL_LIBRARY_DIR}"

mkdir "${UNIVERSAL_LIBRARY_DIR}"

mkdir "${FRAMEWORK}"


######################
# Copy files Framework
######################

cp -r "${DEVICE_LIBRARY_PATH}/." "${FRAMEWORK}"

######################
# Make an universal binary
######################

lipo "${SIMULATOR_LIBRARY_PATH}/${FRAMEWORK_NAME}" "${DEVICE_LIBRARY_PATH}/${FRAMEWORK_NAME}" -create -output "${FRAMEWORK}/${FRAMEWORK_NAME}" | echo

######################
# On Release, copy the result to release directory
######################
OUTPUT_DIR="../"

cp -r "${FRAMEWORK}" "$OUTPUT_DIR"

if [ ${REVEAL_ARCHIVE_IN_FINDER} = true ]; then
open "${OUTPUT_DIR}/"
fi
```

**Comment by marcshilling** [comment]
Can you go into the build settings of these other Native Modules and compare them to ImagePickerManager? If the app is working fine normally and this is purely related to building as a Universal Framework then there is probably a minor difference is some unique build setting.

**Comment by EricPKerr** [comment]
Appears the issue was related to only including the `libRNImagePicker.a` in the "Link Binary With Libraries" of the App Target, and not the Embedded Target.

Thanks.

**Comment by gerardus1995** [comment]
Can you explain more detailed where that is?
