### ISSUE TITLE
[Android] Incorrect dimensions / orientation for image from library

### ISSUE THREAD

**Issue by thomasjonas** [marcshilling/react-native-image-picker#199]
When I use ```ImagePickerManager.launchImageLibrary``` on my Android device (Sony Ericsson LT26i) and select a portrait image it returns the following response:

   ```
{ 
     type: 'image/jpeg',
     fileName: 'IMG_20160502_182352.jpg',
     fileSize: 1657747,
     path: '/storage/sdcard0/Pictures/RCTCameraModule/IMG_20160502_182352.jpg',
     uri: 'content://media/external/images/media/1937',
     height: 3000,
     width: 4000,
     isVertical: false
}
```

So according to the response we're dealing with a landscape image, but that's incorrect. When I log the orientation (using [this line of code](https://github.com/marcshilling/react-native-image-picker/blob/4c6abc024a19dcb06267d5ffb7907375685196ef/android/src/main/java/com/imagepicker/ImagePickerModule.java#L379)) it says the image has this orientation: ORIENTATION_ROTATE_90.

Doesn't that mean that the 4000x3000 (width x height) should be rotated 90 degrees to 3000 x 4000 (width x height) and that isVertical: true? According to [this link](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/) handling image rotation / exif data is not that easy as it looks like...

**Comment by thomasjonas** [comment]
I see that the CameraRoll component from react-native also has this problem. I think using just `BitmapFactory.decodeFile` to determine the orientation and dimensions is probably not enough.

**Comment by yfuks** [comment]
Can you try with more exemples and tell me if you always encounter the issue ?
(Just watch the code and i feel like ```isVertical: false``` and ```isVertical: true``` are maybe inverted)

**Comment by marcshilling** [comment]
Old issue + no response from OP = closing

**Comment by Vietvantue** [comment]
I also face the same issue at latest version
