### ISSUE TITLE
Ability to restrict options

### ISSUE THREAD

**Issue by jacob-israel-turner** [marcshilling/react-native-image-picker#20]
It would be nice to add an option to the JavaScript API that would allow you to only show one option or the other.  We have had problems uploading images from the camera, so we want to restrict users to only using images from their library.

If this is something you'd like in the library, I'd be willing to try for a PR in the next day or two.

**Comment by marcshilling** [comment]
I like this idea! What did you have in mind for the syntax/naming convention of how this will work? 
Maybe `hideCamera` and `hideLibrary` booleans in the options object?

**Comment by jacob-israel-turner** [comment]
Yeah, that would work.  So, 

``` javascript
UIImagePickerManager.showImagePicker({ hideCamera: true }, (type, response) => {...});
```

Would result in only the 'Choose From Library' button appearing?

**Comment by marcshilling** [comment]
Sounds good to me! I can probably do this quickly this afternoon if you want me to save you the work of a PR.

**Comment by jacob-israel-turner** [comment]
Sure, you'll probably make a cleaner PR anyways.  :) I might read over your PR and try to understand what's going on.  I need an excuse to start learning Objective-C.

**Comment by marcshilling** [comment]
Ok @jacob-israel-turner, done in version 0.5! Should be live on npm now. Decided to name the bools `takePhotoButtonHidden` and `chooseFromLibraryButtonHidden` to match the keys for setting the titles.

Thanks for the idea.
