### ISSUE TITLE
unfortunately app has stopped with twitter fabric integrated app

### ISSUE THREAD

**Issue by karthickvkumar** [marcshilling/react-native-image-picker#201]
Hi @marcshilling @yfuks  Thanks for this awesome library. I try to used the image picker library in a [twitter fabric](https://github.com/corymsmith/react-native-fabric/tree/twitterkit-support) integrated app. 
When I press select a photo, it shows camera roll / gallery, but when I save that picked image, its showing alert like **unfortunately app has stopped** and the app gets closed

For that [twitter fabric](https://github.com/corymsmith/react-native-fabric/tree/twitterkit-support) i have configure the MainActivity.java like the below mentioned
![selection_013](https://cloud.githubusercontent.com/assets/11032434/15137937/3d8e5a2c-16aa-11e6-860c-581ac5b1b557.png)
![selection_014](https://cloud.githubusercontent.com/assets/11032434/15137939/42522a2a-16aa-11e6-9586-724121f15319.png)
![selection_015](https://cloud.githubusercontent.com/assets/11032434/15137946/46c63254-16aa-11e6-801c-ea80ef6e906f.png)

Thanks in Advance

**Comment by yfuks** [comment]
Hi

Can you past your stack trace ?

**Comment by karthickvkumar** [comment]
Hi @yfuks, Its not showing any stack trace. Its just simple showing alert unfortunately app has stopped!
I have added an gif image of that problem
![05pzek](https://cloud.githubusercontent.com/assets/11032434/15147824/411b5786-16e0-11e6-8d32-178d4155ef77.gif)

Thanks in Advance

**Comment by yfuks** [comment]
To see your android stack trace you need to do the folowing comand 
```adb logcat```

It's almost impossible to have a crash without something print in your log stack

**Comment by karthickvkumar** [comment]
Thanks for helping me to see the stack trace @yfuks, I have added the output of the stack trace in image format. 

![selection_001](https://cloud.githubusercontent.com/assets/11032434/15176209/9b32c3ec-1787-11e6-8a4b-2ed90014c746.png)
![selection_002](https://cloud.githubusercontent.com/assets/11032434/15176217/a57caa34-1787-11e6-9891-0a9b5daa795c.png)
![selection_003](https://cloud.githubusercontent.com/assets/11032434/15176224/ade378e2-1787-11e6-8f7b-f8793e47f3c0.png)

Thanks in Advance

**Comment by karthickvkumar** [comment]
`D/PhoneApp( 2181): getPhone phoneId:1
V/StateManager(25642): startStateForResult class com.android.gallery3d.app.AlbumPage, 1
D/AutoHLR (25642): AutoHighlightReelBanner()
D/AlbumPage(25642): onSyncDone: ******** result=0
D/AutoHLR (25642): removeHighlightReelView()
D/AutoHLR (25642): dismiss
D/AutoHLR (25642): pause
D/AutoHLR (25642): setIsCancelled = true
I/GLRootView(25642): layout content pane 540x888 (compensation 0)
D/AutoHLR (25642): removeHighlightReelView()
D/AutoHLR (25642): dismiss
D/AutoHLR (25642): pause
D/AutoHLR (25642): setIsCancelled = true
I/ActivityManager(  824): START u0 {act=com.android.camera.action.CROP dat=content://media/external/images/media/63738 flg=0x2000000 cmp=com.motorola.MotGallery2/com.android.gallery3d.filtershow.crop.CropActivity (has extras)} from uid 10029 on display 0
W/ContextImpl( 2109): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
I/SFPerfTracer(  247):      triggers: (rate: 0:16) (129338 sw vsyncs) (0 skipped) (9:92873 vsyncs) (11:234639)
D/AutoHLR (25642): pauseHighlightReelView()
D/AutoHLR (25642): pause
D/AutoHLR (25642): setIsCancelled = true
W/ContextImpl( 2109): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
I/SFPerfTracer(  247):      triggers: (rate: 51:3084) (compose: 0:37) (post: 0:2) (render: 1:135) (6:44346 frames) (7:57453)
D/SFPerfTracer(  247):        layers: (3:12) (FocusedStackFrame (0xb71b5110): 1:1201)* (DimLayer (0xb71b6d60): 0:124)* (StatusBar (0xb71a0010): 5:18581)* (com.android.systemui.ImageWallpaper (0xb7173ba0): 0:1053)* (DimLayer (0xb71e1400): 0:785)* (DimLayer (0xb716f9b8): 0:93)* (NavigationBar (0xb71dc600): 4:37) (com.twitter/com.twitter.MainActivity (0xb7171da8): 0:40)- (Starting com.motorola.MotGallery2 (0xb7201e78): 0:38)- (com.motorola.MotGallery2/com.android.gallery3d.app.GalleryActivity (0xb713d658): 2:13) (SurfaceView (0xb71e2690): 0:76) 
D/PhoneApp( 2181): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 1304): updateDataNetType[0]: phoneId0 is not DDS( =phoneId1 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 1=0x00000001 )
I/LaunchCheckinHandler(  824): Displayed com.motorola.MotGallery2/com.android.gallery3d.filtershow.crop.CropActivity,wp,ca,191
I/Keyboard.Facilitator( 2046): onFinishInput()
I/ActivityManager(  824): Displayed com.motorola.MotGallery2/com.android.gallery3d.filtershow.crop.CropActivity: +191ms
D/PhoneApp( 2181): getPhone phoneId:1
I/ThermalEngine(  284): Sensor:msm_therm:30000 mC
I/SFPerfTracer(  247):      triggers: (rate: 51:3084) (compose: 0:37) (post: 0:2) (render: 1:136) (10:44359 frames) (11:57470)
D/SFPerfTracer(  247):        layers: (5:11) (FocusedStackFrame (0xb71b5110): 0:1203)* (DimLayer (0xb71b6d60): 0:124)* (StatusBar (0xb71a0010): 11:18598)* (com.android.systemui.ImageWallpaper (0xb7173ba0): 0:1053)* (DimLayer (0xb71e1400): 0:785)* (DimLayer (0xb716f9b8): 0:94) (NavigationBar (0xb71dc600): 11:54) (com.motorola.MotGallery2/com.android.gallery3d.app.GalleryActivity (0xb713d658): 11:26) (SurfaceView (0xb71e2690): 11:87) (com.motorola.MotGallery2/com.android.gallery3d.filtershow.crop.CropActivity (0xb7201e78): 11:16) 
V/StateManager(25642): destroy
D/AutoHLR (25642): releaseHighlightReelView()
D/AutoHLR (25642): removeHighlightReelView()
D/AutoHLR (25642): dismiss
D/AutoHLR (25642): pause
D/AutoHLR (25642): setIsCancelled = true
D/AutoHLR (25642): release
D/AutoHLR (25642): dismiss
D/AutoHLR (25642): pause
D/AutoHLR (25642): setIsCancelled = true
W/ContextImpl( 2109): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
W/ContextImpl( 2109): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
D/PhoneApp( 2181): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 1304): updateDataNetType[0]: phoneId0 is not DDS( =phoneId1 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 1=0x00000001 )
D/PhoneApp( 2181): getPhone phoneId:1
I/SBar.MotoNetworkCtrlr( 1304): onReceive: WifiManager.RSSI_CHANGED_ACTION Received
I/SBar.MotoNetworkCtrlr( 1304): updateWifiState: RSSI_CHANGED_ACTION: mWifiConnected=true mWifiLevel=4 mWifiRssi=-55
D/PhoneApp( 2181): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 1304): updateDataNetType[0]: phoneId0 is not DDS( =phoneId1 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 1=0x00000001 )
D/PhoneApp( 2181): getPhone phoneId:1
D/AndroidRuntime(25559): Shutting down VM
E/AndroidRuntime(25559): FATAL EXCEPTION: main
E/AndroidRuntime(25559): Process: com.twitter, PID: 25559
E/AndroidRuntime(25559): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=file:///storage/emulated/0/Pictures/image-3c4c35d6-9394-44ae-bb6f-22857964f4a1.jpg (has extras) }} to activity {com.twitter/com.twitter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.twitter.sdk.android.core.identity.TwitterLoginButton.onActivityResult(int, int, android.content.Intent)' on a null object reference
E/AndroidRuntime(25559): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3626)
E/AndroidRuntime(25559): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3669)
E/AndroidRuntime(25559): 	at android.app.ActivityThread.access$1300(ActivityThread.java:148)
E/AndroidRuntime(25559): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
E/AndroidRuntime(25559): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25559): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(25559): 	at android.app.ActivityThread.main(ActivityThread.java:5312)
E/AndroidRuntime(25559): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25559): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(25559): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/AndroidRuntime(25559): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E/AndroidRuntime(25559): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.twitter.sdk.android.core.identity.TwitterLoginButton.onActivityResult(int, int, android.content.Intent)' on a null object reference
E/AndroidRuntime(25559): 	at com.smixx.fabric.SMXTwitter.onActivityResult(SMXTwitter.java:63)
E/AndroidRuntime(25559): 	at com.smixx.fabric.FabricPackage.handleActivityResult(FabricPackage.java:58)
E/AndroidRuntime(25559): 	at com.twitter.MainActivity.onActivityResult(MainActivity.java:43)
E/AndroidRuntime(25559): 	at android.app.Activity.dispatchActivityResult(Activity.java:6161)
E/AndroidRuntime(25559): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3622)
E/AndroidRuntime(25559): 	... 10 more
W/ActivityManager(  824):   Force finishing activity com.twitter/.MainActivity
E/ActivityManager(  824): Invalid thumbnail dimensions: 288x288
W/ContextImpl( 2109): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
I/ReactNativeJS(25559): 'Response = ', { type: 'image/jpeg',
I/ReactNativeJS(25559):   fileName: 'image-2163ee87-e5d2-4095-adf8-f4564ec3e564.jpg',
I/ReactNativeJS(25559):   fileSize: 6604,
I/ReactNativeJS(25559):   path: '/storage/emulated/0/Pictures/image-2163ee87-e5d2-4095-adf8-f4564ec3e564.jpg',
I/ReactNativeJS(25559):   data: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAEsASwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDlaKKSrRkOHSlbpSLSk8UDI26UgpW70wUCJ0xipAKhjqYUhoXFKOOppMe9Ljj1oGHSnr79aZ3p6daBoeOlMYd6f2NNPSpGQNULipZJY0B3MPwqo9wh+6CapEi9KDx0qLzvalVw1MQ6kJzSZ4ppNACk02ijFACd6CM04ClxQA3bS4p2KMUANAxxSgUhFKvNAC4ppFSYFNYUARmkpWFJQNC0UCigYYopPxpRQJhSUtJQI0Mc00jmn9ab0oEA4FKelIOtLQMYx9KZUhHpTTwKBEkdSLUSVKpzSGh4GRS4x0oBxUMt1GnH3iPSkMlPWmmaOPlmxVGW7kfOPlHtVcnJ55PqaoC9LqHURL+Jqq9xK/3nP4VHRSSC4YopaSmISjJBzQaKAJAc4pwqOM4OKmA7UAIBmjFPAxQBQAmKSn44pOAKAG0uKcoyaQjigBhoFBpBigB4PahqAcUjUARkc0hp3agDigBO1Np2KTFA0GKSlFLigY2ilIooEaOKCKXHrSUEjcUuKO9LjtQAw0wjsalIqJ2CdetAx68dKHnWMf3jVRpmbIHAqLtQBNJcPIcE4HpUQ60g60poAMUmKM0tAxKKKKAsLSUtJQIKTFLRQAlWIjvX3FVzT4n2PntQBZAzQBTxyMjoaAOaAGnimNUjCmEUAApDSCj2oAYT2oFDYpVoAcozS4zSqKeV5oAiK0EcVIRjimGgCM02nGkIoAQU6gUYoHcTFGPSlIpDxQFzRIpvWn0lBI09KAOM0pHpScnrQAyWQIvvVFmJOTU91kSc+lV6CkFFFFAMTvQaKDQIQ0vakpRQAlFOooHcKSiigQUUUUAGKTilooAtW0gYbCeR0qboaz0YqwatFMMoPrQA0ioyKnZcGmEc80rgR7aQjipAKa3Q0wISKFFBoFAEq08mo1NOoAU1Gadn1pDg0ARmkpzAU3FACgUuKUcUcUANNJtzT8U2gDRpMU8ijbk0gsR0EcVKEpSnHSmMo3i/KG7iqrc1ozpmNhVA8LQBHSGnUhoBiUUUUCEpaKWgBKWikoAWko5ooAKKOaXFACUUUtACVPaz+WdrcrUNN6UAapxjI71GaitZt67GPI6VI1IABpG6Uq9KGORQBXbrSLSt1PrTQQByaYWJVpc1EJB2BJoJkPO3aPU0ASmjIHpVdiSfmfH0qa1ggnmWMyPuPSlcaVwPTjmkq3c2UNtHuWQlieAaqZpiasKBSYpRQTQAlFGfajNAGoq5608JnpSqtSgY71JQwJ3pkmBUzHHWqszcGhCZE7DBHrWey4LD0q2zHvUEg+Y1QrkOKYetSEYPNMbk0DG0CjFFAMKBQaBQIWkHNLj3pQQKADB70BRS80etAB0ppNLSGgBKM0UUAFJS0lAArFTkdRVnzdy5quFJ6Amn7MdSBSAmMyjvTPPZvurTMgA8Z+tN3H1pjHHcTl2xRujUcZJpmc9aTigB4kYdOKazM3Uk0U5Iy59BQIaoLdKs26mBhJ/GOntSoAgwv50pP50rDTCRmdssSab2pc+tNoFcUdaKX680h60wEpaQdaXNAG2g6VIFpEGeaf8AWsy0Mf7tUpz2PWrsh+WqM3OaaEyvjmophlTjqDU1McdasgqHjrTO9Pfk/SmqrMcgE0FIbzShS1WI7YZBY5qSRAq8DAoAqBcdaKewxTSKBCdqKAKB39qAFopBS0AIaQ0/A7mmllHTmgB
bhqjbApiG9OtJTS2KbuJoCw/dikL03Galit5JT0wKWw7EROe9SxW005GxCR71aFtDbrvk+Y+lW4PMlwWIij9qhyKSI7bS4UObiQM391a17cRRAeVEVHriqv2+zshwu9qb/wAJEx+7ANvsKzakzVcqNVX3H/Gq+pW4ntJABk4yKrQapE7YdGRj6jitJCGQEEEEY4rKzTLumjiPXPWkqa7j8u6lTphjUFdad0czVmKOtWEwRkVAKdG+05qhExWm4qTqMim4oENAwacKUCgigQlJmikoAWikoHIoAUdaWkFHegEKBk8sBQevakxS4oGdMFxSgU7HNFQWRSDjFU5RzxVyTpVSYUIllcimHjk1Jjrk00jj2qyC9oMwjvvKY/LIpX8e1XbyDEhGMVhRyGKVHX7yEGukv7y2S3WRpVG9c7QetQ0bQehiXC4bjtVSaZIx8x/CorzUDI5EY2rVAsW6mqRLJZJ9xJHAqLcTSfWgUxBipEiLn0oRR3NXYoQQNpBqWwGwwIgyRk1MG2gnsKesZHBGPrSNGW4FRcpIgQ+ZKZZPuL0FR3N40gKqcD2q+2mzyARn9ym3ezvwMVFYacs02FG8M22PI6+/0oHYqW9o8zL8rMW6Cuo0nwzLIVeeM7fQ8Cum0zSLXT4xtjBkIG5yOavyTxxKS7gAeppNlqNjJfRIBHt2oF9MVnvpiWhbyzwTnHYVo3GtWikoJlz7Gs6e/wDtAC243Z4zWUjZI43Woil87DoxzWeRya6HX7aZTG7bdo449awJfvk+9b03dHNNWYg4IoIwaKMVoQSRN2JqXvVfoanQ5UUCHiigdaDQIYaSnEU2gBMUDil5o7UAFFGKWgEJmnUmM0uPegZ1PQUmaccU0j5qgsifkVVl4q2/tVO4dUByaESyKo5JFQfMefSq1xe9VT86otIzHk1RNi3LcryF61VeVmOS309qZnmkxmmUgNA5ooHWkAuKKXGTTlXccAUXAaDipIXIbIDfhWvYeGt
I/OpenGLRenderer(  824): Initialized EGL, version 1.4
D/PhoneApp( 2181): getPhone phoneId:0
D/PhoneApp( 2181): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 1304): updateDataNetType[0]: phoneId0 is not DDS( =phoneId1 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 1=0x00000001 )
D/PhoneApp( 2181): getPhone phoneId:0
W/ActivityManager(  824): Activity pause timeout for ActivityRecord{2158ab6 u0 com.twitter/.MainActivity t241 f}
W/ContextImpl( 2109): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
I/ActivityManager(  824): Killing 19669:com.google.process.gapps/u0a16 (adj 15): empty #7
W/libprocessgroup(  824): failed to open /acct/uid_10016/pid_19669/cgroup.procs: No such file or directory
D/ClClient(25279): Not sending keepalive.  Current connection state=STOPPED
I/ActivityManager(  824): Killing 24868:com.google.android.deskclock/u0a61 (adj 15): empty #7
W/libprocessgroup(  824): failed to open /acct/uid_10061/pid_24868/cgroup.procs: No such file or directory
D/PhoneApp( 2181): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 1304): updateDataNetType[0]: phoneId0 is not DDS( =phoneId1 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 1=0x00000001 )
V/WindowManager(  824): removeAppToken make exiting: AppWindowToken{7421214 token=Token{28952467 ActivityRecord{38289026 u0 com.motorola.MotGallery2/com.android.gallery3d.filtershow.crop.CropActivity t241}}}
D/PhoneApp( 2181): getPhone phoneId:1
I/SFPerfTracer(  247):      triggers: (rate: 0:16) (129338 sw vsyncs) (0 skipped) (30:92993 vsyncs) (32:234769)
I/Process (25559): Sending signal. PID: 25559 SIG: 9
I/SFPerfTracer(  247):      triggers: (rate: 51:3084) (compose: 0:37) (post: 0:2) (render: 1:136) (0:44436 frames) (1:57570)
D/SFPerfTracer(  247):        layers: (6:13) (FocusedStackFrame (0xb71b5110): 0:1210)* (DimLayer (0xb71b6d60): 0:133) (StatusBar (0xb71a0010): 0:18641) (com.android.systemui.ImageWallpaper (0xb7173ba0): 0:1054) (DimLayer (0xb71e1400): 0:785)* (DimLayer (0xb716f9b8): 0:95)* (NavigationBar (0xb71dc600): 0:68) (com.motorola.MotGallery2/com.android.gallery3d.app.GalleryActivity (0xb713d658): 0:27)- (SurfaceView (0xb71e2690): 0:88)- (com.motorola.MotGallery2/com.android.gallery3d.filtershow.crop.CropActivity (0xb7201e78): 0:58)- (Application Error: com.twitter (0xb713d658): 1:42) (com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher (0xb71e2690): 0:6) 
I/WindowState(  824): WIN DEATH: Window{1ea4559f u0 com.twitter/com.twitter.MainActivity}
D/PhoneApp( 2181): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 1304): updateDataNetType[0]: phoneId0 is not DDS( =phoneId1 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 1=0x00000001 )
D/PhoneApp( 2181): getPhone phoneId:1
I/ActivityManager(  824): Process com.twitter (pid 25559) has died
D/PhoneApp( 2181): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 1304): updateDataNetType[0]: phoneId0 is not DDS( =phoneId1 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 1=0x00000001 )
D/PhoneApp( 2181): getPhone phoneId:1`

**Comment by yfuks** [comment]
(It's way easier to past the code/stack than to put images)

That's the part i was looking for : 
![error](https://cloud.githubusercontent.com/assets/9282988/15180265/c5bde1a2-1780-11e6-88eb-4a684ad2a910.png)

From this i can tell that you have a null pointer exception line 43 of your ***MainActivity.java***. Are you sure that you don't need to instanciate your ***FabricPackage*** before using it ?

**Comment by karthickvkumar** [comment]
@yfuks I dono how to handle this instanciate before using it, please provide some code snippet. It would be very helpful

Thanks in Advance

**Comment by saikiranvadlakonda** [comment]
Hi all,
I'm developing android application using react native, in that application I'm using react-native-image-picker and also [react-native-android-voice](https://github.com/JoaoCnh/react-native-android-voice). The problem if I use them individually they are working fine, If I use both then the problem arises. android voice module is working fine, when click on a button and invoking capturing image or selecting image then it says Unfortunately, myApp has stopped. 
And I've used adb logcat, below is the log

![screenshot from 2016-05-12 12 19 52](https://cloud.githubusercontent.com/assets/14762284/15206872/f347920c-183f-11e6-8b2d-c38484fab854.png)


When I invoke camera or choose from gallery, why that VoiceModule.java's 
public void onActivityResult(int requestCode, int resultCode, Intent data)  is invoking, it should invoke
public void onActivityResult(final int requestCode, final int resultCode, final Intent data)  of [this file](https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L302) .

Why it's invoking voice module's onActivityResult method, Am I missing any setup or something.
Awaiting for response.


Thanking you

**Comment by karthickvkumar** [comment]
@yfuks There was a null check missing in **FabricPackage**, now everything is working fine!
Thanks for your help.

**Comment by yfuks** [comment]
Hi @saikiranvadlakonda, 

You miss nothing, there is just a lack of robustness code in **react-native-android-voice**.
The author probably don't consider the result from other module (he don't check his variables before using it). I recommend you to inform the author about this issue.

Since both of this issues are not cause of this module i close.
