### ISSUE TITLE
Stylise buttons

### ISSUE THREAD

**Issue by Tiagojdferreira** [marcshilling/react-native-image-picker#202]
Is there any way of adding icons or making a more stylized menu ? Something like the bottom sheets on android https://www.google.com/design/spec/components/bottom-sheets.html?utm_campaign=android_launch_supportlibrary23.2_022216&utm_source=anddev&utm_medium=blog

**Comment by yfuks** [comment]
You can make your own picker with react-native components. We expose two function that was meant for this purpose.

https://github.com/marcshilling/react-native-image-picker#directly-launching-the-camera-or-image-library

**Comment by marcshilling** [comment]
What he said ^

Closing.
