### ISSUE TITLE
Video extension

### ISSUE THREAD

**Issue by dchartfield** [marcshilling/react-native-image-picker#204]
I need to know the file format of the video selected. When images are picked I can determine the file format from the uri or the path (path only on android)
```
 { "path": "/storage/emulated/0/Pictures/image-7dda44cb-8d84-4df4-82b6-f23dd581d4d3.jpg",
    "uri": "file:///storage/emulated/0/Pictures/image-7dda44cb-8d84-4df4-82b6-f23dd581d4d3.jpg",
    "height": 2048,
    "width": 1536,
    "isVertical": true }
```
Videos however look like this:
```
 { "uri": "content://media/external/video/media/170" }
```
I can't determine the video extension from the uri here. I assume it is normally mp4, but I believe other video types are possible in edge case scenarios (am I right?). Could the extension or file format be included in some way? on the path at least? I could submit a PR if you let me know what sol'n is preferable.

**Comment by yfuks** [comment]
hi @dchartfield,

I already added the ```path``` to video response, it's not published to npm yet. Can you try it ?

```$> npm install https://github.com/marcshilling/react-native-image-picker --save```

**Comment by dchartfield** [comment]
This works great for me @yfuks , thanks!

**Comment by iljaiwjew** [comment]
is it still actual? For now I don't receive path on android on 3.3.2

**Comment by Shik1997** [comment]
I have this problem now in android on mobile phone(Red Mi Note 9,MIUI 12, Android 11).behind is response 
{
duration: 3
fileName: "video:1376"
fileSize: 5926128
uri: "content://com.android.providers.media.documents/document/video%3A1376"
}

**Comment by Shik1997** [comment]
> is it still actual? For now I don't receive path on Android on verion 3.3.2. Is it possible now to get file extension?

hey,have you solved it ?if you solved it,pls tell me how @iljaiwjew

**Comment by Riaz5687** [comment]
same issue with me as well. Has someone solved it ?

**Comment by Riyaztrad** [comment]
same issue facing 
 {"bitrate": 22002638, "duration": 1, "fileName": "video:294656", "fileSize": 4033785, "height": 1920, "type": "video/mp4", "uri": "content://com.android.providers.media.documents/document/video%3A294656", "width": 1080}
