### ISSUE TITLE
[Android] Selecting picture, taking picture fails

### ISSUE THREAD

**Issue by oddball** [marcshilling/react-native-image-picker#209]
While testing react-native-image-picker/Example on version v0.18.17, the iOS version worked, but the on my Android, Selecting and taking a new picture results in a message "Unfortunately, Gallery has stopped. " Tested on 2 Androids,  A Huawei 330 and a Sony Z3 compact. Selecting a picture that was already in the cameraroll worked

**Comment by yfuks** [comment]
> Gallery has stopped

I'm almost sure that it's an issue with the gallery app. Can you past your stack trace to be sure ?

**Comment by Durgaprasad-Budhwani** [comment]
Just put empty options object literal and check result. Pretty sure some option might be responsible for crash.

**Comment by JonathanWi** [comment]
@oddball Any chance you found a solution? I'm having the exact same issue here...

**Comment by marcshilling** [comment]
Can you run the Example project? The Example project works fine for me. I can take a photo and select a photo on a Samsung Galaxy S6 6.0.1

**Comment by marcshilling** [comment]
No response, closing.
