### ISSUE TITLE
How to change the image width and height

### ISSUE THREAD

**Issue by rakesh0r** [marcshilling/react-native-image-picker#210]
Hi

How to change the image width and height, always the width and height of the image is 150 X 150.
There is any way to change the width and height. i want 230 X 138, maxWidth and maxHeight is not working. maxWidth and maxHeight these options works only when the values are less than the image width and height.

thanks in advance

**Comment by yfuks** [comment]
Not in this library maybe [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) can do it since there is a different crop tool (I really don't know)
