### ISSUE TITLE
how to set localization in native

### ISSUE THREAD

**Issue by ivanzhang** [marcshilling/react-native-image-picker#211]
after set options with localized title, while take photos.

'cancel'
'retake'
'use photo'

still cannot not be localized, 
please point where to update these localizable strings ..

**Comment by marcshilling** [comment]
You can specify options as follows to change the strings. Is this not sufficient?

```
var options = {
  title: 'Select Avatar',
  cancelButtonTitle: 'Cancel',
  takePhotoButtonTitle: 'Take Photo...',
}
```

**Comment by 7daysofrain** [comment]
Hello,

Same problem here, the words "retake" and "use photo" can't be localized via options. Is there a place where we can change that literals?

Thanks!

**Comment by 7daysofrain** [comment]
forget it. It's solved in #150 sorry

**Comment by marcshilling** [comment]
Ah, I see - you were talking about the native iOS camera picker buttons. As @7daysofrain said, see #150 for the solution.

**Comment by deoqc** [comment]
@7daysofrain could you explain how to do it?

**Comment by 7daysofrain** [comment]
Just go to the plist file in xcode, look for the location key and change it to your desired language code. In mine it was set to 'en' and i changed it to 'es'

**Comment by deoqc** [comment]
Thanks @7daysofrain
