### ISSUE TITLE
Facebook Button Option

### ISSUE THREAD

**Issue by andrewheppner** [marcshilling/react-native-image-picker#212]
Hello
Just wondering how one would specify the appropriate action to be taken once one of the custom buttons ex. choose from Facebook is pressed, as I can't see any place to specify a function to be called?

Thanks,
andrew

**Comment by marcshilling** [comment]
Read the README...
```
customButtons: {
    'Choose Photo from Facebook': 'fb', // [Button Text] : [String returned upon selection]
  },
```

`response.fb` would be true if selected

**Comment by marcshilling** [comment]
Assuming this is resolved. Feel free to comment if you're still having trouble.
