### ISSUE TITLE
Will this image picker support icloud image

### ISSUE THREAD

**Issue by 6061960** [marcshilling/react-native-image-picker#214]
Image in icloud is not shown in RN build-in CameraRoll.
Will this image picker library support it?
Will this library support to upload icloud image by XHR?

https://github.com/facebook/react-native/issues/1885

**Comment by charlyBerthet** [comment]
Sound like this was closed without any answer. We are still getting issues with icloud https://stackoverflow.com/questions/73306891/react-native-image-picker-icloud-image-problem

No error is raised, instead an empty object is returned with a non existing file.
