### ISSUE TITLE
alert is not showing for camera access

### ISSUE THREAD

**Issue by shaikhussian** [marcshilling/react-native-image-picker#216]
![simulator screen shot 02-jun-2016 5 42 46 pm](https://cloud.githubusercontent.com/assets/11956308/15744430/8970a764-28e9-11e6-83d8-8575e3184a1a.png)
 I am getting like this empty ,using react-native version 0.25.1 and react-native-image-picker: 0.18.17,
please give me suggestion that how resolve it
when click on cancel i got like this 
![simulator screen shot 02-jun-2016 6 19 06 pm](https://cloud.githubusercontent.com/assets/11956308/15745295/b95291d6-28ee-11e6-9af5-bc303b59caf2.png)

In android it working but in ios i  am facing the above problem

**Comment by shaikhussian** [comment]
please respond till i don't know how to solve this issue

**Comment by shaikhussian** [comment]
please respond, let me know whether it is a bug or problem from me

**Comment by marcshilling** [comment]
I've never experienced this. I always get the permissions pop up. If you go into privacy settings can you enable permissions? Can you run the Example project?

**Comment by shaikhussian** [comment]
In privacy settings it didn't shows the app, it shows like this
![simulator screen shot 06-jun-2016 7 40 20 pm](https://cloud.githubusercontent.com/assets/11956308/15824840/ca01fcf0-2c1e-11e6-8f90-00eb89c844c9.png)
i run your example app it working ok but i didn't add any thing to xcode, what you explained in repo

**Comment by marcshilling** [comment]
Don't know what to tell you. If the Example is working then compare your code to that

**Comment by shaikhussian** [comment]
In my sample my react-native version is "react-native": "^0.25.1", But in your example version is 0.22, can you please tell me that is there any version problem.

**Comment by marcshilling** [comment]
It definitely does not have anything to do with react native version

**Comment by marcshilling** [comment]
@shaikhussian check out [this comment](https://github.com/marcshilling/react-native-image-picker/issues/80#issuecomment-175091356). He had the same issue as you and resolved it.

**Comment by shaikhussian** [comment]
@marchiling i checked in some android devices like lenovo A6000 and tab nexus 7, when acessing camera,after click the picture, it shows like this unfortunately, camera has stopped Android version is 5.1, may i know that what is the problem.

**Comment by marcshilling** [comment]
Why are you talking about Android now? This issue with about iOS permissions. Is that resolved?

**Comment by shaikhussian** [comment]
@marcshilling  sorry that i didn't inform you about the ios issue, i check in simulator it was working fine, when i check in device  ios version:8.4, it is working, but in ios version:9.3.2,same problem. And also in android some devices which i mentioned above are the issues, please give me suggestions for the issue

**Comment by shaikhussian** [comment]
@marcshilling  i checked both the  ios version:8.4 and 9.3.2 below are the data which i copy from simulator for both the versions
**Ios:9.3.2**
`Jun  9 17:00:42 6-silver Project1410] <Warning>: Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
Jun  9 17:00:42 6-silver kernel[0] <Notice>: AppleH6CamIn::setPowerStateGated: 1
Jun  9 17:00:42 6-silver kernel[0] <Notice>: AppleH6CamIn::power_on_hardware
Jun  9 17:00:42 6-silver kernel[0] <Notice>: AppleH6CamIn::power_on_hardware - using ISP-FAST
Jun  9 17:00:42 6-silver tccd[691] <Notice>: Unable to prompt for client without display name (/private/var/containers/Bundle/Application/8D1666CB-50C4-42F9-8BBC-E4F7240CC9ED/Project.app/Project)
Jun  9 17:00:42 6-silver tccd[691] <Notice>: Unable to prompt for client without display name (/private/var/containers/Bundle/Application/8D1666CB-50C4-42F9-8BBC-E4F7240CC9ED/Project.app/Project)
Jun  9 17:00:42 6-silver kernel[0] <Notice>: AppleH6CamIn::ISP_SelectBestMIPIFrequencyIndex_gated - channel: 0, currentRawBitDepth: 1, index: 0
Jun  9 17:00:47 6-silver Project[1410] <Warning>: CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.
Jun  9 17:00:57 6-silver timed[705] <Notice>: (Note ) CoreTime: Want active time in 41.25min. Need active time in 8332.91min. Remaining retry interval: 0.000000min.
Jun  9 17:00:57 6-silver UserEventAgent[26] <Error>: validateAndAddDefaults(com.apple.timed): End Time (inf) > now (487164657.7) + BACKGROUND_TASK_AGENT_JOB_WINDOW_MAX_TIME_FROM_NOW_SEC (3024000.0) + BACKGROUND_TASK_AGENT_JOB_TIME_ERROR_MARGIN (300.0)`

**ios:8.4**
`Jun  9 17:07:12 6plus kernel[0] <Notice>: AppleH6CamIn::ISP_FlushInactiveDARTMappings: 0x00000000
Jun  9 17:07:12 6plus Project[1425] <Notice>: 'Response = ', { didCancel: true }
Jun  9 17:07:12 6plus Project[1425] <Notice>: User cancelled photo picker
Jun  9 17:07:12 6plus mediaserverd[23] <Notice>: '' com.app.project(pid = 1425) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
Jun  9 17:07:15 6plus locationd[61] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Jun  9 17:07:15 6plus Project[1425] <Warning>: Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
Jun  9 17:07:15 6plus kernel[0] <Notice>: AppleH6CamIn::ISP_SelectBestMIPIFrequencyIndex_gated - channel: 0, currentRawBitDepth: 1, index: 1`
in ios 8.4 image picker works correctly but in ios:9.3.2 it shows only black screen and in privacy settings project not displaying,Please give me suggestions to solve this

**Comment by marcshilling** [comment]
I don't understand your issue with Android, but for iOS, this should solve your problem: http://stackoverflow.com/questions/32720535/can-not-access-camera-in-ios-9-for-avcapturedevice

**Comment by shaikhussian** [comment]
@marcshilling Thank you for your response, it working fine,but may i know the issues in android
