### ISSUE TITLE
[Android] M Permissions 

### ISSUE THREAD

**Issue by cherniv** [marcshilling/react-native-image-picker#217]
When i'm trying to use image picker on android 6 my app crashes. In adb logcat i see that the app has no permissions to use camera. Image picker for android based on SDK 23 which means Android M. React Native docs says "The open source version of React Native doesn't yet support the Android M permission model." [http://facebook.github.io/react-native/docs/known-issues.html#android-m-permissions](url) . It means that a new app that want to use image picker permissions will not be granted and it will crash in a moment it will try to use camera. I'm not android developer , but i hope i explained the problem correctly.

**Comment by marcshilling** [comment]
Can you run the example project? The Example project runs fine for me on Android 6 because the manifest file includes `<uses-permission android:name="android.permission.CAMERA" />`

**Comment by cherniv** [comment]
@marcshilling nope, this is the end of the log:

> ...
> :react-native-image-picker:processReleaseResources
> /Users/WebbingLabs/projects/StartupTribeMobile/node_modules/react-native-image-picker/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-v23/values-v23.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
> /Users/WebbingLabs/projects/StartupTribeMobile/node_modules/react-native-image-picker/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-v23/values-v23.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
> 
> :react-native-image-picker:processReleaseResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-image-picker:processReleaseResources'.
> > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/WebbingLabs/Library/Android/sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

**Comment by cherniv** [comment]
@marcshilling hmm , i am not sure how exactly i suppose to run it. What i did was running it from Android Studio on emulator and it gave me this:
![image](https://cloud.githubusercontent.com/assets/3829914/15911469/ace0dc16-2dd8-11e6-9dff-edbf85af0e1d.png)

**Comment by marcshilling** [comment]
C'mon man, put a little effort in. It's the same as any other react native app. Run `npm install` and `npm run start` first

**Comment by cherniv** [comment]
Got it now! The trick is to keep targetSdkVersion lower then 23, when compileSdkVersion is not limited:
![image](https://cloud.githubusercontent.com/assets/3829914/15926295/f321eea2-2e43-11e6-9bcc-c64636d75242.png)
 Thanks!
