### ISSUE TITLE
showImagePicker from Modal not working

### ISSUE THREAD

**Issue by ifunk** [marcshilling/react-native-image-picker#22]
When calling showImagePicker from Facebook's `Modal` component I get the following error:

`Warning: Attempt to present <UIImagePickerController: 0x7f8cde1afc00> on <UIViewController: 0x7f8cded45ba0> whose view is not in the window hierarchy!`

**Comment by udfalkso** [comment]
I ran into this one as well.

**Comment by ifunk** [comment]
@udfalkso We ended up using `react-native-swipeable-modal` (drop-in replacement for Facebook's Modal) and it seemed to work with `showImagePicker` (but I'm not sure if this was the solution or we changed something else at the same time).

**Comment by udfalkso** [comment]
For anyone hitting this... here is a more comprehensive fix that handles modal and non-modal cases (As well as some other changes).  https://github.com/marcshilling/react-native-image-picker/pull/25

**Comment by marcshilling** [comment]
Just merged in @udfalkso's PR which fixes this. Thanks!
