### ISSUE TITLE
[Android] The problem of file directory of taken photo

### ISSUE THREAD

**Issue by yonury** [marcshilling/react-native-image-picker#220]
Is it possible to change the directory of taken photo?

**Comment by marcshilling** [comment]
Yes, provide the `storageOptions` key like so:

```
var options: {
  storageOptions: {
    path: 'whateverYouWant`
  }
}
```

The image will then be saved under your app's `Documents/whateverYouWant` folder.

**Comment by yonury** [comment]
path in storageOptions works only IOS, not Android.

**Comment by marcshilling** [comment]
@yonury I will gladly accept a pull request! I'm not actively working on this project

**Comment by antoinerousseau** [comment]
on my phone (LG G3), settings whatever `storageOptions.path` will save the photo in `Pictures/`
