### ISSUE TITLE
Android - Cannot build

### ISSUE THREAD

**Issue by demiro** [marcshilling/react-native-image-picker#221]
So I have installed the package and linked it and when building I get this

> :app:dexDebug
> Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
> Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
> Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
> Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
> Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
> Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
> Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
> Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
> Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
> Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
> Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
> Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)
> 
> :app:dexDebug FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:dexDebug'.
> > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_92\bin\java.exe'' finished with non-zero exit value 2

I checked all the android files as suggested for manual link and they are all there (except for extra permissions needed - which I aded)

I opened the android sdk and updated... 

but still the issue persists

**Comment by marcshilling** [comment]
I'm in the middle of updating the package.

`npm install react-native-image-picker@latest`. Refer to the updated README

**Comment by marcshilling** [comment]
Also, nothing in your stack trace indicates any issue with this particular package

**Comment by demiro** [comment]
Ran from the android studio which warned me there are some problems with the version of gradle?

anyways... after fixing that I ran the build again which produced:

> * What went wrong:
> Execution failed for task ':react-native-image-picker:processReleaseResources'.
> > java.io.IOException: Could not delete folder C:\DEVEOPMENT\tCoach\mobile-app\node_modules\react-native-image-picker\android\build\generated\source\r\release\android\support\v7

I did install the latest before.... if you are in the middle of updating I will wait :)

**Comment by demiro** [comment]
reinstalled the latest, working now!

**Comment by imalbert** [comment]
I'm getting this too. @demiro do you recall what problems you fixed with gradle and how? It seems that is the cause of this problem.

**Comment by demiro** [comment]
@imalbert : I don't know much about android studio, but it offered me at the time to auto-fix it for me (guess it installed some missing dependencies and updated)

**Comment by imalbert** [comment]
I don't use android studio myself as well. Has it been working well since the fix?

@marcshilling I see this build problem on react-native 0.24 and 0.27. Yet if I run `react-native-image-picker` example it runs perfectly. Do you have any ideas about this?

**Comment by demiro** [comment]
It works OK

**Comment by imalbert** [comment]
Hi, running `cd android && ./gradlew clean` fixed the problem for me. I found it [here](https://github.com/ivpusic/react-native-image-crop-picker/issues/11#issuecomment-225498579)

**Comment by matdehaast** [comment]
@imalbert that worked for me aswell. Thanks

**Comment by Ashu-Shah** [comment]
@imalbert Thank you soo much man....

**Comment by LannyCodes** [comment]
@imalbert running  **cd android && ./gradlew clean** fixed my problem,Thanks!

**Comment by Generalomosco** [comment]
thanks this work for me cd android && gradlew clean

**Comment by MadGeorge** [comment]
For me it does not work after `cd android && gradlew clean`.   
```
$ yarn add react-native-image-picker@latest --save
...
yarn add v1.3.2

react-native link
...
Linking assets to android project 
Assets have been successfully linked to your project
```

iOS build is ok, but android still failed.

**Comment by RajaSaravanan** [comment]
https://github.com/react-community/react-native-image-picker/issues/882
It worked!

**Comment by engineerbaraazakariya** [comment]
For me on Ubuntu I used: 
cd android && gradle clean
hope it helps.
