### ISSUE TITLE
[iOS] After taking a photo using a camera, the cropper pans horizontally but doesn't pan vertically

### ISSUE THREAD

**Issue by eulphean** [marcshilling/react-native-image-picker#224]
As I try to pan the image vertically to fit inside the cropper, the image tends to snap back to its original position. This when I pan in up/down direction. 

However, for  horizontal direction it works fine. 

On the other hand, for image picker, both vertical and horizontal work fine.

**Comment by marcshilling** [comment]
Read the README

**Comment by nica0012** [comment]
This is still an issue... Been hoping this would get resolved over 2019 but images taken with the camera are not able to pan to the top (bottom stuck under pan area). Images from the picker work fine.

The current IOS camera crops fine, maybe there needs to be an update?
