### ISSUE TITLE
Application has stopped working

### ISSUE THREAD

**Issue by Saturnyn** [marcshilling/react-native-image-picker#227]
The application crashes after taking a photo (see stack trace below).

Looks like replacing 'ParseException' by 'Exception' in ImagePickerModule.java at line 418 solves the issue, at least it does fore my phone.

E/AndroidRuntime( 6722): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime( 6722):        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1035)
E/AndroidRuntime( 6722):        at java.text.DateFormat.parse(DateFormat.java:577)
E/AndroidRuntime( 6722):        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:416)
E/AndroidRuntime( 6722):        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:202)
E/AndroidRuntime( 6722):        at com.facebook.react.ReactInstanceManagerImpl.onActivityResult(ReactInstanceManagerImpl.java:561)
E/AndroidRuntime( 6722):        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:184)
E/AndroidRuntime( 6722):        at android.app.Activity.dispatchActivityResult(Activity.java:6192)
E/AndroidRuntime( 6722):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
E/AndroidRuntime( 6722):        ... 10 more

**Comment by marcshilling** [comment]
Can you send a PR?

**Comment by Saturnyn** [comment]
I have sent one, I think... (sorry, not used to submiting PR on gitHub)

**Comment by chenjsa** [comment]
It works for me @Saturnyn .

**Comment by crystalxmumu** [comment]
@Saturnyn good, It works on Android 6.0.1 . thx

**Comment by yfuks** [comment]
publish in ```0.19.3``` thanks @Saturnyn
