### ISSUE TITLE
Returns cancelled image picker immediately

### ISSUE THREAD

**Issue by idajimenez** [marcshilling/react-native-image-picker#231]
Hi!
When I tried to run the app in Samsung Note 3 v4.4.4 in genymotion the image picker immediately returns cancelled image picker.
The response is Response =  Object {didCancel: true}
This is working on other android versions and ios.

**Comment by yfuks** [comment]
Try to set ```allowsEditing: false```

**Comment by idajimenez** [comment]
`allowsEditing: false` is already set. I tried running the Example and it's working fine. when I tried to apply the code from Example to the app, it isn't working

**Comment by yfuks** [comment]
You probably miss some install, make sure you folowed all the steps in the README

**Comment by TerenceLampasa** [comment]
onActivityResult in ImagePickerModule.java receives a resultCode of 0 and not Activity.RESULT_OK, forcing it to return prematurely and give a response of {"didCancel", true}. I don't understand why this happens. It runs alright on a Nexus 7 android v5.1.1. It fails in every v4.4 while the the Moto E android v5.1 is the only non-v4.4 we've seen to fail and return {"didCancel", true}.

**Comment by yfuks** [comment]
Some devices are implemented *strangely*, don't know what to say. Try to debug further and post there if you find a solution

**Comment by TerenceLampasa** [comment]
I managed to fix it by removing "android:launchMode="singleInstance"" from AndroidManifest.xml. It was working fine for weeks before just recently. Strange indeed.

**Comment by dgurns** [comment]
OMG. This solved my problem after searching literally every other issue for solutions. 

LG phone, Android 5.1

Thank you!!
