### ISSUE TITLE
Request to change build iOS setting

### ISSUE THREAD

**Issue by npomfret** [marcshilling/react-native-image-picker#233]
I believe by default react-native apps are have a deployment target of 7.0. This project is linked to iOS 9.2:

<img width="525" alt="screen shot 2016-06-16 at 11 24 53" src="https://cloud.githubusercontent.com/assets/5489469/16113645/12ca6358-33b5-11e6-9bee-9f48260fe22f.png">

It results in a warning at build time that I'd like not to have.

If its possible, could you change the `iOS Deployment Target` in `Build Settings` > `Deployment`  to 7.0 (or as low as the code will allow)?

**Comment by marcshilling** [comment]
@npomfret I set it to `8.0` and published it in `v0.19.4` on npm. Does that clear up your warning?

**Comment by npomfret** [comment]
Indeed it did, many thanks!  Out of interest, was version 7 not possible?
