### ISSUE TITLE
[ANDROID] Undefined is not an object (evaluating 'ImagePicker.showImagePicker')

### ISSUE THREAD

**Issue by AylaMendonca** [marcshilling/react-native-image-picker#234]
Hi, I am having an issue when trying to implement this library on Android (it is working just fine on iOs). I linked the module manually (I checked the files 5 times haha), also I debug it on Android Studio, but everything appears working well. I can't find the error. Do u know what else could cause it?

Thanks

**Comment by yfuks** [comment]
Hi,

You rebuild your app ? ```react-native run-android```
How did you import the module in your code ?

**Comment by AylaMendonca** [comment]
It is working now. I tried rebuild before but did not work. I tried again and now is working fine haha thanks :)
