### ISSUE TITLE
shasum check failure on npm 

### ISSUE THREAD

**Issue by mschipperheyn** [marcshilling/react-native-image-picker#237]
npm ERR! shasum check failed for /var/folders/k4/fpstw1bj6z18tl3hcw5ywbhm0000gn/T/npm-7222-e7ee3416/registry.npmjs.org/react-native-image-picker/-/react-native-image-picker-0.19.4.tgz
npm ERR! Expected: 75983f02f3d2844916f2656c73a797c160e52ec8
npm ERR! Actual:   80a49a639119928162b122389226d559dcdf4cfa
npm ERR! From:     https://registry.npmjs.org/react-native-image-picker/-/react-native-image-picker-0.19.4.tgz

It looks like you might have uploaded a new version under an old version number. I'm trying to load 0.19.1, but it looks like its downloading 0.19.4....

**Comment by marcshilling** [comment]
I don't know how I'm supposed to fix this, so just use 0.19.4...
