### ISSUE TITLE
Duration of Video

### ISSUE THREAD

**Issue by swaroopa94** [marcshilling/react-native-image-picker#238]
Hi,
I am Swaroopa, working on react native.
I am using this module to upload Videos and images.
In this i am not using any duration limit for videos, but it is not accepting the video of duration more than 2 mins.
Can u tell me what is the default time limit for videos and if i want to upload a video of duration more than 2 mins what i have to do..??

Please reply fastly as it is urgent..

**Comment by marcshilling** [comment]
You can specify the `durationLimit` option in seconds to limit the video. Look at the README
