### ISSUE TITLE
android doesn't work

### ISSUE THREAD

**Issue by tofrookie** [marcshilling/react-native-image-picker#239]
![87113424-1dfe-422c-8e8c-8313af8b5681](https://cloud.githubusercontent.com/assets/6767116/16225382/dd93b450-37d8-11e6-9ac7-4b4b60f6eb26.png)

**Comment by marcshilling** [comment]
Are you on version 0.19.5?

**Comment by matdehaast** [comment]
Installed today and working on android.

**Comment by bendellarocco** [comment]
Android is also working fine on my app

**Comment by JagdishUpadhyay** [comment]
Yes I am on version 0.19.5 and It is displaying me error like undefined is not an object(evaluating '_reactNativeImagePicker2.default.showImagePicker').
Plz help.

**Comment by matdehaast** [comment]
@JagdishUpadhyay 
Sounds like you need to do a gradlew clean and build, seems the native part has not been registered in your app yet.

Have you done a react-native run-android first?

**Comment by marcshilling** [comment]
@JagdishUpadhyay did you follow the steps in the README to link the native library in your `build.gradle` file?

**Comment by marcshilling** [comment]
I'm gonna close this because we've got 2 confirmations that Android is building fine. Please follow the README steps thoroughly.

**Comment by JagdishUpadhyay** [comment]
Oh.. Thanks. Now, It is working.......
