### ISSUE TITLE
Images submitted by android seem to be lower quality 

### ISSUE THREAD

**Issue by bendellarocco** [marcshilling/react-native-image-picker#240]
I have noticed that if I submit aphoto with an android the quality is lower than if I submit it with iOS. I am have the quality up all the way and it seemed like it didn't effect androids at all. Is anyone else seeing this?

**Comment by marcshilling** [comment]
What do you mean "submit" a photo? The `quality` option should be respected on Android. You're specifying `quality: 1`? How are you accessing the photo in the response - `uri`, `path`, or `data`?

**Comment by bendellarocco** [comment]
I have it set to quality: 1 and then the image is submitted to our server where we store it.  And it is fetched from there.  The quality of the images from android devices are noticeably lower than ones submitted by iphones.  Sorry for my vague initial post.

Here is the code we are using on our image selector component
`var options = {
  title: 'Select Photo',
  cancelButtonTitle: 'Cancel',
  takePhotoButtonTitle: 'Take Photo...',
  chooseFromLibraryButtonTitle: 'Choose from Library...',
  cameraType: 'back', // 'front' or 'back'
  mediaType: 'photo', // 'photo' or 'video'
  videoQuality: 'high', // 'low', 'medium', or 'high'
  durationLimit: 10, // video recording max time in seconds
  maxWidth: 1200, // photos only
  maxHeight: 1200, // photos only
  aspectX: 1, // android only - aspectX:aspectY, the cropping image's ratio of width to height
  aspectY: 1, // android only - aspectX:aspectY, the cropping image's ratio of width to height
  quality: 1, // 0 to 1, photos only
  angle: 0, // android only, photos only
  allowsEditing: true, // Built in functionality to resize/reposition the image after selection
  noData: false, // photos only - disables the base64 `data` field from being generated (greatly improves performance on large photos)
  storageOptions: { // if this key is provided, the image will get saved in the documents directory on ios, and the pictures directory on android (rather than a temporary directory)
    skipBackup: true, // ios only - image will NOT be backed up to icloud
    path: 'images' // ios only - will save image at /Documents/images rather than the root
  }
};

var ImagePicker = React.createClass ({

	getInitialState(){
		return{
			thumbPhoto: this.props.image,
			photo: ''
		};
	},

	selectPhoto() {
    ImagePickerManager.showImagePicker(options, (response) => {

		  if (response.didCancel) {
		    console.log('User cancelled image picker');
		  }
		  else if (response.error) {
		    console.log('ImagePickerManager Error: ', response.error);
		  }
		  else if (response.customButton) {
		    console.log('User tapped custom button: ', response.customButton);
		  }
		  else {
		    var thumbPhoto = 'data:image/jpeg;base64,' + response.data,
		    photo = response.data,
        re = /(?:\.([^.]+))?$/,
        type = re.exec(response.uri);

		    if(type[1] === 'jpg' || type[1] === 'jpeg' || type[1] === 'png' ){
          var imageObj = {thumbPhoto: thumbPhoto, photo: photo};
		      this.setState(imageObj);
		      this.props.updateImage(imageObj);
        }
        else{
          Alert.alert(
            'Invalid Image Type. Please select a non GIF image.',
            '',
            [
              {text: 'Ok', onPress: () => console.log('titties')},
            ]
          );
        }
		  }
		});
  },

	render(){
		return(
      <View>
        <TouchableHighlight onPress={this.selectPhoto} style={styles.button}>
        		<View style={styles.buttonWrapper}>
        		  { this.state.thumbPhoto ? <Image source={{uri: this.state.thumbPhoto}} style={styles.image}/> : <View style={styles.image}><Icon name={'camera'} color={'white'} size={16} style={styles.cameraIcon}/></View>}
           		<Text style={styles.text}>{this.props.image ? 'Update Image' : 'Upload Photo'}</Text>
           	</View>
        </TouchableHighlight>
    	</View>
		);
	}
});`

**Comment by marcshilling** [comment]
Sorry for the kinda obvious question, but I'm just not sure what would be causing this...what's the source of the photos? Are you comparing the same photo on each device? Maybe your users are just taking poorer quality photos on their crappier Android phones?

**Comment by bendellarocco** [comment]
The images are coming from the library

Android 
![2016-06-22](https://cloud.githubusercontent.com/assets/9866222/16273081/41344d4a-386e-11e6-9169-4a04bdb6dd04.png)

Iphone
![2016-06-22-1](https://cloud.githubusercontent.com/assets/9866222/16273085/47b80f8a-386e-11e6-95ff-ab6fc08f07e1.png)

**Comment by marcshilling** [comment]
Can you try using the `uri` or `path` to display the images rather than `data`?

**Comment by bendellarocco** [comment]
Images are displayed using a URI from our image server :/.  Posting the issue here was not my first debug attempt.  I was hoping to see if anyone had this issue other than me.

We use the data to show the thumbnail before it submitted to the image server.  When the user hits submit the base64 is sent to the server and pulled down to the client through URI fetching from that server.

**Comment by bendellarocco** [comment]
Also both of those screenshots were taken from an iphone

**Comment by marcshilling** [comment]
Ok, well I'm asking if you can try to display the image straight-up from the response, before it goes to your server. I'm wondering if whatever you are using to upload behaves differently on Android/iOS and is unrelated to this module. This is the first time someone has complained about image quality.

**Comment by kvieira90** [comment]
We're using the base64, passing it into a buffer, and sending to S3. The upload process is the exact same on both iOS and Android but android seems to be slightly different (I'm working with @bendellarocco )

**Comment by yfuks** [comment]
I confirm the issue, i see it a couple of times. Will try something to adjust the image quality.

**Comment by yfuks** [comment]
Should be fixed in **0.19.7** can you give it a try @kvieira90 @bendellarocco ?

**Comment by bendellarocco** [comment]
We will upgrade today and let you know.  Thank you @yfuks

**Comment by bendellarocco** [comment]
@yfuks This looks to have solved the issue!  Thank you!

**Comment by dannyyaou** [comment]
Hello Guys
My app has the same issue even now with react-native-image-picker 0.25.1
How can I solve this problem please~

**Comment by lj1000** [comment]
hi @dannyyaou im having a similar issue. did you get a solution.

**Comment by Sir-hennihau** [comment]
Same here

**Comment by nmartin867** [comment]
I had the same problem. It seems setting options maxWidth and maxHeight were causing Android image quality to degrade significantly. Explicitly setting the quality property seems to resolve the issue. 

`  let options = {
      title: 'Take Brag Photo',
      aspectX: 1, // android only - aspectX:aspectY, the cropping image's ratio of width to height
      aspectY: 1, // android only - aspectX:aspectY, the cropping image's ratio of width to height
      quality: 1, // 0 to 1, photos only
      angle: 0, // android only, photos only
      maxWidth: 512,
      maxHeight: 512,
      mediaType: 'photo',
      customButtons: [],
      storageOptions: {
        skipBackup: true,
        path: 'images'
      }
    }`

**Comment by chenHungTzu** [comment]
Same here

**Comment by fajieyefu** [comment]
same here

**Comment by 0plus1** [comment]
Same issue here, there are scattered reports of this and it's one hundred percent an actual issue, been developing a cross platform app with media cropping upload functionalities and there is a significant degrade in quality on Android phones, is there any way we can help debug this?

**Comment by rrath-edr** [comment]
I am facing the same issue. Any fix for this?

**Comment by vinayr** [comment]
Using `resizeMethod` property of `<Image>` might help.
https://facebook.github.io/react-native/docs/image#resizemethod
```
<Image source={{ uri: imageUri }} style={styles.image} resizeMethod="scale" />
```

**Comment by mednche** [comment]
I'm facing the same issue on v4.7.3. Photos taken on android (even though of good quality when viewed on the phone's gallery) look really poor quality when passed through react-native-image-picker (and yet the file size is bigger than those taken on iPhone). I'm comparing the quality by opening the public url in a browser from my S3 bucket.
