### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define La ndroid/support/v7/appcompat/R$anim

### ISSUE THREAD

**Issue by johnwonder** [marcshilling/react-native-image-picker#241]
Unknown source file : com.android.dex.DexException: Multiple dex files define La
ndroid/support/v7/appcompat/R$anim;

**Comment by nihgwu** [comment]
the same problem, i'm using RN0.28
```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by marcshilling** [comment]
I can reproduce, but I have no idea how to fix. Everything online indicates it's an issue with the android support library being included twice, but the only dependency that my library declares is for react-native. If anyone knows how to fix this, please send a pull request.

**Comment by nihgwu** [comment]
But it happens only if I install this package

发自我的 iPhone

**Comment by marcshilling** [comment]
I realize that...there is an issue with this package...I don't know how to fix it....

**Comment by nihgwu** [comment]
I've made it out, i tried to change the `build.gradle` as the other packages and it works

**Comment by marcshilling** [comment]
@nihgwu Can you submit a pull request?

**Comment by nihgwu** [comment]
OK, and thanks for your work, this package is awesome

**Comment by 3vilguy** [comment]
I'm still getting this error. I was checking 0.19.6 and updating targetSdkVersion to 23 didn't help.
Went all the way back to 0.19.3 and it seems to be working.

**Comment by nihgwu** [comment]
@3vilguy have you tried to clean the build folders first? i've just add the dependencies section i didn't mention before, please remove the `build` folders both in the package and in the android folder, ( actually i also remove the `.gradle` folder for clean up)
one of my friend has solved the issue by update this packge

**Comment by 3vilguy** [comment]
@nihgwu yeah I did remove almost anything from android folder which wasn't in original template. In fact I even tried doing:

```
react-native init AwesomeProject
cd AwesomeProject

npm install react-native-image-picker@latest --save
rnpm link react-native-image-picker

react-native run-android
```

And this is blowing up. So pretty much brand new project, nothing added yet, not builded yet...

Any other ideas?

**Comment by villetou** [comment]
I was getting the same error (not sure if it was related to react-native-image-picker) but running `cd android && ./gradlew clean` fixed the issue for me.

**Comment by ericraio** [comment]
@villetou thanks for posting that! it fixed it for me :)

**Comment by SeuJota** [comment]
@villetou thanks.... Perfect work for me :)

**Comment by dunhuang** [comment]
@villetou thanks, really helpful!

**Comment by adrienthiery** [comment]
@villetou : Oh man, lost an hour on that.... Thanks for this solution! I might have spend 2 on it ^_^

**Comment by ccdwyer** [comment]
@villetou: Thank you for that tip, solved my issue.

**Comment by supernova23** [comment]
@villetou thinks

**Comment by pocesar** [comment]
oh man @villetou you saved me, thanks

**Comment by brascene** [comment]
@villetou Thanks!!

**Comment by chance-an** [comment]
@villetou I have to let you know that you are actually super awesome!!!

**Comment by Calvin92** [comment]
@villetou Nice,  good job!!!

**Comment by YangEricLiu** [comment]
@villetou thanks!!!

**Comment by luojinghui** [comment]
@villetou Nice, good job

**Comment by cinder92** [comment]
i'm getting same issue and fix from @villetou  is not working for me...

RN version 0.39

**Comment by theredfoxfire** [comment]
@villetou simple but works thank you!!

**Comment by devhyunjae** [comment]
@villetou thanks

**Comment by SeonaeShin** [comment]
@villetou it doesn't work for me ....in my case guess the module (react-native-firebase-analytics) is related. rn 0.38

**Comment by vinogradov** [comment]
@villetou thanks! Save my day

**Comment by EthanChouTW** [comment]
@villetou thanks

**Comment by dmitriev-alexey** [comment]
@villetou thanks

**Comment by Gentlee** [comment]
For me worked [this](https://stackoverflow.com/a/48924360/1768179) answer. Problem was in disabled proguard.
