### ISSUE TITLE
[Android] I can open the image picker, select an image or take a photo but the photo never comes back to my javascript.

### ISSUE THREAD

**Issue by SudoPlz** [marcshilling/react-native-image-picker#243]
Hi, I have managed to make it work on iOS. I can flawlessly take a photo or select an image from my library.

On ANDROID though, I can select a photo, or take a picture from the camera, but when I click ok and it returns to my app, the response callback never gets called. It only gets called when I **cancel** the picker window.

That is my code:

```javascript
      onImageEditClick(){
        console.log('Opening image picker: ', ImagePicker.showImagePicker);

        ImagePicker.showImagePicker(imgPickerOptions, (response) => {

          //CODE from HERE and below will never run on Android (except from when a user cancels the picker window)
          console.log('Response = ', response);
          if (response.didCancel) {
            console.log('User cancelled image picker');
          }else if (response.error) {
            console.log('ImagePicker Error: ', response.error);
          }else if (response.customButton) {
            console.log('User tapped custom button: ', response.customButton);
          }else {
            // You can display the image using either data:
            const newPhoto = 'data:image/jpeg;base64,'+response.data;
            console.log(newPhoto);
            this.props.actions.updateProfilePhoto(newPhoto, this.TOKEN, this.props.global.isDev)
          }
        });
      }
```

 My biggest problem is I get no obvious errors, neither on `logcat` nor on js. I'm using **0.19.5** on a Nexus 5 with Marshmallow **6.0.1** what to do -?

Edit:
 My logcat says this:
```
		E/mm-camera-intf: mm_camera_poll_thread_del_poll_fd: invalid handler 55296 (0)
		E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 56067
		E/mm-camera-intf: mm_camera_poll_thread_del_poll_fd: invalid handler 55808 (0)
		E/mm-camera: isp_unlink_sink_port: E
		E/mm-camera-img: faceproc_save_album:774] Error No album 
		E/mm-camera-img: faceproc_comp_eng_destroy: Album save failed -1
		E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 55041
		E/QCamera3Channel: virtual int32_t qcamera::QCamera3PicChannel::stop(): Attempt to stop inactive channel
		E/mm-camera: isp_unlink_sink_port: E
		E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 55554
		E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 54528
		E/mm-camera-intf: mm_stream_get_v4l2_fmt: Unknown fmt=78
		E/mm-camera: mct_pipeline_get_stream: stream not found in the list
		E/QCamera3Channel: virtual int32_t qcamera::QCamera3Channel::stop(): Attempt to stop inactive channel
		E/QCamera3Channel: virtual int32_t qcamera::QCamera3Channel::stop(): Attempt to stop inactive channel
		E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 56576
		E/mm-camera: mct_pipeline_get_stream: no children
		E/mm-camera: mct_pipeline_process_set:1451: Couldn't find stream
		E/ANDR-PERF-LOCK: Failed to reset optimization for resource: 4 level: 0
```

Thank you.

**Comment by marcshilling** [comment]
Post your `imgPickerOptions`

**Comment by SudoPlz** [comment]
Those are my options: 

```javascript
    const imgPickerOptions = {
      title: 'Select Avatar', // specify null or empty string to remove the title
      cancelButtonTitle: 'Cancel',
      takePhotoButtonTitle: 'Take Photo...', // specify null or empty string to remove this button
      chooseFromLibraryButtonTitle: 'Choose from Library...', // specify null or empty string to remove this button
      mediaType: 'photo', // 'photo' or 'video'
      maxWidth: 50, // photos only
      maxHeight: 50, // photos only
      quality: 0.9, // 0 to 1, photos only
      allowsEditing: true, // Built in functionality to resize/reposition the image after selection
    };
```

**Comment by marcshilling** [comment]
Set `allowsEditing` to false.

**Comment by SudoPlz** [comment]
Ok thanks I'll try that in 2 minutes, but I want to be able to edit the img, is that not supported?

**Comment by SudoPlz** [comment]
Nope, nothing... The callback is still not being called.!

**Comment by SudoPlz** [comment]
Logging the ImagePickerModule I noticed that `onActivityResult` is not being called.. Any idea why that might be?

**Comment by marcshilling** [comment]
Nope, and I can't reproduce, so please try to debug yourself and submit a PR if you figure anything out.

**Comment by SudoPlz** [comment]
Are you trying on android 23 (6.0.0 or 6.0.1?)

**Comment by marcshilling** [comment]
@yfuks any ideas?

**Comment by SudoPlz** [comment]
@yfuks I believe it has to do with where the tmp img the camera acquires gets saved.

**Comment by SudoPlz** [comment]
Ok found out this is closely related to https://github.com/marcshilling/react-native-image-picker/issues/164.

**Comment by SudoPlz** [comment]
Ok my problem was resolved when I added 
`super.onActivityResult(requestCode, resultCode, data);` to my `MainActivity`'s `onActivityResult` method.

I don't understand the error but as long as it is resolved, I'm happy.

For others using fbsdk you will also have to do that as well.
I will add a pull request to the Readme so that others don't waste a day on this.

**Comment by Gagege** [comment]
I'm still having this problem. ImagePickerModule.onActivityResult is not being called, even after adding `super.onActivityResult(requestCode, resultCode, data)` to my MainActivity.

I think the problem has something to do with placing my React component inside of a Fragment in my Android app. I'm guessing I need to pass my MainActivity.onActivityResult (which _does_ get called) data into my fragment manually somehow.

Also, I tried setting a breakpoint in my fragment's onActivityResult, and it is _not_ called. I don't know what that means exactly, but it seems relevant.

**Comment by dgurns** [comment]
@SudoPlz, did you add that to the MainActivity of your app itself, or to the MainActivity of the react-native-image-picker module?

Could you show your code here?

**Comment by SudoPlz** [comment]
Wow that's been a year ago. If I remember correctly I added that to my MainActivity myself and not the module. I hope that helps.

**Comment by dgurns** [comment]
thanks
