### ISSUE TITLE
inconsistent defaults

### ISSUE THREAD

**Issue by mvayngrib** [marcshilling/react-native-image-picker#246]
thanks for the great library!

iOS uses defaultOptions, Android doesn't. So omitting options in showImagePicker() results in different behavior for the two, specifically: iOS will allow you to choose from library or take a photo and Android will present you with zero options. Maybe the easiest way to make it consistent is to have the default options on the javascript side and remove them from iOS?

**Comment by marcshilling** [comment]
Great idea! Wanna submit a PR?

**Comment by mvayngrib** [comment]
haha, of course i do :)
