### ISSUE TITLE
Target version 7?

### ISSUE THREAD

**Issue by deoqc** [marcshilling/react-native-image-picker#248]
It already came up before [here](https://github.com/marcshilling/react-native-image-picker/issues/233).

Cannot set the deployment target to 7?

I would also suggest to indicate the minimum supported version in the README file.

**Comment by marcshilling** [comment]
Ok, I'll make it 7 in the next release

**Comment by marcshilling** [comment]
Should be live on npm `v0.20.0`

**Comment by deoqc** [comment]
Thanks @marcshilling.
