### ISSUE TITLE
Attempt to invoke interface method 'com.facebook.react.bridge.ReadableMapKeySetIterator com.facebook.react.bridge.ReadableMap.keySetIterator()' on a null object refrence

### ISSUE THREAD

**Issue by YashYash** [marcshilling/react-native-image-picker#251]
On IOS everything is working great. However on android it has been a bit of a struggle. I managed to solve the issues with the build, but now i'm getting the following erro when I attempt to call showImagePicker():

Attempt to invoke interface method ';com.facebook.react.bridge.ReadableMapKeySetIterator com.facebook.react.bridge.ReadableMap.keySetIterator()' on a null object refrence

on line126 of ImagePickerModule.java

![image](https://cloud.githubusercontent.com/assets/6455903/16542810/9056c982-406d-11e6-9c65-c1a527044c02.png)

Here is how I am calling showImagePicker:

Import the lib and options
`import ImagePicker from 'react-native-image-picker';`
`import { imagePickerOptions } from '@constants/imagePickerOptions';`

The imagepicker options
```
export const imagePickerOptions = {
  title: 'Select Avatar',
  cancelButtonTitle: 'Cancel',
  takePhotoButtonTitle: 'Take Photo...',
  chooseFromLibraryButtonTitle: 'Choose from Library...',
  customButtons: {
    'Choose Photo from Facebook': 'fb',
  },
  cameraType: 'back',
  mediaType: 'photo',
  videoQuality: 'high',
  durationLimit: 10,
  maxWidth: 100,
  maxHeight: 100,
  aspectX: 2,
  aspectY: 1,
  quality: 0.7,
  angle: 0,
  allowsEditing: false,
  noData: false,
  storageOptions: {
    skipBackup: true,
    path: 'images'
  }
};
```

The method in the service

```
  _triggerImagePicker(customButtons) {
    console.log(imagePickerOptions);
    let options = imagePickerOptions;

    options.customButtons = customButtons ? customButtons : null;

    const request = new Promise((resolve, reject) => {
      ImagePicker.showImagePicker(options, (response) => {
          if (response.didCancel) {
              // handle error
              resolve('CANCEL');
          } else if (response.error) {
              // handle error
              resolve('ERROR');
          } else if (response.customButton) {
              resolve(true);
          } else {
              // const source = { uri: 'data:image/jpeg;base64,' + response.data, isStatic: true };
              const source = { uri: 'data:image/jpeg;base64,' + response.data, isStatic: true   };
              resolve(source);                  
          }
      });
    });

    return request;
  },
```

My react, react native and react-native-image-picker versions

`"react": "15.2.0",`
`"react-native": "^0.28.0"`
`"react-native-image-picker": "^0.20.0"`

Any idea on how I can make it past this. Ive looked through a bunch of the issues, and I haven't found a duplicate one yet, unless I missed something. Ill keep searching for a fix, but any help would be greatly appreciated.

Thanks!

**Comment by marcshilling** [comment]
Can you comment out the line where you set `customButtons` and see if that works? I have a hunch you're passing null there and that I'm not sure we protect against that

**Comment by YashYash** [comment]
Wooow. Can't believe I didn't try that :p. Thanks a lot man! appreciate it. It's working great now.

**Comment by marcshilling** [comment]
Cool. I added some robustness code that will protect against `customButtons: null` in case anyone else runs into it.
