### ISSUE TITLE
[iOS] Saving photos into the default camera roll directory

### ISSUE THREAD

**Issue by vessp** [marcshilling/react-native-image-picker#252]
Hello, in my app I am using the camera to take pictures by calling **ImagePicker.launchCamera** however I would like the pictures to be saved into the default ios camera roll directory so the user has easy access to them later if they would like.  

I'm pretty new to ios so I don't really know the file structure very well.  I'm not sure if this path argument is relative to the root directory of the filesystem or the root directory of the app folder, but could i do this by setting the **storageOptions.path** to something like **/private/var/mobile/Media/DCIM/**?  

Thanks!

**Comment by marcshilling** [comment]
This isn't supported right now. We would need to add a call to [UIImageWriteToSavedPhotosAlbum](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/doc/uid/TP40006894-CH3-SW29) somewhere in the code

**Comment by gilesvangruisen** [comment]
Opened a PR #281 to add this functionality on iOS

**Comment by marcshilling** [comment]
This is live in `v0.21.5` - thanks @gilesvangruisen!
