### ISSUE TITLE
Is there any way I can know if user has not given camera permission(iOS)

### ISSUE THREAD

**Issue by abhiCR7** [marcshilling/react-native-image-picker#253]
**Case** when user doesn't grant camera access to our app. 
1) When i select the "pick from gallery" option the photos app asks to allow the app access to photos by going into settings. 
2) when i select "take photo" which should launch camera. It takes me to a black screen where i can see the below screen. So obviously as app doesn't have access to camera this is expected. But what I want is to notify to user that since the app doesn't have access to camera so please go to privacy settings and allow(or best show Alert for asking permissions again)
![img_0029](https://cloud.githubusercontent.com/assets/13649070/16558640/9eacd894-4204-11e6-955d-ec34cc1d2ad6.jpg)
Is there currently any way this thing can be addressed using image-picker?

**Comment by marcshilling** [comment]
Hey there. Check out `v0.20.1` that I just published. It should now request permissions before displaying the picker view controller or camera. If permissions have not been granted, the module will return an `error` response. I'll leave it up to you to handle that error and instruct your users to go into settings to enable them. The errors will either be:
`error: Camera permissions not granted` or `error: Photo library permissions not granted`

**Comment by abhiCR7** [comment]
Thanks for the info :)
