### ISSUE TITLE
Initiating via WebView?

### ISSUE THREAD

**Issue by nicklanehq** [marcshilling/react-native-image-picker#256]
Hi,

We are attempting to use this great module and initiate an library/camera picker for an android app. However, the file input targeted is part of a web page that we're loading via a WebView & iFrame and our efforts have been unsuccessful. I wanted to reach out and confirm if this was even possible...to invoke this type of selector on a WebView?

Thanks!

**Comment by yfuks** [comment]
Hi,

No idea.

**Comment by maarekj** [comment]
See the [react-native-webview-bridge](https://github.com/alinz/react-native-webview-bridge), it allows a webview to communicate with react-native.

**Comment by nicklanehq** [comment]
Thanks @maarekj - I'll have a look. Thanks for sharing!
