### ISSUE TITLE
Proper way to identify image format

### ISSUE THREAD

**Issue by deoqc** [marcshilling/react-native-image-picker#259]
What is the proper way to identify the image format (working across iOS and Android)?

Should it be inferred from `response.uri` like in [here](https://github.com/marcshilling/react-native-image-picker/issues/240#issuecomment-227770305) (the relevant snippet copied bellow)?

```Javascript
ImagePickerManager.showImagePicker(options, (response) => {
  ...
  const re = /(?:\.([^.]+))?$/,
        type = re.exec(response.uri)

  if (type[1] === 'jpg' || type[1] === 'jpeg' || type[1] === 'png' ){
    ... 
})
```

**Comment by marcshilling** [comment]
If that code is working for you then yes I would say that is the proper way.

**Comment by deoqc** [comment]
Well I haven't tested it thoroughly (only iOS simulator and iOS device so far)...

**Comment by ospfranco** [comment]
Can we confirm this is working, is it possible to add this in the documentation using base64 with a hardcoded mimetype can bring problems.
