### ISSUE TITLE
[Android] Both buttons are cancelling image picker! 

### ISSUE THREAD

**Issue by karkb** [marcshilling/react-native-image-picker#260]
Hi guys, thanks for such a nice package.

I am trying to take a photo and pick it but it did not work because both buttons are cancelling the process. 
note: Choosing image from library is working fine.I am using android 6.0.0 MIUI 7, Xiaomi MI 5.

![13632755_1319265728101635_741729473_o](https://cloud.githubusercontent.com/assets/20394467/16760139/f79db9ca-484c-11e6-9d2e-f591faf046a0.png)

**Comment by karkb** [comment]
I have tested this issue on Nexus 6P - 6.0.1 and it is working fine.
But on Android 6.0.0 - MIUI 7 - Xiaomi MI 5, still getting this issue unless I turn allowEditing to false, then it will work fine.
Could you please explain this situation? 
what could be the solution for it?

**Comment by marcshilling** [comment]
`allowsEditing` is not supported on some Android devices. I'm considering removing the option entirely from Android as this is the number 1 most opened issue on this repo. If you can find a solution that works for all Android devices, please submit a PR.
