### ISSUE TITLE
Display image from response.path in android

### ISSUE THREAD

**Issue by JagdishUpadhyay** [marcshilling/react-native-image-picker#261]
Hi 

Can I display the selected image using response.path instead of uri. I need this because I have to send image file to server(not the data).

**Comment by zvat** [comment]
@JagdishUpadhyay, Hi
try this:
`source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};`
`<Image  source={this.source} />`

**Comment by JagdishUpadhyay** [comment]
Hi Zvat

I do not want to use data. I want original image file

**Comment by zvat** [comment]
`if (Platform.OS === 'android') {`
`source = {uri: response.uri, isStatic: true};`
`} else {`
`source = {uri: response.uri.replace('file://', ''), isStatic: true};`
`}`

**Comment by JagdishUpadhyay** [comment]
Actually I want a file object

**Comment by JagdishUpadhyay** [comment]
Hi Zvat

Can you help me on getting file object. Actually I need to send captured image as file object to Web API.

**Comment by zvat** [comment]
Hi @JagdishUpadhyay 
i made upload on my server with XMLHttpRequest:
<pre>
.....
var request = new XMLHttpRequest();
request.onreadystatechange = (e) => {
  if (request.readyState !== 4) {
    return;
  }

  if (request.status === 200) {
    console.log('success', request.responseText);
  } else {
    console.warn('error');
  }
};
const file = {
            uri: source.uri,
            type: source.type,
            name: source.name,
        };

const params = new FormData();
        params.append('apikey', 'your_key');
        params.append('something_else', 'your_key');
        params.append('file', file);

request.open('POST', 'https://mywebsite.com/endpoint/');
request.send(params);
</pre>
and it's work normaly. You can use POST or GET. I hope this helps.

**Comment by JagdishUpadhyay** [comment]
Can I use fetch instead of XMLHttpRequest for file posting. Actually I am using fetch API for my api request.

**Comment by JagdishUpadhyay** [comment]
Thanks. It is working now. So I am going to close this.
