### ISSUE TITLE
[Android] Undefined is not an object (evaluating 'ImagePickerManager.showImagePicker'')

### ISSUE THREAD

**Issue by vreyesd** [marcshilling/react-native-image-picker#264]
I run `react-native init` then `rnpm install react-native-image-picker` and replace index.android.js with example. Run `react-native start` and `react-native run-android`

<img src="https://cloud.githubusercontent.com/assets/4206312/16962482/c3d255d8-4dbf-11e6-859c-c8459d925a36.png"  width="200" height="400" />

<img src="https://cloud.githubusercontent.com/assets/4206312/16962487/c81b78ae-4dbf-11e6-8c2d-51602fde85f2.png"  width="200" height="400" />

I'm doing something wrong?

**Comment by marcshilling** [comment]
Seems like you didn't link the native libraries. Follow the instructions in the README, you missed some steps.
