### ISSUE TITLE
iOS - Passing image to another file

### ISSUE THREAD

**Issue by shonnamartell** [marcshilling/react-native-image-picker#266]
I would like to pass the image as a prop or something to another 'screen'. I have no been successful using a code I've used in the past which is 

`this.props.navigator.push({
            title: 'Crop',
            screen: "Gym.CropScreen",
            passProps: { imageuri: response.data.uri },
        });`

**Comment by marcshilling** [comment]
This is a general react native question, not an issue with this library so I'm going to close it. However, I can probably still help but I'll need to see more of your code. Can you post the whole image picker response block?

**Comment by shonnamartell** [comment]
Thank you, 
`    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        var source;

        // You can display the image using either:
        source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};
        console.log(response.data.path);
        this.props.navigator.push({
            title: 'Crop',
            screen: "Gym.CropScreen",
            passProps: { imageuri: response.data.uri },
        });

        // Or:
        // if (Platform.OS === 'android') {
        //   source = {uri: response.uri, isStatic: true};
        // } else {
        //   source = {uri: response.uri.replace('file://', ''), isStatic: true};
        // }

        this.setState({
          avatarSource: source
        });
      }
    });
  }`

**Comment by marcshilling** [comment]
@shonnamartell ah I see. You're trying to pass `response.data.uri`...that will always be undefined. You should either use just `response.data` (if you want the base64 string), or `response.uri` which will give you the URI to the file on the device.

**Comment by shonnamartell** [comment]
Thanks @marcshilling that works :) 👍
