### ISSUE TITLE
Image quality?

### ISSUE THREAD

**Issue by shonnamartell** [marcshilling/react-native-image-picker#267]
Is anyone else having a problem with the captured image quality being low? even when I select an image from the library, the image returned looks pixelated. If this is not a problem with the plugin, feel free to close this topic and ill look into react-native solutions as a whole.

**Comment by shonnamartell** [comment]
Never mind, found the correct options. thanks

**Comment by truca** [comment]
What options were those?

**Comment by Kisepro** [comment]
I'm interrested as well :p

**Comment by gogogous88** [comment]
expo imagePicker can justify quality by quality API (0-1)
