### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by gerardus1995** [marcshilling/react-native-image-picker#269]
I've copied the exact example, but when i click the image that should open the menu to chose library or camera, it says "undefined is not an object (evaluating 'ImagePickerManager.showImagePicker'). The rout of the error is in node modules/react-native-image-picker. Any help please?

**Comment by marcshilling** [comment]
You are not linking the native project. Please follow the [README](https://github.com/marcshilling/react-native-image-picker#android) in depth.

**Comment by gerardus1995** [comment]
I did the npm install and the rnpm to automatically complete the installation. Also i tried the manual installation but then my project explodes and still dont work. Can you explain more detailed which steps do i need for android please?

**Comment by marcshilling** [comment]
@gerardus1995 I hate to say it, but if I were to explain in depth, I would just end up copy and pasting the exact same stuff from the README...
If I were you I would delete `/node_modules/react-native-image-picker` and try again from the beginning. No one else is having this issue, so you must be missing something.

**Comment by gerardus1995** [comment]
Okey thanks, one last question, the complete installation to get the module working consists in the npm and rnpm comand only or i have to npm and the complete it manually?

**Comment by marcshilling** [comment]
Since you're having so much trouble, I would avoid `rnpm`. Doing it manually is super quick and easy.

**Comment by marcshilling** [comment]
@gerardus1995 come to think of it, I've never seen your JS code. Can you post how you are importing the module in Javascript?

**Comment by gerardus1995** [comment]
I'm doing it like this : import ImagePicker from 'react-native-image-picker';
Then using it like in the example you have. 
When i install it manually my project explodes when i react-native run-android

**Comment by marcshilling** [comment]
What do you mean your "project explodes"? Error output? Help me help you...

**Comment by gerardus1995** [comment]
I dont remember exactly but whenever i install any module manually when i restart the app with react-native run-android it explodes before launching the app in the phone with a console error like copiling error or something like that so i allways end up installing automatically.

**Comment by marcshilling** [comment]
iOS or Android?

**Comment by gerardus1995** [comment]
android

**Comment by marcshilling** [comment]
Ok here we go:

- `react-native init gerardus`
- `cd gerardus`
- `npm install react-native-image-picker@latest --save`

Now, following the README....

- Added in `android/settings.gradle`:
```
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(settingsDir, '../node_modules/react-native-image-picker/android')
```
- Added under `dependencies` in `android/app/build.gradle`:
`compile project(':react-native-image-picker')`
- In `MainApplication.java` I added `import com.imagepicker.ImagePickerPackage;` and added `new ImagePickerPackage()` to the list in `getPackages()`

Now, to integrate it into Javascript....
- In `index.android.js` I added `import ImagePicker from 'react-native-image-picker';` to the top, and added this method:
```
  componentDidMount() {
    ImagePicker.showImagePicker(null, () => {});
  }
```

Then, to prove it works:
- `react-native run-android`

The app then successfully built and displayed the image picker upon mounting.

I _really_ hope this helps. I'll be closing this issue now because there's nothing I can do beyond what I just did.

**Comment by gerardus1995** [comment]
Thank you for your help i reinstalled the whole module and now its working! But when it opens the dialog with the open camera and gallery it does nothing only lets me cancel with the example you provided.

**Comment by jaymjax1** [comment]
Just in case anyone else ends up here with the same problem. I want to reiterate the 'react-native run-android' or 'react-native run-ios' part. You may be working from your simulator and will have the tendency to just 'reload' the project after you install libraries or make changes. Be sure that you exit the simulator completely, then restart the app after you install this particular library.

**Comment by pacozaa** [comment]
@jaymjax1  Thank you. Do you use Expo? I still have the problem even though I did everything according to the document.

**Comment by ckim16** [comment]
I'm using Expo and I'm facing the same issue saying `Cannot read property 'showImagePicker' of undefined` even after I did `react-native link`.

**Comment by pacozaa** [comment]
@ckim16  Exactly my problem. I search on google and found a lot of the same issue all over the place but only solution suggest is to 'go read the document' which I triple check everything already.

**Comment by ckim16** [comment]
Does this library support react-native Expo?

**Comment by phyzical** [comment]
thankyou @jaymjax1 this fixed my issue

**Comment by ajithes1** [comment]
@jaymjax1  thank you.
