### ISSUE TITLE
react-native-image-picker  NOT WORKING

### ISSUE THREAD

**Issue by abuammar** [marcshilling/react-native-image-picker#270]
I downloaded it and tried to use this react-native-image-picker, but i get error
"UNDEFINED IS NOT AN OBJECT(evalvation 'ImagePickerManager.showImagePicker').

Can someone plz  guide me using this  react-native-image-picker 
step by step

**Comment by yfuks** [comment]
All steps are in the [README](https://github.com/marcshilling/react-native-image-picker#install)
