### ISSUE TITLE
0.29.2 not work

### ISSUE THREAD

**Issue by liugangfeng** [marcshilling/react-native-image-picker#271]
0.29.2 not work

**Comment by liugangfeng** [comment]
Photo library permissions not granted

**Comment by marcshilling** [comment]
iOS or Android?

**Comment by shirleycharlin** [comment]
just adding on the issue. cos it is somewhat relevant.

The eventlistener react very slowly. Can I know where can I change the event listener if there is? :)
thanks!

**Comment by marcshilling** [comment]
@shirleycharlin I doubt the listener is "lagging". Can you try setting the `noData` option to `false`. Sending a giant base64 data string over the react native bridge is expensive.

**Comment by marcshilling** [comment]
No response from OP, closing

**Comment by shirleycharlin** [comment]
Hi Mr @marcshilling ! 

It works! Thanks for your help! :)
