### ISSUE TITLE
When I click on an option, the popup menu goes away but nothing happens. 

### ISSUE THREAD

**Issue by AaronLlanos** [marcshilling/react-native-image-picker#272]
The setup is as follows: 

```js
'use strict';

import React, { Component, PropTypes } from 'react';
import { View, TextInput, Image, Platform } from 'react-native';
import ImagePicker from 'react-native-image-picker';

import styles from '../lib/styles';
import constants from '../lib/constants';
const {
  AMAZON_AWS_URL,
} = constants;

class UserProfilePage extends Component {
  constructor(props) {
    super(props);
    this.startImagePicker = this.startImagePicker.bind(this);
  }
  startImagePicker() {
    // More info on all the options is below in the README...just some common use cases shown here
    const options = {
      title: null,
      storageOptions: {
        skipBackup: true,
        path: 'images'
      }
    };
    /**
     * The first arg is the options object for customization (it can also be null or omitted for default options),
     * The second arg is the callback which sends object: response (more info below in README)
     */
    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else {
        // You can display the image using either data...
        const source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};

        // or a reference to the platform specific asset location
        if (Platform.OS === 'ios') {
          const source = {uri: response.uri.replace('file://', ''), isStatic: true};
        } else {
          const source = {uri: response.uri, isStatic: true};
        }
        this.setState({
          avatarSource: source
        });
      }
    });
  }
  render() {
    return(
      <View style={styles.container}>
          <View style={styles.profileImageContainer2}>
            <Image style={styles.profileImage2} source={{uri: AMAZON_AWS_URL + this.props.user.photo}} />
          </View>
          <Button style={styles.uploadButton} textStyle={styles.white} onPress={this.startImagePicker}>Upload</Button>
      </View>
    );
  }
}
```

and here are my dependencies: 

```
"react": "15.2.1",
"react-native": "0.28.0",
"react-native-image-picker": "^0.21.2",

```

**Comment by marcshilling** [comment]
iOS or Android?

**Comment by AaronLlanos** [comment]
OH! Sorry I thought that I added that. It happens on Android. Not tested with iOS. I also installed using `rnpm link`

**Comment by AaronLlanos** [comment]
@marcshilling I also have checked my log statements whenever I select an option, and the only thing that logs to the console is when I select "cancel". Otherwise, as I stated above the menu just disappears.

**Comment by marcshilling** [comment]
The only thing that comes to mind is potential permissions issues. If you're on Android > 6.0, you should have gotten popups requesting permissions. If those are denied, what you have happening would probably occur.

Can you run the example project?

**Comment by yfuks** [comment]
Do you have a ```onActivityResult``` in your ```MainApplication.java``` @AaronLlanos ?

**Comment by marcshilling** [comment]
Ah yes, good call @yfuks. Not calling `super()` in there might be the issue.

**Comment by yfuks** [comment]
Seems so.
Just like #164 #243

https://github.com/marcshilling/react-native-image-picker/issues/164#issuecomment-207495707

**Comment by AaronLlanos** [comment]
Okay, 

first off: thanks for all of the quick responses. 

Second: I went through the manual android installation and the only thing that `rnpm link` didn't do was add any of the permissions to the androidmanifest.xml file. After adding those permissions everything worked appropriately without even adding the `onActivityResult` functions to my MainActivity.java files. Tested on Android 6.0.1 on debug mode with `react-native run-android`

Third: I tested on iOS to see if there were similar errors but it ran perfectly with no edits.

With that being said, I think that there should be a bug ticket for `rnpm link` to add the proper permissions? Other than that, it works great! Thanks for all of the help, fellas!

Best, Aaron

**Comment by marcshilling** [comment]
Glad you got it working! I'm not sure if permissions falls to the responsibility of `rnpm`, but it might be worth starting the discussion over on that repo...cheers!
