### ISSUE TITLE
CustomButtons don't match order

### ISSUE THREAD

**Issue by superandrew213** [marcshilling/react-native-image-picker#274]
I have 4 custom buttons and their order can't be controlled.

**Comment by marcshilling** [comment]
Android or iOS?

**Comment by superandrew213** [comment]
Only tested it on iOS

**Comment by superandrew213** [comment]
@marcshilling only on iOS, not happening on Android.

**Comment by marcshilling** [comment]
I'm guessing this is because the order of the keys in the dictionary in not guaranteed. We would need to add another key for index I suppose, does that sound right?

**Comment by superandrew213** [comment]
@marcshilling how about adding the custom buttons using an array?

```
customButtons: [
    { id: 'fb', title: 'Facebook' },
    ...
  ],
```

**Comment by marcshilling** [comment]
Haha, duh. Want to send a PR?

**Comment by superandrew213** [comment]
Sure, might take me a bit to get to it.

**Comment by superandrew213** [comment]
@marcshilling please check that [#296](https://github.com/marcshilling/react-native-image-picker/pull/296) is ok and works on your end.

**Comment by marcshilling** [comment]
Merged, so this can be closed now!
