### ISSUE TITLE
When i click any option of the opening menu, dont do anything

### ISSUE THREAD

**Issue by gerardus1995** [marcshilling/react-native-image-picker#277]
Thank you for your help i reinstalled the whole module and now its working! But when it opens the dialog with the open camera and gallery it does nothing only lets me cancel with the example you provided. Its anything with the permissions or i need to do something else? 

  _selectPhotoTapped() {
    const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true
      }
    };

    ImagePicker.showImagePicker(options, (response) => {
      alert('Response = ', response);

      if (response.didCancel) {
        alert('User cancelled photo picker');
      }
      else if (response.error) {
        alert('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        var source;

        // You can display the image using either:
        source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};
		
        this.setState({
          avatarSource: source
        });
      }
    });
  }

**Comment by yfuks** [comment]
#272 #164 #243

**Comment by shirleycharlin** [comment]
It could be due to file size. Base 64 requires a large number of ram and memory space.
What I did was (this method is credits to the owner)
      storageOptions: {
        skipBackup: true, 
        path: 'images'
      }

otherwise. noData to 'false'.

If you are running on an IOS simulator. make sure you turn off the 'slow animation'. 
Go to Debug > Slow animation

**Comment by yfuks** [comment]
no response
