### ISSUE TITLE
 Integration With Existing Android Apps

### ISSUE THREAD

**Issue by ajiang-lee** [marcshilling/react-native-image-picker#280]
i use android studio create a new project, then i put react native which use react-native-image-picker into the project, the result is:
the project run noraml, the **'Select a Photo'** modal is normal, the camera is normal, and i take a photo, but when i select the photo, the **callback** function of  **ImagePicker.showImagePicker(option, callback)** can not work, anyone can help me? thanks

**Comment by marcshilling** [comment]
Seems like a duplicate of #277, which references some other duplicates that should resolve the issue for you.
