### ISSUE TITLE
Unable to see image gallery in Android while picking image

### ISSUE THREAD

**Issue by varungupta85** [marcshilling/react-native-image-picker#284]
Hi, thanks for the awesome package. I am having some difficulty in using the package on Android simulator running via Genymotion. When the `showImagePicker` call is made, a pop up is shown to ask the user for a source of the image. There I select `Choose From Library...` and then a permission box appears show below. When I click `Allow`, the permission box disappears nothing happens.

![screen shot 2016-08-11 at 12 40 53 pm](https://cloud.githubusercontent.com/assets/7475133/17581586/4866bd6e-5fc4-11e6-8e00-f1dabdd42f20.png)

I see that people have opened issues w.r.t. to Android, so they are able to use it successfully. Is it a problem with the emulator. Am I missing some permissions in the `AndroidManifest.xml` file. I don't have an Android phone on me right now due to which I am not able to test on an actual phone. The code works on iPhone (both simulator and actual device) seamlessly.

**Comment by yfuks** [comment]
I think you need to press allow then repress ```Choose From Library...```

**Comment by varungupta85** [comment]
@yfuks Same events happen when I try to `Choose From Library...` again i.e. I click on the button that shows the image picker, I choose `Choose From Library...`, it asks for permission, I press `Allow` and then nothing happens. I tried this multiple times during the same run of the app.

**Comment by mickeyinfoshan** [comment]
@varungupta85 I think you need to add these lines to `AndroidManifest.xml`:
```xml
 <!-- add following permissions -->
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-feature android:name="android.hardware.camera" android:required="false"/>
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>
    <!-- -->
```

**Comment by varungupta85** [comment]
@mickeyinfoshan Thanks for taking the time to reply to the issue. I tried what you have recommended but I am still observing the same behavior. I am waiting on my Android phone to arrive. I will check on that as well and report back. Maybe it's just an issue with the emulator.

**Comment by tijs** [comment]
I think i am running into the same issue. While the permissions dialog is opened when the `ImagePicker.showImagePicker` method is called choosing either Take Photo or Choose from Library simply closes the dialog without a response or a switch to the camera of gallery view respectively. This used to work, and still does on iOS. Not sure when it stopped working i'm afraid so it's hard to pinpoint the cause more precisely then this.

**Comment by marcshilling** [comment]
For me, after allowing permissions, I have to trigger the picker again but then it works fine. Not sure what you guys are experiencing

**Comment by tijs** [comment]
yeah once it has permissions a new tap opens the picker but with the same result; tapping either option doesn't do anything. my hunch is that is has to something with SDK updates,  but not sure how to verify except by downgrading which i'm hesitant to do :)

**Comment by varun-acintyo** [comment]
I was able to get around to testing it on an Android phone and after adding the permissions suggested by @mickeyinfoshan , I was able to see the image gallery or use the camera to take the picture. Just saw that the permissions are mentioned in the Android Install instructions, not sure why I missed them. Nevertheless, the gallery/camera doesn't open on the emulator but that maybe outside the scope of this package. Thanks all for the help.

**Comment by varungupta85** [comment]
I was able to get around to testing it on an Android phone and after adding the permissions suggested by @mickeyinfoshan , I was able to see the image gallery or use the camera to take the picture. Just saw that the permissions are mentioned in the Android Install instructions, not sure why I missed them. Nevertheless, the gallery/camera doesn't open on the emulator but that maybe outside the scope of this package. Thanks all for the help.

**Comment by varungupta85** [comment]
Not sure if I should have closed the issue as @tijs may still be experiencing it. @tijs Please let me know if you want me to reopen the issue.

**Comment by tijs** [comment]
@varungupta85 i've made a note to double check my permissions, and also test on device once more. will re-open if i still have the issue!

**Comment by peterdev6** [comment]
I am experiencing the same issue on my android device. After allowing the permissions, nothing happens and I have to tap one of the options again to either open the camera or open the image library. On ios, the camera will open immediately after i allow the permissions.

Any ideas?
