### ISSUE TITLE
Android, there is no such file like"android/app/src/main/java/com/<...>/MainApplication.java"

### ISSUE THREAD

**Issue by baddif** [marcshilling/react-native-image-picker#285]
Just a file named "MainActivity.java".
And "import com.imagepicker.ImagePickerPackage;" can not work in this file.

Developing with Visio Code on Windows.

Any suggestion would be appreciated.

**Comment by yfuks** [comment]
Can you copy paste your ```MainActivity.java``` ?

**Comment by baddif** [comment]
`package com.myproject;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

      /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "MyProject";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage()
        );
    }
}
`
This is the code.
I got the basic project from some place I could not remember...
Thanks.

**Comment by yfuks** [comment]
I see no differences from a classic ```MainApplication.java```
Juste make sure you folowed all the installations steps in the README.md

**Comment by baddif** [comment]
While, it says for Android,
`// file: android/app/src/main/java/com/<...>/MainApplication.java
...

import com.imagepicker.ImagePickerPackage; // <-- add this import

public class MainApplication extends Application implements ReactApplication {
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ImagePickerPackage() // <-- add this line
        );
    }
...
}`
My problem is there is no such file as 'MainApplication.java'.

**Comment by baddif** [comment]
Seems like my installing is something wrong.
Now it is OK...
Both Windows and my internet may cause some strange problems...
