### ISSUE TITLE
Receiving incomplete `Response` object 

### ISSUE THREAD

**Issue by surendharreddy** [marcshilling/react-native-image-picker#286]
The callback object `response` is incomplete. (Missing a part of image) 

Here is the log of `response object`.

'Response = ', { type: 'image/jpeg',
fileName: 'nobody_m.original.jpg',
fileSize: 26644,
path: '/storage/emulated/0/Download/nobody_m.original.jpg',
data: '/9j/4AAQSkZJRgABAQEBLAEsAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAQABAADAREAAhEBAxEB/8QAHQABAAICAwEBAAAAAAAAAAAAAAYHBQgBAwQCCf/EAFEQAQABAwIBBwcIBgYJAgYDAAABAgMEBREGBxIhMUFRYRMUInGBkaEVIzJCYnKxwQhDUpKy0TM0NoKi4RckNURTVXOTwiVjJlRkdLPwo9Lx/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAIB/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEB/9oADAMBAAIRAxEAPwD9NQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVrx/y0WOBuJKNLjTvlCKbNNy9VRe5lVuqeqmI2mJ6Np9sA+dL/SD4XztoyozNNqnr8tZ59Me2iZ/AE00jjLQtfiPk/V8PKqn6lF6Ir/dnafgDMzG3X0esHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMVxTxJi8JaDl6pmT81Yp9GjfpuVz9GiPGZ/MGn2satk67quXqGXXz8nJuTduT2bz2R4R1R6geMDtie2O0Eh0TlB4j4dmIwNZy7duP1VdflLf7tW8AsHQf0kNRx5po1jTLGbR23cWryVf7s70z8AWXw7yxcLcRzTbo1CMHIq/UZ0eSnfuir6M+8E1iYqppqpmJpqjeJid4mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYPiPjbQ+E7czquo2cavbeLO/Ou1eqiOkEK0jlczeO+IKdK4Z03yFin07+o50b+St79Mxbidt56oiZ6+zrBaNMbREbzPjPaAADryMi1iWLl+/cps2bVM113K52pppjrmZBq5yscpFfHer02sWaqNGxZmMeieiblXVNyqO+eyOyPXIIIAAAAB1xt2AkHDXHuvcJVx8majds2o68euefan+5PR7tgW/wn+kVg5k0WNfxJwLk9HnWNE12p8Zp+lT7NwW1p2p4mr4lGVg5NrLxq/o3bNcVUz7Y/AHpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7/DpBBeLOWbhzhablmnInVM2no83wpiqInuqr+jHxnwBTfFXLnxHxDz7WJdp0bEq6OZiT85MeNyen3bAgFNN7OyoppivIyL1cUx11V11TO0R3zMyDbHk04GtcC8N2sWYpqz7213Lux9avb6MeFPVHtntBLAAdObm4+nYl3Kyr1GPjWqZruXblW1NMd8yDW3lX5W73Gd2rTdNmvH0Sirp36KsmY+tV3U91PtnwCtQAAAAAAAAZXh3inVeFMzznSs25iXJ+lTTO9FfhVTPRPtBe/AnL1p2uTbw9dpo0rNnamMiJ/1e5Prn6E+vo8QWtExVETExMTG8THbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK+405atB4Vm5j49fyvqFPRNjGqjmUT9uvqj1RvIKN4v5VeIeMprt5OXOJhVf7niTNFvb7U9dXtn2AiHUAC0/0fuFKdY4nvatfo51jTKYm3vHRN6rfm+6N59wNjwAR7jDjzR+B8Py2pZG12qN7WLa9K9d9VPZHjO0A1t4/5TdU49yebfnzTTaKt7WFbq9GO6qqfrVePVHYCIAAAAAAAAAAAAn/J3yv6nwVXbxMiatR0ffacaur07Ud9uZ6vuz0eoGyPD3Een8U6Zbz9MyacnHr6N46KqKu2mqOyfAGSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHOMeP9H4HxYuajkfP1RvbxLXpXbnqjsjxnaAa+cccsWt8ZTcx7dc6Zpk9HmuPVO9cfbr66vVG0eAIGAAADZb9HrCox+AJv0x85k5l2qrv9HamPwBMuIuNNE4UtTXqmpWcarbeLO/Ou1eqiN5BTnGH6RGVl03Mbh3G8ytz0eeZMRVdn7tPVT653BUGbnZGpZVzJy79zJyLk713btU1VVT4zIOkAAAAAAAAAAAAAGd4O401LgjVac3Tru0TtF7HrmfJ3qe6qPwnrgG03BfGuncc6RTnYNfNqp2pvY9c+nZq7p8O6e0GfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABT3KRy62dKqu6bw5VRlZkb03M6dqrVqe2KI+tPj1R4goXOzsjUsu7lZd+5k5N2edXdu1c6qqfGQdAAAAAM1h8a67p2jxpWJqmTiYEVVV+RsVczeauveY6fiDDV11XK6q6qpqrq6ZqqneZ9cg4AAAAAAAAAAAAAAAABmuEOLc/gvWrWo4FfpR6N2zVPoXqO2mr+fZPSDbLhXijB4w0SxqeBXNVq50VUVfStVx10VeMfHrBlgAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Configuration: 
"react": "^0.14.8",
"react-native": "^0.24.1",
"react-native-image-picker": "^0.19.2",

**Comment by yfuks** [comment]
Did you just forget to paste the second ' in ```data``` or is it really missing when you log it ?

**Comment by surendharreddy** [comment]
@yfuks It is really missing...

**Comment by yfuks** [comment]
That's simply a ```console.log()``` issue, ```console.log()``` have a max length limit
