### ISSUE TITLE
Prank in the code ?

### ISSUE THREAD

**Issue by shayany** [marcshilling/react-native-image-picker#288]
I am using the android device to take a picture. However, when I pressed the save the photo is discarded and when I press the discard the photo is saved!(Not Funny)
How can I fix this issue?

**Comment by yfuks** [comment]
And when you take a picture without using this pickage did you get the same issue ?

**Comment by marcshilling** [comment]
I can assure you that my library with 1000+ stars is not a "prank"...lol

**Comment by shayany** [comment]
I know it sounds crazy! But that is my problem. When u want to take a picture without the camera, I just press the button and it takes the picture.(there is no save and discard button)

But in the app, after I take the picture , discard save the picture and save discard the picture! Can I somehow change the caption for them?

**Comment by yfuks** [comment]
It's an issue with your native library not this package
