### ISSUE TITLE
[RNPM] Doesn't work for RN ~ 0.3.x

### ISSUE THREAD

**Issue by aviadhahami** [marcshilling/react-native-image-picker#290]
Title has it all, had to manually install it

**Comment by stenmuchow** [comment]
+1

**Comment by marcshilling** [comment]
Any idea why? Will accept a PR to fix, but I don't care about `rnpm`. The manual instructions are listed in the README and super easy to follow.

**Comment by aviadhahami** [comment]
@marcshilling I would gladly make a PR but I'm yet to figure out `rnpm` (if you have a good tut lmk and I'll do the PR)

**Comment by stenmuchow** [comment]
Hi @marcshilling agreed super easy to follow, but i guess it must be cuz i am new to react-native but i cant get the manual install to work. 

I open the existing foler and import the xcodeproject file from it, but i cant seem to see anything called build-phases... only build-setting. I guess i am doing something wrong.

**Comment by marcshilling** [comment]
You don't see Build Phases along the top?

![screen shot 2016-08-24 at 12 05 18 pm](https://cloud.githubusercontent.com/assets/5598961/17938250/24172ea6-69f3-11e6-87e1-42d13c2efcab.png)

**Comment by stenmuchow** [comment]
https://puu.sh/qMPcX/55d7e6efac.png

**Comment by stenmuchow** [comment]
ah funk... i had the wrong target chosen... feel like an idiot

**Comment by stenmuchow** [comment]
First time i had to manually install a package, thanks for holding my hand. Or watching me... Either way nice work on the tool...

**Comment by marcshilling** [comment]
It's related to this https://github.com/facebook/react-native/issues/8603

**Comment by jniemann66** [comment]
Yeah - I gave rnpm a try. 
It didn't work, so then I followed the manual instructions, and they worked perfectly (once I fixed a few errors I made ...) ! 
Marc, I can vouch for your instructions - they are pretty clear. Thanks !

**Comment by marcshilling** [comment]
Closing this for now. I would love to know why this doesn't work with rnpm or what I could do to make it work. If anyone knows, please send a pull request.
