### ISSUE TITLE
Latest Android Studio upgrade breaks Groovy dependency

### ISSUE THREAD

**Issue by tijs** [marcshilling/react-native-image-picker#293]
It seems that the `import groovy.json.JsonSlurper` dependency is no longer available by default if you upgrade Android Studio and the supporting packages. Looks like this is because Groovy 2+ splits dependencies into multiple projects.

the above import no longer resolved for me in either case but i could resolve this by following the instructions for groovy 2.4 here: http://hosain.net/2015/02/07/getting-started-with-android-development-using-groovy-2.4-and-android-studio.html

In short:

In the app module build.gradle:

    apply plugin: 'groovyx.grooid.groovy-android'

    dependencies {
        //..
        compile 'org.codehaus.groovy:groovy:2.4.0:grooid'
    }

In the project build.gradle:

    classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.5'

It does seem like a large dependency just for parsing a json file. Would it perhaps make more sense to get the version with a simple JSONObject? Something along these lines seems common (disclaimer: i'm not an android expert) http://stackoverflow.com/questions/19945411/android-java-how-can-i-parse-a-local-json-file-from-assets-folder-into-a-listvi/19945484#19945484

**Comment by yfuks** [comment]
Hi,

Will look for it thanks!

**Comment by tijs** [comment]
@yfuks My earlier fix no longer works so i have opted to just set the verionName manually in the gradle file. saves a lot of hassle and it's 2 secs of work after an upgrade of the package so might not be a bad fix in general ;)

**Comment by marcshilling** [comment]
@yfuks I don't really understand this one. Is there anything we need to do to close this?

**Comment by tijs** [comment]
@yfuks @marcshilling i have since upgraded again and now it no longer complains about this groovy package no linger being available. So yes i'll close it as this will probably affect hardly anyone.
