### ISSUE TITLE
Not Saving Photo in Camera Roll

### ISSUE THREAD

**Issue by vaibhawc** [marcshilling/react-native-image-picker#297]
Since this is my first comment -  @marcshilling, Thanks a lot man :)
issue: I can't figure out a way to save and access the picked image from camera roll.
Specifying storageOption.cameraRoll as true doesn't seem to 
Am I supposed to skip the storageOption.path?

**Comment by marcshilling** [comment]
Can you try out v0.22 from npm and see if the issue still exists there?

**Comment by vaibhawc** [comment]
Hey @marcshilling I tried v0.22, it works!. But seems like custom buttons have stopped showing.

**Comment by marcshilling** [comment]
@vaibhawc the custom buttons prop has changed slightly. It now takes an array of objects, so that order can be controlled. You should be able to quickly update that (check the README). Seems like saving to the camera roll is working now, so I'll close this!

**Comment by vaibhawc** [comment]
@marcshilling, It seems like in v0.22 it does allow saving in camera roll but when provided with custom buttons it just gives some fatal error and app crashes. If custom button is not provided it works fine and saves to camera roll. Please confirm.

**Comment by marcshilling** [comment]
@vaibhawc please read my previous comment. The API for custom buttons change...it now takes an array rather than an object, so:
```
customButtons: [
  { name: 'fb', title: 'Choose Photo from Facebook' },
],
```

**Comment by vaibhawc** [comment]
Oh no @marcshilling, I am providing it the way you wrote. When I didn't provide them correctly earlier (my last to last comment) they were not appearing. But now when I gave a custom button the way you mentioned, it does show up but crashed the time I choose even the default options.
`var options = {`
      `title: 'Select An Option',`
      `takePhotoButtonTitle: 'Take Photo',`
      `chooseFromLibraryButtonTitle: 'Share Photo From Library',`
      `customButtons: [{name: 'fb', title: 'Choose Photo from Facebook'},],`
      `storageOptions: {`
        `skipBackup: true,`
        `path: 'images',`
        `cameraRoll: true,`
      `},`
      `noData: true,`
      `maxHeight: 800,`
      `maxWidth: 800,//to give around 500KB size`
    `};`

**Comment by marcshilling** [comment]
This is what I get for merging pull requests without testing first...bear with me while I fix...

**Comment by vaibhawc** [comment]
Hey @marcshilling , wait. Somehow it works now. This is embarrassing. I sharply remember it was crashing. I have no clue what changes in other parts of code could have influenced this. 
Thanks for your patience.

**Comment by marcshilling** [comment]
@vaibhawc No, you're right...there is a crash. I'm fixing it now.

**Comment by marcshilling** [comment]
@vaibhawc fixed in `0.22.1` on npm. Thanks for finding this out.

**Comment by vaibhawc** [comment]
@marcshilling , ohk. I will try out. Btw, I am curious what was the issue? Meanwhile I changed the customButton info from those in docs to some of my own and it again started crashing.

**Comment by marcshilling** [comment]
If you download `0.22.1` from npm, and provide `customButtons` as an array just like in the README, there should be no problems.
