### ISSUE TITLE
Video duration

### ISSUE THREAD

**Issue by SlawomirMazgaj** [marcshilling/react-native-image-picker#299]
Hi!
Is there any way to get a duration of selected video? I know there's a `durationLimit` property but that's not really what I'm after. After picking a video I need to know what's the duration of this video but the object I'm getting just contains `uri` :/

**Comment by yfuks** [comment]
[react-native-video](https://github.com/react-native-community/react-native-video) seems to return this info on the ```onLoad```

**Comment by marcshilling** [comment]
At the moment this isn't supported, but I'm sure this could be added to the video response. If someone wants to look into it and submit a PR, I would gladly merge.

**Comment by marcshilling** [comment]
Please send a PR if you want this feature.

**Comment by KonstantinMuliarchuk** [comment]
yes we need this feature for our app thanks!
