### ISSUE TITLE
Let Source

### ISSUE THREAD

**Issue by wheycool** [marcshilling/react-native-image-picker#3]
I'm missing something. When I include the line,

`let source`

and compile, the app launches with a white screen; nothing more.

When I comment out that line, all seems to work fine, including selecting a photo from my library, EXCEPT after tapping the "Take Photo" option, which presents an error:

`    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class])); `

` Thread 1 : Signal SIGBRT `

Any idea what I'm missing?

**Comment by marcshilling** [comment]
Can you try `var source`?

`let` is an ES6 thing

**Comment by wheycool** [comment]
Only a partial. I didn't notice before, but if I selected a photo from my library, I'd get a red screen because of a missing "source" variable. That is now resolved with your fix.

However, "Take Photo" still presents the same error in Xcode that I mentioned earlier.

**Comment by wheycool** [comment]
Seems that it works on my device without an error, and it is only in the simulator that I'm having a problem. Is this to be expected? I've used React Native cameraApp without a problem in the simulator.

**Comment by marcshilling** [comment]
@wheycool that's it, you can't select `UIImagePickerControllerSourceTypeCamera` on the simulator. I had a check in for that, but I did not have the correct line of code inside the conditional. I'll be pushing an updated version right after this.
