### ISSUE TITLE
App crashes after video compression on iOS

### ISSUE THREAD

**Issue by neacsugeorge** [marcshilling/react-native-image-picker#304]
How to disable video compression? I can't make it work on iOS. After choosing a video, it starts to compress the video and when it's finished the app crash. Log:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSFileManager moveItemAtURL:toURL:error:]: source URL is nil'

(last line) libc++abi.dylib: terminating with uncaught exception of type NSException

Device: iPhone 6S Plus ( Simulator )
RN: 0.32 (but it did not worked on 0.25 either)

**Comment by priegler** [comment]
Having the same issue in our project... any idea why this happens?

**Comment by DDTORRES055** [comment]
Same issue :c

**Comment by nguyenanhthai** [comment]
same issue, any ideal?

**Comment by nguyenanhthai** [comment]
same issue
