### ISSUE TITLE
No support for react native 0.33.0

### ISSUE THREAD

**Issue by wuguanghai45** [marcshilling/react-native-image-picker#305]
I want to upgrade my react native 0.33.0;
But it thrrow error;
![img](https://s18.postimg.io/873qzmgfd/16_D8_FEDF_6_A0_A_40_A4_A86_E_69_AEEE15453_E.jpg)

**Comment by marcshilling** [comment]
I just merged #303...can you updating to `v0.22.3` on npm?

**Comment by marcshilling** [comment]
Duplicate of #307...let's keep everything in there
