### ISSUE TITLE
Support RN 0.33

### ISSUE THREAD

**Issue by marcshilling** [marcshilling/react-native-image-picker#308]
RN 0.33 came out and changed the method signature of `onActivityResult`, detailed in [this](https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35) commit. #303 correctly updated this package to be compatible with 0.33, but I merged it before realizing that it would break backwards compatibility as noted in #307, so I reverted the changes. 

Keeping this issue open so that people realize that currently 0.33 is not supported. I've commented on the specific react native commit to see if the author has any ideas. If anyone knows how to support 0.33 and older versions also, please leave a comment!

**Comment by marcshilling** [comment]
We should now be compatible with React Native 0.33 and below. Get version `0.22.5` on npm if you need 0.33 support!

**Comment by weixingsun** [comment]
@marcshilling I am using latest version 0.22.8, but still not working. 
when override ActivityEventListener.onActivityResult method in MainActivity, no error, but module event not triggered, only MainActivity.onActivityResult triggered.
when no override ActivityEventListener.onActivityResult in MainActivity, app crashes, but event was triggered: 
-----------------------------------------------------------------------------
ImagePickerModule.onActivityResult(): requestCode=813882  resultCode=-1
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.share, PID: 3260
AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:226)
AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:616)
AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
AndroidRuntime:        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:6456)
AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
AndroidRuntime:        at android.app.ActivityThread.-wrap16(ActivityThread.java)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager:   Force finishing activity com.myapp/.MainActivity
