### ISSUE TITLE
Android width=0, height =0

### ISSUE THREAD

**Issue by nlt2390** [marcshilling/react-native-image-picker#309]
After selecting image from gallery, the response object is returned with {width: 0, height: 0}. Tested on:
Emulator: 6.0, 5.1.0, 4.4.4
Real device: Samsung A5 5.1.0
react-native: 0.32
react-native-image-picker: 0.22.5

**Comment by qazs** [comment]
Having the same issue.

**Comment by bennyguitar** [comment]
Looks to be solved by this commit: https://github.com/marcshilling/react-native-image-picker/commit/c5761829f193b3c0a38c33c92bbcd7b01eb3cde8

**Comment by marcshilling** [comment]
Can you guys confirm if it's fixed in v0.22.6 on npm?

**Comment by bennyguitar** [comment]
Testing now. That one-line commit I just linked works when I made it in-line into the `ImagePickerModule.java` file in my own node-modules folder.

**Comment by bennyguitar** [comment]
This is confirmed working with two real devices (Samsung Galaxy S7 Edge and HTC 10 running Android 6.x) and genymotion emulator running the same version of Android.

**Comment by nlt2390** [comment]
Re-tested again. All is good.
