### ISSUE TITLE
Send file object to Parse for upload

### ISSUE THREAD

**Issue by kevinzzz007** [marcshilling/react-native-image-picker#31]
This is an amazing package, thank you so much for building it, I was wondering how can I get file object that can be attached to a Parse object?

**Comment by nice2mu** [comment]
I got this problem too.


how to   use fetch  upload  the  image i pick or take photo ?

**Comment by marcshilling** [comment]
If you use the new `storageOptions` option from this PR https://github.com/marcshilling/react-native-image-picker/pull/28, you will get the URI to the file object in iOS storage. Then you could use something like https://www.npmjs.com/package/react-native-file-upload?

Is that sufficient?

**Comment by alvaromb** [comment]
Hey @marcshilling, thanks for pointing that out. I think that that covers the case where you take a picture with the camera, right? I'm currently dealing with uploading a file from the library, picking the ``uri`` and sending through the ``FormData`` object. The thing is that I keep receiving this error from our server:

```
"The submitted data was not a file. Check the encoding type on the form."
```

This is the code I'm using right now but **it's not working**.

```javascript
export function postData (url, params, fileURI) {
  let data = new FormData()
  if (fileURI) {
    data.append('type', 'file')
    data.append('image', fileURI)
  }
  _.map(params, (value, key) => {
    data.append(key, JSON.stringify(value))
  })

  const config = {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'multipart/form-data; boundary=6ff46e0b6b5148d984f148b6542e5a5d',
      'Content-Language': React.NativeModules.RNI18n.locale,
      'Authorization': 'Token SOMETOKEN',
    },
    body: data,
  }
  return fetch(API_URL + url, config)
    .then(checkStatusAndGetJSONResponse)
}
```

The ``fileURI`` looks something like this

```
/Users/xxxxx/Library/Developer/CoreSimulator/Devices/ABCEDF1234567890/data/Containers/Data/Application/ABCEDF1234567890/tmp/ABCEDF1234567890.jpg"
```

**Comment by kevinzzz007** [comment]
Hi @marcshilling thank you so much! I will try this out and let you know :-)

**Comment by marcshilling** [comment]
@alvaromb interesting. The true path of the file (what this library should be returning) is prefixed with `file://`, can you try sending that and see if it makes a difference?

If not, try passing the `storageOptions` option like this:
```javascript
  storageOptions: { 
    skipBackup: true
  }
```
Maybe it has something to do with it being in the tmp directory?

**Comment by levic92** [comment]
@alvaromb I am currently using XHR to upload images with no issues. My implementation is based off of facebook's example https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/XHRExample.ios.js#L183-L230

Something like this:
```js
formdata.append(photo, {type: "image/jpeg", name: ____, uri: ______ });
```
I believe the uri that I pass to this does not include the preceding "file://" but it may still work with it.

**Comment by kevinzzz007** [comment]
@levic92 thank you so much!  Could you give more details on how to implemented it?  It would really help with my project :+1:

**Comment by levic92** [comment]
Same as in the example link above, just removed stuff I didn't need.
```js
    var xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://posttestserver.com/post.php');
    xhr.onload = () => {
      if (xhr.status !== 200) {
        AlertIOS.alert(
          'Upload failed',
          'Expected HTTP 200 OK response, got ' + xhr.status
        );
        return;
      }
     
      // upload succeeded
      ...
    };
    var formdata = new FormData();
    formdata.append(photo, {type: "image/jpeg", name: ____, uri: ______ });
    
    if (xhr.upload) {
      xhr.upload.onprogress = (event) => {
        console.log('upload onprogress', event);
        if (event.lengthComputable) {
          this.setState({uploadProgress: event.loaded / event.total});
        }
      };
    }
    xhr.send(formdata);
```

**Comment by kevinzzz007** [comment]
@levic92 have you tried to do this with the React Native+Parse framework?

**Comment by alvaromb** [comment]
Ok, the code below is now working perfectly when uploading an image:

```js
export function postData (url, params, fileURL) {
  let data = new FormData()
  if (fileURL) {
    data.append('image', {uri: fileURL, name: 'image.jpg', type: 'image/jpg'})
  }
  _.each(params, (value, key) => {
    if (value instanceof Date) {
      data.append(key, value.toISOString())
    } else {
      data.append(key, String(value))
    }
  })
  const config = {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'multipart/form-data; boundary=6ff46e0b6b5148d984f148b6542e5a5d',
      'Content-Language': React.NativeModules.RNI18n.locale,
      'Authorization': 'Token ABCDEF123457890',
    },
    body: data,
  }
  return fetch(API_URL + url, config)
    .then(checkStatusAndGetJSONResponse)
}
```

It is sending the image and some parameters. It's working perfectly with our Django REST back-end.

**Comment by ashleydw** [comment]
@alvaromb `fileURL` is that the `.uri` property from the result of `showImagePicker`, or something different? My `uri` property is in the format: `assets-library://asset/asset.JPG?id=42EB1977-F2B5-4453-BD0E-CA38AAC2074E&ext=JPG`.

I almost have the exact code as you, but my request never gets sent.

**Comment by alvaromb** [comment]
@ashleydw my ``fileURL`` has this format:

```
file:///Users/xxxxx/Library/Developer/CoreSimulator/Devices/ABCEDF1234567890/data/Containers/Data/Application/ABCEDF1234567890/tmp/ABCEDF1234567890.jpg
```

I'm using ``skipBackup: true``, as suggested by @marcshilling

**Comment by petermason** [comment]
Great package! The file:// uri is dynamic and changes each time you run a build. If you are using local storage for your image ensure to set returnBase64Image to true and store that value. Hope this helps someone.

**Comment by ssomnoremac** [comment]
Will chime in to say that the headers in alvaromb's example weren't working for me in RN35, which is a while after the last post so I just removed them and it worked fine

**Comment by khalidahmada** [comment]
@alvaromb Please what is boundary sorry about this stupid question.

**Comment by alvaromb** [comment]
@khalidahmada http://stackoverflow.com/questions/3508338/what-is-the-boundary-in-multipart-form-data

**Comment by marwajawad** [comment]
hello guys, could you please advise what is the code that should be written in the Rest-backend to upload the file on the server? (I'm using Nodejs, Express)

**Comment by josauder** [comment]
Hi, I was wondering how to to the same thing in typescript. I get an error with this line:

```
data.append('image', {uri: fileURL, name: 'image.jpg', type: 'image/jpg'})
```

Because of a type mismatch:

``` 
Argument of type '{ uri: string; name: string; type: string; }' is not assignable to parameter of type 'string | Blob'.
  Object literal may only specify known properties, and 'uri' does not exist in type 'string | Blob'.
```
The documentation of `FormData.append` looks nothing like the code described above. Does anybody have an idea how to solve this?

**Comment by 12343954** [comment]
image to base64 string is another way i used

**Comment by jaeyow** [comment]
@josauder I have a [workaround for this exact problem here](http://www.masteringreactjs.com/2018/04/11/one-neat-typescript-trick-that-saved-the-day/).

**Comment by vshy108** [comment]
The FormData solution won't work for Parse, still finding valid solution others from base64 because i am trying to upload video file to Parse server

**Comment by Frank1234** [comment]
> Hi, I was wondering how to to the same thing in typescript. I get an error with this line:
> 
> ```
> data.append('image', {uri: fileURL, name: 'image.jpg', type: 'image/jpg'})
> ```
> 
> Because of a type mismatch:
> 
> ```
> Argument of type '{ uri: string; name: string; type: string; }' is not assignable to parameter of type 'string | Blob'.
>   Object literal may only specify known properties, and 'uri' does not exist in type 'string | Blob'.
> ```
> 
> The documentation of `FormData.append` looks nothing like the code described above. Does anybody have an idea how to solve this?

add "as any" behind your object...

{ uri: string; name: string; type: string; } as any
