### ISSUE TITLE
[Android] Some gifs have null file.type

### ISSUE THREAD

**Issue by holyxiaoxin** [marcshilling/react-native-image-picker#310]
It seems that most of the gifs have file.type gifs. But I came across one that doesn't.

![giphy 1](https://cloud.githubusercontent.com/assets/5796213/18509237/1fffa146-7aaa-11e6-897c-05fe16290bac.gif)

Not too sure if github's post processing would affect anything.

**Comment by yfuks** [comment]
What did you get into ```response.path``` ?
