### ISSUE TITLE
[android] set options maxwidth and maxheight does not work

### ISSUE THREAD

**Issue by herve1976** [marcshilling/react-native-image-picker#312]
no matter when I Change those values the camera does not take them into consideration.

Here is my code:

    const cam_options = {
      mediaType: 'photo',
      maxWidth: 200,
      maxHeight: 200,
      quality: 1,
      storageOptions: {
        skipBackup: true,
      }
    };
    ImagePicker.launchCamera(cam_options, (response) => {
      this.setState({
        loadingvisible: false,
      })

**Comment by herve1976** [comment]
"react": "^15.3.0",
    "react-native": "^0.33.0",
    "react-native-fetch-blob": "^0.9.4",
    "react-native-image-picker": "^0.22.0",

**Comment by marcshilling** [comment]
iOS or Android?

**Comment by marcshilling** [comment]
Does it work when you choose photos from the gallery? If you look at the `response.error`, does it contain anything like "Can't resize the image"?

**Comment by herve1976** [comment]
I am not getting any error, the response return an image with no height nor width attribute but the image is there with some different sizes

**Comment by marcshilling** [comment]
I just merged #315, can you try version `0.22.6` on npm?

**Comment by herve1976** [comment]
it's working with 0.22.6

Thank you for this great module

Hervé

**Comment by herve1976** [comment]
One more thing, the height and width in the response is wrong I think.

**Comment by marcshilling** [comment]
Yeah, I see the issue - will fix

**Comment by marcshilling** [comment]
@herve1976 should be fixed in 0.22.7...can you confirm?

**Comment by herve1976** [comment]
perfect everything is working now. thanks again

**Comment by luisfuertes** [comment]
I have this issue with launchCamera

Versions
``` 
		"react": "16.0.0-alpha.6",
		"react-native": "0.43.3",
		"react-native-image-picker": "0.26.3",
``` 

ImagePicker code
``` 
    const options = {
      storageOptions: {
        skipBackup: true,
        path: 'wikifarmacia',
        maxWidth: 640, // photos only
        maxHeight: 640, // photos only
      }
    };

    //ImagePicker.showImagePicker(options, (response) => {
    ImagePicker.launchCamera(options, (response)  => {
      console.log("ImagePicker response: ", response)
    })
``` 

Response:
![captura de pantalla 2017-08-07 a las 14 27 32](https://user-images.githubusercontent.com/18212615/29026654-2900a5f4-7b7d-11e7-9586-b179298d230a.png)


I tried with options but it doesnt work: 
``` 
        fileSize: 600,
        quality: 0.7,
```

**Comment by nichesoftgh04** [comment]
Its not working for me in V-0.24. I am trying maxWidth, maxHeight, height, width and also tried aspectX, aspectY but it't not affecting at all. Image remains a square. I am using it on android.
