### ISSUE TITLE
App crashes while using multiple ImagePicker.

### ISSUE THREAD

**Issue by birat-bade** [marcshilling/react-native-image-picker#313]
I am using this library to select multiple images using multiple ImagePicker. I can take one photo but when I take second Photo the app crashes. I am testing this in android 4.4.2 and 5.0.1

**Comment by marcshilling** [comment]
First of all, multiple image selection isn't supported. But it sounds like you aren't actually doing multiple selection, you are just doing two sequential selections. 

I just tried this on my Android device using the example project and it worked fine. I tapped the "Select a Photo" button, then "Take Photo", then took a photo and it successfully displayed. Then I repeated the process again and the second photo I took displayed. Can you be more clear about what you're trying to do?

**Comment by birat-bade** [comment]
I am trying to take three photos consequently.When I take the first photo the it works. But when I take second photo the app crashes. I am having this problem with only the take photo option. The select photo option works perfectly.

**Comment by marcshilling** [comment]
Please post your JS code

**Comment by birat-bade** [comment]
`import React, { Component } from 'react';
import { View } from 'react-native';
import {
  AppRegistry,
  StyleSheet,
  Text,
  Navigator,
  PixelRatio,
  TouchableOpacity,
  TextInput,
  Image,
  TouchableHighlight
} from 'react-native';
import Form from 'react-native-form';
import ImagePicker from 'react-native-image-picker';

import DropDown, {
  Select,
  Option,
  OptionList,
} from 'react-native-selectme';

var DialogAndroid = require('react-native-dialogs');
var dialog;


var arr = [];
var data = [];

class LoginPage extends Component {
    constructor(props) {
    super(props);
    console.log('Login Page constructor');
      this.state = {
      category: ''
    };
  }

  state = {
    image1: null,
    image2:null,
    image3:null

  };

  _getOptionList() {
    return this.refs.navigator.refs['OPTIONLIST'];
  }

  _category(province) {

  this.setState({
      ...this.state,
      category: province
    });
  }

    showDialog(){
    dialog = new DialogAndroid();
    dialog.set({
      title: 'Posting...',
      content: 'Your add is posting this may take a moment.',
    });
    dialog.show();
  }


  selectPhoto(index) {
    
    const options = {
      title: 'Select a Photo',
      cancelButtonTitle:'Cancel',
      takePhotoButtonTitle:'Take a Photo',
      chooseFromLibraryButtonTitle:'Choose from Library',
      quality: 1.0,
      maxWidth: 1000,
      maxHeight: 1000,
      storageOptions: {
        skipBackup: true
      }
    };
    ImagePicker.showImagePicker(options, (response) => {
     

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        console.log(response);
        var source;
        if(index==0){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image1: source
          });
          console.log('image1 ' + this.state.image1.uri);
        } else if(index==1){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image2: source
          });
          console.log('image2 ' + this.state.image2.uri);
        }else if(index==2){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image3: source
          });
          console.log('image3 ' + this.state.image2.uri);
        }
      }
    });
  }


  render() {
    console.log("Login Page Rendered");
    console.disableYellowBox = true; 
    return (
      <Navigator ref="navigator"
          renderScene={this.renderScene.bind(this)}
          navigationBar={
            <Navigator.NavigationBar style={{backgroundColor: '#000000', alignItems: 'center'}}
                routeMapper={NavigationBarRouteMapper} />
          } />
    );
  }
  renderScene(route, navigator) {
    return (
       <View style={styles.body}>
        <Form ref="form">
          <Text style={{color:'black'}}>Add Photos</Text>
          <View style={styles.viewRow}>
            <TouchableOpacity onPress={this.selectPhoto.bind(this,0)}>
              <View style={{width: 100,borderColor:'black',width: 100,marginLeft:5, height: 100, marginTop:5}}>
                { this.state.image1 == null ? <Image style={{width: 100, height: 100}} source={require('./img/add-png.png')}/> :
                  <Image style={styles.selectedImage} source={this.state.image1} resizeMode="contain" />
                }
              </View>
            </TouchableOpacity>
            <TouchableOpacity onPress={this.selectPhoto.bind(this,1)}>
                <View style={{borderWidth: 1,borderColor:'black',width: 100,marginLeft:5, height: 100,marginTop:5}}>

                  { 
                    this.state.image2 == null ?<Image style={{width: 100, height: 100}} source={require('./img/add-png.png')}/> :
                    <Image style={styles.selectedImage} source={this.state.image2} resizeMode="contain" />
                  }
                </View>
            </TouchableOpacity>
            <TouchableOpacity onPress={this.selectPhoto.bind(this,2)}>
                <View style={{width: 100,borderColor:'black',width: 100,marginLeft:5, height: 100,marginTop:5}}>
                  { 
                    this.state.image3 == null ? <Image style={{width: 100, height: 100}} source={require('./img/add-png.png')}/> :
                    <Image style={styles.selectedImage} source={this.state.image3}  resizeMode="contain"/>
                  }
                </View>
            </TouchableOpacity>
          </View>
          <View style={styles.viewRow}>
            <View style={styles.viewColumn}>
              <Text style={{color:'black'}} >Select Category</Text>
              <View style={{marginTop:5}}>
                <Select
                  type="Select"
                  width={190}
                  height={33}
                  ref="SELECT1"
                  optionListRef={this._getOptionList.bind(this)}
                  defaultValue="Category"
                  onSelect={this._category.bind(this)}>
                       <Option>Books</Option>
                      <Option>Cats</Option>
                      <Option>Dogs</Option>
                      <Option>Home Appliances</Option>
                      <Option>Gifts</Option>
                      <Option>Electronics</Option>
                      <Option>Mobiles</Option>
                      <Option>Furnitures</Option>
                      <Option>Property</Option>
                      <Option>Clothings</Option>
                      <Option>Accessories</Option>
                      <Option>Gadgets</Option>
                      <Option>Sports</Option>
                      <Option>Indoor</Option>
              </Select>
            </View>
            </View>
            <View style={styles.viewColumn,{marginLeft:5}}>
              <Text style={{color:'black'}}>Price</Text>
              <TextInput type="TextInput" name="price"
                placeholder='NRs.'
                style={styles.textinputSmall}/>
            </View> 
          </View>
          <View style={styles.viewColumn}>
              <Text style={{color:'black', marginTop:5}}>Title</Text>
                <TextInput type="TextInput" name="title"
                placeholder='Add Title'
                style={styles.textInputMedium}/>
           </View> 
          <View style={styles.viewColumn}>
            <Text style={{color:'black'}}>Description</Text>
            <TextInput type="TextInput" name="description"
              placeholder='Add Description'
              style={styles.textInputBig}/>
          </View>  
          <OptionList ref="OPTIONLIST"/>
       </Form> 
        <View style={{alignSelf:'center'}}>
        <TouchableHighlight style={styles.submit}
            onPress={this.gotoNext.bind(this)}>
          <Text style={styles.submitText}>Post Your Ad</Text>
        </TouchableHighlight>
      </View>
      </View>
      
    );
  }
  gotoNext() {

    this.showDialog();

    var formObject = this.refs.navigator.refs.form.getValues();
    
    var data = new FormData();
    data.append('category', this.state.category);
    data.append('title', formObject.title);
    data.append('price', formObject.price);
    data.append('description', formObject.description);

    for (i = 0; i < arr.length; i++) {
      try{ 
      var dataURI = arr[i].uri;
      data.append('image'+i,dataURI);
    }catch(e){

    }
    }

    //console.log(data);



    var xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://192.168.169.188/classifiedad/AdvertisementSvc.svc/NewAdvertisement', true);
    xhr.onload = function () {
        console.log('response ' + this.responseText);
        if(this.responseText=='"Uploading Error"'){
          console.log("asdasdasd");
          dialog.dismiss();
        }
    };
    xhr.send(data);
    //this.props.navigator.push({
    //  id: 'MainPage',
    //  name: 'MainPage',
    //});
  }




}

var NavigationBarRouteMapper = {
  LeftButton(route, navigator, index, navState) {
    return null;
  },
  RightButton(route, navigator, index, navState) {
    return null;
  },
  Title(route, navigator, index, navState) {
    return (
      <TouchableOpacity style={{flex: 1, justifyContent: 'center'}}>
        <Text style={{color: 'white', margin: 10, fontSize: 16}}>
          Login
        </Text>
      </TouchableOpacity>
    );
  }
};
const styles = StyleSheet.create({

  body:{
    padding:20,
    marginTop:60,
    flex:5
  },
  viewRow:{
    flexDirection: 'row',
    marginTop:5
  },
  viewColumn:{
    flexDirection: 'column'
  },
  textinputSmall:{
    color:'black',
    height: 40,
    width:123,
    borderColor: 'gray', 
    borderWidth: 1
},
textInputMedium:{
    color:'black',
    height: 40,
    alignSelf: 'stretch',
    borderColor: 'gray', 
    borderWidth: 1
  },
textInputBig:{
  color:'black',
  height: 100,
  alignSelf: 'stretch',
  borderColor: 'gray', 
  borderWidth: 1},
submit:{
    marginBottom:10,
    borderRadius:10,
    width:150,
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#000',
    //borderRadius: 10,
    borderWidth: 1,
    marginTop:5,
    borderColor: '#fff'
  },
  submitText:{
      color:'#fff',
      textAlign:'center',
  },
  selectedImageContainer: {
    borderColor: '#9B9B9B',
    borderWidth: 1 / PixelRatio.get(),
    justifyContent: 'center',
    alignItems: 'center'
  },
  selectedImage: {
    width: 100,
    height: 100
  }
});

module.exports = LoginPage;
`

**Comment by birat-bade** [comment]
`  selectPhoto(index) {
    
    const options = {
      title: 'Select a Photo',
      cancelButtonTitle:'Cancel',
      takePhotoButtonTitle:'Take a Photo',
      chooseFromLibraryButtonTitle:'Choose from Library',
      quality: 1.0,
      maxWidth: 1000,
      maxHeight: 1000,
      storageOptions: {
        skipBackup: true
      }
    };
    ImagePicker.showImagePicker(options, (response) => {
     

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        console.log(response);
        var source;
        if(index==0){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image1: source
          });
          console.log('image1 ' + this.state.image1.uri);
        } else if(index==1){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image2: source
          });
          console.log('image2 ' + this.state.image2.uri);
        }else if(index==2){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image3: source
          });
          console.log('image3 ' + this.state.image2.uri);
        }
      }
    });
  } `

**Comment by birat-bade** [comment]
import React, { Component } from 'react';
import { View } from 'react-native';
import {
  AppRegistry,
  StyleSheet,
  Text,
  Navigator,
  PixelRatio,
  TouchableOpacity,
  TextInput,
  Image,
  TouchableHighlight
} from 'react-native';
import Form from 'react-native-form';
import ImagePicker from 'react-native-image-picker';

import DropDown, {
  Select,
  Option,
  OptionList,
} from 'react-native-selectme';

var DialogAndroid = require('react-native-dialogs');
var dialog;


var arr = [];
var data = [];

class LoginPage extends Component {
    constructor(props) {
    super(props);
    console.log('Login Page constructor');
      this.state = {
      category: ''
    };
  }

  state = {
    image1: null,
    image2:null,
    image3:null

  };

  _getOptionList() {
    return this.refs.navigator.refs['OPTIONLIST'];
  }

  _category(province) {

  this.setState({
      ...this.state,
      category: province
    });
  }

    showDialog(){
    dialog = new DialogAndroid();
    dialog.set({
      title: 'Posting...',
      content: 'Your add is posting this may take a moment.',
    });
    dialog.show();
  }


  selectPhoto(index) {
    
    const options = {
      title: 'Select a Photo',
      cancelButtonTitle:'Cancel',
      takePhotoButtonTitle:'Take a Photo',
      chooseFromLibraryButtonTitle:'Choose from Library',
      quality: 1.0,
      maxWidth: 1000,
      maxHeight: 1000,
      storageOptions: {
        skipBackup: true
      }
    };
    ImagePicker.showImagePicker(options, (response) => {
     

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        console.log(response);
        var source;
        if(index==0){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image1: source
          });
          console.log('image1 ' + this.state.image1.uri);
        } else if(index==1){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image2: source
          });
          console.log('image2 ' + this.state.image2.uri);
        }else if(index==2){
          source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}
          this.setState({
            image3: source
          });
          console.log('image3 ' + this.state.image2.uri);
        }
      }
    });
  }


  render() {
    console.log("Login Page Rendered");
    console.disableYellowBox = true; 
    return (
      <Navigator ref="navigator"
          renderScene={this.renderScene.bind(this)}
          navigationBar={
            <Navigator.NavigationBar style={{backgroundColor: '#000000', alignItems: 'center'}}
                routeMapper={NavigationBarRouteMapper} />
          } />
    );
  }
  renderScene(route, navigator) {
    return (
       <View style={styles.body}>
        <Form ref="form">
          <Text style={{color:'black'}}>Add Photos</Text>
          <View style={styles.viewRow}>
            <TouchableOpacity onPress={this.selectPhoto.bind(this,0)}>
              <View style={{width: 100,borderColor:'black',width: 100,marginLeft:5, height: 100, marginTop:5}}>
                { this.state.image1 == null ? <Image style={{width: 100, height: 100}} source={require('./img/add-png.png')}/> :
                  <Image style={styles.selectedImage} source={this.state.image1} resizeMode="contain" />
                }
              </View>
            </TouchableOpacity>
            <TouchableOpacity onPress={this.selectPhoto.bind(this,1)}>
                <View style={{borderWidth: 1,borderColor:'black',width: 100,marginLeft:5, height: 100,marginTop:5}}>

                  { 
                    this.state.image2 == null ?<Image style={{width: 100, height: 100}} source={require('./img/add-png.png')}/> :
                    <Image style={styles.selectedImage} source={this.state.image2} resizeMode="contain" />
                  }
                </View>
            </TouchableOpacity>
            <TouchableOpacity onPress={this.selectPhoto.bind(this,2)}>
                <View style={{width: 100,borderColor:'black',width: 100,marginLeft:5, height: 100,marginTop:5}}>
                  { 
                    this.state.image3 == null ? <Image style={{width: 100, height: 100}} source={require('./img/add-png.png')}/> :
                    <Image style={styles.selectedImage} source={this.state.image3}  resizeMode="contain"/>
                  }
                </View>
            </TouchableOpacity>
          </View>
          <View style={styles.viewRow}>
            <View style={styles.viewColumn}>
              <Text style={{color:'black'}} >Select Category</Text>
              <View style={{marginTop:5}}>
                <Select
                  type="Select"
                  width={190}
                  height={33}
                  ref="SELECT1"
                  optionListRef={this._getOptionList.bind(this)}
                  defaultValue="Category"
                  onSelect={this._category.bind(this)}>
                       <Option>Books</Option>
                      <Option>Cats</Option>
                      <Option>Dogs</Option>
                      <Option>Home Appliances</Option>
                      <Option>Gifts</Option>
                      <Option>Electronics</Option>
                      <Option>Mobiles</Option>
                      <Option>Furnitures</Option>
                      <Option>Property</Option>
                      <Option>Clothings</Option>
                      <Option>Accessories</Option>
                      <Option>Gadgets</Option>
                      <Option>Sports</Option>
                      <Option>Indoor</Option>
              </Select>
            </View>
            </View>
            <View style={styles.viewColumn,{marginLeft:5}}>
              <Text style={{color:'black'}}>Price</Text>
              <TextInput type="TextInput" name="price"
                placeholder='NRs.'
                style={styles.textinputSmall}/>
            </View> 
          </View>
          <View style={styles.viewColumn}>
              <Text style={{color:'black', marginTop:5}}>Title</Text>
                <TextInput type="TextInput" name="title"
                placeholder='Add Title'
                style={styles.textInputMedium}/>
           </View> 
          <View style={styles.viewColumn}>
            <Text style={{color:'black'}}>Description</Text>
            <TextInput type="TextInput" name="description"
              placeholder='Add Description'
              style={styles.textInputBig}/>
          </View>  
          <OptionList ref="OPTIONLIST"/>
       </Form> 
        <View style={{alignSelf:'center'}}>
        <TouchableHighlight style={styles.submit}
            onPress={this.gotoNext.bind(this)}>
          <Text style={styles.submitText}>Post Your Ad</Text>
        </TouchableHighlight>
      </View>
      </View>
      
    );
  }
  gotoNext() {

    this.showDialog();

    var formObject = this.refs.navigator.refs.form.getValues();
    
    var data = new FormData();
    data.append('category', this.state.category);
    data.append('title', formObject.title);
    data.append('price', formObject.price);
    data.append('description', formObject.description);

    for (i = 0; i < arr.length; i++) {
      try{ 
      var dataURI = arr[i].uri;
      data.append('image'+i,dataURI);
    }catch(e){

    }
    }

    //console.log(data);



    var xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://192.168.169.188/classifiedad/AdvertisementSvc.svc/NewAdvertisement', true);
    xhr.onload = function () {
        console.log('response ' + this.responseText);
        if(this.responseText=='"Uploading Error"'){
          console.log("asdasdasd");
          dialog.dismiss();
        }
    };
    xhr.send(data);
    //this.props.navigator.push({
    //  id: 'MainPage',
    //  name: 'MainPage',
    //});
  }




}

var NavigationBarRouteMapper = {
  LeftButton(route, navigator, index, navState) {
    return null;
  },
  RightButton(route, navigator, index, navState) {
    return null;
  },
  Title(route, navigator, index, navState) {
    return (
      <TouchableOpacity style={{flex: 1, justifyContent: 'center'}}>
        <Text style={{color: 'white', margin: 10, fontSize: 16}}>
          Login
        </Text>
      </TouchableOpacity>
    );
  }
};
const styles = StyleSheet.create({

  body:{
    padding:20,
    marginTop:60,
    flex:5
  },
  viewRow:{
    flexDirection: 'row',
    marginTop:5
  },
  viewColumn:{
    flexDirection: 'column'
  },
  textinputSmall:{
    color:'black',
    height: 40,
    width:123,
    borderColor: 'gray', 
    borderWidth: 1
},
textInputMedium:{
    color:'black',
    height: 40,
    alignSelf: 'stretch',
    borderColor: 'gray', 
    borderWidth: 1
  },
textInputBig:{
  color:'black',
  height: 100,
  alignSelf: 'stretch',
  borderColor: 'gray', 
  borderWidth: 1},
submit:{
    marginBottom:10,
    borderRadius:10,
    width:150,
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#000',
    //borderRadius: 10,
    borderWidth: 1,
    marginTop:5,
    borderColor: '#fff'
  },
  submitText:{
      color:'#fff',
      textAlign:'center',
  },
  selectedImageContainer: {
    borderColor: '#9B9B9B',
    borderWidth: 1 / PixelRatio.get(),
    justifyContent: 'center',
    alignItems: 'center'
  },
  selectedImage: {
    width: 100,
    height: 100
  }
});

module.exports = LoginPage;

**Comment by ubatin** [comment]
I'm have the same problem on `v0.21.5`. But, It perfect worked for me on `v0.22.7`.

**Comment by birat-bade** [comment]
@ubatin Can I take a look at you code??

**Comment by ubatin** [comment]
```javascript
    var options = { quality: 0.8, };
    ImagePicker.showImagePicker(options, (response) => {
      let source = { uri: response.uri };
      let imageData = response;
      if (response.didCancel) {
        this.setState({ image: require('../../../images/logo.png') });
      } else {
        this.setState({ image: source, choice: true, imageData: imageData  });
      }
    });
```

**Comment by marcshilling** [comment]
First of all please try upgrading to the latest version of this package and see if that resolves your issue. I'd also recommend dealing with the `response.uri` rather than `response.data`. Posting your particular crash or stacktrace would be helpful as well.

**Comment by birat-bade** [comment]
Ok I updated the package and made few tweaks in my code and now It works fine. This library is awesome. Keep up the good work and thank you very much.

**Comment by birat-bade** [comment]
@ubatin Thanks for the help cheers.
