### ISSUE TITLE
Getting Error : Did not get valid calls back from JS: %s[[],[],[],[],[]]

### ISSUE THREAD

**Issue by petervavro** [marcshilling/react-native-image-picker#314]
Adding just "import ImagePicker from require('react-native-image-picker')" causing error :

> Did not get valid calls back from JS: %s[[],[],[],[],[]]
> run
>     NativeRunnable.java:-2
> handleCallback
>     Handler.java:733
> dispatchMessage
>     Handler.java:95
> dispatchMessage
>     MessageQueueThreadHandler.java:31
> loop
>     Looper.java:212
> run
>     MessageQueueThreadImpl.java:196
> run
>     Thread.java:841

**Android 4.4.4**

**Comment by marcshilling** [comment]
I don't think that's valid import syntax...

Try
`var ImagePicker = require('react-native-image-picker');`
or
`import ImagePicker from 'react-native-image-picker';`
