### ISSUE TITLE
iOS10 Crash - Requires Permissions.. 

### ISSUE THREAD

**Issue by Gnative** [marcshilling/react-native-image-picker#317]
Not a bug - a note for other users. You may find this component crashes due to iOS10 needing addition descriptions in info.plist. 

NSPhotoLibraryUsageDescription
NSCameraUsageDescription

Might be only related to using XCode - 8 beta.

**Comment by Gnative** [comment]
Might like to add that to the iOS installation instructions.

**Comment by yn5** [comment]
Same issue here. @Gnative could you describe a little more explicitly what needs to be done to prevent the crash?

**Comment by marcshilling** [comment]
@yn5 you just need to add the `NSPhotoLibraryUsageDescription` and `NSCameraUsageDescription` keys to your `Info.plist`. The values should be strings describing why your app needs each permission.

I will add this to the README, thanks @Gnative.
