### ISSUE TITLE
How to configure on iOS?? 

### ISSUE THREAD

**Issue by rogerluo410** [marcshilling/react-native-image-picker#319]
Hi, dear authors,

  I follow the steps you posted on README on iOS, 
```
iOS

1.In the XCode's "Project navigator", right click on your project's Libraries folder ➜ Add Files to <...>
2.Go to node_modules ➜ react-native-image-picker ➜ ios ➜ select RNImagePicker.xcodeproj
3.Add RNImagePicker.a to Build Phases -> Link Binary With Libraries
4.Compile and have fun
```

I did as you posted, but, the first block is where the  `RNImagePicker.a` is, 
I searched with full address, found the only similar one `ios/build/Build/Products/Debug-iphonesimulator/libRNImagePicker.a`,   I have to link it to build the source code. 

When I ran with the example code  you posted on README, there is an error that `Cannnot read property 'showImagePicker'` of undefined`

Obviously, the configure on iOS has problems. 

Could somebody tell me how to fix the configure issue.  BTW, my react-native environment is 0.31.

Thank you in advance.

**Comment by rogerluo410** [comment]
fixed

**Comment by drewsapp** [comment]
I'm having the same issue, how did you fix this?

**Comment by rogerluo410** [comment]
@drewsapp   

Hi,  you need to include the library into your project first,

**Comment by ctorresthrash** [comment]
@rogerluo410 I'm facing the same problem, I've done all the manual steps, the library runs when the project is running from XCode, but error is shown when it's started with `react-native run-ios`. The point is I can't understand what are you talking about with ` you need to include the library into your project first`, could you pleas tell me?

**Comment by rogerluo410** [comment]
@ctorresthrash  

1. In the XCode's "Project navigator", right click on your project's Libraries folder ➜ Add Files to <...>, choose the react-native-image-picker's  .xcodeproj  file which is in "node_modules/react-native-image-picker" folder  into Libraries folder in your project.   

2. Add RNImagePicker.a to Build Phases -> Link Binary With Libraries.  

3. If also have issue, try to clean build.

**Comment by hoainamcr** [comment]
![image](https://user-images.githubusercontent.com/8084862/32858219-616d37dc-ca7d-11e7-9d62-0af664d1ea8a.png)
I don't see any file name is RNImagePicker.a, i just see libRNImagePicker.a, have a error when I add libRNImagePicker.a, so please have any picture for tutorial :((((((, Thanks alll

**Comment by AJDowds** [comment]
Where did you find RNImagePicker.a in the end? I still only see libRNImagePicker.a when I've added the file to my library.
