### ISSUE TITLE
Video recording crashes ios Simulator

### ISSUE THREAD

**Issue by GeoffreyPlitt** [marcshilling/react-native-image-picker#322]
I think several people have seen using this module to do video recording crashes the iOS Simulator. 

Any way around it?

**Comment by marcshilling** [comment]
The simulator is not supported because it does not have a camera. How can you record video without a camera? Try it on a real device.

**Comment by GeoffreyPlitt** [comment]
Yeah, but we have flows where video recording happens in the middle, and we can't test these flows.

Instead of just crashing, can we solve the crash and just return a dummy video, so the component doesn't break the whole app?

**Comment by marcshilling** [comment]
It doesn't crash for me.

As you can see right [here](https://github.com/marcshilling/react-native-image-picker/blob/master/ios/ImagePickerManager.m#L186), we immediately return an error response on the simulator.
