### ISSUE TITLE
react native升级到0.33 报错

### ISSUE THREAD

**Issue by sjb996** [marcshilling/react-native-image-picker#324]
import com.facebook.react.bridge.BaseActivityEventListener;找不到这个东西了

**Comment by hewen1125** [comment]
I don`t have the same problem with RN0.33

**Comment by skellock** [comment]
I'm currently stuck on this too.   It's really strange actually.  That class is clearly there, I'm looking at it right now haha.

I've nuked my `node_modules` and rebuilt with no success.

* My host project is on `react-native` at `0.33.0`.  
* I've nuked and reinstalled `node_modules`
* I've `./gradlew clean`'ed
* My `app/build.gradle` has compile "com.facebook.react:react-native:+"

The only thing I can think of is something in my `app/build.gradle` bringing in a `react-native` version <= 32.  I'm trying to figure that out right now.  I could be totally wrong though.

**Comment by marcshilling** [comment]
Go to your project-level `build.gradle` and make sure your maven config looks like this:
```
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
```

**Comment by skellock** [comment]
Yep, that's in there.

**Comment by PHOEBEYIN2015** [comment]
have the same issue, could not get the com.facebook.react.bridge.BaseActivityEventListener

**Comment by marcshilling** [comment]
I don't know what to tell you guys...it's working for me and many others. Can you run the Example project?

**Comment by skellock** [comment]
Ya Marc.  I'm with you.  This shouldn't not work.  My project was an upgrade (from rn 31) and contains a bunch (7-ish) other 3rd party Android RN libs.  Was never a problem before.

I'll check out the example as you've said.  I'll also try a fresh a fresh RN project and do some eyeball diffing on the key files.

**Comment by skellock** [comment]
Example is fine.  Problem is in our projects somewhere.

**Comment by marcshilling** [comment]
The code regarding this _did_ change recently to support RN 0.33. We now use `BaseActivityEventListener` rather than `ActivityEventListener` directly. However, `BaseActivityEventListener` has been around in RN for many versions now, so I'm not sure why your compiler isn't picking it up.

Please double check the maven setting in the project `build.gradle` again. The url path defined here by `react-native init` changed in a recent version and I know for a fact this fixed this exact same issue for another person recently. It should look exactly like this (`$rootDir` used to be called something else):
```
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
```

**Comment by skellock** [comment]
You sir, are an allstar.

I apologize for missing that nuance the first time you mentioned it.  I saw an "entry" and thought... nah, that's never changed.

Can't thank you enough.

**Comment by skellock** [comment]
Side note... for months, I've been dodging learning how gradle deps are glued together.  If it's one thing I've learned from this issue (other than reading comprehension is an underrated skill), it's time to learn gradle enough to be competent.

**Comment by marcshilling** [comment]
As far as I can tell, everything is working here.

**Comment by vivekkhurana** [comment]
Even I am facing the same issue. This is how my build.grade looks like

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by npomfret** [comment]
After upgrading to rn 0.38-rc, i noticed that file `BaseActivityEventListener.java` is missing.  It should be app in `/Users/nickpomfret/Documents/github/datr/app/pomochat/android/app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.20.1/jars/classes.jar!/com/facebook/react/bridge`, but doesn't:

![screen shot 2016-11-10 at 10 24 17](https://cloud.githubusercontent.com/assets/5489469/20173141/f13e49a4-a72f-11e6-9ad4-2d9d8099cb68.png)

I downloaded [react native](http://central.maven.org/maven2/com/facebook/react/react-native/0.20.1/react-native-0.20.1.aar) from the maven repo and unzipped it.  The class file `BaseActivityEventListener.class` isn't in _classes.jar_:

![screen shot 2016-11-10 at 10 32 45](https://cloud.githubusercontent.com/assets/5489469/20173432/31cd561c-a731-11e6-973e-aca1f3ac8cbc.png)

**Comment by npomfret** [comment]
Can anyone actually compile this project if the open it up in isolation in android studio (outside of their react-native project)?

**Comment by liuliangsir2016** [comment]
![image](https://cloud.githubusercontent.com/assets/22698933/20553202/862de22e-b18d-11e6-9e41-e052d454bd4a.png)

**Comment by npomfret** [comment]
Yes. It doesn't compile.  Apparently by design: https://github.com/marcshilling/react-native-image-picker/issues/386

**Comment by chetstone** [comment]
I just ran into this error when I upgraded react-native from 0.32 to 0.33. I've checked everything mentioned above: `gradlew clean`, $rootDir in my maven, etc.

I'm using version 0.22.14 of this project. What could be the problem?

**Comment by sigrlami** [comment]
@npomfret did you find a way to fix this? aar package install, but project can't find even base interfaces like `ReactPackage`

**Comment by npomfret** [comment]
No, it cannot be fixed.  Seems like the react community don't like to compile code in isolation.  You have to create a react native project and code your library within that.  Madness.

**Comment by marcshilling** [comment]
@npomfret First of all, have you guys upgraded to React Native 0.40 yet and v0.260 of this package? All the `BaseActivityEventListener` stuff has been removed because we now enforce > RN 0.40. 
Beyond that, I still don't understand your real issue and you haven't really offered any suggestions to fix it. This project is not meant to be used outside of a React Native project. It _requires_ React Native in the parent project to build. So you saying you can't "compile code in isolation" doesn't really make sense to me. Help me understand and offer a solution that won't break things for everyone else.

**Comment by sigrlami** [comment]
@marcshilling I just have similar issue with my own library. If we depending on fb react native lib it's obvious that it should be linked against it,  without react native sources on top

**Comment by marcshilling** [comment]
@sigrlami what do you mean "without React Native sources on top"?

**Comment by sigrlami** [comment]
@marcshilling meaning from your words `It requires React Native in the parent project to build.` I think this is required because you use some not public APIs?

**Comment by marcshilling** [comment]
From looking at the post @npomfret linked, it seems like the React Native core team disagrees with what you guys are trying to accomplish. If you can convince them to take steps to make this possible then I'm onboard, but for now I think I'm doing the correct thing with this library.

**Comment by sigrlami** [comment]
@marcshilling I don't mean to question library codebase, it's architecture and your vision at any level. Just have a similar problem on another project that leads to significant inconvenience. Anyway, thank you for engaging in discussion.
