### ISSUE TITLE
Is there a way to always get images with vertical = true?

### ISSUE THREAD

**Issue by liuzhen2008** [marcshilling/react-native-image-picker#328]
I am not quite sure why we should get images that is rotated?

**Comment by marcshilling** [comment]
First of all, are you having issues with iOS or Android?

Secondly, the image is always returned in the same orientation it was taken at, unless you specified the `rotation` option for Android. Is this not what you're experiencing?

**Comment by liuzhen2008** [comment]
@marcshilling I have a portrait image that i took using a regular camera.

I imported the image into an android emulator.

When I read the image using the image picker, and rendered it in a rich text editor, the portrait image is shown 90 degrees rotated to the right (horizontally basically). And the response.vertical = false.

For all the other images that i took using a regular camera horizontally. The image shows up in the correct orientation. And response.vertical = true.

When viewing the portrait image in the android gallery, the portrait image shows up vertically.

**Comment by liuzhen2008** [comment]
@marcshilling I tested again. It seems that the issue only occurred for images that are transferred from a computer to a phone. It worked pretty well for images that were taken by the phone itself.
