### ISSUE TITLE
Setting a Video Duration Limit Triggers an Error Modal

### ISSUE THREAD

**Issue by quadsurf** [marcshilling/react-native-image-picker#329]
The Error Modal that gets displayed to the User says:

"Video Too Long to Send - Please select a smaller clip from this video."

No matter what duration limit I set, it always records 1 second past the duration limit, and that's why this error modal is being triggered... perhaps if the video recording mode ended one second prior to whatever duration limit I hard code, then this wouldn't be an issue and the UI wouldn't force the user to trim down their video by 1 second.

**Comment by marcshilling** [comment]
iOS or Android?

**Comment by mouneyrac** [comment]
Screenshot: https://goo.gl/photos/Z1NsTW5jcaHgQcRp9

I have almost the same error (iOS 10.1 - iPhone 5c). If I put timelimit to 0 there is no issue. But if I put a time limit, once I reach the timelimit then I see "VIDEO_TOO_LONG_TITLE", "Please select a smaller clip from this video". It has no impact has I still can continue using the recorded file, it just looks like the app is broken from the user point of view.

Looking at this issue I found:
http://stackoverflow.com/questions/29497518/video-too-long-to-send-but-it-isnt (they say we need to switch self.picker.allowsEditing = YES; to NO)
http://stackoverflow.com/questions/40317259/video-too-long-title-alert-shown-by-uiimagepickercontroller (they say it is an iOS bug)

I confirm that if I change for self.picker.allowsEditing = NO;
then I don't see the warning message anymore.

**Comment by mouneyrac** [comment]
I just create a pull request in case it is good enough to change to NO (but I understand I don't have a full understanding of the impae picker project, so it just in case it save you some time Marc)

**Comment by marcshilling** [comment]
Ok, I merged the PR so this should be resolved in `v0.22.13`.

**Comment by mouneyrac** [comment]
Thanks Marc.
