### ISSUE TITLE
iOS 10 Photo Library, Camera permission issue

### ISSUE THREAD

**Issue by devhyunjae** [marcshilling/react-native-image-picker#331]
After ios10, the policy have changed to ask the allow popup for photo & camera
![2016-07-03-002](https://cloud.githubusercontent.com/assets/12890257/18771948/05894e22-817e-11e6-8b6e-431a4dc97caa.png)

if i say ok, it fines.

But i say dont' allow, the spinner keeps loading, and the app crashes after few second.

**Comment by marcshilling** [comment]
Dupliate of #330, let's handle it there
