### ISSUE TITLE
It would be great if ActionSheet part can be modularized into a separate repo.

### ISSUE THREAD

**Issue by joonhocho** [marcshilling/react-native-image-picker#336]
This is somewhat an out of topic issue, but I have been looking for a cross platform (iOS and Android) ActionSheet and couldn't find one that works really well on both platforms.
I came across this library, and it has the perfect implementation of ActionSheet on both platforms.
I think it will be really useful for the community if it can be factored out into a separate repo.
What do you think?

**Comment by marcshilling** [comment]
Does [this one](https://github.com/exponentjs/react-native-action-sheet), not do the job? I realize it's pure JS rather than native, but often times that makes life a lot easier.

**Comment by marcshilling** [comment]
Either way, this would be easy to do. If I get some spare time I could do it, but anyone else is welcome to rip the code out and publish it themselves!

**Comment by joonhocho** [comment]
I've seen the one you mentioned, but I think its implementation on Android is not as native as yours.

**Comment by yfuks** [comment]
In **Android** we used the native [AlertDialog](https://developer.android.com/guide/topics/ui/dialogs.html#AlertDialog)

**Comment by yfuks** [comment]
Done: https://github.com/yfuks/react-native-action-sheet
