### ISSUE TITLE
Show videos in gallery

### ISSUE THREAD

**Issue by mihaisee** [marcshilling/react-native-image-picker#34]
Hi, thank you for this package. It helped me a lot, but I was wondering if there is a possibility to also pick a video from the library? thanks

**Comment by marcshilling** [comment]
While this is certainly possible with `UIImagePickerController`, this functionality extends beyond the goals for this library. I'd suggest you fork it and try to implement it yourself. Check out http://stackoverflow.com/questions/11572757/how-can-i-choose-a-video-from-uiimagepickercontroller-and-play-it

**Comment by ababol** [comment]
I am using this https://github.com/ababol/react-native-video-picker it's just a quick workaround but it is working, feel free to improve it.
