### ISSUE TITLE
Delay between pick and showImagePicker callback

### ISSUE THREAD

**Issue by sambwest** [marcshilling/react-native-image-picker#341]
Hi,

There is a 5 second delay between when I select an image to when the ImagePicker.showImagePicker callback is fired. Is this the expected behaviour?

If so, is there any way I can fire a method at the point the image is selected so that I can show a loading message?

Any help appreciated, thanks

**Comment by marcshilling** [comment]
You should set `noData: true` or lower the quality/maxWidth/maxHeight options to get better performance. The delay is due to sending a giant base64 encoded string over the React Native bridge.

**Comment by sambwest** [comment]
Thank you! That helped allot

**Comment by Romick2005** [comment]
Hi! Now there are like 2 sec delay after picture selection. Can we have event "beforeSelect" just right after user click?

**Comment by robsco** [comment]
Seeing the same delay, roughly 2 seconds, even with:

mediaType: 'photo',
maxWidth: 800,
maxHeight: 600,
quality: 0.5,

**Comment by vviss** [comment]
2024. Same issue
