### ISSUE TITLE
Version 0.22.9 crashes in Android

### ISSUE THREAD

**Issue by georgi-kovachev** [marcshilling/react-native-image-picker#342]
I upgraded to 0.22.9 and it fixes the crash when gallery picture is selected.
But the app crashes itself although doing nothing for a 2-3 mins.

**Comment by georgi-kovachev** [comment]
I found that it crashes when remote debug is enabled. I am testing on device.

**Comment by marcshilling** [comment]
Set `noData: true`, or lower your `quality/maxWidth/maxHeight` to improve performance. Sending the base64 encoded string over the react native bridge is very slow.

**Comment by marcshilling** [comment]
@georgi-kovachev still having issues?
