### ISSUE TITLE
[Android] Hide cancel button

### ISSUE THREAD

**Issue by t-moe** [marcshilling/react-native-image-picker#343]
Like with the other buttons where you can pass "null" to hide it, this should also work for `cancelButtonTitle`.

**Comment by marcshilling** [comment]
But shouldn't there always be a cancel button?

**Comment by t-moe** [comment]
There's a back button on android....
Also: Why not add the same API semantics to this button as to the others ;) ?

**Comment by yfuks** [comment]
Hi,

I agree for the **Android** usage @t-moe
Will add a specific options for **Android** only since there is no use case for **iOS**

**Comment by yfuks** [comment]
Added in ```0.22.10```
