### ISSUE TITLE
Duplicate photos

### ISSUE THREAD

**Issue by RatFou** [marcshilling/react-native-image-picker#344]
Hi, I'm running the last version of the picker on Android.

My problem is that when I fetch a photo from my library, the app duplicate it on my photos folder. 

I use data64 in my fetch.

Thanks for your help.

**Comment by marcshilling** [comment]
Can you try _not_ providing the `storageOptions` option key?

**Comment by RatFou** [comment]
Hey!

Thank you, it seems to be working now.
