### ISSUE TITLE
Android crash: The callback launchImageLibrary() exists in module ImagePickerManager...

### ISSUE THREAD

**Issue by npomfret** [marcshilling/react-native-image-picker#345]
Got this on Android 5.1 after taking a photo:

`E/ReactNativeJS: The callback launchImageLibrary() exists in module ImagePickerManager, but only one callback may be registered to a function in a native module.`

Any ideas?

**Comment by yfuks** [comment]
Hi,

Seems like a callback is called twice or more, can you debug further ?
It happens every times ?

**Comment by npomfret** [comment]
Hmm, its difficult to reproduce.  Seems to have gone away without me changing anything.  I'll close this for now - but thanks for the response.
