### ISSUE TITLE
Feature Request: Minumum Size requirements

### ISSUE THREAD

**Issue by bendellarocco** [marcshilling/react-native-image-picker#346]
I would like to have a minimum size (width, height) requirement as well as a maximum size

**Comment by marcshilling** [comment]
What maxWidth/maxHeight does is resize the image such that the image returned is within those constraints. To implement minimum size, we would be scaling the image up from it's original (possibly resulting in a stretched, blurred image). Why would you ever need this?

**Comment by marcshilling** [comment]
No response.
