### ISSUE TITLE
Animated GIF become JPEG

### ISSUE THREAD

**Issue by RatFou** [marcshilling/react-native-image-picker#348]
Hi,

When I want to use an animated GIF with the picker, the image I receive is a JPEG.
Do you know how to tell the picker this image is a GIF and aplly to it a GIF data64?

I'm on Android, my piece of code:
```
selectPhotoTapped() {
		const options = {
			quality: 1.0,
			maxWidth: 800,
			maxHeight: 800,
			title: 'Select a picture',
			cancelButtonTitle: 'Cancel',
			title: 'Select a picture',
			cancelButtonTitle: 'Cancel',
			takePhotoButtonTitle: 'Take picture',
			chooseFromLibraryButtonTitle: 'Phone'
			//noData: false, // we use response.data to display gif
			//allowsEditing: false // make sure we don't edit the gif
		};
		ImagePicker.showImagePicker(options, (response) => {
			if (response.didCancel) { }
			else if (response.error) { alert('ImagePicker Error: ', response.error); }
			else if (response.customButton) { alert('User tapped custom button: ', response.customButton); }
			else {
				var source;
				source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};
				//Or:
				//if (Platform.OS === 'android') { source = {uri: response.uri, isStatic: true}; }
				//else { source = {uri: response.uri.replace('file://', ''), isStatic: true}; }
				//this.setState({ avatarSource: source });
				this.setState({ photo: source });
				this.setState({ photoUpload: source.uri });
			}
		});
}
```

Thank you for your help!

**Comment by yfuks** [comment]
#106

**Comment by RatFou** [comment]
Thank you @yfuks but I already tried this solution: no auto resize, no quality, add `noData: false, allowsEditing: false`

I saw this in the Java code (ImagePickerModule, line 659), I don't know if it is related to my issue:
`String filename = "image-" + UUID.randomUUID().toString() + ".jpg";`

**Comment by RatFou** [comment]
I tried this code to be sure that the module exports a GIF:
`const re = /(?:\.([^.]+))?$/;
type = re.exec(response.uri);
alert(type[1]);`

But it's always alert "jpg", expect for this image where I receive nothing: http://ressources.blogdumoderateur.com/2013/02/gif-anime.gif

**Comment by yfuks** [comment]
```javascript
const options = {
            // quality: 1.0, // we don't change the quality
            // maxWidth: 800, // we don't resize
            // maxHeight: 800, // we don't resize
            title: 'Select a picture',
            cancelButtonTitle: 'Cancel',
            title: 'Select a picture',
            cancelButtonTitle: 'Cancel',
            takePhotoButtonTitle: 'Take picture',
            chooseFromLibraryButtonTitle: 'Phone'
            //noData: false, // we use response.data to display gif
            //allowsEditing: false // make sure we don't edit the gif
        };
```

What is the filename of the file you get ?

**Comment by RatFou** [comment]
Merci yfuks ;)

My problem is that the component always render a JPG file, you can try if you load an animated GIF and export the extension filename:
`
...
var source;
const re = /(?:\.([^.]+))?$/;
type = re.exec(response.uri);
alert(type[1]);
...
`
You will get JPEG/JPG.

If I change the data:image to gif, Imagick (PHP treatment) tell me that this GIF is not in a good format: "no decode delegate for this image format"

If I don't force resize, any GIF file will not have render in the app, just a blank. If I force resize I will have the render in the app but animation will be lost.

Thanks for your help!

**Comment by yfuks** [comment]
> If I change the data:image to gif, Imagick (PHP treatment) tell me that this GIF is not in a good format: "no decode delegate for this image format"

Are you sure that your Imagick support gif ? [stackoverflow](http://stackoverflow.com/a/30006432)

> If I don't force resize, any GIF file will not have render in the app, just a blank. If I force resize I will have the render in the app but animation will be lost.

If you force resize that basically transform your image into jpg. So don't do it if you want gif.
To display animated gif in your **Android** app : [react native doc](https://facebook.github.io/react-native/docs/image.html#gif-and-webp-support-on-android)

**Comment by RatFou** [comment]
Imagick supports animated GIF: [http://stackoverflow.com/questions/13997518/php-imagick-create-gif-animation](stackoverflow)

Thanks for the link to display GIF in Android, I saw it before, but I can't upload animated GIF so I will see that at the right moment ;)

**Comment by RatFou** [comment]
If I don't force resize on animated GIF, it will be uploaded as a JPG (the fille type is undefined regarding to `type[1]`).

**Comment by yfuks** [comment]
And in ```response.type``` ?

**Comment by RatFou** [comment]
`response.type` image/gif

**Comment by yfuks** [comment]
- You can't always get the file extension with the uri, the uri don't always have the file extension in it.
- ```response.type``` is there for the purpose you want.

> If I don't force resize on animated GIF, it will be uploaded as a JPG 

- And know i repeat my self but don't resize the image if you want a ```gif```

> ```response.type``` image/gif

- so you have a gif you know how to display it you are SURE that your version of Imagick support gif and you still have issue ?

**Comment by RatFou** [comment]
Thank you for `response.type` I will use it now.

> And know i repeat my self but don't resize the image if you want a gif
That's the point, I don't force resize to be sure i'm getting GIF but the image I receive is a JPG.

I'm sure Imagick is working fine, I've tested it with a classic web upload.

**Comment by yfuks** [comment]
Can you paste your upload code and your picker code ?

**Comment by RatFou** [comment]
My bad, I sent full header to Imagick, not just the data64. Thanks for your time!

**Comment by SiyabongaNzulwana** [comment]
@yfuks in my case I am resizing the image deliberately, I just want a way that when the gallery of my photo opens, we filter out `gifs` ... so my gallery would only show `image/jpeg` or `image/png` ONLY. so that the user does not get a chance to select `gifs`
