### ISSUE TITLE
Library/Camera doesn't open on Android 7.0 with RN 0.31

### ISSUE THREAD

**Issue by TroutZen** [marcshilling/react-native-image-picker#351]
The imagepicker options opens, but click on the library or the camera fails to launch those services.

**Comment by funkysoul** [comment]
@TroutZen I'm actually experiencing the same issue with the exact versions you mentioned above, did you fix that or do you know why this happens?

**Comment by thorbenprimke** [comment]
I'm seeing a crash with Android 7 and RN 0.38. Seems to be isolated to Android 7. Will dig into the Java crash stack tonight.
