### ISSUE TITLE
App closes after chooseFromLibraryButton

### ISSUE THREAD

**Issue by shengzihong** [marcshilling/react-native-image-picker#352]
react-native-cli@1.0.0
rnpm@1.9.0

react-native-image-picker@0.20.0

I followed all the steps in README.

Does anyone have the same problem?

**Comment by francois-roget** [comment]
Same problem...

**Comment by yfuks** [comment]
**Android**/**iOS** ?

**Comment by marcshilling** [comment]
@shengzihong for starters, update the react-native-image-picker package to 0.22.9 - you're many versions behind.

**Comment by francois-roget** [comment]
For my part: 
react-native@0.35.0
react-native-image-picker@0.22.9

Crash on chooseFromLibraryButton on iOS

**Comment by marcshilling** [comment]
@francois-roget crash log?

**Comment by shengzihong** [comment]
@yfuks No errors, No crash outputs, On IOS. I have updated the latest version before I posted this issue. However, it's still the same problem.

**Comment by francois-roget** [comment]
My bad! I missed the NSPhotoLibraryUsageDescription in the Info.plist
Seems to work now.

Thanks for the quick feedback

**Comment by marcshilling** [comment]
@shengzihong can you try what @francois-roget said?

**Comment by shengzihong** [comment]
@marcshilling Problem is solved! After adding NSPhotoLibraryUsageDescription into info.plist. Thanks @francois-roget, and thanks others.

**Comment by bendman** [comment]
The _Info.plist_ changes seem to still be necessary when installing the automatic way using `react-native link`.  Maybe this merits documentation in the _README.md_?

**Comment by bgriffith** [comment]
Just to chip in that I also had this issue after installing automatically and fixed it by manually adding the missing keys to the info.plist.
