### ISSUE TITLE
Open Front Camera Directly in Android

### ISSUE THREAD

**Issue by sstur** [marcshilling/react-native-image-picker#354]
According to the readme this package doesn't support opening directly to the front-facing camera on Android.

<img width="569" alt="screenshot 2016-10-14 16 47 38" src="https://cloud.githubusercontent.com/assets/369384/19383354/182e34dc-922e-11e6-9f3b-c17ea9dbe996.png">

Any plans to support this in the future? Is it even possible on Android?

**Comment by yfuks** [comment]
It's possible.
But we have no plan on doing it in **Android** since it's badly supported with native camera

**Comment by KingAmo** [comment]
what a pity...really hope it can be suported...

**Comment by HarshitMadhav** [comment]
Any update on this? I want to open the front camera directly in Android.

**Comment by pawan8525** [comment]
use[](https://react-native-community.github.io/react-native-camera/docs/rncamera)
