### ISSUE TITLE
Android: Can I select multiple image?

### ISSUE THREAD

**Issue by prashen** [marcshilling/react-native-image-picker#355]
As you already said:

> Multiple image selection, more control over the crop tool, and landscape support are things missing from the native iOS functionality - not issues with my library.

Can I select multiple image in Android os?

**Comment by yfuks** [comment]
> Multiple image selection, more control over the crop tool, and landscape support are things missing from the native iOS functionality - not issues with my library. If you need these things, [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) might be a better choice for you.

[react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker)
