### ISSUE TITLE
Version 0.22.10 crashes in iOS 10

### ISSUE THREAD

**Issue by Tao-Oak** [marcshilling/react-native-image-picker#356]

**Comment by nbastoWM** [comment]
Did you manage to get it working?
I'm still getting a crash in iOS10, everytime I click on "Select from library" or "Take photo".

**Comment by nbastoWM** [comment]
Ok, I was missing the NSPhotoLibraryUsageDescription and NSCameraUsageDescription keys.

**Comment by liuliangsir2016** [comment]
![image](https://cloud.githubusercontent.com/assets/22698933/19553720/ed955f66-96e7-11e6-9736-d750ec5cda1f.png)
not solve problem
