### ISSUE TITLE
Removing iOS 7 Support

### ISSUE THREAD

**Issue by marcshilling** [marcshilling/react-native-image-picker#360]
According to [Apple](https://developer.apple.com/support/app-store/), 54% of devices are on iOS 10, 38% are on iOS 9, leaving just 8% on iOS 8 or below. They don't show the breakdown of that 8%, but I think it's safe to say that less than 1% of users are still on iOS 7. I'd love to remove all the iOS 7 stuff and make the iOS code way more readable. I will probably do this soon unless anyone objects.

**Comment by npomfret** [comment]
+1
RN doesn't even support iOS 7 now, it's moved to 8.

**Comment by marcshilling** [comment]
[Done](https://github.com/marcshilling/react-native-image-picker/releases/tag/v0.23.0)
