### ISSUE TITLE
(Android) (Question) Image being moved from cache to pictures folder

### ISSUE THREAD

**Issue by sandrarivera** [marcshilling/react-native-image-picker#362]
Almost sure this is an Android issue but just want to run it by you just in case.

I reported an issue to you #273. so the pictured could get saved in the temporary folder (cache) instead of the pictures folder. You fixed it and it works beautifully, except for a little problem in Android (in Phone works just fine).

When we take the picture in our app using your component it goes into the cache **Android\data\APP_NAME\cache** folder as it should, so if we go to the phone gallery we don't see the picture we just took. (perfect!!)

But.... if we delete from the phone's gallery any picture, the picture that was in the cache folder magically appear in the phone's gallery (what???)  if we check, the image was moved from the cache folder to the picture folder.

I was wondering if you can delete the cache earlier to avoid this scenarios?

Thanks for any feedback,

**Comment by yfuks** [comment]
Hello,

I guess Android suprised me once again... Never heard about this "feature" before.
Thanks for the report.

Since i never heard about that before i don't any workaround. It's up to you to find out !

(WTF)

**Comment by sandrarivera** [comment]
Thanks anyways

**Comment by marcshilling** [comment]
No action here, so gonna close this. Will accept a PR for a `clean()` method if someone wants to send one.
