### ISSUE TITLE
Example too big, separate into another repo?

### ISSUE THREAD

**Issue by mvayngrib** [marcshilling/react-native-image-picker#363]
react-native-image-picker is 115MB in my node_modules folder, almost 100% due to the Example folder. Could you move it out to another repo maybe? 

edit: or maybe add it to .npmignore and let people clone from git to play with the example

**Comment by marcshilling** [comment]
Interesting...well yeah like you said adding it to `.npmignore` is definitely the correct solution, but I'm curious - why does the size of it in your node_modules matter to you? When building your iOS or Android app it would only include the ImagePicker library which is tiny. Your node_modules folder doesn't get bundled.

**Comment by mvayngrib** [comment]
@marcshilling yea, from a bundling perspective there's no problem, but from a disk space and `npm install` perspective, i'd rather not have to pull in 100MB when I'm not going to use it.

**Comment by marcshilling** [comment]
Fair enough. `v0.22.11` on npm has the Example/ folder ignored.

**Comment by mvayngrib** [comment]
@marcshilling awesome, thanks :)
