### ISSUE TITLE
is it possible to get both 'uri' and 'data uri' returned when chosen select from the library

### ISSUE THREAD

**Issue by pgmemk** [marcshilling/react-native-image-picker#37]
In my application I need to save the value of an image as a URI and at the same time I need to send it as data object.

Is it possible to add another option to pass to ImagePicker that will it to return both?

Thank you

**Comment by marcshilling** [comment]
I suppose there's no harm in always returning both...I'll take a shot at it.

**Comment by marcshilling** [comment]
Ok I reworked the response to always return both data and uri. Check it out in version `0.8.0` on npm. Thanks for the idea!

**Comment by pgmemk** [comment]
Great!

Thank you
ᐧ

On Mon, Oct 19, 2015 at 3:54 PM, Marc Shilling <notifications@github.com>
wrote:

> I suppose there's no harm in always returning both...I'll take a shot at
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcshilling/react-native-image-picker/issues/37#issuecomment-149238971>
> .
>



-- 
Ellen Katsnelson
Lead Developer
