### ISSUE TITLE
ImagePickerManager.showImagePicker is undefined

### ISSUE THREAD

**Issue by crellison** [marcshilling/react-native-image-picker#378]
I am trying to use this module, but it says that ImagePickerManager is not an object...

Below is my code
```
const options = {
  title: 'Select Avatar',
  customButtons: [
    {name: 'fb', title: 'Choose Photo from Facebook'},
  ],
  storageOptions: {
    skipBackup: true,
    path: 'images'
  }
};

openPhotos() {
  ImagePicker.showImagePicker(options, (response) => {
    if (response.error) return Alert.alert('ImagePicker Error: ', response.error);
    this.setState({ avatarSource: {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true} });
  });
};
```

and the error message
```
2016-11-02 11:51:44.991 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] 
Unhandled JS Exception: undefined is not an object (evaluating 'ImagePickerManager.showImagePicker')
```

Any thoughts???

**Comment by christianversloot** [comment]
How did you solve this?
I'm running into the exact same thing.
Followed the installation instructions strictly.

**Comment by zhangyuan521** [comment]
How did you solve this?
I'm running into the exact same thing.
Followed the installation instructions strictly.

**Comment by christianversloot** [comment]
@zhangyuan521 wtf man?

**Comment by zk6859** [comment]
How did you solve this?
I'm running into the exact same thing.
Followed the installation instructions strictly.

**Comment by marcshilling** [comment]
Well, these comments are certainly odd...

That aside, this error means the native Xcode project was not correctly linked. I'd recommend starting from scratch and following the manual instructions in the README.

**Comment by arhmnsh** [comment]
Comments are umm...

Anyhow, on iOS, after linking with `react-native link`, make sure to add `NSPhotoLibraryUsageDescription`, `NSCameraUsageDescription` and `NSMicrophoneUsageDescription` as strings in your Info.plist file.
as described in the 4th step of manual configuration for iOS

> For iOS 10+, Add the NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription (if allowing video) keys to your Info.plist with strings describing why your app needs these permissions
