### ISSUE TITLE
Cannot read property 'showImagePicker' of undefinde

### ISSUE THREAD

**Issue by cydiacen** [marcshilling/react-native-image-picker#381]
ios:10
osx:10.12.1
react-native-cli: 1.0.0
react-native: 0.36.1
when write 'react-native run-ios' in Terminal and click the 'Select a Photo' ,will show red box with "Cannot read property 'showImagePicker' of undefinde".But when I run code with  Xcode ,no Error.

**Comment by AsafBrieferyDev** [comment]
Are you sure you installed the package correctly?
Usually "Cannot read property '.....' of undefinde", for npm package that implements/uses a native model, is caused due to missings steps in the installation (linking problem).

**Comment by marcshilling** [comment]
What @AsafBrieferyDev said is correct.

**Comment by Rutheniceye92** [comment]
is there any alternate library for this?
