### ISSUE TITLE
[Android] ImagePicker not launching after permissions dialog

### ISSUE THREAD

**Issue by damathryx** [marcshilling/react-native-image-picker#385]
After I choose Allow it does nothing.
What seems to be the problem?
![image](https://cloud.githubusercontent.com/assets/14576761/20125534/097d591e-a669-11e6-8ac0-b207db75c7c3.png)
![image](https://cloud.githubusercontent.com/assets/14576761/20125664/da511e4a-a669-11e6-955c-4f31509c7479.png)

I get no error message either.

**Comment by varungupta85** [comment]
Make sure that you have added the permissions as specified in the readme file in the manifest file

**Comment by marcshilling** [comment]
After you allow, it will then open the picker on subsequent calls. I haven't made it automatically launch after allowing permissions yet (PR would be nice).

**Comment by pvanliefland** [comment]
@damathryx @marcshilling see my comment in #581
