### ISSUE TITLE
[Android] processRescouces FAILED

### ISSUE THREAD

**Issue by bfine9618** [marcshilling/react-native-image-picker#391]
after running run-android, the build fails with the following exception: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-picker:processReleaseResources'.
> at index 4

any suggestions?

**Comment by marcshilling** [comment]
Need more info than that. Still having this issue?

**Comment by bfine9618** [comment]
I think i figured it out. It had to do with my linking.
