### ISSUE TITLE
Can I use this library to access files other than videos and pictures? 

### ISSUE THREAD

**Issue by shivam17** [marcshilling/react-native-image-picker#392]

**Comment by shivam17** [comment]
I need to upload an xlsx file from my app, and I can't seem to find any file picker module/ library in react native to do that as of yet. A little help would be much appreciated. :)

**Comment by npomfret** [comment]
Try react-native-fs

**Comment by marcshilling** [comment]
What he said ^

I'm not going to make react-native-**image**-picker allow you to pick excel files :)
