### ISSUE TITLE
[iOS] Cannot edit images taken from Camera

### ISSUE THREAD

**Issue by RyanMitchellWilson** [marcshilling/react-native-image-picker#393]
If you select the "Take Photo..." option in the image picker, then try to move the image around in the editor, it does not let you drag the photo around. You can zoom in and out but it still doesn't let you use the top or bottom of the image.

Using these as my options:
```
const options = {
  allowsEditing: true,
  mediaType: 'photo'
}
```

If you look at the image below, the editor does not allow you to drag the photo any higher or lower than it already is. You can zoom in, but it still doesn't let you past the same points.
<img src="https://cloud.githubusercontent.com/assets/11371200/20504336/0eea1ae6-b004-11e6-851c-5efb18bf61f3.png" width=300/>

Using iOS10, react-native 0.30.0, and latest image picker.

**Comment by marcshilling** [comment]
This is default iOS behavior. If you need more flexibility check out react-native-image-crop-picker.
