### ISSUE TITLE
Needs update for activity result for RN 0.37

### ISSUE THREAD

**Issue by skyride99** [marcshilling/react-native-image-picker#395]
Image picker is unstable in version 0.37, and crashes. This is due to a new interface change.

 public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
}

Activity Result has a new interface:

  public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
}

**Comment by desmondhume** [comment]
@skyride99 did you find any quick solution or temporary hack for this?
I'm having the same issue.

**Comment by skyride99** [comment]
I had several issues with upgrades with other components. Had to go back to RN 32 for the app to work correctly. Looking forward to the update on this.

**Comment by marcshilling** [comment]
I just updated the Example project to RN 0.38 and I'm not having any issues. We are handling the new Activity Result interface, so I'm not sure how you're running into this. I will push the changes to the Example project - can you run that?

**Comment by skyride99** [comment]
It seems to be running now. Not crashing.  But now have an issue "Network Error". Lets close this issue.
