### ISSUE TITLE
warning: setState(..): Can only update a mounted or mouting component.

### ISSUE THREAD

**Issue by DaBeastGTxx** [marcshilling/react-native-image-picker#397]
I have been working with this package for a few weeks on both IOS an Android and everything was great until yesterday. I keep getting this error on Android: warning: setState(...): Can only update a mounted or mounting component when I use "this.setState({source: source})".

**Comment by DaBeastGTxx** [comment]
I fixed it.

**Comment by BroshkovD** [comment]
Hello Ghost. How did you solve this problem? Could you provide some example?
