### ISSUE TITLE
[Android] Incompatible types: ImagePickerActivityEventListener unable to convert ActivityEventListener

### ISSUE THREAD

**Issue by shurong2199** [marcshilling/react-native-image-picker#399]
Compilation failed:
Symbolfile could not be found: BaseActivityEventListener;
Incompatible types: ImagePickerActivityEventListener unable to convert ActivityEventListener;
Execution failed for task ':react-native-image-picker:compileReleaseJavaWithJavac'.

"react": "^15.3.2",
"react-native": "^0.36.1",
"react-native-image-picker": "^0.23.0"

**Comment by shurong2199** [comment]
I'm very anxiously awaiting solution.

**Comment by marcshilling** [comment]
I believe this issue to be solved. There are many existing issues about it. Check #311 for solution.
