### ISSUE TITLE
Image Quality. How should I handle it?

### ISSUE THREAD

**Issue by JoaoCnh** [marcshilling/react-native-image-picker#40]
I'm using this for the first time and I'm not really experienced in the mobile world. 

I want to use this to get a photo and then post it to a server. The photo needs a certain level of quality.

By setting quality to 1.0 it does not put an enough quality for me. Is there any way of handling this?

Why is the example so low? 0.2 in quality?

If anyone can offer explanation and advice I would appreciate it

**Comment by andreacab** [comment]
@JoaoCnh you found a way to get a high quality? I am struggling with the same challenge..

**Comment by yfuks** [comment]
For maximun quality you need to set quality to 1.0 and don't set maxHeight and maxWidth options
