### ISSUE TITLE
[Android] Use MaterialDialogs

### ISSUE THREAD

**Issue by radko93** [marcshilling/react-native-image-picker#400]
Dialogs currently does not look great on newer Android phones. And it's hard to style them. Can we replace them with [this great library](https://github.com/afollestad/material-dialogs)? It's used for example [here](https://github.com/aakashns/react-native-dialogs). I would be happy to make a PR!

**Comment by marcshilling** [comment]
I really strive for this library to be as close to native behavior as possible. As long as `Dialog` is the agreed upon built-in Android solution then we'll probably stick to that. I'd like to avoid third party dependencies if we can. If dialogs don't look great on newer Android phones then it sounds like Android needs an update, not this library.

**Comment by yfuks** [comment]
Agree !
In my opinion if you want a custom picker Dialogs just make it in react-native.
The [natives functions](https://github.com/marcshilling/react-native-image-picker#directly-launching-the-camera-or-image-library) that we expose are for this kind of usage.

**Comment by radko93** [comment]
That's a good workaround. I will close that issue then.

**Comment by marcshilling** [comment]
@radko93 hey, try out v0.24.1 on npm. I'm now forcing the Holo Light theme if that suites your needs. I suppose we could make this a customizable option that gets passed in going forward.
