### ISSUE TITLE
Compatibility with <= 0.33 

### ISSUE THREAD

**Issue by christianversloot** [marcshilling/react-native-image-picker#402]
Today I attempted to install your image picker into a RN0.33 application. Despite adherence to the installation instructions, installation failed, saying that ImagePickerManager was undefined.

My last straw was updating RN to the latest version (0.38) and this has resolved the problem. Therefore, I expect that for at least RN0.33 and older versions, the bridge between the Native Module and the RN JavaScript environment cannot be established. As such, and for documentation reasons, I request that this module is made incompatible (e.g., through text in the README file) with (at least) RN0.33 and lower.

**Comment by marcshilling** [comment]
Android or iOS? As far as I know, things should work fine with < RN 0.33.

**Comment by christianversloot** [comment]
Android indeed!


Met vriendelijke groet,

Christian Versloot
Student M-BIT, Universiteit Twente
E: c.w.a.versloot@student.utwente.nl
T: +31 (0)6 533 28 377

2016-11-28 17:22 GMT+01:00 Marc Shilling <notifications@github.com>:

**Comment by christianversloot** [comment]
Android indeed!



2016-11-28 17:22 GMT+01:00 Marc Shilling <notifications@github.com>:

**Comment by marcshilling** [comment]
@christianversloot I just downloaded a zip of the repo, changed `Example/package.json` to install `"react-native": "0.33.1"`, ran `npm install`, and was able to run the Example project just fine. You must be linking something incorrectly.

**Comment by chrisdukey** [comment]
I get the same issue when installing on RN 0.39 (using react-native link) and also when trying the Example project (RN 0.38). I got the Example project working by switching the react-native dependency to 0.33.1 and the react dependency to 15.3.1

**Comment by marcshilling** [comment]
@chrisdukey this is an issue for it not working on <= 0.33 and you are saying it doesn't work on 0.39 but it does on 0.33!? From my testing, it works on both versions, so I don't know how to move forward with this...

**Comment by marcshilling** [comment]
When 0.40 is released we will be enforcing that as a minimum so hopefully this gets cleared up.

**Comment by chrisdukey** [comment]
@marcshilling Yep, was just hinting to @christianversloot that it might be related to the version of react. Just tried the Example project with react-native 0.39 and react 15.4.1 and it's working fine. My first try was in a different project with react-native 0.39 and an older version of react.

**Comment by marcshilling** [comment]
Gonna close this because I believe we're fine on latest React Native and we'll be enforcing 0.40 soon.

**Comment by carlos-wong** [comment]
I see the issue, You need restart the package server. I think the package server need restart when add new third party modules js code
