### ISSUE TITLE
Automatically save camera image?

### ISSUE THREAD

**Issue by Cygnus2112** [marcshilling/react-native-image-picker#403]
Hi! I am trying to use ImagePicker.launchCamera as the default camera component in my app, since the other published React Native camera modules don't meet my needs. Is there a way to bypass the approve/reject view that appears after a photo is taken (see attached) and automatically save the photo to the gallery? I'd love to know. Thanks!

![screenshot_2016-11-28-19-55-04](https://cloud.githubusercontent.com/assets/12438838/20696019/464d5e7a-b5a5-11e6-9ce8-75956b9c3f94.png)

**Comment by marcshilling** [comment]
Unfortunately not...that is the built-in Android image capture intent behavior. This library isn't meant to be a camera replacement, so I'd keep exploring other options.
