### ISSUE TITLE
Status bar is light when an gallery is opened

### ISSUE THREAD

**Issue by swaroopa94** [marcshilling/react-native-image-picker#404]
HI 
Iam using module for choosing an image
But I had a small issue 

My status bar color for the whole app is light and i set it in the appdelegate.m file as:
`[[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];`

And now in my screen my satus bar color is blue and with light color text.
When I open an image picker then the status bar color is changing to white but text remains in  white.

So how to make my status bar to default when opening any imagepicker and again changing to light when closing it.

**Comment by marcshilling** [comment]
This library does not do anything with the status bar. I'd recommend reading up on [the StatusBar component](https://facebook.github.io/react-native/docs/statusbar.html) and using it to deal with changing the bar and text colors.

**Comment by colorfulberry** [comment]
@swaroopa94 How to solved it at the end ? 
@marcshilling if our system use the
 `<StatusBar barStyle="light-content"/>`
when we use react-native-image-picker to select a photo. then the statusBar changed to default with dark and not show it.

**Comment by hmenzagh** [comment]
@colorfulberry Same issue here ! Did you find any solutions ? i'm thinking about doing a PR
