### ISSUE TITLE
The Photo taken is not clear

### ISSUE THREAD

**Issue by BTMouseKing** [marcshilling/react-native-image-picker#405]
I'm running the example on my iPad and took photo but the photo looks blurry every time. Has anyone encountered this issue?

![img_0005](https://cloud.githubusercontent.com/assets/5598303/20698809/8dce7b18-b5d1-11e6-8375-26260174963f.PNG)

A photo taken by the default iOS camera is much clearer.

**Comment by marcshilling** [comment]
What's your `quality` option? Try setting it to `1`?

**Comment by BTMouseKing** [comment]
@marcshilling The quality is 1, i'm using the example code. This morning i tested on two devices, the iPad mini 2 ( iOS 9.3.5 ) works fine but the iPad Air 2 ( iOS 10.1.1 ) has the issue.

**Comment by marcshilling** [comment]
Maybe related to #268? Is the image being scaled up to fill the iPad screen?

**Comment by BTMouseKing** [comment]
The image is filling the entire iPad screen but i'm not sure if it's scaled up. I changed the code a bit as follows but it's still not working:

const options = {
	quality: 1.0,
	maxWidth: Dimensions.get('window').width,
	maxHeight: Dimensions.get('window').height,
	storageOptions: {
		skipBackup: true
	},
	noData: true
};

**Comment by marcshilling** [comment]
Yeah, setting the maxWidth/Height won't do anything. Honestly, from your screenshot the quality really doesn't look that bad to me at all. What I'm wondering though is if you actually try to go display that image in React Native as say 500x500...it probably looks pretty good right?

**Comment by BTMouseKing** [comment]
Here is the comparison of the photos:

Photo taken by the default ios camera:

![img_0012](https://cloud.githubusercontent.com/assets/5598303/20720651/ffda073e-b62d-11e6-83d5-366a2a46119b.JPG)

The preview photo of react-native-image-picker:

![img_0014](https://cloud.githubusercontent.com/assets/5598303/20720662/0895f7f2-b62e-11e6-9d6a-1c4dfbd08a31.PNG)

Photo displayed in the avatar ( I set width and height to be 700 and removed borderRadius )

![img_0015](https://cloud.githubusercontent.com/assets/5598303/20720669/0fb47676-b62e-11e6-9fc3-7c00ff901f67.PNG)

Not good as the one taken by the default camera, especially the preview. But when i use the iPad mini 2 ( iOS 9.3.5 ), the preview is pretty good, like it's taken by the default camera, but the image in the avatar looks the same as the last screenshot.

**Comment by marcshilling** [comment]
Ok...I agree you are definitely losing quality. Do you have the `allowsEditing` option enabled? Try turning that off?

**Comment by BTMouseKing** [comment]
just tried but still not working...

const options = {
			quality: 1.0,
			maxWidth: Dimensions.get('window').width,
			maxHeight: Dimensions.get('window').height,
			storageOptions: {
				skipBackup: true
			},
			noData: true,
			allowsEditing: false
		};

**Comment by marcshilling** [comment]
And just to be completely sure, remove `maxWidth` and `maxHeight` for me. If that doesn't work then this might be a bug with the built-in iOS image picker.

**Comment by BTMouseKing** [comment]
I removed maxWidth and maxHeight, the image in the avatar looks great, but the preview is still bad.

Here is the image in the avatar before removing maxWidth and maxHeight, still slightly blurry:

![img_0016](https://cloud.githubusercontent.com/assets/5598303/20724155/224f281e-b63b-11e6-8c5b-54e3bf3f8797.PNG)

Here is the image in the avatar after removing maxWidth and maxHeight:

![img_0017](https://cloud.githubusercontent.com/assets/5598303/20724163/28202edc-b63b-11e6-9e8e-c29c2f860e0c.PNG)

Both image were taken with allowsEditing: false.

**Comment by BTMouseKing** [comment]
I also set the logging and found the selectPhotoTapped method seems called twice:

const options = {
			quality: 1.0,
			storageOptions: {
				skipBackup: true
			},
			noData: true,
			allowsEditing: false
		};

		console.log('max width: ' + options.maxWidth);
		console.log('max height: ' + options.maxHeight);

		ImagePicker.showImagePicker(options, (response) => {

Here is the logging result:

2016-11-29 13:44:03.180 [info][tid:com.facebook.react.JavaScript] max width: 1024
2016-11-29 13:44:03.180620 TestSample[1438:569164] max width: 1024
2016-11-29 13:44:03.181 [info][tid:com.facebook.react.JavaScript] max height: 768
2016-11-29 13:44:03.181342 TestSample[1438:569164] max height: 768

**Comment by BTMouseKing** [comment]
For the preview issue, i've tried other solutions and had the same issue with iPad Air 2 ( iOS 10.1.1 ), I agree it might be a bug with the built-in iOS image picker for specific devices or iOS version. Removing maxWidth and maxHeight and setting allowsEditing: false makes the final image clearer for me.
