### ISSUE TITLE
Is multiple selection of photos from Library supported?

### ISSUE THREAD

**Issue by BTMouseKing** [marcshilling/react-native-image-picker#406]

**Comment by marcshilling** [comment]
Won't be supported until it's supported with built-in iOS APIs. Check out [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker)

**Comment by isaachinman** [comment]
@marcshilling Sorry to bring up an old thread. I know this question of multi-picking is asked on this repo all the time, but why not have an assortment of "Android Only" config options? This is a very common pattern with RN projects.
