### ISSUE TITLE
ios Choose from Library… .Flashback

### ISSUE THREAD

**Issue by haomingden** [marcshilling/react-native-image-picker#407]

**Comment by marcshilling** [comment]
I don't know what this means, please provide more info.

**Comment by haomingden** [comment]
click Choose from Library… ., Flashback . Other buttons are normal

**Comment by haomingden** [comment]
react-native: 0.37.0   react-native-image-picker 0.23

**Comment by marcshilling** [comment]
Still not sure what "Flashback" means...but just taking a guess here...have you added the `NSPhotoLibraryUsageDescription` and `NSCameraUsageDescription` keys to your `Info.plist`?

**Comment by haomingden** [comment]
“Flashback”  exit the app  ,I do not add PhotoLibraryUsageDescription and NSCameraUsageDescription keys

**Comment by haomingden** [comment]
My English is not very good

**Comment by marcshilling** [comment]
Adding those keys to your plist should fix the crash (flashback)

**Comment by marcshilling** [comment]
@haomingden did that fix your issue?

**Comment by marcshilling** [comment]
No response.
