### ISSUE TITLE
Can i use this for landscape only app?

### ISSUE THREAD

**Issue by BTMouseKing** [marcshilling/react-native-image-picker#408]
"Take Photo" is fine but "Choose from Library" seems to require portrait mode. I wonder if there is a way to make it work with landscape mode only. Thanks.

**Comment by marcshilling** [comment]
This is a limitation of iOS. See #35.
Maybe [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) would better suite your needs?

**Comment by BTMouseKing** [comment]
Thank you for recommendation, i'm using react-native-image-crop-picker now, it's great.
