### ISSUE TITLE
Style issue when opening the image picker

### ISSUE THREAD

**Issue by qlerebours** [marcshilling/react-native-image-picker#409]
Hi,

I've got a style issue when opening the image picker on Android. The style seems to be missing... I wonder what I did wrong.

The imports: 
```
var Platform = require('react-native').Platform;
var ImagePicker = require('react-native-image-picker');
```

The basic opening function:
```
openPhotoPicker() {
        ImagePicker.showImagePicker(options, (response) => {
            console.log('Response = ', response);
            if (response.didCancel) {
                console.log('User cancelled image picker');
            }
            else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            }
            else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            }
            else {
                // You can display the image using either data...
                const source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};

                // or a reference to the platform specific asset location
                if (Platform.OS === 'ios') {
                    const source = {uri: response.uri.replace('file://', ''), isStatic: true};
                } else {
                    const source = {uri: response.uri, isStatic: true};
                }

                this.setState({
                    avatarSource: source
                });
            }
        });
    }
```

My view:
`<Button info rounded style={AddTripStyles.roundedButton} onPress={() => self.openPhotoPicker()}><Icon name='md-add'/></Button>`

My options:
```
var options = {
    title: 'Select Avatar',
    customButtons: [
        {name: 'fb', title: 'Choose Photo from Facebook'},
    ],
    storageOptions: {
        skipBackup: true,
        path: 'images'
    }
};
```

My version of RN is 0.33

The result:
![screenshot_2016-11-30-16-29-21-560_com applicovoit](https://cloud.githubusercontent.com/assets/17043042/20758512/52882b18-b71a-11e6-9678-cc17cc389c65.png)

If someone could help me, i'll be greatfull ! :)

**Comment by marcshilling** [comment]
I'm not sure I understand what you mean...We don't provide any way to style the pop up, that's just the built-in Android `Dialog`. If you want a custom style for it, you should build the dialog yourself in JavaScript and use the `ImagePicker.launchCamera()` and `ImagePicker.launchImageLibrary()` functions.

**Comment by qlerebours** [comment]
I know you're not providing any style, but my problem is that the style of the popup on my screen is not the Android one, and I didn't change anything. Do you have an idea of what I could did wrong ?

I'd like this style: 
![image](https://cloud.githubusercontent.com/assets/17043042/20759507/632ebf4c-b71d-11e6-8721-f9764c557a20.png)

**Comment by marcshilling** [comment]
Interesting. Well, the plain white is how it looks on my Galaxy S6 as well. I wasn't aware of that other style. How did you produce that? We're just using `AlertDialog` right out of the Android box.

**Comment by qlerebours** [comment]
Sorry I'm not english and i don't want a misunderstanding: 
When you say "other style" you mean the second one ? 
And the plain white is the first I published ?

If it's what you mean, I took the second style on the masterpage of this github.
The first one is the style on my application that popped when using the code I shared on my post

**Comment by marcshilling** [comment]
Ok, I think I see what's going on here. Give me a few minutes and I will try to fix.

**Comment by marcshilling** [comment]
Alright, try out `v0.24.1` on npm. I'm now forcing the Holo Light theme.

**Comment by qlerebours** [comment]
It's working ! 
Thanks a lot for your work and your help !
I close
