### ISSUE TITLE
UIImagePickerManager.m no such file?

### ISSUE THREAD

**Issue by fozzarelo** [marcshilling/react-native-image-picker#411]
no such file or directory: '/blabla/node_modules/react-native-image-picker/ios/UIImagePickerManager.m'

I just installed it and ran the link.. Am I doing anything wrong?

**Comment by marcshilling** [comment]
Well something is certainly wrong because that file is no more - it was renamed to `ImagePickerManager.m` many versions ago. Make sure you're running `npm install react-native-image-picker@latest`

**Comment by fozzarelo** [comment]
Yea, that makes sense.. Im dealing with old code. Look like I had a legacy uiimagepicker requirement suck in my appdelegate. Your response helped a lot in sorting it out. thanks.
