### ISSUE TITLE
[Android] App restarting when taking a picture

### ISSUE THREAD

**Issue by agrass** [marcshilling/react-native-image-picker#412]
Hi,

When I take the picture and press OK button the app get restarted. I have already checked out #244 and #190 and #316, but still restarting some times only in a Samsung Galaxy J7. In my Nexus 5x works perfect.  

I'm working with 0.23.0  version of react-native-image-picker and RN 0.35. 

Any help it would be greatly appreciated!

Thanks!

**Comment by marcshilling** [comment]
Can you post a crash log or anything? Works fine on my Galaxy S6...

**Comment by agrass** [comment]
I'm using this config:
```
{
  title: 'Select Picture',
    noData: true,
    quality: 0.5,
    maxWidth: 600,
    maxHeight: 500,
    allowsEditing: false,
    storageOptions: {
      skipBackup: true,
      path: 'images'
      }
};
```

Anyway I updated the software of the Galaxy J7 and now it's working. 

Thanks!

**Comment by GopiKrishna10** [comment]
hi Guys,
  i am still facing a issue when I take the picture and press OK button the app get restarted.in all mobiles like redmi note4 and moto g2. am trying to resolve from one day. am not able to solve this can u please help me thanks in advance @marcshilling @agrass 

config
====
 "react-native": "^0.42.3",
"react-native-image-picker": "^0.26.3"
db is firebase

**Comment by SudoPlz** [comment]
Actually that issue is a duplicate of https://github.com/react-community/react-native-image-picker/issues/732
