### ISSUE TITLE
undefined is not an object(evaluating 'ImagePickerManager.showImagePicker')

### ISSUE THREAD

**Issue by ywqian** [marcshilling/react-native-image-picker#414]
error：undefined is not an object(evaluating 'ImagePickerManager.showImagePicker')

devices: oppo R8007

**Comment by TrustTheBoy** [comment]
@ywqian How to solve error? I have encountered an error message

**Comment by TrustTheBoy** [comment]
Solutions:  https://github.com/marcshilling/react-native-image-picker/issues/381

**Comment by ywqian** [comment]
ok, I alreay solve this problem.

**Comment by TrustTheBoy** [comment]
How do you resolve them? One of my errors

**Comment by ywqian** [comment]
first：execute the command：   react-native link react-native-image-picker
second：
check directory android/app/build.gradle：compile project(':react-native-image-picker')

android/setting.gradle：
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')

android/app/src/..../MainApplication
![image](https://cloud.githubusercontent.com/assets/13879218/20913409/a41edc0a-bbb2-11e6-843d-0bed1f825468.png)

then everything is ok!   you may can see https://github.com/ivpusic/react-native-image-crop-picker, this repository is the same operation.

**Comment by TrustTheBoy** [comment]
Thank you very much for your answer. Solve this problem @ywqian

**Comment by newosetroc** [comment]
@ywqian this worked for me :)
Thank you

**Comment by yash2code** [comment]
In addition to @ywqian  add this line also at the top `import com.imagepicker.ImagePickerPackage;`

**Comment by dalip123** [comment]
where is MainApplication.java inside react-native-image-picker/android/src ?

**Comment by nzrsrk** [comment]
first：execute the command： react-native link react-native-image-picker
second：
check directory android/app/build.gradle：compile project(':react-native-image-picker')

android/setting.gradle：
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')

android/app/src/..../MainApplication 

all are clear but same error
