### ISSUE TITLE
showImagePicker of undefined

### ISSUE THREAD

**Issue by DiegoGallegos4** [marcshilling/react-native-image-picker#415]
I have run into this problem. In version 0.23 and 0.24. I run react-native link and it add .xcodeproj into libraries and .a file into linking libraries as well as the Header Search Paths.

I have tried everything and Im using the same version Im using for another app.

**Comment by cinder92** [comment]
+1 i'm using react native 0.36.1 it says `undefined is not an object (evauluating 'ImagePickerManager.showImagePicker')`

**Comment by cinder92** [comment]
figured out! you need to set this permissions on `AndroidMnifest.xml` 

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

and then restart the server :)

**Comment by varun-raj** [comment]
I face this issue when using in iOS, anyone one fixed it for ios?

**Comment by acomito** [comment]
did you ever get this fixed @varun-raj

**Comment by DiegoGallegos4** [comment]
@acomito did you restart the npm server?

**Comment by acomito** [comment]
@DiegoGallegos4 I just restarted now but still no luck. I see this in terminal:

```
=== BUILD TARGET RNImagePicker OF PROJECT RNImagePicker WITH CONFIGURATION Debug ===


Check dependencies

Unable to run command 'Libtool libRNImagePicker.a' - this target might include its own product.
```

**Comment by DiegoGallegos4** [comment]
Have you linked the project with `react-native link`? If you have, make sure the library is linked. Go to Xcode and check under Build Phases -> Link with libraries to make sure its there. Close all the simulator and stop the npm server and reinstall it, link it before running `react-native run-ios` or `npm start`

**Comment by YoLoADR** [comment]
I'm not an expert but you can solved this issue thanks to :
- this tutorial showImagePicker https://dev-yakuza.posstree.com/en/react-native/react-native-image-picker/ & https://github.com/dev-yakuza/react-native-image-picker-example
- (!) I'm on React Native >= 0.60 but the react-native-image-picker version is "react-native-image-picker": "2.3.1"
- To use react-native-image-picker on iOS, open ios/[project name]/Info.plist and modify it like below.
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  ...
  <key>NSPhotoLibraryUsageDescription</key>
  <string>$(PRODUCT_NAME) would like access to your photo gallery</string>
  <key>NSCameraUsageDescription</key>
  <string>$(PRODUCT_NAME) would like to use your camera</string>
  <key>NSPhotoLibraryAddUsageDescription</key>
  <string>$(PRODUCT_NAME) would like to save photos to your photo gallery</string>
  <key>NSMicrophoneUsageDescription</key>
  <string>$(PRODUCT_NAME) would like to use your microphone (for videos)</string>
</dict>
</plist>`

Don't hesitate to remove your nodes_modules and pod files then restart your server
