### ISSUE TITLE
[Android] Bug cannot show alert after pick image

### ISSUE THREAD

**Issue by pewh** [marcshilling/react-native-image-picker#418]
Hello. This repo is great, until I found a glitch on my use-case, which I need to show confirmation after pick image. 

```
ImagePickerManager.showImagePicker(options, response => {
      const { didCancel, error, ...data } = response
      alert('foo bar')            // Not show
      Alert.alert('foo', [ ... ]) // Not show
     console.log('foo bar baz') // Show on console
```

Tested on RN Image Picker version 0.23 & 0.24.1 with RN 0.39 (Android Genymotion)

**Edit:**
It show alert & console if I click cancel on popup. But when I pick image, it just show console later.
Tested on `showImagePicker` and `launchCamera`

**Comment by marcshilling** [comment]
The response callback is not called until you've selected or taken a photo.

"It show alert & console if I click cancel on popup" - yes because you've cancelled the dialog so we execute the callback with `didCancel: true`.

**Comment by pewh** [comment]
Hello @marcshilling, thanks for the reply. Sorry for my incomplete post.

I've pick an image, and after that, it shows output on console, but still no alert dialog.

**Comment by pewh** [comment]
But if I trigger `didCancel: true` by click cancel on popup, it shows console and alert. So, I'm confused why alert is not triggered after image is picked, but console show.

**Comment by marcshilling** [comment]
Seems like maybe a race condition. Try this:

```
import { InteractionManager } from 'react-native';

...

ImagePickerManager.showImagePicker(options, response => {
  InteractionManager.runAfterInteractions(() => {
    // show your alert
  });
});
```

**Comment by pewh** [comment]
Have try that, but no luck.

Based on some experiments:
1. Without `InteractionManager` -> alert not show
2. With `InteractionManager` -> alert not show
3. Debug JS remotely is ON and without `InteractionManager` -> alert is show
4. Debug JS remotely is ON and with `InteractionManager` -> alert is show

So, alert is show when `debug JS remotely` is on.

**Comment by marcshilling** [comment]
Very odd. Can you try just wrapping everything in a long `setTimeout`? See if it fires after a 5 second delay?

```
ImagePickerManager.showImagePicker(options, response => {
  setTimeout(() => {
    // show your alert
  }, 5000);
});
```

**Comment by pewh** [comment]
`setTimeout` is working, either value is `5000` or `1`. So I can make it work on:
```
ImagePickerManager.showImagePicker(options, response => {
  setTimeout(() => {
    // show your alert
  }, 1);
});
```

I' close this issue as I get it working, although it seems a hack way. Thanks so much, bro :beers:

**Comment by marcshilling** [comment]
Hmm really just a 1ms delay...weird! If that's all it takes, using `requestAnimationFrame(() => { })` may be "better" than `setTimeout`.

**Comment by vasuchawla** [comment]
I know its old but Same happening for me.

After i pick the image, app wide alerts stop working. Not sure about the reason but after app restart, alerts work, then i pick an image, no alerts are working now.
