### ISSUE TITLE
Include instructions to upload

### ISSUE THREAD

**Issue by esganzerla** [marcshilling/react-native-image-picker#420]
Hi,

I've started developing in react-native just recently and I had a lot of trouble to implement this module with upload. I found out that many people have this problem also.

I suggest to include instructions to upload to the bottom of the Read Me. I'm willing to make the pull request if you consider this interesting too.

By the way, my main problem was php ```upload_max_filesize```, which I solved by using options ```maxWidth``` and ```maxHeight``` for the ImagePicker.

**Comment by marcshilling** [comment]
There are a ton of different ways to upload an image to a web server, so I doubt 1 set of instructions in the README would even begin to cover everyone's use cases. Besides, image uploading isn't the responsibility of this package - choosing the image is.
