### ISSUE TITLE
Instructions for manual install are incorrect (I think!)

### ISSUE THREAD

**Issue by cyphire** [marcshilling/react-native-image-picker#422]
settings.gradle file shows install instructions of:

`project(':react-native-image-picker').projectDir = new File(settingsDir, '../node_modules/react-native-image-picker/android')
`

when it should be:

`project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')`

**Comment by marcshilling** [comment]
You're right - fixed! Thank you!

**Comment by cyphire** [comment]
my pleasure!
