### ISSUE TITLE
Not working in ios 10.2!!!

### ISSUE THREAD

**Issue by tanmynguyen** [marcshilling/react-native-image-picker#426]
![image](http://imageshack.com/a/img922/7338/AkgWZ2.png)

**Comment by marcshilling** [comment]
I can't reproduce. Working fine for me in iOS 10.2. Can you post what options you are setting for the image picker and what action you are performing (taking photo or choosing from library).

**Comment by tanmynguyen** [comment]
`chooseImageCard(id){
    const options = {
      quality: 1.0,
      maxWidth: 400,
      maxHeight: 200,
      storageOptions: {
        skipBackup: true
      },
      allowsEditing: true,
      mediaType: 'photo'
    };

    ImagePicker.showImagePicker(options, (response) => {
      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        ImagePicker.launchCamera(options, (response)  => {
          console.log(response);
        });
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        var source;

        //Or:
        if (Platform.OS === 'android') {
          source = {uri: response.uri, isStatic: true};
        } else {
          source = {uri: response.uri.replace('file://', ''), isStatic: true};
        }

        var _image = {
          image_type: 1,
          image_base_64: 'data:image/jpeg;base64,' + response.data,
          section_type: 'owner',
          filter: 1
        }
        var _arr = this.state.cards;
        var _this = this;
        this.props.insertGiftCardImage(_image, (data) => {
          _this.props.getListGifCardImage((data) => {});
        });
      }
    });
  }`
Hi you. Function worked in android but ios not work. When i touch taking photo or choosing from library then app have been crash ;(

**Comment by marcshilling** [comment]
I was just able to successfully choose a photo with your options, so I'm not sure what's going on here. Your crash stacktrace isn't particularly helpful, can you provide me any more info? Are you using the latest version on npm? Can you run the Example project?

**Comment by tanmynguyen** [comment]
yeah.
i'am using 
react-native: 0.39
node v7.0.0
npm 3.10.8

**Comment by marcshilling** [comment]
Latest version of `react-native-image-picker` I meant:

`npm install react-native-image-picker@latest --save`

**Comment by onyxrev** [comment]
@tanmynguyen make sure you set `NSPhotoLibraryUsageDescription`. I got this error along with some console output:

```
connected handler
2016-12-24 17:06:16.348400 AnyoneWantTo[68689:6243634] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.
(lldb) 
```

Once I set that value everything worked swimmingly.
