### ISSUE TITLE
[Android feature] Request editing video duration after user chooses it from the library

### ISSUE THREAD

**Issue by congnguyen91** [marcshilling/react-native-image-picker#432]
It's ok for limiting video duration from recording now. Could you add a feature for editing video duration after choosing it from the library on Android :)

**Comment by congnguyen91** [comment]
I found a solution on android with REQUEST_LAUNCH_VIDEO_LIBRARY. After choosing video we can Use trim intent. But I don't know how to set limit duration

        Intent trimVideoIntent = new Intent("com.android.camera.action.TRIM");
        trimVideoIntent.putExtra("media-item-path",getRealPathFromURI(data.getData()));
        trimVideoIntent.setData(data.getData());
        Activity currentActivity = getCurrentActivity();
        currentActivity.startActivity(trimVideoIntent);

**Comment by marcshilling** [comment]
[react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) may be a better choice for you.

**Comment by congnguyen91** [comment]
This is a helpful source: https://github.com/knowledge4life/k4l-video-trimmer
