### ISSUE TITLE
React-native-image-picker will select the photos in Android will be crashed

### ISSUE THREAD

**Issue by iamdurui** [marcshilling/react-native-image-picker#434]
When I take a picture ,the app is crashed, react-native :0.35, android version 5.11, "react-native-image-picker": "^0.22.8",the container is ScrollView ,it contain six image-picker,my phone is Redmi3,please give me solution，thanks.

**Comment by usergyt** [comment]
Meet the same problem, how to solve?

**Comment by SirPhemmiey** [comment]
Fixed?
