### ISSUE TITLE
crashes on iOS (solved)

### ISSUE THREAD

**Issue by Gys** [marcshilling/react-native-image-picker#438]
It took me some experimenting before I got this working on iOS without crashes.

So to clearify the readme (which is correct):

The Info.plist is to be found in
`<root app dir>/ios/<app name>/Info.plist`

Add the keys in the list between the `<dict>` and `</dict>` tags, like:
```
<key>NSPhotoLibraryUsageDescription</key>
<string>Select an existing photo for us</string>
<key>NSCameraUsageDescription</key>
<string>Take a photo for us</string>
```

If you have a simulator running, close everything en then run it again: react-native run-ios

**Comment by matejkramny** [comment]
This should be in `readme.md`

**Comment by marcshilling** [comment]
@matejkramny it is!

**Comment by matejkramny** [comment]
I see. Sorry, overlooked.

**Comment by matejkramny** [comment]
The reason I didn't see it is because I installed with `react-native link` and therefore didn't look at the Manual steps

**Comment by Gys** [comment]
@marcshilling 

Yes, this is more or less in the readme
But there are two Info.plist files in a react native project, so I think its useful to mention which one.
Plus an example of how to add them; to me as a non-Apple programmer it was not clear what to make of 'Add the NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription (if allowing video) keys'. Took me a moment to understand these are really <key> entries and that they need a <string> for value.
Just want to save time for others.

**Comment by tedjames** [comment]
Hey @marcshilling, @Gys has got a solid point. I had no idea what to do and had to refer to this issue for help.

**Comment by rishiankush** [comment]
Can anyone please tell me the steps to add NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription to the info.plist file?

**Comment by marcshilling** [comment]
@rishiankush your Xcode project contains a file `Info.plist`. This is a simple key-value store. You just need to add the keys `NSPhotoLibraryUsageDescription`, etc, with a string value that you want displayed to the user for why you are requesting that permission. For example:
`NSPhotoLibraryUsageDescription` : `"We need access to your photo library so that we can select photos"`

**Comment by rishiankush** [comment]
Yes I did it, I am using Xcoce 8.2 and I just added the key `Privacy - Photo Library Usage Description` inside the `Info.plist` and it worked fine. Thanks @marcshilling

**Comment by sundariragavan** [comment]
@marcshilling  In iPhone 6 camera is working fine. But iPhone 6+ while taking the photo the app is getting crashed. Any solution for the issue..And how to handle this issue

**Comment by russelRajitha** [comment]
same issue in iphone 7 (ios 12.2). `NSCameraUsageDescription`,`NSPhotoLibraryUsageDescription`,`NSPhotoLibraryAddUsageDescription`, permitions added in `info.plist`.
