### ISSUE TITLE
Directly Launching the Camera or Image Library

### ISSUE THREAD

**Issue by abuammar** [marcshilling/react-native-image-picker#439]
when i click touchable component i want to open only either imageLibrary or camera , what is happening is first camera is opened in both cases. this is the code

<TouchableOpacity onPress={() => this.selectPhotoTapped()}>
              <View style={[styles.avatar, styles.avatarContainer]}>
              { this.state.avatarSource === null ?
                <Image style={{width: 60, height: 60}}
                  source={require('./../common/img/icon07.png')}
                    />
                    :
                <Image style={{width: 60, height: 60}}
                  source={require('./../common/img/icon07.png')}
                    />
              }
              <Text style={{fontSize:20,alignItems:'center',color:'#777777',margin:10}}>{t.t('Upload ')}</Text>
              </View>

            </TouchableOpacity>

selectPhotoTapped() {
    const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
      skipBackup: true
      }
    };

    console.log('inside selectPhotoTapped ')

      ImagePicker.launchImageLibrary(options, (response) => {
      //  console.log('Response = ', response);

        // if (response.didCancel) {
        //   console.log('User cancelled photo picker');
        // }
        // else if (response.error) {
        //   console.log('ImagePicker Error: ', response.error);
        // }
        // else if (response.customButton) {
        //   console.log('User tapped custom button: ', response.customButton);
        // }
        // else {
          var source;

          // You can display the image using either:
          //source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};

          //Or:
          if (Platform.OS === 'android') {
            source = {uri: response.uri, isStatic: true};
          } else {
            source = {uri: response.uri.replace('file://', ''), isStatic: true};
          }

          this.setState({
            avatarSource: source
          });
          this.setState({step:4});
        //}
      });

**Comment by marcshilling** [comment]
You're calling `launchImageLibrary()`, so obviously that will be launched every time. It sounds like you want to use the default picker, so you should just be using `showImagePicker()`, which presents the action sheet to choose between library/camera.
