### ISSUE TITLE
When Pick from Library it closes the App

### ISSUE THREAD

**Issue by radvc** [marcshilling/react-native-image-picker#440]
I copy the example in the repo and run IOS, why app closes when I tap choose from library and there is no photo selection. Did i missed something?

**Comment by marcshilling** [comment]
Yes, you're probably missing something. Did you follow all the README instructions? Look at your Xcode logs. Forgetting to add permissions to Info.plist is a common mistake.

**Comment by radvc** [comment]
@marcshilling thanks for your reply, I reinstall again the package and follow the README, I set the permissions in Info.plist, unfortunately the app still closes when I tap choose from library

**Comment by radvc** [comment]
@marcshilling its working now, I pasted the line for permission in another Info.plist. hahaha. Thanks!
