### ISSUE TITLE
Native Android jump to ReactNative then push pick err

### ISSUE THREAD

**Issue by JusticeLai** [marcshilling/react-native-image-picker#445]
Native iOS jump to ReactNative then push pick correct,Native Android jump to ReactNative then push pick err,if on ReactNative push pick is ok
![image](https://cloud.githubusercontent.com/assets/13083749/21801672/a4de8c46-d75d-11e6-8b30-37bc60bc2d2e.png)

**Comment by JusticeLai** [comment]
I/ReactNativeJS: 'Response = ', { error: 'can\'t find current Activity' }
I/ReactNativeJS: 'ImagePicker Error: ', 'can\'t find current Activity'


another error..  if i add  this  ---  .addPackage(new ImagePickerPackage())    --

**Comment by wubangshun** [comment]
same problem

**Comment by JusticeLai** [comment]
### Version
- react-native-image-picker v0.24.1
- react-native v0.40

### Platform
- Android

### Steps to reproduce

1.Android hava a button ,then jump to ReactNative Activity(if only ReactNative is ok,to show picker)

2.In ReactNative Activity click a button,to show this  image-picker

3.Android Studo log Error
I/ReactNativeJS: 'Response = ', { error: 'can\'t find current Activity' }
I/ReactNativeJS: 'ImagePicker Error:', 'can\'t find current Activity'

**Comment by marcshilling** [comment]
This means you did not properly link the native library. I'd recommend following the README through again in detail.

**Comment by JusticeLai** [comment]
no,i,have alerady Integrate other is ok.
The steps are the same, but other components can
![image](https://cloud.githubusercontent.com/assets/13083749/21834322/398fb1d0-d7ef-11e6-894b-6e5236dc4f18.png)

**Comment by marcshilling** [comment]
@JusticeLai the error from your original post is different from the second error you posted. For the 2nd error, try upgrading to `react-native-image-picker@0.25.0`

**Comment by JusticeLai** [comment]
1.AndroidManifest.xml  add  permission
2.addPackage(newImagePickerPackage())----in ReactNative Activity
3.settings.gradle  add some code
4.build.gradle      add some code
5.and rebuild the project
6.The steps are the same, but other components can

**Comment by JusticeLai** [comment]
@marcshilling  
Problem 1
i addPackage in the MainApplication
but really addPackage in the ReactNative Activity,because my root ReactNative is not MainApplication

Problem 2
update  react-native-image-picker@0.25.0  and did not show anyThing 
Android Studo  log 
I/ReactNativeJS: 'Response = ', { error: 'can\'t find current Activity' }
I/ReactNativeJS: 'ImagePicker Error:', 'can\'t find current Activity'

**Comment by JusticeLai** [comment]
@marcshilling   he aslo have same problem,i had alerady talk to  @wubangshun
Can you understand what I describe? My English is not very good
The above problems I have written in more detail, the use of other components is the same integration, it is possible to run
