### ISSUE TITLE
(iOS) Customize Camera Button (take photo, switch front and back ... )

### ISSUE THREAD

**Issue by ju5td0m7m1nd** [marcshilling/react-native-image-picker#447]
If set "showsCameraControls" to false, and hide all the default button

and let customized components can overlay on the Camera view,

once those components triggered, we can use takePhoto() or set 

UIImagePickerControllerCameraDevice to corresponding camera.

Then we can let components work.

Wonder if it is possible to achieved, or any suggestion to get this done.

Thanks.

**Comment by marcshilling** [comment]
From the README "Before you open an issue":
This library started as a basic bridge of the native iOS image picker, and I want to keep it that way. As such, functionality beyond what the native UIImagePickerController supports will not be supported here.

What you need seems to be a more customized approach than what the goal of this package is. I'd suggest forking and trying to implement something yourself. Sorry!
