### ISSUE TITLE
launchImageLibrary not working on iPhone emulator

### ISSUE THREAD

**Issue by tones411** [marcshilling/react-native-image-picker#449]
react-native-cli: 2.0.1
react-native: 0.40.0
"react-native-image-picker": "^0.25.1",

It works fine on Android, but when I run it in the iOS emulator or physical iphone device I get this error:

> undefined is not a function (evaluating '_reactNativeImagePicker2.default.launchImageLibrary(options, function(response){  })')

Here is the stripped down version of my source code:
```
import ImagePicker from 'react-native-image-picker';

class EditListing extends Component {
    pickImage(imageType){
	let options = {
		mediaType: 'photo',
		quality: 1,
		maxWidth: 144,
		maxHeight: 144
	}

	ImagePicker.launchImageLibrary(options, (response) => {
		...
	});
    }
   ...
}
```

The only thing different I can think of is that when I linked the binary with the library, I could only find "libRNImagePicker.a" (instead of "RNImagePicker.a" like the documentation states.)

**Comment by PuppyYuan** [comment]
install it manually, do not use auto link command line

**Comment by tones411** [comment]
Thanks, I tried the auto link command line at first, but then installed it
manually after. But the issue happened after I did the manual installation.

**Comment by tones411** [comment]
I created a new RN project and tried it there. It worked just fine. It must be something I did wrong in my project.

**Comment by PuppyYuan** [comment]
it's a library dependency problem, get some help from ur ios developer,  I've changed my Library " header search path “and work fine

**Comment by tones411** [comment]
I tried a new project and it worked there. So I removed the iOS references
in my original project and added them again. Voila! It's working. Thanks!

**Comment by cosydney** [comment]
Hi @anthony-tietjen, following your thread I'm running in the same issue. Could you be more precise on how you removed the iOS references? 

Thanks

**Comment by anthony-tietjen** [comment]
No problem @cosydney. In the readme file, refer to the manual iOS installation instructions. It talks about manually linking up libraries in your Xcode project. I undid all of that and then walked through the steps again and it worked that time. I must have just done it wrong the first time.

**Comment by cosydney** [comment]
@anthony-tietjen right It worked for me too, I didn't know that to remove the references it was just right click delete files from xcode and then adding them again ! Did the trick for me thanks !!!

**Comment by kawashimaken** [comment]
I am using react-native-firebase-starter and I added react-native-image-picker, it did not work, however when I did it manually according to the document, it worked!
So, the automatic configuration is not working by react-native link command  at this point of time (2018-05-09)?
