### ISSUE TITLE
error：ImagePickerModule不是抽象的，并且未覆盖activitiyEventListener中的onActivityResult抽象方法

### ISSUE THREAD

**Issue by cjl-df** [marcshilling/react-native-image-picker#451]
![image](https://cloud.githubusercontent.com/assets/3387329/21924092/79a63c16-d9b2-11e6-8008-a191f8293d4f.png)

我按照github官方上的安装说明做的。
先用npm install --save react-native-image-picker 安装，
然后在用 rnpm link的时候抱如下错误，
![image](https://cloud.githubusercontent.com/assets/3387329/21924250/59f81582-d9b3-11e6-9838-bff5a5394028.png)
请高手解答，感激不尽。

**Comment by hygkui** [comment]
Please use English! 
Thanks so much.

**Comment by cjl-df** [comment]
thank you very much. this problem have been sovled.  it is juset beacause the version of component of react-native and react-native-image-picker. also thanks a lot.
