### ISSUE TITLE
About magePickerManager.showImagePicker

### ISSUE THREAD

**Issue by jackjunjiang** [marcshilling/react-native-image-picker#452]
undefined is not an object (evaluating'ImagePickerManager.showImagePicker')

**Comment by eboomyl** [comment]
in  xCode  your project Libraries path，selected RNImagePicker.xcodeproj  
in "build Setting" -> "Search Paths" ->"Header Search Paths"  add ( $(SRCROOT)/../../react-native/React )

**Comment by marcshilling** [comment]
Follow the README manual install instructions.
