### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by iwoork** [marcshilling/react-native-image-picker#453]
Getting 'React/RCTBridgeModule.h' file not found when building this plugin. 

`=== BUILD TARGET RNImagePicker OF PROJECT RNImagePicker WITH CONFIGURATION Debug ===

Check dependencies

CompileC /Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/Objects-normal/x86_64/ImagePickerManager.o ImagePickerManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/efren/meetdine-react/node_modules/react-native-image-picker/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/efren/.rvm/gems/ruby-2.0.0-p247/bin:/Users/efren/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/efren/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/efren/.rvm/bin:/Users/efren/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/MAMP/Library/bin:/Users/efren:/Users/efren/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=90 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/efren/meetdine-react/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/efren/meetdine-react/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/RNImagePicker-generated-files.hmap -I/Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/RNImagePicker-own-target-headers.hmap -I/Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/RNImagePicker-all-target-headers.hmap -iquote /Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/RNImagePicker-project-headers.hmap -I/Users/efren/meetdine-react/ios/build/Build/Products/Debug-iphonesimulator/include -I/Users/efren/meetdine-react/ios/build/Build/Products/Debug-iphonesimulator/usr/local/include -I/Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/DerivedSources/x86_64 -I/Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/DerivedSources -F/Users/efren/meetdine-react/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/Objects-normal/x86_64/ImagePickerManager.d --serialize-diagnostics /Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/Objects-normal/x86_64/ImagePickerManager.dia -c /Users/efren/meetdine-react/node_modules/react-native-image-picker/ios/ImagePickerManager.m -o /Users/efren/meetdine-react/ios/build/Build/Intermediates/RNImagePicker.build/Debug-iphonesimulator/RNImagePicker.build/Objects-normal/x86_64/ImagePickerManager.o
In file included from /Users/efren/meetdine-react/node_modules/react-native-image-picker/ios/ImagePickerManager.m:1:
/Users/efren/meetdine-react/node_modules/react-native-image-picker/ios/ImagePickerManager.h:1:9: fatal error:
      'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^
1 error generated.

** BUILD FAILED **`

**Comment by eboomyl** [comment]
file：ImagePickerManager.h   
 change  #import <React/RCTBridgeModule.h>  
to  #import "RCTBridgeModule.h"

**Comment by marcshilling** [comment]
We require RN 0.40 now. Guessing you're below that version.

**Comment by XHTeng** [comment]
I require the 0.39,also has the issues  , how to solve it ?

**Comment by zizizi17** [comment]
i even set up RN 0.40 and the app is breaking anyway
how to solve it?

**Comment by marcshilling** [comment]
@XHTeng 0.39 is no longer supported. You can try to `npm-install react-native-image-picker@0.24.0 --save` to use the previous version of this package.

@zizizi17 There should be no issues if you're on RN 0.40. What's your error?

**Comment by eboomyl** [comment]
**first**  in xcode 
Libraries -> RNImagePicker.xcodeproj -> buid Settings ->Search Paths ->Header Search Paths
add $(SRCROOT)/../../react-native/React   because   node_modules/react-native-image-picker/**ios**
**second** 
in xcode your project select ，is not Libraries  ，you select Build Phases  at "Link Binary With Libraries"  add  "libRNImagePicker.a"
**third**
ImagePickerManager.h  and ImagePickerManager.m   two file change
#import <React/RCTBridgeModule.h>   to #import "RCTBridgeModule.h"
#import <React/RCTConvert.h>   to #import "RCTConvert.h"

**Comment by marcshilling** [comment]
@eboomyl your "first" and "second" steps are described in the README and your "third" step is incorrect for people using React Native 0.40. `v0.25.0` of this package will work out of the box for React Native 0.40. If using less than React Native 0.40 you should install `v0.24.0` of this package.

**Comment by eboomyl** [comment]
My RN is 0.39  , react-native-image-picker is 0.25.1

**Comment by marcshilling** [comment]
@eboomyl if you're not yet on RN 0.40 you should install `v0.24.0` of this package then there will be no need to manually change the files - but your call.

**Comment by XHTeng** [comment]
@marcshilling Thank you ! it work!

**Comment by zizizi17** [comment]
@marcshilling i set up RN 0.40.0, and react-native-image-picker 0.24.0
but i have another dependencies at my project. maybe it causes the problem with RCTBridge.h file not found?

**Comment by marcshilling** [comment]
@zizizi17 search for your issue on the React Native repo. There is some discussion happening there about this since the release of RN 0.40.

**Comment by qq326646683** [comment]
"react-native": "^0.40.0","react-native-image-picker": "^0.25.1",don't work....

**Comment by safi-manar** [comment]
I'm also getting this error. I have:

```
    "react-native": "0.40.0",
    "react-native-image-picker": "^0.25.1",
```

Any news or luck with this?

**Comment by marcshilling** [comment]
The example project runs fine. I'd recommend comparing your project to that.

**Comment by iamrutvik** [comment]
@eboomyl Bro, saved me from getting fired. It was already there while linking it. But still you have to add as a separate non-recursive entry.

**Comment by PeterRock** [comment]
You can look here [React Native / Xcode Upgrade and now RCTConvert.h not found](http://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found)

**Comment by oscar10176** [comment]
you need to add the library(RCT) into your Xcode  library folder

then go to build phases-> link binary-> add the new library

**Comment by sosoyososo** [comment]
I also run into a similar issue  few days ago. And with a long struggle , i found when importing RN projects to main project, using 'New Group Without Folder' instead using of 'New Group' will make everything okey !

My own issue happends when Integrating  all RN Projects to my project manurally .

**Comment by sturmenta** [comment]
For me it worked like this:

1) xcode -> build settings -> header search paths
2) add `$(SRCROOT)/../node_modules/react-native-fbsdk/ios/RCTFBSDK`

Where for you `react-native-fbsdk` is the name of you module and `RCTFBSDK` is the name of the subfolder
