### ISSUE TITLE
Duplicate interface definition for class 'RCTBridge'

### ISSUE THREAD

**Issue by jsappme** [marcshilling/react-native-image-picker#454]
I am getting the following error when building with xcode:

RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'

I am using rn 0.40 with the latest react-native init DemoApp

**Comment by marcshilling** [comment]
That error sounds like an issue with your specific project, not this library. The error is thrown in React Native code.

**Comment by jsappme** [comment]
I am using the latest xcode version 8.2.1 and the init react native app. when I remove the module it works without any problem again. So I am not sure to understand what do you mean by "an issue with your specific project, not this library".

**Comment by marcshilling** [comment]
Your error says there is a duplicate definition of 'RCTBridge'. This package does not declare or import RCTBridge, so something is up with your configuration. Hard for me to tell you what's going on with this limited information. Try to do some more debugging by yourself, and find out where the duplicate declaration is coming from.

**Comment by jsappme** [comment]
I think I was able to remove the errors but I still have this weird warning:

[RCTBridge.m:111] Class GooglePlusShare was not exported. Did you forget to use RCT_EXPORT_MODULE()?

any idea why?

**Comment by marcshilling** [comment]
I wouldn't worry about that warning. Again, that's coming from a different module in your code. If you aren't explicitly using `GooglePlusShare` you won't have any issues.

**Comment by jsappme** [comment]
Cool. Who still uses GooglePlusShare?

Thanks for your help.

**Comment by marcshilling** [comment]
It's likely included in some other package you depend on. Maybe FacebookSDK?

**Comment by jsappme** [comment]
Sorry I got confused with another issue. When I uninstall react-native-image-picker I have no more error, but as soon I reinstall it using:

```
yarn add react-native-image-picker
react-native link react-native-image-picker
```

I still experience the following errors:

/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:154:55: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:40:28: Redefinition of 'RCTLogLevel'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:159:48: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:41:3: Redefinition of enumerator 'RCTLogLevelTrace'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:165:37: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:42:3: Redefinition of enumerator 'RCTLogLevelInfo'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:43:3: Redefinition of enumerator 'RCTLogLevelWarning'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:170:61: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:44:3: Redefinition of enumerator 'RCTLogLevelError'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:175:53: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:45:3: Redefinition of enumerator 'RCTLogLevelFatal'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:180:56: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:51:28: Redefinition of 'RCTLogSource'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:52:3: Redefinition of enumerator 'RCTLogSourceNative'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:185:54: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTBridge.h:190:63: Property has a previous declaration
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTLog.h:53:3: Redefinition of enumerator 'RCTLogSourceJavaScript'
/Users/herve76/Desktop/Fishii/node_modules/react-native/React/Base/RCTConvert.h:26:1: Duplicate interface definition for class 'RCTConvert'

**Comment by jsappme** [comment]
I am using version 0.25.1

**Comment by marcshilling** [comment]
Can you try not using `react-native link`? Uninstall the image picker again, reinstall, then follow the manual instructions in the README.

**Comment by jsappme** [comment]
It's working now! Thanks again.

**Comment by avishayil** [comment]
That Google plus warning thing is coming from the `react-native-share` library, which is now not necessary anymore since `Share` is now integrated into react native itself.
