### ISSUE TITLE
Android image paths

### ISSUE THREAD

**Issue by kill4food** [marcshilling/react-native-image-picker#458]
Is there a way to select images that are not located in the gallery?
for example downloaded images

**Comment by dannyyaou** [comment]
Is there any situation that the downloaded images not int the gallery?

**Comment by rusfearuth** [comment]
@dannyyaou Yeap. When you choose it from Google Photos and it's missing on device.

**Comment by rusfearuth** [comment]
@kill4food Do you have any questions?
