### ISSUE TITLE
[Question] Disable crop?

### ISSUE THREAD

**Issue by jameskhamil** [marcshilling/react-native-image-picker#459]
Is it possible to disable the cropper in both platforms? Docs don't say if this is supported.

I see that in iOS, this is defined by props, but does android support?:

https://github.com/marcshilling/react-native-image-picker/blob/8f0aff1edb517f0cfbfff367809c18c1364ad8a8/ios/ImagePickerManager.m#L294

This seem like a good package to use for custom crop: https://github.com/stoffern/react-native-image-cropper

edit to be more clear

**Comment by marcshilling** [comment]
Set `allowsEditing: false` in your options. The cropping is only available on iOS, the feature was removed from Android.
