### ISSUE TITLE
Exception 'Actions added to UIAlertController must have a title' was thrown while invoking showImagePicker

### ISSUE THREAD

**Issue by safi-manar** [marcshilling/react-native-image-picker#460]
Hello,
I'm trying to use ImagePickerManager. When I try to call `showImagePicker()`, I get the following exception:

```
Exception 'Actions added to UIAlertController must have a title' was thrown while invoking showImagePicker on target
ImagePickerManager with params (
{
title = "Select Profile Picture";
},
31
)
```

I'm not sure why this is. I provide a title. When I set the options to empty `{}`, the same error is thrown, but with an empty bracket. 

Additionally, if I opt to use `ImagePicker.launchCamera()`, the app crashes when pressing the button.

Dependencies:
```
    "react-native": "0.38.0",
    "react-native-image-picker": "^0.24.0",

```

Any ideas?

**Comment by safi-manar** [comment]
![screen shot 2017-01-29 at 12 50 52 am](https://cloud.githubusercontent.com/assets/16773027/22402969/65bee334-e5be-11e6-89ba-692a45124477.png)

**Comment by marcshilling** [comment]
Can I see the `options` object you are passing to the ImagePicker function call?

**Comment by safi-manar** [comment]
Of course!

```
  onPress() {
    let options = {
      title: 'Select Profile Picture'
    };

    NativeModules.ImagePickerManager.showImagePicker(options, (picture) => {
      if (picture.data) {
        this.setState({
          profilePicture: {
            uri: 'data:image/jpeg;base64,' + picture.data, isStatic: true
          }
        });
      }
    });
  }
```

I also tried:

```
  onPress() {
    NativeModules.ImagePickerManager.showImagePicker({
      title: "Select Profile Picture"
    }, (picture) => {
      if (picture.data) {
        this.setState({
          profilePicture: {
            uri: 'data:image/jpeg;base64,' + picture.data, isStatic: true
          }
        });
      }
    });
  }
```

**Comment by marcshilling** [comment]
Well, you should not be accessing `NativeModules.ImagePickerManager` directly. You should be doing `var ImagePicker = require('react-native-image-picker');` and using that. The reason it's crashing is because you aren't providing values for `cancelButtonTitle`, `takePhotoButtonTitle`, or `chooseFromLibraryButtonTitle`. If you want to keep using the Native Module, just provide those keys in your options object. Otherwise, use the JavaScript module like I said and default values get provided.

**Comment by safi-manar** [comment]
Wow, great! That fixed it, thanks so much.

You're welcome to close the issue now, but I'm new to React-Native so if you have the time, I'd appreciate it if you could explain just a couple points of confusion!

1. What was the difference between using it directly and the `require` syntax? I've had to use that syntax for a couple of other modules, but I haven't understood exactly the purpose.
2. For other instances where I used `require`  (Such as for Firebase), I wrote it outside the actual class, right under my imports. For the Image-Picker, I wrote it in the method. Does it make a difference where it is written? Also, when writing it outside the class under the imports, when is that line of code executed? With the constructor when the class is first used? Before? After? 

Thanks again!

**Comment by marcshilling** [comment]
1. The require syntax is including the JavaScript wrapper class (you can view it here: https://github.com/marcshilling/react-native-image-picker/blob/master/index.js). As you can see, then the JavaScript code deals with interacting with the Native Module. Not everyone designs their Native Modules like this, but this allows me to specify default options. 

2. It doesn't really matter, but typically you want to put requires at the top of the file with your other imports, and not inside a class. Remember, `import` is new JavaScript syntax for `require()`, they do the same things.
