### ISSUE TITLE
Questions on Image Resizing

### ISSUE THREAD

**Issue by safi-manar** [marcshilling/react-native-image-picker#463]
Is there any more documentation on how the image resizing works?

If not, could someone explain these:

1. Just to clarify maxWidth and maxHeight automatically resize an image, for both iOS/Android. Correct assumption?
3. If `maxWidth = maxHeight = n` but for some image, the dimensions are `a x b`, is the image resized to `nxn` or are the proportions kept?
4. Suppose I provide some maxWidth and maxHeight, but upon checking the fileSize, I decide it's still too large. Is there a way to correct this/change the {options} without showing the ImagePicker again?
(Explanation: I am actually more interested in a maxSize than I am in a maxWidth/maxHeight, but I provide max dimensions, with an assumption that it the resized image will be less than the size cap.)
5. What exactly is the "quality" flag and how does it work?

Thank you!

**Comment by marcshilling** [comment]
1. Yes
2. Proportions should be kept
3. Not currently
4. Quality simply changes the photo compression. 0.0 (worst quality) to 1.0 (best)

**Comment by IkerArb** [comment]
The image size is returned in bytes @marcshilling ?

**Comment by temitope** [comment]
@marcshilling great module. thank you! i didnt realize it resized with those dimensions. and it keeps proportions! thats amazeballs

**Comment by weiliank** [comment]
The image size is returned in bytes @marcshilling ? +1

**Comment by ialmoqren** [comment]
@IkerArb @weiliank @marcshilling In what unit the image size is returned on? and how to convert it to bytes
