### ISSUE TITLE
0.25.1 iOS - Crash Autorotate - Tablet . - iPad Air 10.2

### ISSUE THREAD

**Issue by vivekparekh8** [marcshilling/react-native-image-picker#466]
PUUIAlbumListViewController shouldAutorotate] is returning YES

I open image picker in landscape mode and it crashes giving above exception

Please advice.

Thank you. @marcshilling

**Comment by marcshilling** [comment]
Is portrait mode enabled for your app? Even if you are designing a landscape app, `UIImagePickerController` only supports portrait.
