### ISSUE TITLE
React/RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by a805883237** [marcshilling/react-native-image-picker#467]
#import <React/RCTBridgeModule.h>
#import <UIKit/UIKit.h>

builds errors: 'React/RCTBridgeModule.h'file not found 
And console Error :Unhandled JS Exception: Cannot read property 'showImagePicker' of undefined

console.log(ImagePicker) 
result:{}     ，Nothing！

Help me please.

**Comment by marcshilling** [comment]
Are you using React Native 0.40 or greater?

**Comment by rishiankush** [comment]
+1 getting same error for RN 0.39 version

**Comment by marcshilling** [comment]
@rishiankush we now require RN 0.40. If you need to support 39, use a lower version of this library. Check the README

**Comment by rishiankush** [comment]
@marcshilling let me update my project to RN 0.40 and check. thanks
