### ISSUE TITLE
no height and width in response

### ISSUE THREAD

**Issue by pgmemk** [marcshilling/react-native-image-picker#47]
I just installed the new version but when choosing the photo from the library response does not have width and height. Do I need to specify some options?

**Comment by marcshilling** [comment]
Are you surreeeee you're on the latest version? `response.width` & `response.height` are there for me. You don't need to specify options.

`npm install react-native-image-picker@latest --save`

**Comment by pgmemk** [comment]
You are right it works!!!

Thank you so very much

I just had *returnBase64Image *option passed and with that requested the
response did not have the dimensions


ᐧ

On Mon, Nov 2, 2015 at 4:58 PM, Marc Shilling <notifications@github.com>
wrote:

> Are you surreeeee you're on the latest version? response.width &
> response.height are there for me. You don't need to specify options.
>
> npm install react-native-image-picker@latest --save
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcshilling/react-native-image-picker/issues/47#issuecomment-153082642>
> .
>



-- 
Ellen Katsnelson
Lead Developer

**Comment by marcshilling** [comment]
@pgmemk cool. Just FYI though, `returnBase64Image` is no longer an option. I refactored the options recently...check the README for the updated usage.
