### ISSUE TITLE
Deleting Images

### ISSUE THREAD

**Issue by ranjeev75** [marcshilling/react-native-image-picker#475]
How would you be able to delete images that have been previously selected, or are they overwritten in the same location?

**Comment by alexustinovsm** [comment]
@ranjeev75 for what?

**Comment by rusfearuth** [comment]
@ranjeev75 for what?

**Comment by ranjeev75** [comment]
So the `ur` in the response object shows where an image has been stored: 

`uri: content://media/external/images/media/2715`

When selecting another image will the above persist or is it deleted/ overwritten?

If  not what's the optimal way to delete the current image?

**Comment by finch001** [comment]
@ranjeev75 i think may be you need fs to delete by hand
