### ISSUE TITLE
Take photo crashes on Android v16

### ISSUE THREAD

**Issue by novotnej** [marcshilling/react-native-image-picker#476]
I noticed you changed the minimum SDK requirement to 19, but that doesn't really cut it - according to this there are still > 11% of users using v16, 17, 18 and that's quite a lot... 

[https://developer.android.com/about/dashboards/index.html
](https://developer.android.com/about/dashboards/index.html)

I noticed choosing a picture from the SD card doesn't crash the app. Could you please just hide the "Take Photo" button instead of increasing minSDK version? I still need to support the older versions..

**Comment by marcshilling** [comment]
@rusfearuth is there no way to support SDK 16 and 7.0?

**Comment by rusfearuth** [comment]
@marcshilling I'll checkout it today.

**Comment by rusfearuth** [comment]
@marcshilling You can move back API version to 16. It'll work fine. I've tested this case.

**Comment by marcshilling** [comment]
I've set `minSdkVersion` back to 16 in `v0.25.5` on npm. Sorry about that!
