### ISSUE TITLE
Consistent permission denied behavior between iOS and android 

### ISSUE THREAD

**Issue by skv-headless** [marcshilling/react-native-image-picker#478]
**ios will call callback**
https://github.com/marcshilling/react-native-image-picker/blob/master/ios/ImagePickerManager.m#L203

**but android will not**
https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L258

I can make PR but it may break someone's code.

**Comment by rusfearuth** [comment]
I see. Will be fixed this week.

**Comment by skv-headless** [comment]
It happens when select `never ask again`.

**Comment by ptomasroos** [comment]
Looking forward to that @rusfearuth !

**Comment by rusfearuth** [comment]
@ptomasroos I'm going to make PR in the next 2 days. Everything is ready, but I need to test my solution.

**Comment by ptomasroos** [comment]
Great!

**Comment by rusfearuth** [comment]
```
bug still on lastest version 0.25.7 (my device : android 4.4.2).
Crash on Camera option.
Debug log :
"02-27 18:18:19.858 29125-29172/com.package W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.package/files/Pictures"
```

**Comment by marcshilling** [comment]
@rusfearuth good to close this now?

**Comment by rusfearuth** [comment]
I think yes.
вс, 5 марта 2017 г. в 3:55, Marc Shilling <notifications@github.com>:
