### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by whokilledtheelectricmonk** [marcshilling/react-native-image-picker#48]
It would be great to have support for this library on Android, using a native module or the [React Native Camera Roll API](https://facebook.github.io/react-native/docs/cameraroll.html)

**Comment by marcshilling** [comment]
Currently no plans to work on this, but would gladly accept a PR!

**Comment by nikki93** [comment]
Hey! I created a very basic (no extra options supported yet and has only `.launchCamera(...)` or `.launchImageLibrary(...)` directly) Android implementation of this API. You can find it here: https://github.com/exponentjs/react-native-image-picker-android

**Comment by marcshilling** [comment]
@nikki93 sweet! Eventually we should try to merge these 2

**Comment by marcshilling** [comment]
Merged in #54! Thanks @nikki93 and @yfuks!
