### ISSUE TITLE
Change camera and photo library language needed

### ISSUE THREAD

**Issue by bilalkosker** [marcshilling/react-native-image-picker#480]
Change camera and photo library language needed for multilanguage app

**Comment by marcshilling** [comment]
The options `title`, `cancelButtonTitle`, `takePhotoButtonTitle`, and `takePhotoButtonTitle` allow you to customize the text. Is this sufficient?

**Comment by bobos** [comment]
But seems like "title", "cancelButtonTitle", "takePhotoButtonTitle" don't work with ImagePicker.launchCamera, or I did something?
var options ={quality: 1,
                       maxWidth: 800,
                       maxHeight: 800,
                       takePhotoButtonTitle: "some text",
                       cancelButtonTitle: "some text",
                       mediaType: 'photo',
                       title: "title text",
                       storageOptions: {
                             skipBackup: true }
                      };
     ImagePicker.launchCamera(options, callback)

neither "title" nor "cancelButtonTitle" nor "takePhotoButtonTitle" is working, or how can I rename "Retake", "Use Photo" and "Cancel" when I only use ImagePicker.launchCamera?

**Comment by marcshilling** [comment]
That's out of my control. You need to set localization settings in your Xcode project. See this link: http://stackoverflow.com/questions/8258391/how-do-i-localize-uiimagepickercontroller

**Comment by bobos** [comment]
thx, I will have a try :)

**Comment by jsina** [comment]
@marcshilling I've done as you said but the title doesn't change, [issue 859](https://github.com/react-community/react-native-image-picker/issues/859)

**Comment by HelbertCampos** [comment]
> The options `title`, `cancelButtonTitle`, `takePhotoButtonTitle`, and `takePhotoButtonTitle` allow you to customize the text. Is this sufficient?

chooseFromLibraryButtonTitle
