### ISSUE TITLE
0.25.5 Automatic Installation not work on Android

### ISSUE THREAD

**Issue by weeravit** [marcshilling/react-native-image-picker#481]
I found problem can't open camera or gallery but I fixed.
If you can't open camera or gallery, you follow this step.

Add this step to AndroidManifest.xml
`<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`

**Comment by rusfearuth** [comment]
@weeravit G'day mate!

Thanks for reporting, but it's not a problem. You can see from readme you need to add the next lines of code
```xml
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
to your `project/android/app/src/main/AndroidManifest.xml` file.
