### ISSUE TITLE
Crashes on RN 0.40

### ISSUE THREAD

**Issue by moerabaya** [marcshilling/react-native-image-picker#487]
The app crashes when importing from the library, also the following error show up when using the camera.

<img width="1512" alt="screen shot 1438-05-29 at 2 52 20 pm" src="https://cloud.githubusercontent.com/assets/12199727/23339836/488d7a2e-fc33-11e6-925a-d2b900e8d7a7.png">

**Comment by cjb** [comment]
Same crash here on RN 0.41.2.

**Comment by cjb** [comment]
Ah, fixed it -- the lack of a NSPhotoLibraryUsageDescription entry in Info.plist causes the SIGABRT crash for me.  I bet that's your problem too.

**Comment by marcshilling** [comment]
This is mentioned in the README ^

@moerabaya can you confirm if that fixes it?

**Comment by moerabaya** [comment]
Yes @marcshilling I confirm that was the issue, thank you @cjb.

**Comment by marcshilling** [comment]
@cjb I thought that it showed a warning in the console. There's nothing really that we can do to change the error, but yes I can clarify the symptoms more in the README.

**Comment by cjb** [comment]
Thanks!  Didn't notice anything in the console, but perhaps I missed it.
