### ISSUE TITLE
Image is not saving in Camera Roll

### ISSUE THREAD

**Issue by patrickomeara** [marcshilling/react-native-image-picker#49]
When I take a photo the image is not being saved in the Camera Roll

I am using the following options

```js
UIImagePickerManager.showImagePicker({
	title: 'Select Photo',
	cancelButtonTitle: 'Cancel',
	takePhotoButtonTitle: 'Take Photo',
	chooseFromLibraryButtonTitle: 'Choose from Library',
	returnBase64Image: false,
	returnIsVertical: false,
	quality: 0.8,
	noData: true,
	storageOptions: {
		skipBackup: true
	}
}
```

I have also tried setting storageOptions.path to different values.

**Comment by marcshilling** [comment]
This library does not save photos to the Camera Roll. When you specify `storageOptions`, you are simply saving the photo in your application's `Documents` directory rather than a temp directory where it could be purged.
