### ISSUE TITLE
When to support multiple picture?

### ISSUE THREAD

**Issue by pheromone** [marcshilling/react-native-image-picker#490]
Is going to do pictures multiselect function?

**Comment by rusfearuth** [comment]
@pheromone If you read `README.md`, you could see the next message at the beginning. 

## Before you open an issue

This library started as a basic bridge of the native iOS image picker, and I want to keep it that way. As such, functionality beyond what the native UIImagePickerController supports will not be supported here. **Multiple image selection, more control over the crop tool, and landscape support** are things missing from the native iOS functionality - **not issues with my library**. If you need these things, react-native-image-crop-picker might be a better choice for you.
