### ISSUE TITLE
ShotPhotos, photos can not be displayed

### ISSUE THREAD

**Issue by left-handed** [marcshilling/react-native-image-picker#492]
response.didCancelReturn,‘true’

**Comment by marcshilling** [comment]
I don't understand. Can you provide more info?

**Comment by left-handed** [comment]
Start Camera photographs taken can not upload。





------------------ 原始邮件 ------------------
发件人: "Marc Shilling";<notifications@github.com>;
发送时间: 2017年3月5日(星期天) 凌晨4:55
收件人: "marcshilling/react-native-image-picker"<react-native-image-picker@noreply.github.com>; 
抄送: "澤 。"<928231861@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [marcshilling/react-native-image-picker] ShotPhotos, photos cannot be displayed (#492)




I don't understand. Can you provide more info?
