### ISSUE TITLE
Failed to run react-native-image-picker on Android

### ISSUE THREAD

**Issue by joeyzhao0113** [marcshilling/react-native-image-picker#493]
I am using `"react-native-image-picker": "^0.25.7"` on a react-native android app. I have followed the instruction to install the package as well as link the dependencies.  In my code, when I require this package as below:

`import ImagePicker from 'react-native-image-picker';`

I will get below error message. It seems that the `react-native-image-picker` doesn't exist. But I have run `npm install` and I can see it under `node_modules` directory. 

`Unknown named module: 'react-native-image-picker'`

**Comment by joeyzhao0113** [comment]
It turned out that this relates to react-native cache. Restart react-native process solve this issue.

**Comment by rusfearuth** [comment]
@joeyzhao0113 just reduce version to 0.25.6 and read https://github.com/marcshilling/react-native-image-picker/issues/485 this one.
