### ISSUE TITLE
[Solved] undefined ImagePicker.ShowImagePicker

### ISSUE THREAD

**Issue by N3TC4T** [marcshilling/react-native-image-picker#494]
Hey

first of all I've read all same issues and no one solved my problem .

I'm just tried this steps:

- using "react-native link"
- adding required permissions in AndroidManifest.xml
- installing manualy by steps descriped in README
- restarting packager and removing app and recompiling 

I've check everything (EVERYTHING) and seems all is ok but I got this error :

> Undefined is not an object (evaluating '_reactNativeImagePicker.ImagePicker.showImagePicker'') 

in my run-android command I get this warning :

> android/app/src/main/AndroidManifest.xml:13:9-22:20 Warning: 
> provider#android.support.v4.content.FileProvider@android:authorities was tagged at AndroidManifest.xml:13 to replace other declarations but no other declaration present

react-native : 0.40.0
react-native-image-picker : 0.25.7
Android version : 5.1

thanks for help :)

**Comment by rusfearuth** [comment]
@N3TC4T You should reduce `react-native-image-picker` package to `v0.25.6` and read this issue (https://github.com/marcshilling/react-native-image-picker/issues/485),

**Comment by N3TC4T** [comment]
@rusfearuth  thanks for reply and good support 

Unfortunately after upgrading gradle and gradle-wrapper , and also downgrading react-native-image-picket to v0.25.6 issues is stilll remaining .

need to send my gradle and other files for better debuggingg ?

**Comment by N3TC4T** [comment]
build.gradle:

>  // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     repositories {
>         jcenter()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:2.2.+'
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         jcenter()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
>     }
> }

settings.gradle:

> 
> rootProject.name = 'myproject'
> include ':react-native-image-picker'
> project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')
> include ':react-native-fs'
> project(':react-native-fs').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fs/android')
> include ':react-native-vector-icons'
> project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
> include ':react-native-google-analytics-bridge'
> project(':react-native-google-analytics-bridge').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-analytics-bridge/android')
> include ':react-native-device-info'
> project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
> 
> include ':app'

app/build.gradle:

> dependencies {
>     compile project(':react-native-image-picker')
>     compile project(':react-native-fs')
>     compile project(':react-native-vector-icons')
>     compile project(':react-native-google-analytics-bridge')
>     compile project(':react-native-device-info')
>     compile fileTree(dir: "libs", include: ["*.jar"])
>     compile "com.android.support:appcompat-v7:23.0.1"
>     compile "com.facebook.react:react-native:+"  // From node_modules
> }


AndroidManifest.xml : 

> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.myproject"
>     android:versionCode="1"
>     android:versionName="1.0">
> 
>     <uses-permission android:name="android.permission.CAMERA" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
> 
>     <uses-sdk
>         android:minSdkVersion="16"
>         android:targetSdkVersion="22" />
> 
>     <application
>       android:name=".MainApplication"
>       android:allowBackup="true"
>       android:label="@string/app_name"
>       android:icon="@drawable/ic_launcher"
>       android:theme="@style/AppTheme">
>       <activity
>         android:name=".MainActivity"
>         android:label="@string/app_name"
>         android:windowSoftInputMode="adjustResize"
>         android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>       </activity>
>       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
>     </application>
> 
> </manifest>

MainApplication.java :

>     @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>             new ImagePickerPackage(),
>             new RNFSPackage(),
>             new VectorIconsPackage(),
>             new GoogleAnalyticsBridgePackage(),
>             new RNDeviceInfo()
>       );
>     }

**Comment by ahsanazwar** [comment]
Same Issue

**Comment by rusfearuth** [comment]
@N3TC4T Do you use proguard?

**Comment by N3TC4T** [comment]
@rusfearuth Not really .

**Comment by dsvictor94** [comment]
make sure you are importing that way
`import ImagePicker from 'react-native-image-picker';`
and **not** that way
`import { ImagePicker } from 'react-native-image-picker';`

**Comment by ahsanazwar** [comment]
I'am importing the same way you

**Comment by ahsanazwar** [comment]
![error1](https://cloud.githubusercontent.com/assets/20488590/23578335/3f445bd2-00f6-11e7-92f1-7dffe5ea7d84.PNG)

**Comment by rusfearuth** [comment]
@ahsanazwar Could you show `import` of library in `Upload.js` and `android/build.gradle`?

**Comment by ahsanazwar** [comment]
Upload.js:

import React ,{Component} from 'react'
import {
  StyleSheet,
  Text,
  View,
  PixelRatio,
  TouchableOpacity,
  Platform,
  Image,
  Alert
} from 'react-native'
import ImagePicker from 'react-native-image-picker';
var FileUpload = require('NativeModules').FileUpload;

export default class Upload extends Component {
  constructor(props){
    super(props);
    this.state = {
      avatarSource: null,
      imgBase64: '',
    }
  }

  selectPhotoTapped() {
    const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true
      }
    };

    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        var source, temp;
        // You can display the image using either:
        //source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};

        temp = response.data;

        //Or:
        if (Platform.OS === 'android') {
          source = {uri: response.uri, isStatic: true};
        } else {
          source = {uri: response.uri.replace('file://', ''), isStatic: true};
        }

        this.setState({
          avatarSource: source,
          imgBase64: temp,
        });
      }
    });
  }

  upload(){
    console.log("click");
    var obj = {
        uploadUrl: 'http://pttkht.esy.es/uphinhanh.php',
        method: 'POST', // default 'POST',support 'POST' and 'PUT'
        headers: {
          'Accept': 'application/json',
        },
        fields: {
          'img': this.state.imgBase64,
        },
        files: [

        ]

    };
    FileUpload.upload(obj, function(err, result) {
      console.log('upload:', err, result);
      if (err == null){
        Alert.alert(
          'Thong Bao',
          'Upload thanh cong',
          [
            {text: 'OK', onPress: () => console.log('OK Pressed')},
          ]
        )
      }else{
        Alert.alert(
          'Thong Bao',
          err,
          [
            {text: 'OK', onPress: () => console.log('OK Pressed')},
          ]
        )
      }

    })
  }

  render() {
    return (
        <View style={styles.container}>
          <TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
            <View style={[styles.avatar, styles.avatarContainer, {marginBottom: 20}]}>
            { this.state.avatarSource === null ? <Text>Select a Photo</Text> :
              <Image style={styles.avatar} source={this.state.avatarSource} />
            }
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={{backgroundColor:'yellow', width:60, height:20,marginTop:20,justifyContent: 'center',
          alignItems: 'center'}} onPress={this.upload.bind(this)}>
            <Text>Upload</Text>
          </TouchableOpacity>

          <TouchableOpacity style={{backgroundColor:'yellow',width:60, height:20, marginTop:20,justifyContent: 'center',
          alignItems: 'center'}} onPress={this.props.cancel}>
            <Text>Cancel</Text>
          </TouchableOpacity>

        </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center'
  },
  avatarContainer: {
    borderColor: '#9B9B9B',
    borderWidth: 1 / PixelRatio.get(),
    justifyContent: 'center',
    alignItems: 'center'
  },
  avatar: {
    borderRadius: 75,
    width: 150,
    height: 150
  }

});

build.gradle:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by rusfearuth** [comment]
@ahsanazwar Are you sure that you have options when you call showImagePicker? I see problem in your code ( Could you check it?

**Comment by ahsanazwar** [comment]
@rusfearuth what's the problem

**Comment by rusfearuth** [comment]
I see that you create options as constant in scope of some method and call `showImagePicker` in another place.

**Comment by N3TC4T** [comment]
@dsvictor94  Thanks , solved my problem .

@rusfearuth Thanks man :)

**Comment by ahsanazwar** [comment]
I copy past the example code but still getting the same error @N3TC4T please guide me how did you solve

**Comment by N3TC4T** [comment]
@ahsanazwar , as @rusfearuth  pointed in upper comments "You should reduce react-native-image-picker package to v0.25.6 and read this issue (#[485](https://github.com/marcshilling/react-native-image-picker/issues/485)), "

but in my case importing was the problem .

**Comment by dsvictor94** [comment]
@ahsanazwar can you edit your comment with the code and past it formatted as code (maybe in a gist)?
but anyway, your error message is a little different than N3TC4T error.
Basicly its is showing that it could not load the native module.

Make sure you run `react-native link`, rebuild the apk and restart the server

If it not work, post your `android/app/src/main/java/com/[APP_NAME]/MainApplication.java` and  your `android/app/build.gradle`

**Comment by novotnej** [comment]
Similar problem here, but works fine in debug. However building release version fails at 

Execution failed for task ':app:processReleaseResources' 

with 

android/app/src/main/AndroidManifest.xml:13:9-22:20 Warning:
provider#android.support.v4.content.FileProvider@android:authorities was tagged at AndroidManifest.xml:13 to replace other declarations but no other declaration present

Tried with react-native 40 and package 0.25.6 and 0.25.5 and also RN 42 and 0.26.0

**Comment by dsvictor94** [comment]
@novotnej this #497 should solve this warning, but this should not crash the app. Can you post the error?

**Comment by novotnej** [comment]
Yep I just edited the comment, the crash is coming from react-native issue itself 
[https://github.com/facebook/react-native/issues/5787](https://github.com/facebook/react-native/issues/5787)

**Comment by deepeshkarkee** [comment]
Possible Solution:

There is a high chance that this is not a React Native issue, rather that of your phone(Only Android) settings. Try this:

Go to Settings > Developer options.
Scroll Down till you find "Don't keep activities". Usually it should be under "App" heading.
Disable it IF it's enabled. (If its disabled, then this solution is not for you)
Try running the file upload now. It should work.
****** Description:

Don't keep activities - destroys every activity as soon as the user leaves it.
React native image picker opens system's file system using React-native-fs.
At this point your RN app becomes a background app, which is destroyed by the setting in step 3.
This is the case with all apps that use native file systems. Thats the reason some apps like facebook, messanger, whatsapp etc have their own native filesystem.
Happy coding

**Comment by tahahk** [comment]
@dsvictor94 u are a genius man (y)

**Comment by NicholasJCameron** [comment]
My fix was importing it like this var ImagePicker = require('react-native-image-picker');

**Comment by RobamKatebe** [comment]
Hello? I am new at react native. Can someone post a working example please? Thank you in advance.

**Comment by Leenachauhan** [comment]
My fix in **react-native@60** was importing it like this----
    import ImagePicker  from 'react-native-image-picker';
instead of
    var ImagePicker = require('react-native-image-picker');

Thankyou.

**Comment by amkaub** [comment]
2020 still existing this issue.

**Comment by MomarDev** [comment]
make sure to bind the method before using

**Comment by avisek123** [comment]
I'm trying again and again but same error shows , please help me .

**Comment by Johan-dutoit** [comment]
Locking as there is no useful discussions being made here.  Read the docs on how to link and import the library.
