### ISSUE TITLE
When taking a photo with front camera the image is mirrored

### ISSUE THREAD

**Issue by ptomasroos** [marcshilling/react-native-image-picker#495]
Happens both on Nexus 6P (6.0) and Samsung S6 (7.0)

**Comment by skv-headless** [comment]
http://androidforums.com/threads/any-way-to-stop-front-facing-camera-from-mirroring-inverting-image.622351/#post-4998168
it is default front camera behaviour. I guess we can close it.

**Comment by ptomasroos** [comment]
Wow, didnt know. I guess all major social networks have their own picker then.
