### ISSUE TITLE
Unmet dependancy issue for rn0.40

### ISSUE THREAD

**Issue by anahitsk123** [marcshilling/react-native-image-picker#502]
Hi, 

I just installed the latest version and it was supposed to work with >=RN0.40.
I have exactly RN0.40 installed and after installation is finished, it shows 'UNMET PEER DEPENDENCY react-native@0.40.0'.

**Comment by rusfearuth** [comment]
Will be fixed in the nex pr.

**Comment by rusfearuth** [comment]
@anahitsk123 Could you checkout with v0.26.2?

**Comment by anahitsk123** [comment]
Yes, it si fixed now. Thanks
