### ISSUE TITLE
Fail to link react-native-image-picker

### ISSUE THREAD

**Issue by Style-Tender** [marcshilling/react-native-image-picker#505]
I Integrated React Native into an original android project,and using 'react-native-image-picker@0.26.1' on it. When i carry out 'react-native link', the terminal return 'Scanning 438 folders for symlinks in /Users/densakai/Documents/ESPWorkspace/node_modules (3ms)'. How can i solve it?

**Comment by rusfearuth** [comment]
@Style-Tender  tried to remove key `peerDependencies` from `node_modules/react-native-image-picker/package.json`.

**Comment by Style-Tender** [comment]
@rusfearuth thank you so much,I remove key 'peerDependencies'from `node_modules/react-native-image-picker/package.json`,but it does't work seemingly.

**Comment by rusfearuth** [comment]
@Style-Tender Could you give me some logs from `react-native link`?

**Comment by Style-Tender** [comment]
@rusfearuth  Here is the logs in my  terminal 
```
tianyudeMacBook-Air:ESPWorkspace densakai$ npm install react-native-image-picker@latest --save
friendcircle@1.0.0 /Users/densakai/Documents/ESPWorkspace
└── react-native-image-picker@0.26.1 

npm WARN friendcircle@1.0.0 No repository field.
tianyudeMacBook-Air:ESPWorkspace densakai$ react-native link
Scanning 438 folders for symlinks in /Users/densakai/Documents/ESPWorkspace/node_modules (3ms)
tianyudeMacBook-Air:ESPWorkspace densakai$
```

**Comment by marcshilling** [comment]
@Style-Tender apart from the string that it is outputting, was the link successful? It's likely nothing to worry about if it works regardless..

**Comment by Style-Tender** [comment]
@marcshilling May be it has linked successfully. Because that I Integrated React Native into an original android project,and my Activity `extends Activity implements DefaultHardwareBackBtnHandler`,I add the import `com.imagepicker.permissions.OnImagePickerPermissionsCallback` and `com.facebook.react.modules.core.PermissionListener`,then add the implements `OnImagePickerPermissionsCallback`,finally add the code
```
@Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults)
    {
        if (listener != null)
        {
            listener.onRequestPermissionsResult(requestCode, permissions, grantResults);
        }
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    public void setPermissionListener(PermissionListener listener) {;
        this.listener = listener;
    }
```
To here, my problem is comming. It can run into the album, but after i click a picture,the js can not get a result.

**Comment by rusfearuth** [comment]
@Style-Tender Hm.. It I understand right, you added React Native to exist native project. Right?

**Comment by Style-Tender** [comment]
@rusfearuth Yes.

**Comment by Style-Tender** [comment]
I have solved the problem. Thanks everyone!

**Comment by StanislavMaslow** [comment]
I am facing with the same issue. How did you solved it?
