### ISSUE TITLE
Image doesn't appear in gallery after saving [Android]

### ISSUE THREAD

**Issue by cooperka** [marcshilling/react-native-image-picker#508]
When setting `storageOptions: {}` (such as in the example app), the docs say "the image will get saved in ... the Pictures directory on Android". I think it used to do this, but no longer.

Repro steps:

1. Run the example app on Android
2. Take a picture
3. Check your gallery app, it's not there
4. Check your Pictures folder, it's not there either

Tested on a Nexus 5X 6.0 emulator (using latest master 62cf9edbde45240a75b45c789042c9db488c6b76) and a Nexus 6P 6.0 physical device (using v0.25.7). I haven't tested on iOS because the simulator isn't able to take pictures.

---

Clarification: It sounds like currently the image is being saved under your app's `.../your_package_name/files/Pictures/`, whereas I assumed it would be saved under the shared `/sdcard/Pictures/`. Read below for more details about upcoming changes.

**Comment by marcshilling** [comment]
@rusfearuth did your refactor break this?

**Comment by rusfearuth** [comment]
@cooperka Does it left in photo apps or in Photo directory?

**Comment by cooperka** [comment]
@rusfearuth the image isn't saved in the Pictures directory, and it doesn't show up in the Gallery app. Is that what you mean?

**Comment by rusfearuth** [comment]
@cooperka Photos are saved to /external_storage/Android/your_package_name/files/Pictures. 

I see     MediaScannerConnection.scanFile doesn't work properly.

**Comment by cooperka** [comment]
Hmm, so are they supposed to be saved to the public location but they aren't? To me, "Pictures" means the public folder at the root of /sdcard/Pictures, not a private folder within your app's sandbox. I just want to make sure I understand.

**Comment by rusfearuth** [comment]
@cooperka Why `sandbox`? It depends on cases. If you need only to take and upload photo and you don't want to see it in your gallery, it'll be fine. If you want to save photo to Picture after app will be removed (your case), It'll be better to save in public Picture.

I think you need to read [this](https://developer.android.com/about/versions/nougat/android-7.0-changes.html). Now, app `sandbox` folder is NOT sandbox as you can see ;)

I'll add support to save files to 2 different folders, you'll be able to change it by js configs.

**Comment by cooperka** [comment]
Sorry for the confusion; I just meant sandbox [generically](https://en.wikipedia.org/wiki/Sandbox_(computer_security)), not the Android-specific folder.

My desire is to take a photo using `react-native-image-picker` and have that photo automatically show up in any standard "gallery" type app so the user can find it later. In most cases that means saving the photo under `DCIM/` or `Pictures/` at the root of `sdcard/`.

If you're planning to add support for this, that's great! Thank you. I would also recommend updating the README to clarify that `storageOptions` will save the photo under **your app's** `Pictures/` directory, rather than the shared `sdcard/Pictures/` as I had assumed. Would you like me to submit a PR for this?

**Comment by rusfearuth** [comment]
@cooperka No problems. You can do PR for update documentation if you want.
Later it'll be updated.

**Comment by cooperka** [comment]
@rusfearuth we're actually going to prioritize this feature for our app. Have you already started working on the changes? If not, I'd be happy to do it instead. Let me know what you prefer :)

**Comment by rusfearuth** [comment]
@cooperka I've already started working for this task.

**Comment by cooperka** [comment]
Great! I'll use a workaround for now and wait for your changes.

**Comment by rusfearuth** [comment]
@cooperka Could you check it out from bugfix/508 branch?

**Comment by marcshilling** [comment]
I've added my feedback to #513.

The way we should make this work is by using the same option we use to accomplish this on iOS: `storageOptions.cameraRoll`. The way it works on iOS is as follows:
- If `storageOptions` key is provided, we store the image in the app's sandbox Documents folder (or a subfolder if `storageOptions.path` is provided.
- If `storageOptions.cameraRoll` is true, we also save the image in the public iPhone camera roll

**Comment by rusfearuth** [comment]
@marcshilling Unfortunately, I can't use `storageOptions.path` for Android 7 and higher. That's way, I pass this option.

Okey, If user adds empty `storageOptions` or doesn't add it at all, app will use own folder for saving taken photo. If user adds `storageOptions.cameraRoll = true`, photo will be saved to public folder.

Is it fine?

**Comment by antoinerousseau** [comment]
settings `storageOptions.path` still saves my pic in `Pictures/` on my LG G3 (Android 7.1) instead of the given sub path. any idea?

**Comment by cpjolicoeur** [comment]
per @rusfearuth It does appear that `MediaScannerConnection.scanFile` isn't always working properly.  On Android OS 8.x devices the scan happens and media immediately appears in the gallery.  On an Android 7.1.0 device the media doesnt appear until reboot or an SD card remount.
