### ISSUE TITLE
Does this library compress image quality by default?

### ISSUE THREAD

**Issue by just4fun** [marcshilling/react-native-image-picker#509]
I did some tests on this library and [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) with iOS simulator.

If I select first default image in iOS simulator, this library will get,

fileSize: 314945
height: 2848
width: 4288

while `react-native-image-crop-picker` will get,

size: 6209998
height: 2848
width: 4288

I'm not sure what is the size of original image, but it seems like react-native-image-crop-picker read the original size and this library compressed it.

Is that right?

**Comment by just4fun** [comment]
I found there is `quality` to be used by `UIImageJPEGRepresentation`, so what is the default value of `quality`?

**Comment by marcshilling** [comment]
The maximum value is 1.0, which is the default. If you don't want any compression I would suggest passing the `imageFileType: 'png'` option.

**Comment by just4fun** [comment]
@marcshilling ah OK, I think it's good.
Thank you.

**Comment by ShenghuGong** [comment]
@marcshilling  How can i use the `imageFileType: 'png'` option ? , I selected a png image on iphone, but get a jpg image. How can i fixed it?  Thank you.
