### ISSUE TITLE
Base64 to Blob

### ISSUE THREAD

**Issue by quangas** [marcshilling/react-native-image-picker#510]
Is there anyway we can convert the base64 image from response.data to a bytes/blob?

**Comment by marcshilling** [comment]
You can do this yourself in JavaScript: See [here](http://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript). Not going to do this in our library because of the performance impact.

**Comment by abdurrahmanekr** [comment]
When I tried method that you are mentioned. I'm run across an error called "res.blob() is not a function". Because of this error I can use this method:

```javascript
function urlToBlob(url) {
    return new Promise((resolve, reject) => {
        var xhr = new XMLHttpRequest();
        xhr.onerror = reject;
        xhr.onreadystatechange = () => {
            if (xhr.readyState === 4) {
                resolve(xhr.response);
            }
        };
        xhr.open('GET', url);
        xhr.responseType = 'blob'; // convert type
        xhr.send();
    })
}

var data = 'data:image/png;base64,...';
urlToBlob(data)
.then(blob => {
    console.log(blob)
})
```

**Comment by Jason-CHY** [comment]
Solution is not work without remote js debugging.

**Comment by Johan-dutoit** [comment]
FWIW React Native supports, although untested... you could try the following

```
const response = await fetch(...);
const blob = await response.blob();
```

**Comment by SudoPlz** [comment]
Posted an example here, thanks @Johan-dutoit https://stackoverflow.com/a/59002760/1658268

**Comment by josealvarez97** [comment]
> You can do this yourself in JavaScript: See [here](http://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript). Not going to do this in our library because of the performance impact.

Is it slower to use blob/byte arrays? I thought that was faster than bas64 in most cases. What do you mean exactly by performance impact?

**Comment by snios** [comment]
> > You can do this yourself in JavaScript: See [here](http://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript). Not going to do this in our library because of the performance impact.
> 
> Is it slower to use blob/byte arrays? I thought that was faster than base64 in most cases. What do you mean exactly by performance impact?

I agree with you here. Blob should have less performance impact than base64 does.
