### ISSUE TITLE
Can't get image source from callback parameter

### ISSUE THREAD

**Issue by joeyzhao0113** [marcshilling/react-native-image-picker#519]
I am using below code to select images:

```
const options = {
      title: 'Select Image',
      cancelButtonTitle: 'Cancel',
      takePhotoButtonTitle: 'Camera',
      chooseFromLibraryButtonTitle: 'Choose from Libraray',
    };
    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);
```

from the response in the callback, I don't know which option users select, `Camera` or `Choose from Library`

**Comment by rusfearuth** [comment]
@joeyzhao0113 Hi! If you read [README.md](https://github.com/marcshilling/react-native-image-picker#directly-launching-the-camera-or-image-library), you could see the next paragraphs.

## Directly Launching the Camera or Image Library

To Launch the Camera or Image Library directly (skipping the alert dialog) you can do the following:

```javascript
// Launch Camera:
ImagePicker.launchCamera(options, (response)  => {
  // Same code as in above section!
});

// Open Image Library:
ImagePicker.launchImageLibrary(options, (response)  => {
  // Same code as in above section!
});
```

Note

On iOS, don't assume that the absolute uri returned will persist. See #107 

I hope it'll help you.

**Comment by zhaoyi0113** [comment]
That means I need to use customised button and call image or camera directly from their callback. Right?

**Comment by rusfearuth** [comment]
@zhaoyi0113 Right
