### ISSUE TITLE
uploading image from camera taking more time 

### ISSUE THREAD

**Issue by shaikhussian** [marcshilling/react-native-image-picker#52]
@marcshilling it was great, It's very useful module, But what the problem is that when i choose image from camera, it take more time when compare with the image from library.

**Comment by Obooman** [comment]
So did I.Besides,it went crash sometimes after my taking photo.Wondering for solutions.

**Comment by Obooman** [comment]
@shaikhussian I fond the solution.Because of the 'data' param of 'response'.The example's options hasn't set the property{noData:true}.Furture more In README.md demo.

**Comment by shaikhussian** [comment]
@Obooman  when i set the property{noDta:true}.just now i checked it,for first time the image is not showing, but when i choose second time it working and time not taking much,

**Comment by Obooman** [comment]
@shaikhussian I have't seen this problem.Have you log some informations in DevTool? Some debug info may help you.

Or you can paste your code here,the problem is weired.

**Comment by shaikhussian** [comment]
[react-nativ.pdf.docx](https://github.com/marcshilling/react-native-image-picker/files/41568/react-nativ.pdf.docx)

**Comment by Obooman** [comment]
By your code and expression,I think it's because of the wrong value of <Image/> source property.
Source property of Image element requires an 'Object' to describe the Image element.

[React Native Image Element](https://facebook.github.io/react-native/docs/images.html#content)

Try to change your JSX code of render function in 'camera' class  from
```
{ this.state.avatarSource === null ? 
                      <Image style={styles.image} source={{uri,}}/> : //<- 
                      <Image style={styles.image} source={this.state.avatarSource} />
                    }
```

to

```
{ this.state.avatarSource === null ?
                      <Image style={styles.image} source={{uri:uri,static:true}}/> : //<- To this
                      <Image style={styles.image} source={this.state.avatarSource} />
                   }
```

Hope it will work.BTY,cool portrait.

**Comment by shaikhussian** [comment]
@Obooman i wrote it as per your comment,but even though sample problem, this will happen only when i checked in the device not in the simulator, in simulator it works.
```
<View >
 { this.state.avatarSource === null ?  
         <Image style={styles.image} source{{uri:uri,static:true}}/> :
        <Image style={styles.image}  source={this.state.avatarSource}  />
</View>
```

**Comment by Obooman** [comment]
@shaikhussian Maybe the reason is that your code versions are different between your simulator and device.I can't tell other possiblities.Try to ask the owner.

**Comment by marcshilling** [comment]
@shaikhussian still having this issue?

**Comment by shaikhussian** [comment]
@marcshilling yes

**Comment by marcshilling** [comment]
@shaikhussian play around with the options `maxWidth`, `maxHeight`, `quality`, and `noData`. You should be able to reach a good compromise regarding performance.

**Comment by shaikhussian** [comment]
@marcshilling when i try to save image in source i am getting [object Object] , when i save like this when i check in database there also it saves like object .how can i save image uri
