### ISSUE TITLE
How does image picker support Android for storage?

### ISSUE THREAD

**Issue by zhaoyi0113** [marcshilling/react-native-image-picker#520]
I read the README about `storageOptions`. It says `storageOptions` is OK for both `Android` and `iOS` but none of its sub-options support `Android`. How can I use it on Android then?

**Comment by rusfearuth** [comment]
@zhaoyi0113 It's going to use only caneraRoll option. Look at [this](https://github.com/marcshilling/react-native-image-picker/pull/516) PR.
