### ISSUE TITLE
Update Android build tools version 

### ISSUE THREAD

**Issue by alexeypodolian** [marcshilling/react-native-image-picker#521]
Android Studio 2.3 requires build tools version 25.0.0 or higher

**Comment by rusfearuth** [comment]
@alexeypodolian Hi! Hmmm... I've seen dialog for upgrading to 25.0.0 build tools, but I ignored them. Do you have problem with building project or?

**Comment by alexeypodolian** [comment]
@rusfearuth Yes, unfortunately I can not build the project without 25.0.0 (or higher)

**Comment by rusfearuth** [comment]
@alexeypodolian Do you use gradle cli or Android Studio?

**Comment by alexeypodolian** [comment]
@rusfearuth Android Studio 2.3

**Comment by rusfearuth** [comment]
@alexeypodolian Did you try use `gradlew` for building?

**Comment by alexeypodolian** [comment]
@rusfearuth Yes, the same issue because of I have updated `gradlew` to version 3.3 after Android Studio update

**Comment by rusfearuth** [comment]
@alexeypodolian Are you sure? It's only recommendation you can build project with old build tools.

**Comment by alexeypodolian** [comment]
@rusfearuth Yes, I'm sure. 

<img width="1261" alt="screen shot 2017-03-31 at 8 11 06 am" src="https://cloud.githubusercontent.com/assets/15009596/24537287/c65e995e-15e9-11e7-8f47-8b662d0d3bdb.png">

**Comment by rusfearuth** [comment]
@alexeypodolian Could you show me the log from cli on calling `./gradlew assembleDebug`?

**Comment by alexeypodolian** [comment]
@rusfearuth Yes. By the way, Android Studio is just wrapper upon Gradle CLI. 
```
Alexeys-MacBook-Pro-2:android alexey$ ./gradlew assembleDebug
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_devDebugApk'.
   > A problem occurred configuring project ':react-native-image-picker'.
      > The SDK Build Tools revision (23.0.3) is too low for project ':react-native-image-picker'. Minimum required is 25.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.797 secs
```

**Comment by alexeypodolian** [comment]
@rusfearuth There is a pull request 

[https://github.com/marcshilling/react-native-image-picker/pull/535](url)

**Comment by BigRoma** [comment]
I try set this version, but i get the error
![image](https://cloud.githubusercontent.com/assets/251894/24537599/2897a564-15ec-11e7-8e10-edd3caabb677.png)

**Comment by alexeypodolian** [comment]
@BigRoma Do you have `comlileVersion 25` at your `build.gradle`?

**Comment by rusfearuth** [comment]
@alexeypodolian Okay. Do you add react-native to exist project or?

**Comment by alexeypodolian** [comment]
@rusfearuth What do you mean? I added `react-native-image-picker` as described at `Install` section of README. And It worked well until I have updated `Gradle Wrapper` and Android Studio.

**Comment by rusfearuth** [comment]
@alexeypodolian Did you add react-native to exist native project or create a new one?

**Comment by rusfearuth** [comment]
@alexeypodolian Could you show the next options from `android/app/build.gradle`?

* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig

**Comment by BigRoma** [comment]
@alexeypodolian Yes i have

**Comment by alexeypodolian** [comment]
@rusfearuth 
I have a exist native project. 

My `build.gradle`: 
```
compileSdkVersion 25
buildToolsVersion '25.0.2'
defaultConfig {
        applicationId 'my.package'
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 123
        versionName '123'
        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }
        multiDexEnabled true
}
```

**Comment by rusfearuth** [comment]
@alexeypodolian I was right =) It's main problem. Okay, I'll think about your PR.

**Comment by BigRoma** [comment]
@rusfearuth What about my problem?

**Comment by rusfearuth** [comment]
@BigRoma Did you add react-native to exist native project?

**Comment by rusfearuth** [comment]
@BigRoma your problem isn't here ) As you can see problem into react-native-maps.

**Comment by BigRoma** [comment]
@rusfearuth Oh! I'm sorry didn't pay attention, after changing versions of all packages it worked. Thank you very much =)

**Comment by rusfearuth** [comment]
@BigRoma u'r welcome.

**Comment by marcshilling** [comment]
#535 has been merged so closing this.
