### ISSUE TITLE
hi,does this plugin provide generating video-thumbnail for me? 

### ISSUE THREAD

**Issue by dandingol03** [marcshilling/react-native-image-picker#528]

**Comment by marcshilling** [comment]
Currently we do not return a video thumbnail. Would accept PR.

**Comment by RigoTheDev** [comment]
@marcshilling You literally denied a PR (https://github.com/react-native-community/react-native-image-picker/pull/42) for this 2 years prior.

**Comment by marcshilling** [comment]
@RigoTheDev lots of things change in 2 years. For example, in present times I find software development to be soul sucking, and dealing with little children like you posting snappy comments on a 3 year old GitHub issue is _literally_ the last thing I care about. Good day.

**Comment by RigoTheDev** [comment]
@marcshilling "Little children"... really? I didn't insult you, so I don't know why you're taking it so personal.
