### ISSUE TITLE
How can we monitor via a callback for when a selected photo is returned ?

### ISSUE THREAD

**Issue by ajonno** [marcshilling/react-native-image-picker#540]
At the moment, if we choose an image from the photo gallery, the image picker will close -- then there is a wait for a few seconds, then we can render the image using ```<Image..``` etc.

How can we know when the actual image has been returned ? We dont mind the wait but would like to display a spinner up until the point that the image is ready to be rendered in the UI.

**Comment by rusfearuth** [comment]
@ajonno Hmm... I don't think that this is problem of our library.

**Comment by ajonno** [comment]
running on device the response time seems acceptable after the image picker is closed so will leave it at that for now

**Comment by jbreuer95** [comment]
+1

**Comment by hmenzagh** [comment]
+1

**Comment by bacancy-swaroopa** [comment]
+1

**Comment by aaronliew** [comment]
+1
