### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by AdamGorkoz** [marcshilling/react-native-image-picker#57]
Hi , Just added image picker using the guide but i get this error : 
![image](https://cloud.githubusercontent.com/assets/10440278/11650241/0f061868-9d90-11e5-9128-a822f44b2f78.png)

Any ideas ?

UPDATE : solved the issue by adding a missing android folder , maybe you should look into it.

**Comment by yfuks** [comment]
**Actually Android support is not published to npm**

I hope it will be soon, actually you need to add the android folder manualy (like you said)
I made a pr #56 where i ask the owner to publish but i have no response yet

**Comment by marcshilling** [comment]
Doing it today. Give me a couple hours.
