### ISSUE TITLE
how to access state from UIImagePickerManager.launchImageLibrary function

### ISSUE THREAD

**Issue by YanzhuVAS** [marcshilling/react-native-image-picker#59]
this line   this.setState({ avatarSource: source }); 
gave error " this.setState({ avatarSource: source }) _this2.setState is not a function ", any possible other cause of it? I tried different methods to fix it, but still no luck access this in launchImageLibrary. 

Code is copied from index.ios.js /node_modules/react-native-image-picker/Example 

UIImagePickerManager.launchImageLibrary(options, (didCancel, response) => {
      console.log('Response = ', response);
      if (didCancel) {
        console.log('User cancelled image picker');
      } else {
        if (response.customButton) {
          console.log('User tapped custom button: ', response.customButton);
        } else {
          console.log('User pick one image');
          // You can display the image using either:
          //const source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};
          //this.startuploadnewcargo();
          const source = {
            uri: response.uri.replace('file://', ''),
            isStatic: true
          };
          this.setState({ avatarSource: source });
          console.log('after setState showImagePicker');
        }
      }
    });
  }

![screen shot 2015-12-10 at 9 34 48](https://cloud.githubusercontent.com/assets/14838886/11734549/53842cc6-9f86-11e5-8cdb-05e1d8ea6498.png)

**Comment by YanzhuVAS** [comment]
'use strict';

var React = require('react-native');

var {
  AppRegistry,
  StyleSheet,
  Text,
  TextInput,
  View,
  TabBarIOS,
  StatusBarIOS,
  SwitchIOS,
  ActivityIndicatorIOS,
  TouchableHighlight,
  Image,
  PixelRatio,
  TouchableOpacity,
  NativeModules: {
    UIImagePickerManager
  }
} = React;

var styles = StyleSheet.create({
  text: {
    marginTop: 10,
    marginBottom: 10,
    fontSize: 18,
    textAlign: 'center',
    color: '#656565'
  },

  textinput: {
    marginTop: 10,
    marginBottom: 10,
    fontSize: 18,
    textAlign: 'center',
    color: '#656565'
  },

  backgroundtext: {
    marginTop: 18,
    marginBottom: 2,
    marginLeft: 30,
    fontSize: 18,
    alignSelf: 'center',
    color: '#353535'
  },

  container: {
    marginTop: 65,
    alignItems: 'stretch',
    backgroundColor: '#F0F0F0',
    borderColor: '#F0F0F0',
    borderWidth: 1,
    height: 700
  },

  textinputstyle: {
    borderColor: '#F5F5F5',
    borderWidth: 1,
    backgroundColor: '#FFFFFF',
    justifyContent: 'space-around',
    height: 40,
    color: '#656565'
  },

  button: {
    height: 36,
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderColor: '#48BBEC',
    marginBottom: 10,
    marginTop: 10,
    alignSelf: 'stretch',
    justifyContent: 'center'
  },

  avatarContainer: {
    alignSelf: 'center',
    borderColor: '#9B9B9B',
    backgroundColor: '#48BBEC',
    borderWidth: 1 / PixelRatio.get(),
    justifyContent: 'center',
    alignItems: 'center'
  },
  avatar: {
    borderRadius: 75,
    width: 150,
    height: 150
  }

});

function urlForQueryAndPage(cargotype, cargoweight, imagename) {
  return 'http://172.31.98.187:8882/rest/cargo';
};

class NewCargo extends React.Component {

  constructor (props) {
    super(props);
    this.state = {
      cargoinfo_type: 'default type',
      cargoinfo_weight: 'default 8kg',
      isLoading: false,
      message: '',
      trueSwitchIsOn: true,
      falseSwitchIsOn: false,
      avatarSource: null
    };
    //this.UIImagePickerManager.launchImageLibrary(options, didCancel, response)=this.UIImagePickerManager.launchImageLibrary(options, didCancel, response).bind(this);
    //this.UIImagePickerManager.launchImageLibrary=this.UIImagePickerManager.launchImageLibrary.bind(this);

    //console.log(this);
  }

  avatarTapped () {
    const options = {
      title: null,
      quality: 0.5,
      storageOptions: {
        skipBackup: true
      }
    };

    UIImagePickerManager.launchImageLibrary(options, (didCancel, response) => {
      console.log('Response = ', response);
      if (didCancel) {
        console.log('User cancelled image picker');
      } else {
        if (response.customButton) {
          console.log('User tapped custom button: ', response.customButton);
        } else {
          console.log('User pick one image');
          // You can display the image using either:
          //const source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true};
          //this.startuploadnewcargo();
          const source = {
            uri: response.uri.replace('file://', ''),
            isStatic: true
          };
          this.setState({ avatarSource: source });
          console.log('after setState showImagePicker');
        }
      }
    });
  }

  onLocationPressed () {}
  _handleResponse (response) {
    this.setState({isLoading: false});
    if (response.application_response_code.substr(0, 1) === '1') {
      console.log('at _handleResponse');
      this.props.navigator.push({
        title: 'Results',
        component: TruckResults,
        passProps: {
          listings: response.listings
        }
      });

    } else {
      this.setState({message: 'Location not recognized please try again.'});
    }
  }
  _executeQuery (query) {
    this.setState({isLoading: true, message: ''});
    fetch(query).then(response => response.json()).then(json => this._handleResponse(json.response)).catch(error => {
      this.setState({
        isLoading: false,
        message: 'Something bad happened ' + error
      });
    });
  }
  startuploadnewcargo () {
    var query = urlForQueryAndPage('sample_cargotype', 'sample_cargoweight', 'sample_imagename');
    this._executeQuery(query);
  }

  render () {
    var spinner = this.state.isLoading
      ? (<ActivityIndicatorIOS hidden='true' size='large'/>)
      : (<View/>);

    return (
      <View style={styles.container}>
        <Text style={styles.text}>
          New cargo request
        </Text>

        <Text style={styles.backgroundtext}>
          Input cargo information
        </Text>
        <TextInput onChangeText={(text) => this.setState({text})} value={'Sample TextInput'}/>
        <TextInput style={styles.textinputstyle} onChangeText={(text) => this.setState({text})} value={'Type eg: foods, woods'}/>
        <TextInput style={styles.textinputstyle} onChangeText={(text) => this.setState({text})} value={'Weight eg: 20kg, 30pb'}/>
        <Text style={styles.backgroundtext}></Text>

        <TouchableOpacity onPress={this.avatarTapped}>
          <View style={[styles.avatar, styles.avatarContainer]}>
            {this.state.avatarSource === null
              ? <Text>Select a Photo</Text>
              : <Image style={styles.avatar} source={this.state.avatarSource}/>
            }
          </View>
        </TouchableOpacity>

        {spinner}
        <Text style={styles.description}>{this.state.message}</Text>
      </View>
    );

  }

}

module.exports = NewCargo;

**Comment by YanzhuVAS** [comment]
No need to worry about it,     I found the problems,  fixed by 
Change from <TouchableOpacity onPress={this.avatarTapped}>
to <TouchableOpacity onPress={this.avatarTapped.bind(this)}>

  <TouchableOpacity onPress={this.avatarTapped.bind(this)}>
          <View style={[styles.avatar, styles.avatarContainer]}>
            {this.state.avatarSource === null
              ? <Text>Select a Photo</Text>
              : <Image style={styles.avatar} source={this.state.avatarSource}/>
            }
          </View>
        </TouchableOpacity>

**Comment by qasimalbaqali** [comment]
Could you show your solution with a correct markdown format, because I am having the same problem for some reason with the setState for avatarsource

**Comment by yfuks** [comment]
I update his comment.

**Comment by yfuks** [comment]
You should use the arrow notation if you whant to bind your function with the composent context
example:
```javascript
onPress={() => this.avatarTapped()}
```

**Comment by qasimalbaqali** [comment]
Yeah, that fixed it for me :+1:  Thank you!
