### ISSUE TITLE
Sending a image to backend server

### ISSUE THREAD

**Issue by BigPun86** [marcshilling/react-native-image-picker#61]
Hey there. I am trying to send a image which i get from the response and send it via fetch to my server.

     UIImagePickerManager.showImagePicker(options, (didCancel, response) => {
            console.log('Response = ', response);
            if (didCancel) {
                console.log('User cancelled image picker');
            }
            else {
                var fileName = response.uri.substring(response.uri.lastIndexOf("/") + 1);
                var fsPath = response.uri;
                var binaryResponse = response.data;
                fetch('http://XXXX/user/avatar', {
                    method: 'POST', // default 'POST',support 'POST' and 'PUT'
                    headers: {
                        'Authorization': AuthStore.getUserTokenWithBearer()
                    },
                    body: JSON.stringify({image: fsPath})
                }).then(function (response) {
                    console.log(response)
                }).catch(function(error){
                    console.log(error);
                });
            }

I know this isn´t a modules issue, but trying to find solution from stackoverflow or any other sources failed. Maybe someone has tried this with this component and success?

**Comment by marcshilling** [comment]
I'd recommend using https://github.com/booxood/react-native-file-upload

I haven't found success with anything else.

You can upload like this in the image picker success callback:
```javascript
        const obj = {
          uploadUrl: 'http://XXXX/user/avatar',
          method: 'POST',
          headers: {
            'Authorization': AuthStore.getUserTokenWithBearer()
          },
          files: [{
            filename: 'file', // this is what your server is looking for
            filepath: response.uri, // uri from response (local path of image on device)
            filetype: 'image/jpeg'
          }]
        };

        FileUpload.upload(obj, (err, result) => {
          console.log('uploaded avatar to url: ' + result.data);
          this.setState({
            avatarUrl: result.data,
            avatarUploading: false
          });
        });
```

**Comment by yfuks** [comment]
Hello ! I don't really understand what is your problem but i can give you an example,
in the folowing example i post an image to cloudinary using fetch, fileUpload is still a good solution !

```javascript
var _ = require('underscore');
let { UIImagePickerManager: ImagePickerManager } = NativeModules;
var sha1 = require('sha1');

 UIImagePickerManager.showImagePicker(options, (didCancel, response) => {
       console.log('Response = ', response);
       if (didCancel) {
           return console.log('User cancelled image picker');
       }
       var url = 'https://api.cloudinary.com/v1_1/' + cloud_name +   '/image/upload';
       var header = {
            method: 'post',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json'
           }
       };
      var timestamp = Date.now();

      var values = {
       file: 'data:image/png;base64,' + fileBase64,
       api_key: api_key,
       timestamp: timestamp,
       tags: tags,
       signature: sha1("tags=" + tags + "&timestamp=" + timestamp + api_secret)
     };

     var request = _.extend({
        body: JSON.stringify(values)
     }, header);

     fetch(url, request)
         .then((response) => response.json())
         .then((data) => {
      console.log(data);
    })
    .catch((err) => { console.log(err) });}
```

**Comment by BigPun86** [comment]
@marcshilling i tried to use this module, i need it especially for Android and i didn´t get it work yet. but thanks i will try your way and update how it works. 
@yfuks I am not sure if this works. My backend server is waiting for an image, but sending an response.data (is it the binary?) i think won´t be the right way. But thanks, i will give it a try if first way doesn´t works....

**Comment by yfuks** [comment]
@BigPun86 the way to send an image to a distance host is to send his data, the "uri" is the local filepath to your image so your server can not access to the given image with it.

Data is actually the file encoded in base64 (most common usage for image upload)

I asume that react-native-file upload work the same way, take the filePath, transform it to "raw" data then upload it.

In your case you can probably use the folowing as your image data
```javascript
var file = 'data:image/png;base64,' + response.data;
```

**Comment by BigPun86** [comment]
Hey there. It worked great with react-native-fileupload instead of file-upload :P. I tried @yfuks way, but unfortunately it didn´t work. But generally your explanation to send the image "raw" helped me a lot +1. So i think fileupload will do the same...

**Comment by huanglong** [comment]
@yfuks Great! I've done that exactly the same way. Helped me a lot. :+1:

**Comment by kazaff** [comment]
for android，use this: https://github.com/PhilippKrone/react-native-fileupload

**Comment by aroth** [comment]
I've released react-native-uploader as another alternative. It supports assets-library URIs, base64 data or file paths. Also handles progress.  Works well with react-native-image-picker.

https://github.com/aroth/react-native-uploader

**Comment by marcshilling** [comment]
Sounds like most people have figured this out.

**Comment by ShanthiSenguttuvan** [comment]
Can anyone help me? 
how can i save the file on my server? I am using express with node js in my server side.

**Comment by haitaoli** [comment]
@ShanthiSenguttuvan grab the url from image picker, then:
```/* global XMLHttpRequest */
const xhr = new XMLHttpRequest();

xhr.onload = () => {
  if (xhr.status < 400) {
    // succeeded
  } else {
    const error = new Error(xhr.response);
  }
};

xhr.onerror = (error) => {
};

xhr.open('PUT', signedURL);
xhr.setRequestHeader('content-type', contentType);
xhr.send({ uri: imageURI });
```

**Comment by ShanthiSenguttuvan** [comment]
thanks for your replay.

**Comment by iMaciah** [comment]
@haitaoli I spent around 4 hours trying to solve this issue. I tried everything!!! Your little "xhr.send({ uri: imageURI });" was solution for my code.

Thank you.

**Comment by monolithed** [comment]
There was the same problem, here is a simple solution using Fetch API:

```js
{
	geImageType (file: string) {
		let extension = 'jpeg', _;

		try {
			[ _, extension ] = file.match(/\.(\w+)$/);
		}
		catch {
			extension = 'jpeg';
		}

		return `image/${extension}`;
	}

	async sendPhoto (url: string, image: string): Promise<ISearchResult> {
		let body = new FormData();

		body.append('image', {
			uri: image,
			name: 'image',
			type: this.geImageType(image),
		});

		let request;

		try {
			request = await fetch(url, {
				method: 'POST',
				headers: {
					'Accept': 'application/json',
					'Content-Type': 'multipart/form-data',
				},
				body
			});
		}
		catch (error) {
			throw new Error('Could not send image');
		}

		try {
			let { status, body } = await request.json();

			switch (status) {
				case HTTPStatus.BAD_REQUEST:
				case HTTPStatus.INTERNAL_SERVER_ERROR:
					throw new Error('Something went wrong...');

				case HTTPStatus.FORBIDDEN:
					return { status };

				default:
					return { body, status };
			}
		}
		catch (error) {
			throw new Error('Could not wait for the result');
		}
	}
}
```

**Comment by shide1989** [comment]
POST with `'Content-Type': 'multipart/form-data'` throws a `Multipart: Boundary not found` error on server side

**Comment by eightyfive** [comment]
@shide1989 I ran into the same issue, just don't set `Content-Type` header at all. I believe `fetch` is setting it properly (with boundary) if `FormData` is passed to `Request.body`.

@yfuks Thanks for the heads up.

**Comment by shide1989** [comment]
also tried that at the time, but it didn't work either. After spending 1day on this i ended up using a different solution

**Comment by aprilmintacpineda** [comment]
I ran into this when trying to upload files to S3 pre-signed URL, the URL expects the body to be raw binary. I used `fetch` instead of `XMLHttpRequest`.

```js
async function uploadFileToSignedUrl ({ signedUrl, file }) {
  const response = await fetch(signedUrl, {
    method: 'put',
    headers: {
      'Content-Type': file.mime
    },
    body: { uri: file.path }
  });

  if (response.status !== 200) throw response;
  return response;
}
```

- `file.path` is the absolute path to the target file, like `file://blahblah`
- `file.mime` is the mime type fo the file, like `image/jpeg`

**Comment by Muhammad-Wasi** [comment]
> POST with `'Content-Type': 'multipart/form-data'` throws a `Multipart: Boundary not found` error on server side

user this one
"Content-Type": "multipart/form-data; boundary=${form._boundary}",

**Comment by MayoudP** [comment]
> I ran into this when trying to upload files to S3 pre-signed URL, the URL expects the body to be raw binary. I used `fetch` instead of `XMLHttpRequest`.


Using a pre-signed URL too and react-native-image-picker, but I'm always getting this error on my side for the S3 validation `your proposed upload exceeds the maximum allowed size` ... or else with your snippet `status: 400`, whereas I'm using the same uri that I used to get the presigned URL...

**Comment by kirandesai303** [comment]
@MayoudP Did you get any solution for this error?
