### ISSUE TITLE
How can the taken photo/selected be displayed in the app?

### ISSUE THREAD

**Issue by mihaivinaga** [marcshilling/react-native-image-picker#63]
I have installed the default react app and then added the code from this project, but when I try to reload it I get a "Cannot read property 'avatarSource' of null"

**Comment by banderson623** [comment]
Hey @mihaivinaga here is my approach (i've simplified all the react classes).

I have three components.

A master component (`CameraSample`) and two sub components

https://gist.github.com/banderson623/da98e46f1946e8914a97.

**Comment by mihaivinaga** [comment]
Hello @banderson623 thank you for your response, I've tried your code but I think I am to dumb to figure out the missing parts :)

This is code:

```
'use strict';

var React = require('react-native');
var UIImagePickerManager = require('NativeModules').UIImagePickerManager;

var {
    AppRegistry,
    Text,
    View,
    TouchableHighlight,
    Image
    } = React;

var ImageSelector = React.createClass({

    options: {
        title: 'Select the Picture',
        // cancelButtonTitle: 'Cancel',
        // takePhotoButtonTitle: 'Take Photo...',
        chooseFromLibraryButtonTitle: 'Choose from Library...',
        quality: 0.2,
        allowsEditing: false,
        noData: false,
        storageOptions: {
            skipBackup: true,
            path: 'images'
        }
    },

    // this is called when a button is pressed.
    showCamera: function(){
        UIImagePickerManager.launchCamera(this.options, (didCancel, response) => {
            if (didCancel) {
                console.log('User cancelled image picker');
            }

            else {
                // Get the source and set the state
                const source = {uri: response.uri ,isStatic: true};

                // call back to the function handed to me by the parent component
                this.props.onSourceChange(source);
            }
        });
    },
    render: function () {
        return(
            <View>
                <TouchableHighlight onPress={this.showCamera}>
                    <Text>1234</Text>
                </TouchableHighlight>
            </View>
        )
    }
});

var CameraSample = React.createClass({
    getInitialState: function() {
        return {
            imageSource: null
        };
    },

    setImage: function(src){
        this.setState({
            imageSource: src
        })
    },

    render: function(){
        return (
            <View>
                <ImagePane source={this.state.imageSource}/>
                <ImageSelector onSourceChange={this.setImage}/>
            </View>
        );
    }
});

var ImagePane = React.createClass({

    render: function(){
        return (
            <View>
                <Image source={this.props.source}/>
            </View>
        );
    }
});

AppRegistry.registerComponent('AwesomeProject', () => CameraSample);
```

Cant get it to work. Do you have a full code example because I am really a rookie regarding react and I'm trying to figure it out while playing with it.

Thanks

**Comment by banderson623** [comment]
To be honest, I am brand new to this as well, so i might be missing some pieces. 

One thing to try is to put `console.log` statements all over so you can see what is going on, this helped me a bunch. Give that a shot and make sure that `showCamera` is being called, as is `setImage`.

Also it can be simplified into a single component if you want, so you don't need those `prop` callbacks.

**Comment by mihaivinaga** [comment]
Do you have a working example which you can paste here?

**Comment by banderson623** [comment]
Hey @mihaivinaga here is the basic `AwesomeProject` with the addition of Marc's library and showing the image on iOS: https://github.com/banderson623/react-native-image-picker-example

**Comment by kevando** [comment]
@mihaivinaga A couple things might be happening. 

When you upload your photo from the picker, this line contains the source of the image:
const source = {uri: response.uri ,isStatic: true};

(on a mac) the uri  will look like "file://Users/../../simulator/tmpdir/tmpdir/asdfasd.jpg"

So what to do? Add this line after you declar source:
console.log(response);
1) Check if this file actually exists after uploading
2) When you reload your simulator, it reloads in a different directory and usually breaks the image. I am currently facing this issue :/
