### ISSUE TITLE
How to select multiple images from library ?

### ISSUE THREAD

**Issue by parmarnishant** [marcshilling/react-native-image-picker#64]

**Comment by marcshilling** [comment]
Since support for multiple selection isn't baked into `UIImagePickerController` on iOS, I have no plans to implement this. That would require a completely custom implementation.

**Comment by kyle-ssg** [comment]
That's interesting, think I might implement my own (:

**Comment by srameshr** [comment]
@kyle-ssg Did you do it?

**Comment by kyle-ssg** [comment]
No not in the end, there are a few libs that accomplish this now though e.g. react-native-image-crop-picker

**Comment by srameshr** [comment]
That has few issues. Well more than few:
https://github.com/ivpusic/react-native-image-crop-picker/issues/491
