### ISSUE TITLE
Please rename Android folder to lower case

### ISSUE THREAD

**Issue by dshizzle** [marcshilling/react-native-image-picker#66]
Building the Android app under Linux fails because the include statement in the settings.gradle looks for the android folder with lower case "a" which does not exist. Renaming the "Android" folder to lower case "android" fixed this issue for me.

**Comment by marcshilling** [comment]
@yfuks can you tackle this? Do you see anything that this could effect? Maybe we should split the whole repo into android/ios root folders?

**Comment by yfuks** [comment]
> @yfuks can you tackle this? Do you see anything that this could effect?

I don't see any side effect on setting android repo to lower case.

> Maybe we should split the whole repo into android/ios root folders?

That could clearify the module for sure. The decision is up to you.

**Comment by marcshilling** [comment]
Folder is now lowercase in version 0.11.1
