### ISSUE TITLE
[Android] Can't display image with uri

### ISSUE THREAD

**Issue by deeppatidar** [marcshilling/react-native-image-picker#67]
As given instruction in readme.md  file i make changes but  it is  not working, So is there anything else which i need to configure apart from the given instruction.

I am following this way.

1 react-native init imageUploaderAndroid
2 npm install react-native-image-picker@latest --save
3  changes in  file: android/settings.gradle
4  changes in // file: android/app/build.gradle
5 changes in // file: android/app/src/main/java/com/myappli/MainActivity.java

Project structure.
imageUploaderAndroid
- android
- ios
- node_modules
- index.ios.js
- index.android.js

**Comment by yfuks** [comment]
All you need to do is in the [readme.md](https://github.com/marcshilling/react-native-image-picker/blob/master/README.md#android-1)

> Image picker is not working on Android

Did you get a build failure ? You can't open the image picker ? The app crash ? Can  you debug ?

**Comment by MrPluto** [comment]
cant choose image if i dont use other app?

**Comment by deeppatidar** [comment]
Thanks for reply,

Build is getting proper and application is also rendering but when i am selecting any image for upload. Its giving the error. "checkNotNull preconditions.java 20" 
Is there anything that i missing to pass because as i am seeing its null pointer .


![screenshot_2015-12-29-14-53-09](https://cloud.githubusercontent.com/assets/13794593/12032280/73a628aa-ae3c-11e5-9a64-f61a6f77ec0c.png)

**Comment by yfuks** [comment]
Can you tell me the source of your picture ? (Facebook, dropbox, camera..)

**Comment by deeppatidar** [comment]
@yfuks 
https://www.dropbox.com/sh/empove29w3pdtp5/AACIKoY5QFr5WqitZEByUd33a?dl=0

**Comment by deeppatidar** [comment]
@yfuks 

"  const source = {uri: 'data:image/jpeg;base64,' + response.data, isStatic: true}; " 

I found the issue, i have to use the above line in UIImagePickerManager.showImagePicker method
rather than this  " const source = {uri: response.uri.replace('file://', ''), isStatic: true};  "

**Comment by yfuks** [comment]
Ok, i was looking for an uri refactorisation on Android anyway, will look into this issues.
Actually uri is the filepath, will change it into the android uri. Could maybe fix this.

I'm **REALLY** busy actually with my job if you feel your self to get into the JAVA code it would be awesome!

**Comment by ashleydw** [comment]
I too am getting this, using version 0.12.1. Building an image from: `let photoSource = { isStatic: true, uri: response.uri} ;`

My returned response is: 

`Object {uri: "/storage/emulated/0/Pictures/1e7179cc-5475-49d8-8c94-5012803be03c.jpg", height: 631, width: 631, isVertical: true}`

I am selecting an image via the file system option.

I see you have a fix in 01406f2 - can you point me to what the fix was so I can debug further.

**Comment by yfuks** [comment]
Hello,

``` /storage/emulated/0/Pictures/1e7179cc-5475-49d8-8c94-5012803be03c.jpg ```

isn't an uri, it's the filepath, there was some problem with accesing it from react ``` uri: "filepath" ``` don't work, i set  the``` response.uri ``` with the android uri

it will be fix in 0.12.3 (not publish yet)

You can install 0.12.3 : 
```$> npm install https://github.com/marcshilling/react-native-image-picker.git ```

**Comment by ashleydw** [comment]
Thanks. Will 0.12.3 resolve the issues between API's for ios/android.

IOS currently returns only `response` whereas the android code returns `didCancel, response`

**Comment by yfuks** [comment]
Yes, android will also return ```response``` like iOS in 0.12.3

**Comment by ashleydw** [comment]
Great! I just installed the latest and everything works perfectly.

**Comment by marcshilling** [comment]
@yfuks sorry for changing the callback on you like that! Totally forgot it would break Android and I know enough Java to have made that code change myself :-P
I appreciate all your help with the Android side of this!

**Comment by yfuks** [comment]
Thanks !

**Comment by pbhargavi** [comment]
Hi

I am selecting image from gallery and here's my image path { uri: 'content://media/external/images/media/56' }

Its not getting displayed.

Can you please tell me what changes do i need to make to display the image
