### ISSUE TITLE
showImagePicker from Modal still not working

### ISSUE THREAD

**Issue by Shenenkaka** [marcshilling/react-native-image-picker#69]
When calling showImagePicker from Facebook's Modal component I get the following error:

Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior

Warning: Attempt to present  UIImagePickerController: 0x7f8cde1afc00 on  UIViewController: 0x7f8cded45ba0  whose view is not in the window hierarchy!

**Comment by mpretty-homepass** [comment]
@Shenenkaka @marcshilling really quick fix for this is to replace line 98 of UIImagePickerManager.m with the following:

```
UIViewController *root = [[[[UIApplication sharedApplication] delegate] window] rootViewController];

while (root.presentedViewController != nil) {
    root = root.presentedViewController;
}
```

This will recursively look up any modally presented view controllers until it finds the last one, and present from that view controller.

**Comment by marcshilling** [comment]
Thanks for the fix @mpretty-homepass!

This is pushed now @Shenenkaka
