### ISSUE TITLE
`this.setState` no effect

### ISSUE THREAD

**Issue by booxood** [marcshilling/react-native-image-picker#7]
In the function `UIImagePickerManager.showImagePicker`, use `this.setState` set some state, no effect...

Code like : 
```
  componentDidMount: function() {
    var self = this;
    UIImagePickerManager.showImagePicker({title: 'select...'}, function (type, response) {
      console.log(self.state.imageSource);
      self.setState({imageSource: {uri: response}});
      console.log(self.state.imageSource);  // no effect
    });
  },

```

React native version 0.6.

**Comment by marcshilling** [comment]
While `this.setState` is typically very very fast, it's still an async method. It has an optional second argument which is a function that is called after the state is set. Try logging your state like so:

```javascript
  componentDidMount: function() {
    var self = this;
    UIImagePickerManager.showImagePicker({title: 'select...'}, function (type, response) {
      console.log(self.state.imageSource);
      self.setState({imageSource: {uri: response}}, () => {
         console.log(self.state.imageSource);
      });
    });
  }
```

You should see the correct logging with that. Also, try using the imageSource in an `<Image>` in your render method and you'll see the picture!

**Comment by booxood** [comment]
:joy:  My mistake...

@marcshilling You are right. Thank you very much.
