### ISSUE TITLE
Scale size in response

### ISSUE THREAD

**Issue by BasitAli** [marcshilling/react-native-image-picker#70]
When specifying maxWidth, is there a way to return the new scaled size?

Update: Reviewing the code, I think the issue is only is iOS.

**Comment by BasitAli** [comment]
I've copied the scaledSize code out of ```downscaleImageIfNecessary``` method for now. Something like this works for now,

```
    CGSize scaledSize = CGSizeMake(image.size.width, image.size.height);
    
    // Nothing to do here
    if (image.size.width > maxWidth || image.size.height > maxHeight) {
      if (maxWidth < scaledSize.width) {
        scaledSize = CGSizeMake(maxWidth, (maxWidth / scaledSize.width) * scaledSize.height);
      }
      if (maxHeight < scaledSize.height) {
        scaledSize = CGSizeMake((maxHeight / scaledSize.height) * scaledSize.width, maxHeight);
      }
    }

    image = [self downscaleImageIfNecessary:image maxWidth:maxWidth maxHeight:maxHeight];

    // Create the response object
    NSMutableDictionary *response = [[NSMutableDictionary alloc] init];
    
    [response setObject:@(scaledSize.width) forKey:@"width"];
    [response setObject:@(scaledSize.height) forKey:@"height"];
```

**Comment by marcshilling** [comment]
`response.width` & `response.height` give you these values.

**Comment by BasitAli** [comment]
@marcshilling  the returned width/height in iOS is not the correct scaled size. See my code fix above.

**Comment by marcshilling** [comment]
@BasitAli ah, I see. The fix is even simpler than your solution...these lines just need to use `image.size.width` and `image.size.height`
https://github.com/marcshilling/react-native-image-picker/blob/master/ios/UIImagePickerManager.m#L244-L245
After the call to `downscaleImageIfNecessary`, these will be the correct scaled values. Fixed and published now, thanks!
