### ISSUE TITLE
[Android] Do I need to add <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

### ISSUE THREAD

**Issue by VansonLeung** [marcshilling/react-native-image-picker#71]
I could not load the saved image from camera in Android

Do I need: ```<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>``` ?

**Comment by yfuks** [comment]
When you say you can't 
> load the saved image from camera in Android

What did you mean exactly ? You can't display it ?

The permissions are in the [module manifest](https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/AndroidManifest.xml) don't know if you need to add it to your project to, try it and tell me if that work for you.

**Comment by yfuks** [comment]
Add the permissions in the android install process

**Comment by VansonLeung** [comment]
It really needs me to add the permission to read the image.
Yeah, thanks
