### ISSUE TITLE
Locationinfo

### ISSUE THREAD

**Issue by oliwerhelsen** [marcshilling/react-native-image-picker#78]
Hey,

I'm new to React native and trying to build a Camera app. 
I need to get the locationinformation from a imageresponse. Is this possible with react-native-image-picker?

Thanks in advance!

//O

**Comment by yfuks** [comment]
Actually you can't.

Since i'm in charge of the android part i can implement it for android, if this feature is a real need.

**Comment by mpretty-homepass** [comment]
If you modify the code you can include image metadata in the information returned to iOS so if the image metadata includes the GPS information then you should be good. If you take a look at my fork I've done a really simple implementation of this - https://github.com/HomePass/react-native-image-picker

**Comment by oliwerhelsen** [comment]
@mpretty-homepass your mod worked just fine. Thanks to you both!

**Comment by yfuks** [comment]
Looks like you find a way, i close this.
