### ISSUE TITLE
Problem with IOS

### ISSUE THREAD

**Issue by AdamGorkoz** [marcshilling/react-native-image-picker#80]
Hi , When i followed the instructions and i just get a black screen when i acess the camera or the photo library on IOS , i mean the camera open with the buttons and i see the auto focus working but there is no picture , any ideas ?

**Comment by korkinet** [comment]
Is it possible that there's a problem with IOS 9 ?

**Comment by korkinet** [comment]
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

This is the error i'm getting , help needed.

**Comment by korkinet** [comment]
Also it doesn't seem like the app is asking for permissions to use the camera roll or the camera.

**Comment by marcshilling** [comment]
@korkinet that's just a warning right? I don't think it impacts the functioning of the app. 

The app will automatically ask for permissions when the image picker launches. @AdamGorkoz is it possible that you denied permissions? Check out Settings on the phone.

**Comment by korkinet** [comment]
I checked the settings , there is not mention of camera permissions there.

**Comment by marcshilling** [comment]
@korkinet Settings > Privacy > Camera or Settings > Privacy > Photos (depending what function you selected)...whatever app you made (or the Example app) should be listed there

**Comment by korkinet** [comment]
@marcshilling  Like i said , It is not there , obviously i missed a step , any ideas ?

**Comment by marcshilling** [comment]
@korkinet the permissions wouldn't appear there until you actually try to access the camera/photo library from an app. Can you run the example project? I just pulled down the latest code and it runs fine.

**Comment by korkinet** [comment]
Couldn't run the exmaple also , it gave me an error with something to do with RCDatePicker.
Any way , i am opening the camera but its not asking me for permissions and it just stays black and i've tried this on several devices.

**Comment by marcshilling** [comment]
@korkinet well I think step 1 to figuring out your issue is getting the Example running. As I said, it runs fine for me when I clone the repo, why wouldn't it for you?

RCTDatePicker is completely unrelated to this project, so something else must be going on. Did you run `npm install` in the Example directory first?

**Comment by marcshilling** [comment]
@korkinet just realized I had my IP in `AppDelegate.m` rather than localhost. This is fixed now on `0.13` on npm. Try to run the example again, I'm guessing that's why you couldn't.

**Comment by korkinet** [comment]
@marcshilling Ok i got the example working , Maybe there is something working with my xcode project ?

**Comment by marcshilling** [comment]
If the Example is running then yes I would compare that project to your own to find the difference. It's gotta be something small.

**Comment by AdamGorkoz** [comment]
Issue resolved - There was a string missing in the info.plist file Bundle display name , The application name string was added and the issue was resolved.

Thanks.
