### ISSUE TITLE
[Android] Taking a video

### ISSUE THREAD

**Issue by Raisin-Man** [marcshilling/react-native-image-picker#81]
Hi
Are there any plans to allow taking videos as well? I'm not sure if it's the same on IOS but on Android, I can't take videos only pictures. Thanks

**Comment by yfuks** [comment]
Hello,
Video picking isn't implemented yet on Android.

Will implement it soon (probably this week).

**Comment by yfuks** [comment]
btw,
You can see all available options here:
https://github.com/marcshilling/react-native-image-picker#options

**Comment by Raisin-Man** [comment]
Ok Thanks

**Comment by yfuks** [comment]
Will take more time than i thought

**Comment by bcalik** [comment]
I need video picking feature on Android too.
It is possible to play videos with [react-native-video](https://github.com/brentvatne/react-native-video) package on Android.

**Comment by yfuks** [comment]
Video picking now available on **Android** with **0.17.0**
Since [react-native-video](https://github.com/brentvatne/react-native-video) take an uri as source i assume it's possible.
