### ISSUE TITLE
 Picture does not appear

### ISSUE THREAD

**Issue by montogeek** [marcshilling/react-native-image-picker#84]
Hi!

Thanks for this package, really useful!

I followed the instructions, but I have a problem when displaying the image, it does not.
When logging the response I get this:
![screen shot 2016-01-13 at 23 37 16](https://cloud.githubusercontent.com/assets/1002461/12315924/a4409dce-ba4e-11e5-8188-0c7a160c47c5.png)

From these log:
```
var source = {uri: response.uri.replace('file://', ''), isStatic: true};
console.log(source);
```

What I am doing wrong?

PD: When loading the route on Chrome, it loads the image, in other words, the file exists and is valid.
Thanks!

**Comment by yfuks** [comment]
Hello!

Thanks!

Is it on android or on iOS? Or maybe both?

If it's on android you don't need to remove the ``` file:// ``` from the uri to diplay it

You can do like so 
```javascript
var source = {uri: response.uri, isStatic: true}
```

```javascript
var React = require('react-native');
var {
  Platform
} = React;

var source;
if (Platform.OS === 'android') {
  source = {uri: response.uri, isStatic: true}
} else {
  source = {uri: response.uri.replace('file://', ''), isStatic: true}
}
```

**Comment by montogeek** [comment]
Hi @yfuks 
I am using iOS, I solved it by defining `width` and `height` of the Image component.
