### ISSUE TITLE
[iOS] Landscape support

### ISSUE THREAD

**Issue by wootwoot1234** [marcshilling/react-native-image-picker#86]
This is a great component, it's only limitation is that it doesn't support selecting an image from the photo gallery in landscape mode.  I saw in another issue (https://github.com/marcshilling/react-native-image-picker/issues/35) that it's related to a limitation of a iOS library but I've seen other apps that allow image picking in landscape.  How do they do it?

**Comment by wootwoot1234** [comment]
I came across this library that could be used instead of UIImagePickerController.  It would also allow for multiple photo selections:

https://github.com/B-Sides/ELCImagePickerController

**Comment by wootwoot1234** [comment]
Or maybe a better option is to use a Popover.  This is how cordova did it:

https://github.com/apache/cordova-plugin-camera/blob/master/src/ios/CDVCamera.m

**Comment by wootwoot1234** [comment]
I tried adding it myself but I don't know Objective C and got lost in error. :(

**Comment by yfuks** [comment]
Try harder :+1:

**Comment by wootwoot1234** [comment]
Was landscape support added?

**Comment by yfuks** [comment]
Nop ^^
Since ```UIImagePickerController``` is only supported in portrait mode for the moment this feature will only be added by  Apple. 
(There is no plan on using anything else than ```UIImagePickerController```)
