### ISSUE TITLE
Android doesn't get the picture after update from 0.10 to 0.13 

### ISSUE THREAD

**Issue by nbastoWM** [marcshilling/react-native-image-picker#87]
It works fine in ios and android with version 0.10.
Now I tried to upgrade to 0.13 but in Android, after taking or selecting the picture, none gets to show. 
In ios it keeps working fine.
Do I have to change anything in the Android files (gradle, main activity) ?

**Comment by marcshilling** [comment]
Can you give us a little more to work with here? Throw a `console.log(response)` in your callback for starters.

**Comment by nbastoWM** [comment]
In 0.13, as soon as I select a picture, it receives the event "didCancel"

```I/ReactNativeJS( 1503): 'Response = ', undefined```
```I/ReactNativeJS( 1503): User cancelled image picker```

In 0.12 the same error occurs. 
I'm now with 0.11.1 and everything works fine.

**Comment by yfuks** [comment]
Ok,

You miss something :)

There is a breaking point in android in 0.12.3

```javascript
UIImagePickerManager.showImagePicker(options, (didCancel, response) => {
```

become

```javascript
UIImagePickerManager.showImagePicker(options, (response) => {
```

https://github.com/marcshilling/react-native-image-picker#usage

**Comment by nbastoWM** [comment]
Thanks for pointing me that. I should have seen the instructions again.
It's working now!
Thanks!
