### ISSUE TITLE
[Android] Image Editing and Cropping

### ISSUE THREAD

**Issue by narychen** [marcshilling/react-native-image-picker#90]
allowsEditing: true could make cropping an image on ios. But android doesn't have this feature. 
Is there a way of making it ?

**Comment by yfuks** [comment]
Well nothing it's impossible it just take a large a small or a massive amount of time.

If you find a way will gladly accept a **PR** or doc for this purpose.

**Comment by marcshilling** [comment]
The editing functionality is built into iOS, so it was very easy to add. I'm not sure if it's built in on Android or how difficult it would be, but yes like @yfuks said...PRs please :)

**Comment by yfuks** [comment]
Just look at it with my [friend](http://stackoverflow.com/). That don't seems to hard will try to add it as soon as possible.

**Comment by narychen** [comment]
You guys're really cool.

**Comment by yfuks** [comment]
Now available with 0.13.2

**Comment by narychen** [comment]
I try it. It's awesome.
And I read the code found that maybe adding the aspect ratio to 1:1 to give the behavior same as ios will be better.
The code could be 
```java
     if (requestCode != REQUEST_IMAGE_CROPPING && allowEditing == true) {
        Intent cropIntent = new Intent("com.android.camera.action.CROP");
        cropIntent.setDataAndType(uri, "image/*");
        cropIntent.putExtra("crop", "true");
        cropIntent.putExtra("aspectX", 1);  // add this two lines
        cropIntent.putExtra("aspectY", 1);

**Comment by yfuks** [comment]
There is a **PR** #99 that allow you to choose the aspectX & aspectY
I'm on it

**Comment by yfuks** [comment]
Available in 0.13.4

**Comment by spencexyz** [comment]
I'm trying to use allowsEditing: true on Android, but nothing is happening. Is there something else I need to do?

**Comment by marcshilling** [comment]
@spencexyz allowsEditing functionality was removed on Android due to issues with certain Android versions and devices

**Comment by smithaitufe** [comment]
Please has AllowsEditing feature been added back in Android?
