### ISSUE TITLE
Android,Cannot read property 'showImagePicker' of undefined

### ISSUE THREAD

**Issue by gufanyuanying** [marcshilling/react-native-image-picker#96]

**Comment by yfuks** [comment]
Make sure you folow all the [installation](https://github.com/marcshilling/react-native-image-picker#install)

You can instanciate the module in **RN** like this :

```javascript
var UIImagePickerManager = require('NativeModules').UIImagePickerManager;
```

**Comment by Iliyass** [comment]
same here, are you sure about the require statement ? `NativeModules` ?

**Comment by yfuks** [comment]
you can try like this too
```javascript
var { NativeModules } = require('react-native');
var UIImagePickerManager = NativeModules.UIImagePickerManager;
```

it's maybe cause you don't ``` require('react-native') ``` at the beginning of the file
```javascript
var React = require('react-native');
var UIImagePickerManager = require('NativeModules').UIImagePickerManager;
```

**Comment by yfuks** [comment]
no response i close

**Comment by palmsey** [comment]
In case anyone else runs into this, running `react-native run-android` (not included in the installation steps) fixed this for me.

**Comment by callcter** [comment]
You need to rebuild you project

**Comment by cihanbas** [comment]
thank you @callcter 
ı made cd android 
after than
gradlew clean 
and runing
