### ISSUE TITLE
0 bytes for the file

### ISSUE THREAD

**Issue by skyride99** [marcshilling/react-native-image-picker#97]
Trying to upload the file from the uri, using RN 17, Genymotion emulator, 
 
let formData = new FormData();
formData.append('image', {uri: pic.uri, type: 'image/jpg', name: 'seventh.jpg'});

let options = {};
options.body = formData;
options.method= 'post';
fetch("http://posttestserver.com/post.php", options).then((response) => {

  debugger;
});

message back: post body has 0 char long

it seems like the file is 0 bytes.

**Comment by marcshilling** [comment]
I'm guessing this isn't an issue with my package. Can you log your response from `.showImagePicker()`? If the URI returned is valid, I can assure you it's not 0 bytes and the issue is with `fetch`.

I personally had success using the `react-native-file-upload` package (https://github.com/booxood/react-native-file-upload)


```javascript
        const obj = {
          uploadUrl: 'https://yourawesomewebsite.com/upload',
          method: 'POST',
          headers: {
            'Authorization': this.props.authToken
          },
          files: [{
            filename: 'file',
            filepath: response.uri,
            filetype: 'image/jpeg'
          }]
        };

        FileUpload.upload(obj, (err, result) => {
          console.log('uploaded avatar to url: ' + result.data);
        });
```

**Comment by skyride99** [comment]
It shows the picture Image tag with URI.

**Comment by yfuks** [comment]
That look like an android file path, i recommend you to update your version of image-picker.
The uri was the filepath and it's now an uri

**Comment by skyride99** [comment]
I have version 13.1, 

I have tried to use several file upload, including react-native-file-upload. I have tried iOS and Android and get this same error:

"<?xml version="1.0" encoding="UTF-8"?> <Error><Code>InvalidArgument</Code><Message>POST requires exactly one file upload per request.</Message><ArgumentName>file</ArgumentName><ArgumentValue>0</ArgumentValue><RequestId>9988428B13D691F9</RequestId><HostId>BDZ+tRRV9F0HipT7At1ZfMhn4L+yMknD6pr97pqqRcJ3N2vELa01H7NreX6DmSKN0pRNi64+DGQ=</HostId></Error>"

**Comment by skyride99** [comment]
I have tried on the iOS simulator, a real iPod with iOS 8, emulator, and a real Android LG phone with Lollipop.

**Comment by yfuks** [comment]
I don't think that's an issue with this package, that's look like it's an issue with your upload
http://stackoverflow.com/questions/6030371/http-post-with-httpwebrequest
http://stackoverflow.com/questions/21498845/s3-upload-issue

Try to upload using fetch it with the proper header etc..
https://github.com/marcshilling/react-native-image-picker/issues/61#issuecomment-164467359

**Comment by yfuks** [comment]
http://stackoverflow.com/questions/30737226/react-native-upload-image-to-amazons-s3

**Comment by skyride99** [comment]
I have tried fetch, and xhr. And if I upload as a file with the base64 string that works

var base64Policy = data.policy;
    //console.log('base64Policy:', base64Policy);
    var s3Signature =  data['x-amz-signature'];

    let formdata = new FormData();

    this.addTextParams(s3Signature, base64Policy, data['x-amz-date']);
    this.textParams.forEach((param) => {
        formdata.append(param.name, param.value)
      }
    );

    var xhr = new XMLHttpRequest();
    xhr.open('POST',  'http://makeuroffer.s3.amazonaws.com'); //'http://posttestserver.com/post.php');
    xhr.onload = () => {
      console.log('status ' + xhr.status);
      debugger;
    };

    formdata.append('file', pic.data);// {...'.\test.jpg', name: ('first'+".jpg") });
    xhr.send(formdata);

**Comment by skyride99** [comment]
Amazon is happy the signature is correct if just the base64 string.

 But if i try to upload the actual file

formdata.append('image', {uri: pic.uri, type: 'image/jpg'});

I get the error. Always no matter what method of uploading or device.

**Comment by skyride99** [comment]
Ahhh I got it ,

    formdata.append('file', {uri: pic.uri, type: 'image/jpg'});

This works. The RN documentation is a bit wrong. See https://github.com/facebook/react-native/issues/5308.

**Comment by skyride99** [comment]
You can close but all the bugs in RN github have file upload as 'image' for a picture. I think Amazon wants to see 'file'.
